### ISSUE TITLE
openttd-custom-jgrpp-0.8.0-Ubuntu14.04-amd64.zip

### ISSUE THREAD

**Issue by openbufounder** [JGRennison/OpenTTD-patches#1]
openttd-custom-jgrpp-0.8.0-Ubuntu Trusty 14.04-amd64.zip

---Compile----

sudo apt-get install build-essential pkg-config libsdl1.2-dev subversion patch zlib1g-dev liblzo2-dev liblzma-dev libfontconfig-dev libicu-dev

cd <directory in which the OpenTTD source code is located> and 
./configure 
Your system's default compiler (usually GCC) will be used - if you want to use a specific compiler, temporarily set the CC and CXX environment variables accordingly: $ CC=<command for C compiler> CXX=<command for C++ compiler> ./configure 
NOTE: Without a compiler configured, you will receive the "please define the CC/CXX environment to where it is located" message when running configure. Define (export) them, or pass them as given in the example above. 
This will create a Makefile, then run make. If you have changed files or updated your source, only modified code will be recompiled. Now: 
make --jobs=<#> 
On multi-core systems, using a high thread number (the #) can speed up compiling greatly; it's commonly recommended to use the number of logical cores (obtainable using getconf _NPROCESSORS_ONLN on Linux at least) plus one. (The theory behind this is that if one compiling thread is currently limited by I/O speed, the others should still fully saturate the available hardware threads.) For example, on an Intel i5 with two hyper-threaded cores (i.e. four logical ones), make --jobs=5 took 1 minute and 33 seconds, and plain make three minutes and 18 seconds. 
There should now be an OpenTTD executable in the bin subdirectory. To install the OpenTTD binary to a directory included in your PATH variable, so it can be run as only openttd<code>, do a <code>make install as root/using sudo.

**Comment by JGRennison** [comment]
Is this the same problem you posted on tt-forums or something else? Can you clarify?
Is there a reason for creating two issues?

**Comment by openbufounder** [comment]
thanks,JGRennison,I am compiling on linux amd 64,
# git clone https://github.com/JGRennison/OpenTTD-patches
#./configure 
#make --jobs=5 
it works.
thanks.
