### ISSUE TITLE
Can't play music

### ISSUE THREAD

**Issue by SJang1** [JGRennison/OpenTTD-patches#101]
## Version of OpenTTD
~master current (all)

## Expected result
Play music correctly (OpenMSX)

## Actual result
All the music seems to be skipped
![image](https://camo.githubusercontent.com/37b264f009b224b2c1a16479527cdb9d6cb75ebb/68747470733a2f2f696d672e6e7477732e6b722f5065656b253230323031392d31302d303425323031312d33322e676966)
but the main page music come out correctly.

## Steps to reproduce
On Linux, Build OpenTTD, add OpenMSX baseset, run openttd, play a game.

On the openttd master branch, it seems working (maybe) after this commit :
https://github.com/OpenTTD/OpenTTD/commit/2d27e8e6856cc7488842b01a271f57ae4bd07230
Maybe we also need to support SDL2 and sound driver thing?

**Comment by SJang1** [comment]
on v0.32.0, music plays but sound is weird (enen on main page)

**Comment by JGRennison** [comment]
I think the music sounds weird at the best of times.
It plays OK here with SDL2 but the music volume control does not work.
Sound effects seem fine here, and the volume control does work.
This is not something that I can really debug/fix, it may be worth submitting a bug upstream against trunk/master.

**Comment by SJang1** [comment]
Weird music sound was because of the music driver. using fluidsynth made fine. All those skipping was seemed because of extmidi.
Volume control works here.
now I am using Roland_SC-88.sf2 as a soundfont, this config seemed fine to me.
`musicdriver = "fluidsynth:driver=pulseaudio,soundfont=/usr/share/soundfonts/Roland_SC-88.sf2"`

It maybe seems this is almost the only of the way to fix this problem for now.
