### ISSUE TITLE
Feature request: 2 additional routefinding restrictions

### ISSUE THREAD

**Issue by kostya** [JGRennison/OpenTTD-patches#102]
Hi, this patch is very nice, thanks. Routefinding restrictions is good feature, but if add two cases, it would be better, i think.
1) condition for percent of loading (right now i using weight, but this is not so nice when using many cargos).
2) logical triggers (like if number of train % 2 == 0, then deny), to split the flow in two directions evenly. (i saw people create large constructions with logical trains to do it).
Is it possible?

**Comment by JGRennison** [comment]
1. Percent loaded should be easy to do, I can look into this.

2. Logical expressions in general are a bit problematic.
How does the user enter them? Offering a text box to enter a correctly formatted expression creates quite a lot of UI, parsing and validation issues. Using buttons/etc to assemble a mathematical expression is not great either. Many users already find it difficult to use.
There are also issues with performance and storage as currently the instruction format is based on fixed-size instructions.
Common use cases (possibly including filtering on train unit number) are probably better off added as extra instruction types.

**Comment by kostya** [comment]
2) common use cases is splitting flow. so need 2 numbers only divider(A), comparer(B) and operation OP (==|<=|>=|>|<)
`if number of passing through signal train (or train id if not possible) % A OP B then Peny/pass`

This allow logics like:
  * send every second train to another path (A 2, OP ==,  B 0)
  * send 3 trains to first path, and others 4 trains to another (A 7, OP <=, B 3)
  * send every 7th train to another path (A 7, OP ==, B 0)

**Comment by JGRennison** [comment]
1. Is implemented now, see: 7332c0b6731d29876178e6c0a85a572817769e0e

**Comment by kostya** [comment]
thanks, just tested it works

**Comment by kostya** [comment]
I also make patch for 2, it works, but there is some strange thing. I increment counter every time when train check condition, and most time it works, but some time not. I found that train can check this signal more than 1 time (and counter changed), before pass through it (maybe cache path or something). Is there way to check in TraceRestrictProgram::Execute is this caching or passing action?

**Comment by JGRennison** [comment]
You would probably need to add something similar to the TraceRestrictProgramInput permitted_slot_operations field, which describes what slot operations are valid/meaningful for this execution.
You may also need to adjust handling of TraceRestrictProgramActionsUsedFlags/actions_used_flags to ensure that the execution is called at all times required for the counter mechanism.
The execute function is called whenever a pathfinding decision is required within the signal evaluation distance and when indicated by actions_used_flags

**Comment by JGRennison** [comment]
Superseded by 817bc44a3ea33c5e410733f061b02cc90732bce2, 9ee8091eccdc0ffd1630074c9d3fbe4776da7edb, abb7b69861caa010af558e82b3dddcab1050001e

**Comment by kostya** [comment]
i not tried it yet, but seems this what i wanted: https://github.com/JGRennison/OpenTTD-patches/wiki/Signalling, thanks
