### ISSUE TITLE
Create/Edit template window is slightly broken (in curtain korean config)

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#105]
## Version of OpenTTD
All of jgrpp

## Expected result
![image](https://user-images.githubusercontent.com/10726524/66693760-98ff9d00-ece7-11e9-8761-62a0f117dd9a.png)

## Actual result
![image](https://user-images.githubusercontent.com/10726524/66693772-bfbdd380-ece7-11e9-8de0-73ffe6aff81b.png)

## Steps to reproduce
Create/Edit template window is slightly broken, as you can see the above actual result's right bottom side.

I'm using ``NanumGothic.ttf`` which is downloadable [here](https://fonts.google.com/specimen/Nanum+Gothic) with this config:
(where ``NanumGothic.ttf`` file is stored under ''(OpenTTD)/font'' directory)
```
(...)
[misc]
small_font = ./font/NanumGothic.ttf
medium_font = ./font/NanumGothic.ttf
large_font = ./font/NanumGothic.ttf
mono_font = ./font/NanumGothic.ttf
small_size = 10
medium_size = 12
large_size = 16
mono_size = 12
small_aa = true
medium_aa = true
large_aa = true
mono_aa = true
(...)
```

**Comment by JGRennison** [comment]
Thanks, this should be fixed now.

**Comment by telk5093** [comment]
Checked it is fine at 0.32.1
