### ISSUE TITLE
configure does not auto detect SDL1 if SDL2 is not installed

### ISSUE THREAD

**Issue by SJang1** [JGRennison/OpenTTD-patches#107]
## Version of OpenTTD
 v0.32.0

## Expected result
auto detects SDL1 if SDL2 is not installed.

## Actual result
```
checking sdl2... not found
configure: error: pkg-config sdl2 couldn't be found
configure: error: you supplied '2', but it seems invalid
```

changing config.lib `with_sdl="1"` to `with_sdl="sdl1"` is needed to use sdl1.

## Steps to reproduce
git clone or download, ./configure WITHOUT SDL2-devel(libsdl2-dev) installed.

**Comment by JGRennison** [comment]
Can you try it now?

**Comment by SJang1** [comment]
Now it detects. Thanks.
