### ISSUE TITLE
Server offline but not in vanilla game. Can't connect through server list

### ISSUE THREAD

**Issue by dorobouNeko** [JGRennison/OpenTTD-patches#111]
## Version of OpenTTD
Since at least version 0.31.5 to 0.32.1
## Expected result
Find server on server list and be able to connect/donwload newgrfs
## Actual result
It show the IP of the server as server offline
## Steps to reproduce
Fresh install of jgrpp-0.32.1
Open multiplayer menu
Press on Find server with advertised on

##Additional notes
I tried checking with the vanilla game and it shows there and you can download the newgrfs but obviously you cannot connect(version mismatch)
Also you can connect on jgrpp if you have the newgrfs already downloaded but only with console commands. 
The server in question is https://servers.openttd.org/en/server/117026 and i am trying this on a Linux machine

**Comment by dorobouNeko** [comment]
If there is any extra info i can provide let me know.

**Comment by JGRennison** [comment]
The output of `bin/openttd -Z` may be useful.
The server seems like it is online and available, though I do not have the
password so cannot join.
Which console commands are you referring to?

**Comment by dorobouNeko** [comment]
[info.txt](https://github.com/JGRennison/OpenTTD-patches/files/3775227/info.txt)
the command is
connect ip:port#company-number

**Comment by JGRennison** [comment]
It might be a UDP packet MTU issue.
Are you using a VPN, network tunnel or similar?

**Comment by dorobouNeko** [comment]
Nope. I am not using anything like that.

**Comment by JGRennison** [comment]
I've made some adjustments to the server code to be more conservative about the MTU, this will be in the next release.

For testing, you could try `tracepath 194.88.107.194`, or use wireshark and see what traffic there is between your machine and the server. (The filter `ip.addr == 194.88.107.194` may be useful).

**Comment by dorobouNeko** [comment]
I ran tracepath and it detects a path MTU of 1480. I don't think that's low.
