### ISSUE TITLE
Process hangs on Mac OS Catalina with no output

### ISSUE THREAD

**Issue by taniaraven** [JGRennison/OpenTTD-patches#113]
## Version of OpenTTD
(jgr) 0.32.1
## Expected result
OpenTTD opens 
## Actual result
OpenTTD's icon bounces in the dock indefinitely and spins up the laptop's fans. When run from the Terminal, the process hangs with no output until I quit it with ctrl-c
## Steps to reproduce
Compile OpenTTD-jgr from source on MacOS 10.15, and try to run either the app bundle or the terminal executable.

[https://youtu.be/7n6_V3lkErM](https://youtu.be/7n6_V3lkErM) video of the problem

Official (unpatched) OpenTTD works fine.

**Comment by taniaraven** [comment]
[iTerm2Sample.txt](https://github.com/JGRennison/OpenTTD-patches/files/3776299/iTerm2Sample.txt)

Not sure if it helps, but I did a CPU usage profile with iTerm and got this output.

**Comment by JGRennison** [comment]
It may be worth doing a clean rebuild (make clean) and checking that all the libraries/dependencies are up to date if you haven't already.

The usage profile looks to be that of iTerm2 itself.

I don't have access to any machines which run MacOS 10.15 at present, but if one becomes available I'll look into it.

This issue may be relevant https://github.com/OpenTTD/OpenTTD/issues/7623

**Comment by taniaraven** [comment]
This is a clean install of Catalina, with clean installs of all libraries. The issue you linked appears to be due to new security requirements which don't apply to apps compiled from source. Vanilla OpenTTD works fine.

**Comment by flow23** [comment]
Hi, I'm having the same issues sind 0.32.1. If you guys need help let me know.
Also did a make clean before running make bundle.

**Comment by JGRennison** [comment]
Would you mind trying with the most recent commit?

**Comment by flow23** [comment]
Hi, sure.
Please find attached the output of running configure and make bundle.
Used the following commit:
`47629d6ed9 (HEAD -> jgrpp, origin/jgrpp, origin/HEAD)`

[configure.txt](https://github.com/JGRennison/OpenTTD-patches/files/3805481/configure.txt)
[make_bundle.txt](https://github.com/JGRennison/OpenTTD-patches/files/3805527/make_bundle.txt)
[warnings.txt](https://github.com/JGRennison/OpenTTD-patches/files/3805528/warnings.txt)

Best regards,
Florian

**Comment by JGRennison** [comment]
I don't see anything obviously wrong with the build.

Does this still not work in the same way as previously?
Are there any error logs in the system/event logs or the Mac equivalents?

**Comment by flow23** [comment]
> I don't see anything obviously wrong with the build.
> 
> Does this still not work in the same way as previously?
> Are there any error logs in the system/event logs or the Mac equivalents?
> 
> Edit: Could you run it via lldb and see if that gives any useful information?

Yes, icon is present in the dock and cpu load is 100%.

**Comment by flow23** [comment]
Nothing specific in the logs. Is there a chance to start openttd in debug mode? /bin/openttd -d 1 doesn't work.

[openttd_2019-11-05-090119_mac-004.cpu_resource.txt](https://github.com/JGRennison/OpenTTD-patches/files/3807839/openttd_2019-11-05-090119_mac-004.cpu_resource.txt)
[openttd_used_libs.txt](https://github.com/JGRennison/OpenTTD-patches/files/3807840/openttd_used_libs.txt)

**Comment by JGRennison** [comment]
> stack_not_16_byte_aligned_error

This looks like the problem.

It seems that this problem has affected several projects on MacOS Catalina, going by bug reports I've found.
I will add some mitigations to get round this.

**Comment by JGRennison** [comment]
Could you try again with the most recent commit?

**Comment by flow23** [comment]
> Could you try again with the most recent commit?

Problem solved, game starts again.
Thank you very much.

Best regards,
Florian

**Comment by taniaraven** [comment]
Fixed for me too. Thanks a lot!
