### ISSUE TITLE
Visual Studio 2017 can't build Win32 configuration on latest

### ISSUE THREAD

**Issue by Yourself** [JGRennison/OpenTTD-patches#116]
When attempting to build Release-Win32 using the Visual Studio 2017 solution (openttd_vs141.sln), the build fails with an error:

`openttd-patches\src\os\windows\crashlog_win.cpp(625): error C3861: 'AddVectoredExceptionHandler': identifier not found`

The Release-x64 configuration builds successfully. I'm not familiar enough with the WinAPI to know what this is for or why it would be different between the two configurations.

This is on the latest from the jgrpp branch

**Comment by JGRennison** [comment]
Thanks for reporting this, could you try the most recent commit?

**Comment by Yourself** [comment]
Looks to be fixed, builds successfully for me. Thanks!
