### ISSUE TITLE
cannot compile in macos openttd jgrpp 0.32.2

### ISSUE THREAD

**Issue by ecolortest** [JGRennison/OpenTTD-patches#118]
## Version of OpenTTD
openttd jgrpp 0.32.2

## Expected result
compile error when `make`
## Actual result
`[SRC] Linking openttd
ld: warning: text-based stub file /System/Library/Frameworks/Cocoa.framework/Cocoa.tbd and library file /System/Library/Frameworks/Cocoa.framework/Cocoa are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/Cocoa.framework/Cocoa.tbd and library file /System/Library/Frameworks/Cocoa.framework/Cocoa are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/AudioUnit.framework/AudioUnit.tbd and library file /System/Library/Frameworks/AudioUnit.framework/AudioUnit are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox.tbd and library file /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox are out of sync. Falling back to library file for linking.
ld: library not found for -lfluidsynth
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [openttd] Error 1
make: *** [all] Error 1`
## Steps to reproduce
`./configure`
`make`

**Comment by JGRennison** [comment]
This suggests that something is wrong with your build environment. Once those issues are fixed, try `make clean`.

**Comment by ecolortest** [comment]
> This suggests that something is wrong with your build environment. Once those issues are fixed, try `make clean`.

how to fix that?

**Comment by ecolortest** [comment]
> This suggests that something is wrong with your build environment. Once those issues are fixed, try `make clean`.
@JGRennison im is compile in macos high sierra 10.13.6
