### ISSUE TITLE
Feature request: Flip order of Orders

### ISSUE THREAD

**Issue by sam-cross** [JGRennison/OpenTTD-patches#120]
Thank you for making such an amazing patch pack - I play jgrpp exclusively now, can't live without the timetable automation and tunnel/bridge signals!

Anyway, the way I'm doing routes is as follows:

1. Set up orders on vehicle
2. Clone vehicle without sharing orders
3. Manually move orders of new vehicle into opposite order

This way, I can have vehicles going in both directions simultaneously, which means no long waits for passengers! However, with long order lists, this is a very tedious process, so I'd love a button to flip the order of Orders on the Orders window.

I'm not sure how I'd implement it myself as I've been away from C++ for so long, so I'm requesting it here - hope that's okay!

**Comment by JGRennison** [comment]
This makes sense and would not be too hard to implement.
The main issue is where to put it in the UI.
The order window already has a lot of buttons.
I will look into it.

**Comment by sam-cross** [comment]
Thank you so much!

I was thinking of placing the button next to the existing "Shared Orders" button. It would have a tooltip and would therefore only need a small space.

**Comment by auge8472** [comment]
I really see no reason for the described feature *as I understand the description*.

If you want to start a further vehicle on the half way of the orders list, do it as described hereinafter. Clone the vehicle with shared orders (possibly in another depot), step through the orders list to the order you want to begin with and start the vehicle.

That way one needs only *one* (shared) orders list for *all* vehicles on one route. Less administration effort, no need for a further button.

**Comment by sam-cross** [comment]
That's not what I meant.

If you have 10 orders on vehicle A, you duplicate it to make vehicle B, and
you move down to the 5th order on vehicleB, it's still running through
stations in the same order. What I want is a feature to make vehicles A and
B run against each other, to emulate a more realistic service. With
real-life buses, for example, they run services to and from destinations
simultaneously, passing each other at some point. This is what I want to do
in OTTD. Keeping vehicle A's orders the same, and flipping the order of
vehicle B's orders, would enable this.

**Comment by auge8472** [comment]
> What I want is a feature to make vehicles A and
B run against each other, to emulate a more realistic service.

Ah, a circle line? Running one (set of) vehicle(s) clockwise (Stations A => B => C => D => A ...) and a second (set of) vehicle(s) counterclockwise (A => D => C => B => A ...)?

**Comment by sam-cross** [comment]
Yeah that's a better way of describing it!
