### ISSUE TITLE
Feature: Tollgate please

### ISSUE THREAD

**Issue by Penta0308** [JGRennison/OpenTTD-patches#122]
In real life, we have tollgate and a company charges fee.
We need a Tollgate part that we can adjust fee freely.
please.

**Comment by SylvainDevidal** [comment]
Hello Penta0308,

I'm not sure, but tollgates could be added as simple newgrf objects (with no functionality).

Thus, here are two links showing modern toll systems. The second one doesn't need anything, just a camera, so there is no "gate" anymore.

https://en.wikipedia.org/wiki/Electronic_toll_collection
https://fr.wikipedia.org/wiki/Portique_%C3%A9cotaxe

As a result, I'm not sure a "tollgate" functionality would be actually usefull.

**Comment by JGRennison** [comment]
I think that this concept is not workable for several few reasons, so I'm closing this one for the time being.
