### ISSUE TITLE
Can't transfer saves from the latest Joker's Patch Pack to the JGR patch pack.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#123]
## Version of OpenTTD
Source: LtJoker's Patch Pack v1.27 (latest/possibly final version, with latest commit being on 11 May 2018)
Target: JGR Patch Pack (latest version)
LtJoker's patch pack: https://github.com/KeldorKatarn/OpenTTD_PatchPack
JGR patch pack: https://github.com/JGRennison/OpenTTD-patches

## Expected result
You can load saves started in the latest Joker's Patch Pack into the JGR patch pack and "seamlessly" continue (no major problems or things that need to be reconfigured for JGR).

## Actual result
You are unable to load saves started in the latest Joker's Patch Pack into the JGR patch pack. Attempting to do so yields a "This save was made for a newer version" error.

## Steps to reproduce
1. Obtain a save from the Joker's Patch Pack. For example, the latest download of M4J_Gaming's network map from https://www.m4jmedia.co.uk/download/openttd.
2. Try to load it in the JGR Patch Pack.
3. The save will fail to load.

## Reasoning
I would like if we could transfer saves from the latest Joker's Patch Pack into the JGR patch pack or if we could convert saves made using Joker's Patch Pack for use with the JGR patch pack. This would allow us to bring many of our games from what was buggy and dead for a couple of years into something that is still in active development as well as improving stability and performance of games started in Joker's patch pack. It would also allow people to take advantage of new features introduced in both trunk and the JGR patch pack over the past couple of years.

For example, M4J_Gaming (https://www.youtube.com/user/M4J3FFR135, https://discord.gg/wsc6dw2) has been having problems with his current OpenTTD map and has said that he would like to move to the JGR patch pack to take advantage of Scheduled Dispatch as well as improved performance and stability so he can watch his network run without the game crashing.

See KeldorKatarn/OpenTTD_PatchPack#12

**Comment by JGRennison** [comment]
If you could give this most recent commit a try, or if you have any test savegames, that'd be helpful, thanks.

**Comment by James103** [comment]
This is the latest save game that M4J_Gaming has:
https://drive.google.com/drive/folders/1F1TyV1O2wbQKBav7_LnnbqaMh_MNj41y

And these are the NewGRFs that M4J_Gaming uses with the savegame:
https://drive.google.com/drive/folders/1nwK7lgP_CfQvNp6JpT7Sy39pzgC_1hji

**Comment by James103** [comment]
M4J_Gaming said on his Discord server: "That all sounds pretty reasonable. It'll reboot the network in terms of cargo which I'm ok with, and besides programmed signals I don't use any signal logic anyway so no loss there. I'll test it out tomorrow and post my results"

**Comment by James103** [comment]
@JGRennison Do you have a pre-compiled version of this patch pack that includes the commit adding support for Joker's Patch Pack savegames?

**Comment by JGRennison** [comment]
> @JGRennison Do you have a pre-compiled version of this patch pack that includes the commit adding support for Joker's Patch Pack savegames? Or, can you compile the latest commit of the Joker's Patch Pack for me please?

I'm assuming that you're on Windows?
If so, not at present, I could look into a non-public build tomorrow though.

**Comment by JGRennison** [comment]
> @JGRennison Do you have a pre-compiled version of this patch pack that includes the commit adding support for Joker's Patch Pack savegames? Or, can you compile the latest commit of the Joker's Patch Pack for me please?

[openttd-custom-jgrpp-0.32.4-17-g796a878b90-MINGW-win64.zip](https://github.com/JGRennison/OpenTTD-patches/files/4009759/openttd-custom-jgrpp-0.32.4-17-g796a878b90-MINGW-win64.zip)
Note that this is unreleased, etc.
