### ISSUE TITLE
Can't reset inflation nor manually configure the inflation factor for costs or payments.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#124]
## Version of OpenTTD
796a878

## Expected result
You should be able to not only turn on or off inflation, but also to reset inflation to the default state (as if the game was just started) and manually set the inflation factor for costs and payments separately. Resetting inflation or manually adjusting the inflation factor are both considered cheats.

## Actual result
You are not able to reset inflation or manually adjust the inflation factor for costs or payments at all in-game.

## Steps to reproduce
* Try to find a way to change or reset the inflation factor for costs or payments.

## Reasoning
M4J_Gaming's saved game has maxed-out inflation, which may be causing him to pretty much constantly be losing money. By being able to reset inflation, he will be able to basically reset his finances to smaller numbers and hopefully get a profit. However, resetting inflation may generate too much profit, which is where being able to manually adjust the inflation factor for costs and payments separately may come in, as he can increase the costs slightly to reduce the profit margins to realistic levels.

**Comment by JGRennison** [comment]
This is in 0.34.2
