### ISSUE TITLE
Can't control+click to set wait times for all stations only, not just all stations and waypoints

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#125]
## Version of OpenTTD
796a878

## Expected result
* You should be able to control-click to set wait times for all stations OR all waypoints, not just both at once. A new game setting should be added to reflect this.

## Actual result
* You are not able to control-click to set wait times for all stations OR all waypoints. Attempting to add wait times for all stations by control-clicking will set wait times for all waypoints as well.

## Steps to reproduce
* Try to add wait times to all stations by control-clicking.

## Reasoning/Evidence
M4J_Gaming has said the following on his Discord:
![image](https://user-images.githubusercontent.com/37945304/71646452-8aa19b80-2cae-11ea-962c-eed245ac9d5b.png)

![image](https://user-images.githubusercontent.com/37945304/71646446-7198ea80-2cae-11ea-8317-f25ac0231ab8.png)

**Comment by JGRennison** [comment]
I've adjusted it to no longer set the wait time for waypoint orders.
I don't think that a new setting is really necessary. I cannot think of a use case where setting the wait time for a large number of waypoint orders at once would be useful.

**Comment by James103** [comment]
Closing this issue as it is (probably) fixed.
