### ISSUE TITLE
Assertion failed 

### ISSUE THREAD

**Issue by RedVelvet0801** [JGRennison/OpenTTD-patches#127]
##Version of OpenTTD
jgrpp-0.32.4

## Expected result
Keep making assertion failed error in certain date (2008-4-15), thought it was the NEWGRF but even if i deleted NewGRF, keep making error.

## Actual result
*** OpenTTD Crash Report ***

Crash at: Fri Jan 10 03:50:26 2020
In game date: 2008-04-15 (57, 0) (DL: 1)
Game loaded at: 2008-04-04 (70, 0), Fri Jan 10 03:50:19 2020

Crash reason:
 Exception:  E1212012
 Location:   00007FF8A735A839
 Message:    Assertion failed at line 239 of /home/jgr/openttd/cross-win64/src/road_map.h: MayHaveRoad(t)

Within context:
     0: RunTileLoop: tile: 277x328

OpenTTD version:
 Version:    jgrpp-0.32.4 (0)
 NewGRF ver: 1a006d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Dec 13 2019 21:20:30
 Configure:  ./configure --host=x86_64-w64-mingw32 --prefix=/home/jgr/mingw64/ CFLAGS=-I/home/jgr/mingw64/include LDFLAGS=-L/home/jgr/mingw64/lib --without-sdl --without-icu --with-lzo2=/home/jgr/mingw64/lib/liblzo2.a --without-uniscribe
 Defines:    MINGW _FORTIFY_SOURCE=2 WITH_SSE WITH_DBGHELP WITH_BFD WITH_BITMATH_BUILTINS WITH_DEMANGLE WIN WITH_ZLIB WITH_LIBLZMA LZMA_API_STATIC WITH_LZO _SQ64 WITH_PNG WIN32_ENABLE_DIRECTMUSIC_SUPPORT UNICODE _UNICODE WITH_PERSONAL_DIR

Stack trace:
 00000000 00000000 00000016 00000000 A7A246B8 00007FF8 00080000 00000000
 E1212012 00000000 00000000 00000000 A735A839 00007FF8 00000000 00000000
 00000001 00000000 00000080 00000000 00000100 00000000 000D7A30 00000000
 00000080 00000000 A9781DE1 00007FF8 00080000 00000000 00080000 00000000
 000D7A20 00000000 80000000 00000000 00000015 00000000 00000015 00000000
 00000001 00007FF8 00000001 00007FF8 00000101 00000000 00000000 00000000
 C8C0471D 000094CA 00000000 00000000 00000000 00000000 A79BAE7B 00007FF8
 00000016 00000000 00080000 00000000 00000016 00000000 A7A246B8 00007FF8
 00000000 00000000 00000000 00000000 000D7A20 00000000 A7C07DC7 00007FF8
 0A0E1A10 00000000 00E31D60 00000000 0414D400 00000000 0414D0C0 00000000
 01EF9D80 00000000 A79BF28B 00007FF8 00000001 00000000 00000030 00000003
 00000006 00000000 002908A8 00000000 09090101 00000000 00000010 0000007C
 99000990 00007FF8 04BFF1F0 00000000 00000082 00000000 0414CB48 00000000
 00000000 00000000 00000001 00000000 000D7A20 00000000 00000000 00000000
 00000000 00000000 A978083D 00007FF8 00080000 00000000 00080000 00000000
 00000000 00000000 000D7A30 00000000 00000000 00000000 00000030 00000002
 062C0066 00000000 00000202 00000000 00000000 00000000 00050023 00000000
 6621FAC9 00000438 00000251 00000000 000D7A30 00000000 A7C50B00 00007FF8
 00000000 00000000 A7BE0000 00007FF8 00000001 00000000 00000001 00000000
 00000000 00000000 00002010 00000000 000D7A30 00000000 A977FC11 00007FF8
 A7C50B00 00007FF8 00080000 00000000 0414CD50 00000000 00000000 00000000
 00000000 00000000 00000001 00000000 000D7A30 00000000 A7C52BF0 00007FF8
 00010003 00000000 0414CF70 00000000 0414CF70 00000000 000D7A30 00000000
 0414CF70 00000000 00000000 00000000 00000017 00000000 000000F8 00000000

Registers:
 RAX: 00007FF8A7C10A2A RBX: 0000000000000016 RCX: 0000000004BFF1F0 RDX: 0000000004BFF1F0
 RSI: 00007FF8A7A246B8 RDI: 0000000000000000 RBP: 0000000000E31D68 RSP: 000000000414C990
 R8:  0401A30100002A2C R9:  0000000000000001 R10: 00007FF8A7C50C03 R11: 000000000004053C
 R12: 0000000000000910 R13: 0000000000000000 R14: 0000000000587080 R15: 0000000000000001
 RIP: 00007FF8A735A839 EFLAGS: 00000206

 Bytes at instruction pointer:
 0F 1F 44 00 00 48 8B 8C 24 C0 00 00 00 48 33 CC E8 C2 EE 04 00 48 81 C4

Operating system:
 Name:     Windows
 Release:  10.0.18363 ()
 Compiler: GCC 9.2.0 "9.2-win32 20191008"

Configuration:
 Blitter:      32bpp-sse2-anim
 Graphics set: OpenGFX (7019)
 Language:     D:\게임\Openttd\lang\korean.lng
 Music driver: dmusic
 Music set:    OpenMSX (96)
 Network:      no
 Sound driver: win32
 Sound set:    OpenSFX (87)
 Video driver: win32
 Pathfinder:   YAPF YAPF YAPF

Fonts:
 Small:  굴림
 Medium: 굴림
 Large:  굴림
 Mono:   sprite

Map size: 0x100000 (1024 x 1024)

AI Configuration (local: 0) (current: 16):
  0: Human

Libraries:
 LZMA:       5.2.1
 LZO:        2.09
 PNG:        1.5.23
 Zlib:       1.2.8

Module information:
 D:\게임\Openttd\openttd.exe handle: 0000000000400000 size: 49017559 crc: 8C7C27BD date: 2019-12-13 12:22:02
 C:\Windows\SYSTEM32\ntdll.dll handle: 00007ff8a9740000 size: 2000168 crc: 91C1FCE6 date: 2019-10-07 02:56:49
 C:\Windows\System32\KERNEL32.DLL handle: 00007ff8a8f50000 size: 722288 crc: FF4820CE date: 2019-10-07 02:56:29
 C:\Windows\System32\KERNELBASE.dll handle: 00007ff8a7320000 size: 2762296 crc: DF5CB0C1 date: 2019-12-10 23:17:54
 C:\Windows\System32\ADVAPI32.dll handle: 00007ff8a8c10000 size: 654912 crc: 37E52142 date: 2019-10-07 02:56:26
 C:\Windows\System32\msvcrt.dll handle: 00007ff8a7990000 size: 638072 crc: 162578A8 date: 2019-03-19 04:44:35
 C:\Windows\System32\sechost.dll handle: 00007ff8a8e80000 size: 606112 crc: 0A9F850D date: 2019-10-07 02:56:49
 C:\Windows\System32\RPCRT4.dll handle: 00007ff8a7870000 size: 1171704 crc: 556397DF date: 2019-12-08 00:52:22
 C:\Windows\System32\GDI32.dll handle: 00007ff8a9010000 size: 147912 crc: D05A781B date: 2019-03-19 04:44:06
 C:\Windows\System32\win32u.dll handle: 00007ff8a66d0000 size: 127272 crc: E59E4C10 date: 2019-12-10 23:17:52
 C:\Windows\System32\gdi32full.dll handle: 00007ff8a70b0000 size: 1647072 crc: 2FE73A8C date: 2019-12-10 23:17:54
 C:\Windows\System32\msvcp_win.dll handle: 00007ff8a7650000 size: 639400 crc: 13F940AD date: 2019-10-07 02:56:47
 C:\Windows\System32\ucrtbase.dll handle: 00007ff8a76f0000 size: 1023128 crc: 38CC2E73 date: 2019-10-07 02:56:47
 C:\Windows\System32\USER32.dll handle: 00007ff8a7be0000 size: 1656600 crc: B94B0BF2 date: 2019-12-10 23:17:52
 C:\Windows\System32\IMM32.dll handle: 00007ff8a8f20000 size: 176152 crc: 2F06A7FC date: 2019-10-07 02:56:50
 C:\Windows\System32\ole32.dll handle: 00007ff8a88d0000 size: 1395600 crc: A9A1AAED date: 2019-10-07 02:56:45
 C:\Windows\System32\combase.dll handle: 00007ff8a7ea0000 size: 3371928 crc: 876C7EF0 date: 2019-12-08 00:52:21
 C:\Windows\System32\bcryptPrimitives.dll handle: 00007ff8a72a0000 size: 524216 crc: DFD51AB1 date: 2019-10-07 02:56:49
 C:\Windows\System32\SHELL32.dll handle: 00007ff8a81e0000 size: 7263992 crc: BC5DBF8F date: 2019-12-10 23:17:53
 C:\Windows\System32\cfgmgr32.dll handle: 00007ff8a7250000 size: 293344 crc: 692DD58F date: 2019-10-07 02:56:48
 C:\Windows\System32\shcore.dll handle: 00007ff8a9520000 size: 684352 crc: F474ABD7 date: 2019-03-19 04:44:21
 C:\Windows\System32\windows.storage.dll handle: 00007ff8a67b0000 size: 7905000 crc: 952B50F5 date: 2019-12-10 23:17:52
 C:\Windows\System32\profapi.dll handle: 00007ff8a6690000 size: 110280 crc: 468DCA89 date: 2019-03-19 04:44:36
 C:\Windows\System32\powrprof.dll handle: 00007ff8a6640000 size: 291336 crc: 5EA3DD21 date: 2019-03-19 04:44:35
 C:\Windows\System32\UMPDC.dll handle: 00007ff8a6610000 size: 54960 crc: DD4A4D6A date: 2019-03-19 04:43:49
 C:\Windows\System32\shlwapi.dll handle: 00007ff8a96a0000 size: 329200 crc: AC7F2587 date: 2019-03-19 04:45:05
 C:\Windows\System32\kernel.appcore.dll handle: 00007ff8a6620000 size: 59088 crc: E549CD16 date: 2019-03-19 04:44:15
 C:\Windows\System32\cryptsp.dll handle: 00007ff8a75d0000 size: 80112 crc: 4C3EEAA9 date: 2019-03-19 04:44:33
 C:\Windows\System32\WS2_32.dll handle: 00007ff8a8d40000 size: 442704 crc: 2DDECC74 date: 2019-10-07 02:56:49
 C:\Windows\SYSTEM32\WINMM.dll handle: 00007ff8a4590000 size: 129880 crc: 55B5B362 date: 2019-03-19 04:43:47
 C:\Windows\SYSTEM32\WINMMBASE.dll handle: 00007ff8a4550000 size: 169632 crc: 8AE99BA1 date: 2019-03-19 04:43:47
 C:\Windows\system32\uxtheme.dll handle: 00007ff8a4990000 size: 606720 crc: ABDDBC69 date: 2019-12-08 00:52:21
 C:\Windows\System32\MSCTF.dll handle: 00007ff8a8a30000 size: 1261464 crc: 8C540C9A date: 2019-12-10 23:17:53
 C:\Windows\System32\OLEAUT32.dll handle: 00007ff8a95d0000 size: 797112 crc: B890FF49 date: 2019-12-10 23:17:53
 C:\Windows\SYSTEM32\TextInputFramework.dll handle: 00007ff89eab0000 size: 642208 crc: 03AAAE2A date: 2019-10-07 02:56:37
 C:\Windows\SYSTEM32\CoreUIComponents.dll handle: 00007ff8a2470000 size: 3327256 crc: E389630F date: 2019-10-07 02:56:35
 C:\Windows\SYSTEM32\CoreMessaging.dll handle: 00007ff8a4470000 size: 859632 crc: 31890910 date: 2019-03-19 04:44:30
 C:\Windows\SYSTEM32\ntmarta.dll handle: 00007ff8a5670000 size: 181856 crc: 06EC83CA date: 2019-03-19 04:44:35
 C:\Windows\SYSTEM32\wintypes.dll handle: 00007ff8a2230000 size: 1394168 crc: 3F216877 date: 2019-12-08 00:52:21
 C:\Windows\SYSTEM32\iertutil.dll handle: 00007ff89a680000 size: 2772272 crc: A45EDA15 date: 2019-12-08 00:52:23
 C:\Windows\System32\clbcatq.dll handle: 00007ff8a7d80000 size: 643752 crc: C1F090C7 date: 2019-03-19 04:44:30
 C:\Windows\SYSTEM32\PROPSYS.dll handle: 00007ff8a2fd0000 size: 977688 crc: C4E7943E date: 2019-10-07 02:56:38
 C:\Windows\SYSTEM32\VERSION.dll handle: 00007ff8a1320000 size: 30680 crc: B07A186D date: 2019-03-19 04:45:05
 C:\Windows\System32\IME\IMEKR\imkrapi.dll handle: 00007ff88d3e0000 size: 241464 crc: 598EF72D date: 2019-03-19 04:46:54
 C:\Windows\System32\IME\shared\imjkapi.dll handle: 00007ff89adc0000 size: 237880 crc: F074ACB1 date: 2019-03-19 04:45:40
 C:\Windows\system32\mswsock.dll handle: 00007ff8a5e80000 size: 407544 crc: 4F05F9C0 date: 2019-03-19 04:44:33
 C:\Windows\SYSTEM32\MMDevAPI.DLL handle: 00007ff8a18e0000 size: 449888 crc: A7B29868 date: 2019-10-07 02:56:24
 C:\Windows\SYSTEM32\DEVOBJ.dll handle: 00007ff8a6410000 size: 159112 crc: E7C8A00D date: 2019-10-07 02:56:48
 C:\Windows\SYSTEM32\wdmaud.drv handle: 00007ff88cbb0000 size: 253952 crc: 0D3BE49A date: 2019-03-19 04:43:47
 C:\Windows\SYSTEM32\ksuser.dll handle: 00007ff8a2f10000 size: 23264 crc: B862C2FB date: 2019-03-19 04:43:47
 C:\Windows\SYSTEM32\AVRT.dll handle: 00007ff8a2a80000 size: 30672 crc: CC5AFD63 date: 2019-03-19 04:43:47
 C:\Windows\SYSTEM32\AUDIOSES.DLL handle: 00007ff8a19c0000 size: 1413912 crc: 86AACF5C date: 2019-12-08 00:52:13
 C:\Windows\SYSTEM32\msacm32.drv handle: 00007ff89ec70000 size: 29184 crc: DCE0859B date: 2019-03-19 04:43:47
 C:\Windows\SYSTEM32\MSACM32.dll handle: 00007ff890920000 size: 107640 crc: C340459C date: 2019-03-19 04:43:47
 C:\Windows\SYSTEM32\midimap.dll handle: 00007ff89ae90000 size: 25600 crc: 1A533078 date: 2019-03-19 04:43:47
 C:\Windows\System32\IME\IMEKR\imkrtip.dll handle: 00007ff88caa0000 size: 837432 crc: 0328ACC5 date: 2019-03-19 04:46:54
 C:\Windows\System32\IME\shared\imetip.dll handle: 00007ff88c8b0000 size: 1266488 crc: 269AACA5 date: 2019-03-19 04:45:40
 C:\Windows\SYSTEM32\OLEACC.dll handle: 00007ff8a4740000 size: 395776 crc: BABEA70D date: 2019-03-19 04:45:00
 C:\Windows\SYSTEM32\DUI70.dll handle: 00007ff8890c0000 size: 1748992 crc: C0174F6E date: 2019-03-19 04:44:47
 C:\Windows\System32\dmusic.dll handle: 00007ff891120000 size: 132608 crc: C9F5B874 date: 2019-03-19 04:45:38
 C:\Windows\System32\DSOUND.dll handle: 00007ff88a2c0000 size: 602112 crc: C9C6543E date: 2019-03-19 04:43:47
 C:\Windows\System32\bcrypt.dll handle: 00007ff8a6f30000 size: 144376 crc: 49BE6FB0 date: 2019-10-07 02:56:48
 C:\Windows\System32\dmsynth.dll handle: 00007ff8910a0000 size: 122880 crc: 408A0AD2 date: 2019-03-19 04:45:38
 C:\Windows\SYSTEM32\resourcepolicyclient.dll handle: 00007ff8a4cc0000 size: 70256 crc: 6783400B date: 2019-03-19 04:44:04
 C:\Windows\System32\Windows.UI.dll handle: 00007ff89bb40000 size: 1383856 crc: 2FA5BFF4 date: 2019-10-07 02:56:29
 C:\Windows\System32\InputHost.dll handle: 00007ff89a560000 size: 1150240 crc: 1305BF7F date: 2019-10-07 02:56:37
 C:\Windows\System32\psapi.dll handle: 00007ff8a9040000 size: 18832 crc: BED9353E date: 2019-03-19 04:44:28

Events: i, nDcij

---- gamelog start ----
Tick 0: game loaded
Conversion from OTTD savegame without gamelog: version 90, 0
Revision text changed to 1.6.1, savegame version 195, not modified, _openttd_newgrf_version = 0x16186bd9
New game mode: 2 landscape: 0
Tick 0: GRF config changed
Added NewGRF: GRF ID 544B5555, checksum 7D1BDEE768822F7135630508D4D9F176, filename: korea_train_set-1.6.10\ko_train_set.grf (matches GRFID only)
Added NewGRF: GRF ID 544B0202, checksum C336DF8D4ED416B99892E403303C9CA7, filename: korean_bus_set-0.3.6\ko_bus_set.grf (md5sum matches)
Tick 0: game loaded
Revision text changed to jgrpp-0.32.3, savegame version 217, not modified, _openttd_newgrf_version = 0x1a006d64
Missing NewGRF: GRF ID 544B5555, filename: korea_train_set-1.6.10\ko_train_set.grf (matches GRFID only)
Missing NewGRF: GRF ID 544B0202, filename: korean_bus_set-0.3.6\ko_bus_set.grf (md5sum matches)
Tick 0: GRF config changed
Added NewGRF: GRF ID 544B5555, checksum 7529155253259859D14EF3BA43E09EAD, filename: korea_train_set-1.6.10\ko_train_set.grf (matches GRFID only)
Added NewGRF: GRF ID 4B570001, checksum 88445EBC1103ACEBE48B3E5CF4A0EAC5, filename: kiwitree_station_set-0.7.3\kws1.grf (matches GRFID only)
Added NewGRF: GRF ID 4B570002, checksum 78900E9D19A29FFB0EA7DB07B8BBA400, filename: kiwitree_station_set_part_2-0.7.3\kws2.grf (matches GRFID only)
Added NewGRF: GRF ID 4B4F4230, checksum 415AEE6B3B63FAC286F45915BB43C99F, unknown GRF
Tick 0: game loaded
New game mode: 1 landscape: 0
Tick 6702: settings changed
Setting changed: construction.command_pause_level : 1 -> 3
Tick 42608: GRF config changed
Added NewGRF: GRF ID 544B0202, checksum C336DF8D4ED416B99892E403303C9CA7, filename: korean_bus_set-0.3.6\ko_bus_set.grf (md5sum matches)
Tick 44943: GRF config changed
Added NewGRF: GRF ID 4A4B0102, checksum E266EACC1B3452D7538497F1332100DB, filename: korean_bus_set_expansion-v1.17.0\kbs_expand_1.17.0.grf (md5sum matches)
Tick 37882: settings changed
Setting changed: construction.max_tunnel_length : 64 -> 65
Tick 37890: settings changed
Setting changed: construction.max_tunnel_length : 65 -> 66
Tick 37897: settings changed
Setting changed: construction.max_tunnel_length : 66 -> 67
Tick 37907: settings changed
Setting changed: construction.max_tunnel_length : 67 -> 68
Tick 37915: settings changed
Setting changed: construction.max_tunnel_length : 68 -> 69
Tick 37923: settings changed
Setting changed: construction.max_tunnel_length : 69 -> 70
Tick 37930: settings changed
Setting changed: construction.max_tunnel_length : 70 -> 71
Tick 37936: settings changed
Setting changed: construction.max_tunnel_length : 71 -> 72
Tick 37942: settings changed
Setting changed: construction.max_tunnel_length : 72 -> 73
Tick 37950: settings changed
Setting changed: construction.max_tunnel_length : 73 -> 74
Tick 37957: settings changed
Setting changed: construction.max_tunnel_length : 74 -> 75
Tick 37963: settings changed
Setting changed: construction.max_tunnel_length : 75 -> 76
Tick 37970: settings changed
Setting changed: construction.max_tunnel_length : 76 -> 77
Tick 37976: settings changed
Setting changed: construction.max_tunnel_length : 77 -> 78
Tick 37982: settings changed
Setting changed: construction.max_tunnel_length : 78 -> 79
Tick 37988: settings changed
Setting changed: construction.max_tunnel_length : 79 -> 80
Tick 37994: settings changed
Setting changed: construction.max_tunnel_length : 80 -> 81
Tick 38000: settings changed
Setting changed: construction.max_tunnel_length : 81 -> 82
Tick 38066: settings changed
Setting changed: construction.max_tunnel_length : 82 -> 50
Tick 38146: settings changed
Setting changed: construction.max_tunnel_length : 50 -> 150
Tick 15428: game loaded
Revision text changed to jgrpp-0.32.4, savegame version 217, not modified, _openttd_newgrf_version = 0x1a006d64
Tick 15482: game loaded
Compatible NewGRF loaded: GRF ID 544B5555, checksum 3C6D4F008CCA9EB6F5C0F09846F5D910, filename: korea_train_set-1.6.10\ko_train_set.grf (md5sum matches)
Compatible NewGRF loaded: GRF ID 4B570001, checksum FCFBF8E3C23CBA08F708373D7CD2066A, filename: kiwitree_station_set-0.7.3\kws1.grf (md5sum matches)
Compatible NewGRF loaded: GRF ID 4B570002, checksum AC4FACFECFA2E092FE19D4CE85D80177, filename: kiwitree_station_set_part_2-0.7.3\kws2.grf (md5sum matches)
Missing NewGRF: GRF ID 4B4F4230, unknown GRF
---- gamelog end ----

Recent news messages (5 of 5):
(2008-04-15) StringID: 705, Type: 10, Ref1: 2, 751, Ref2: 0, 4294967295
(2008-04-14) StringID: 707, Type: 10, Ref1: 2, 57, Ref2: 0, 4294967295
(2008-04-11) StringID: 705, Type: 10, Ref1: 2, 427, Ref2: 0, 4294967295
(2008-04-10) StringID: 705, Type: 10, Ref1: 2, 738, Ref2: 0, 4294967295
(2008-04-07) StringID: 677, Type: 4, Ref1: 4, 702, Ref2: 0, 4294967295

Command Log:
 Showing most recent 3 of 3 commands
   0 | 2008-04-04, 70,   0 | --m----- |        0 x       0, p1: 0x00000008, p2: 0x00000000, cc:   0, lc:   0, cmd: 0x0000003F (CmdPause)
   1 | 2008-04-04, 70,   0 | --m----- |        0 x       0, p1: 0x00000001, p2: 0x00000000, cc:   0, lc:   0, cmd: 0x0000003F (CmdPause)
   2 | 2008-04-04, 70,   0 | --m----- |        0 x       0, p1: 0x00000002, p2: 0x00000000, cc:   0, lc:   0, cmd: 0x0000003F (CmdPause)

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] KERNELBASE           0x00007FF8A735A839 RaiseException + 105
[01] msvcrt               0x00007FF8A79BAE7B raise + 539
[02] msvcrt               0x00007FF8A79BF28B abort + 27
[03] openttd              0x000000000056F066
[04] openttd              0x00000000005B0FB9
[05] openttd              0x00000000005BB35A
[06] openttd              0x00000000004E8645
[07] openttd              0x0000000000579817
[08] openttd              0x0000000000579B50
[09] openttd              0x00000000006E0EDD
[10] openttd              0x000000000057128B
[11] openttd              0x000000000058870D
[12] openttd              0x00000000004013C7
[13] openttd              0x00000000004014CB
[14] KERNEL32             0x00007FF8A8F67BD4 BaseThreadInitThunk + 20
[15] ntdll                0x00007FF8A97ACED1 RtlUserThreadStart + 33

*** End of additional info ***

**Comment by JGRennison** [comment]
Thanks for reporting this.
A savegame would be useful.
In the absence of a savegame to be sure, it is probably this issue https://github.com/JGRennison/OpenTTD-patches/commit/b3e46cbe002a0ab242fb4bca63e09c37a3c6fa7c which has been fixed recently.
