### ISSUE TITLE
Bus stop sprite numbers inconsistent with official OpenTTD releases

### ISSUE THREAD

**Issue by Eriphia** [JGRennison/OpenTTD-patches#129]
## Version of OpenTTD
JGR 0.33, JGR 0.32
Does not happen in JGR 0.30
## Expected result
In official OpenTTD releases, bus stop sprites for "straight" bus stops are registered between 5970 and 5973.

## Actual result
Bus stop sprites for "straight" bus stops are registered between 5974 and 5977

## Steps to reproduce
Place a "straight" bus stop, and use the sprite aligner to locate the sprite.

## Background
I've made a NewGRF that replaces bus stop sprites, and I designed it using the latest version of JGR. I found out that it doesn't work for official OpenTTD releases, and that the sprites would show up 4 sprite numbers _after_ the bus stop sprites, which is where truck stops are saved.

Image to show the difference between versions: https://i.imgur.com/5IpDAux.png

**Comment by JGRennison** [comment]
Thanks for reporting this, this should be fixed now.
