### ISSUE TITLE
Compiler warning because of korean language file

### ISSUE THREAD

**Issue by auge8472** [JGRennison/OpenTTD-patches#133]
## What happens?

When I compile the version 0.33.2 I got a warning when compiling the korean language file.

~~~
~/OpenTTD-patches/src/lang/korean.txt:6215: warning: STR_SCHDISPATCH_SUMMARY_L2: Param idx #2 '<empty>' doesn't match with template command 'DATE_WALLCLOCK_TINY'
~~~

It *might* be caused by one of the latest PR belonging new translations by @telk5093. But I don't know if it happened also with one of the latest previous versions. I normally scroll back in the console window to see what happened during the compiler run but I am not sure if I did this every single time. This compiler run (for version 0.33.2) I saw the error for the first time.

## Version of OpenTTD

JGRPP 0.33.2

## Steps to reproduce

Compile the tag jgrpp-0.33.2 in Ubuntu 18.04.4

**Comment by telk5093** [comment]
I didn't notice that the string has been changed.
The string ``STR_SCHDISPATCH_SUMMARY_L2`` contains one ``{STRING}`` and two ``{DATE_WALLCLOCK_TINY}``s, but I missed one.
I made a PR again which will fix this. Sorry!

**Comment by JGRennison** [comment]
Not to worry, I've merged the PR which should fix the warning.
