### ISSUE TITLE
Game crash when trying to boot up the game

### ISSUE THREAD

**Issue by GrafHammerman** [JGRennison/OpenTTD-patches#134]
## Version of OpenTTD
jgrpp-0.33.1 (0)
## Expected result
Start the game.
## Actual result
Game crashing.
## Steps to reproduce
Copied the game folder and mods from my laptop to another laptop and started a new game, played for a while and closed the game, when i start again the game, freezes in a black screen and crashes.
[crash.txt](https://github.com/JGRennison/OpenTTD-patches/files/4272365/crash.txt)

**Comment by JGRennison** [comment]
This issue is fixed in 0.33.2, or alternatively, the 64-bit version of 0.33.1 does not have this issue.
