### ISSUE TITLE
Game crashing when trying to buy new vehicle in maglev depot (MP game)

### ISSUE THREAD

**Issue by Mazth** [JGRennison/OpenTTD-patches#136]
## Version of OpenTTD
jgrpp-0.33.2

## Expected result
buying new vehicle in maglev depot

## Actual result
game crashes with crash screen
Assertion failed at line 1042 of /home/jgr/openttd/cross-win64/src/gfx.cpp: sprite->height > 0

## Steps to reproduce
crash log attached
[crash.log](https://github.com/JGRennison/OpenTTD-patches/files/4333233/crash.log)
[Northern Islands Express, 21st Sep 1995.zip](https://github.com/JGRennison/OpenTTD-patches/files/4333249/Northern.Islands.Express.21st.Sep.1995.zip)

[edit: added savegame]

**Comment by JGRennison** [comment]
Thanks for the report, this should be addressed by https://github.com/JGRennison/OpenTTD-patches/commit/722af5f77a1d38b46117a18c0729a384a3d0c5a2

**Comment by Mazth** [comment]
Nice, thanks!
Somehow I managed to fix it with resetting newgrfs, but there were many loaded so hard to find the culprit and this seems a more permanent solution anyway.
