### ISSUE TITLE
Crash on attempting to move in the viewport

### ISSUE THREAD

**Issue by swlines** [JGRennison/OpenTTD-patches#137]
## Version of OpenTTD
jgrpp-0.33.2 (fa73e42)

## Expected result
Not to crash. 

## Actual result
A dialog appears with "OpenTTD has encountered an error" and "NOT_REACHED triggered at line 529 of /Users/tom/temp/openttd/src/viewport.cpp". OpenTTD locks in such a way that it cannot produce a crash.log or crash.sav and requires a reboot to escape. This happens on macOS Catalina and requires a reboot to remove the process completely.

## Steps to reproduce
A good number of train windows open (see screenshot) and then attempt to move around the map using an arrow and shift, mostly. 
![Screenshot 2020-03-28 at 16 21 02](https://user-images.githubusercontent.com/1021082/77828013-16da2800-7111-11ea-96a8-9c2e4a3136df.jpg)

**Comment by JGRennison** [comment]
Thanks for reporting this.
I was not able to reproduce the bug on my system, however I've made a fix which ought to address the issue.
It would be useful if you could see if the most recent commit fixes the issue on your system.
Many thanks.

**Comment by swlines** [comment]
I'll give that a go - it's quite a hard one to reproduce as it tends to just happen mid game. 

I'm going to see if I can find out and see what is causing the crash to just hang the process completely rather than creating a crash log/sav.

**Comment by swlines** [comment]
It looks like this one is now fixed as I haven't been able to replicate it with that patch applied, thanks!
