### ISSUE TITLE
Patch inclusion request: Minimum Town Distance

### ISSUE THREAD

**Issue by UntouchedWagons** [JGRennison/OpenTTD-patches#14]
Hi there

I would like to request that you add a patch to your patchpack: [Minimum Town Distance](https://www.tt-forums.net/viewtopic.php?f=33&t=33625&start=40#p1095146) The linked patch will only work on two of the four files but it's not hard to apply the failed changes manually.

Thanks

**Comment by JGRennison** [comment]
This looks quite reasonable, so adding it shouldn't be a problem.
I'll look into it sometime soon.

**Comment by UntouchedWagons** [comment]
Sweet, thanks.

**Comment by JGRennison** [comment]
I've added this in commit 7b88f7a2
