### ISSUE TITLE
Scheduled dispatch: incorrect departure time on the first dispatch

### ISSUE THREAD

**Issue by vtual** [JGRennison/OpenTTD-patches#141]
I love the scheduled dispatch functionality. Were I fluent in C++, I would definitely spend some time to add new features.

I'm not sure however if it is a bug or me not understanding enough how the functionality works.

## Version of OpenTTD
JGRPP 0.33.2

## Steps to reproduce
The attached save is a simple vanilla game, with two trains in a depot and a scheduled dispatch every 10 minutes.

**1. The first scheduled vehicle starts at a late dispatch slot**

When the first vehicle is started and reaches its first stop, its timetable start time is set quite late (20.10), while there are nearer departure slots (19.50 or 20.00).

**2. The second vehicle starts at an offset**

When the second vehicle reaches its first stop, its departure time seems to be offset by the dwell time at the first stop. Eg. if there is a 3 minute dwell time, instead of departing at 20.20 it will depart at 20.23.

On both cases, the behaviour becomes correct on later dispatches.

[Horni Vysupy Transport, 23 Jan 2000.zip](https://github.com/JGRennison/OpenTTD-patches/files/4456164/Horni.Vysupy.Transport.23.Jan.2000.zip)

**Comment by JGRennison** [comment]
Thanks a lot for this. I've made some changes which should address these two issues, they'll be in the next release.

**Comment by vtual** [comment]
Cool thanks!
