### ISSUE TITLE
Shift doesn't work with korean+fcitx

### ISSUE THREAD

**Issue by SJang1** [JGRennison/OpenTTD-patches#142]
## Version of OpenTTD
master and even before(a lot before)

## Expected result
Input Korean with Shift works

## Actual result
It doesn't recognize shift key.

## Steps to reproduce
Same to #100 , with fcitx thing and SDL2.
Shift key doesn't work with hangul(korean) when using fcitx. (I've not checked the other methods)

Environment : Linux (Fedora 31 / Arch)

**Comment by JGRennison** [comment]
As far as I can tell, shift key presses are transmitted to fcitx, and it also works as a modifier key.
What is fctix supposed to be doing with the shift key, that it isn't doing?

**Comment by SJang1** [comment]
In korean, shift key is used to input things like 가 to 까 (add same letter twice if supported), and like on english, it needs to input $ than 4 like it, but those doesn't work.

**Comment by JGRennison** [comment]
Does the shift key work in a non text-entry context, e.g. to to show a cost estimate instead of doing a command?

**Comment by SJang1** [comment]
In non-text entry context, it looks like it is fixed to english, and shift does work.
