### ISSUE TITLE
Minimap feature is implemented in stable and works weird in JGRPP

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#143]
## Version of OpenTTD
jgrpp-0.33.x ~ 0.34.1

## Expected result
``screenshot minimap <file_name>`` saves top-view minimap screenshot into <file_name>

## Actual result
Minimap screenshot is taken but its name is ``screenshot.png`` or ``screenshot#1.png`` ...

## Steps to reproduce
First, thanks for your nice maintainance for minimap codes.
By referencing in this project's codes, my PR is merged [the minimap screenshot feature into main project](https://github.com/OpenTTD/OpenTTD/pull/7817).
But ``minimap`` command still exists in JGRPP so both command ``minimap`` and ``screenshot minimap`` exist.
And ``screenshot minimap <file_name>`` does not recognize the <file_name> parameter at only JGRPP.

**Comment by JGRennison** [comment]
This is fixed in 0.34.2
