### ISSUE TITLE
Departure board changes when train enter and leave depot

### ISSUE THREAD

**Issue by GrupoDO** [JGRennison/OpenTTD-patches#144]
## Version of OpenTTD
jgr patch 0.34.1

## Expected result
Time on departure board must not change
## Actual result
Time is changing when train enter to depot and change again when train leaves the depot
## Steps to reproduce
1.- Create a timetable with several stations and a go to depot order like this: Station A -> Station B -> Station C -> Goto depot and wait -> Station C -> Station B -> Station A
2.- Run the train with Autofill option enables to calculate the times for each segment
3.- Add departure slots.
4.- Dispacth the train
5.- Open the Station C's departure board and see how the departure time changes when the train enters to depot and when the train leaves the depot.

You can see this behavior here: https://youtu.be/_rknd8ehZMI

**Comment by JGRennison** [comment]
Thanks, should be fixed now.

**Comment by GrupoDO** [comment]
@JGRennison great! Now this works fine. Thank you :)
