### ISSUE TITLE
Crash when using 'reverse behind signal'

### ISSUE THREAD

**Issue by kiwitreekor** [JGRennison/OpenTTD-patches#147]
## Version of OpenTTD
jgrpp-0.34.1

## Expected result
Game runs without crashing

## Actual result
Game crashes

## Steps to reproduce
![jgrpp_crash](https://user-images.githubusercontent.com/24273113/80269403-4701f000-86ea-11ea-833c-74c2f3e99bff.png)
1. Load the attached savegame
2. Start the train

[jgrpp_crash2.zip](https://github.com/JGRennison/OpenTTD-patches/files/4532235/jgrpp_crash2.zip)

**Comment by JGRennison** [comment]
Thanks, this should be fixed now.

**Comment by kiwitreekor** [comment]
Thanks! 👍
