### ISSUE TITLE
STR_MONEY_CHEAT_MULTIPLAYER has inconsistent name

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#148]
## Version of OpenTTD
Since ab99c1660131f5b13accd32238169359c0c38fd5

## Expected result
`STR_MONEY_CHEAT_MULTIPLAYER` should be `STR_CONFIG_SETTING_MONEY_CHEAT_MULTIPLAYER` like all other setting strings.
Similarly, `STR_MONEY_CHEAT_MULTIPLAYER_HELPTEXT` should be `STR_CONFIG_SETTING_MONEY_CHEAT_MULTIPLAYER_HELPTEXT` like all other setting description strings.

## Actual result
The aforementioned strings are still called `STR_MONEY_CHEAT_MULTIPLAYER` and `STR_MONEY_CHEAT_MULTIPLAYER_HELPTEXT`, as shown below.
https://github.com/JGRennison/OpenTTD-patches/blob/a3652b998e64a1fffcae69d4180e56638c996acc/src/lang/english.txt#L1191-L1192

## Steps to reproduce
Look for the string in the language files.

## Known Fix
Going through all the lang files as well as settings.ini, replace every instance of `STR_MONEY_CHEAT_MULTIPLAYER` with `STR_CONFIG_SETTING_MONEY_CHEAT_MULTIPLAYER` and replace every instance of `STR_MONEY_CHEAT_MULTIPLAYER_HELPTEXT` with `STR_CONFIG_SETTING_MONEY_CHEAT_MULTIPLAYER_HELPTEXT`.
https://github.com/JGRennison/OpenTTD-patches/blob/a3652b998e64a1fffcae69d4180e56638c996acc/src/table/settings.ini#L386-L387

**Comment by JGRennison** [comment]
Thanks
