### ISSUE TITLE
What toolchain do you use for compiling?

### ISSUE THREAD

**Issue by UntouchedWagons** [JGRennison/OpenTTD-patches#15]
Hi again. I want to try making my own patches using your patch pack as a base. I've got the dependencies installed in cygwin64 but when I try to compile it compilation fails because SOCKET was not declared in this scope. The same issue occurs in msys2. What do you do to compile openttd?

**Comment by JGRennison** [comment]
I do all my builds and testing on Linux.
For Windows builds I cross-compile using mingw. The Windows version of mingw should work as well.

**Comment by UntouchedWagons** [comment]
I spent about 10 to 12 hours trying to compile your patchpack under cygwin, cygwin64, mingw, mingw64 and visual studio. It just would not work.

**Comment by JGRennison** [comment]
I've pushed an update which should remove the problem with ssize_t in btree.h.

Are you able to build unpatched trunk with your build environment?

**Comment by UntouchedWagons** [comment]
I can only build unpatched trunk in visual studio, nothing else. I can't compile your patch pack in anything, not even visual studio. In mingw64 compilation fails for both trunk and your patch pack due to some missing [networking structures](https://gist.github.com/UntouchedWagons/b65351ebc2e92c7266dc87a33385c1ba)

**Comment by JGRennison** [comment]
What versions of mingw/gcc and visual studio are you using?

**Comment by UntouchedWagons** [comment]
I'm not sure how to find out what version of mingw I'm using, but I downloaded msys2-x86_64-20161025.exe which provides gcc 6.3.0. I'm using visual studio 2015 update 3

**Comment by JGRennison** [comment]
Closing this for now...
