### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by kiwitreekor** [JGRennison/OpenTTD-patches#150]
## Version of OpenTTD
jgrpp 0.34.2

## Expected result
Game runs without crashing

## Actual result
Game crashes

## Steps to reproduce
Load the attached savegame
[crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/4571420/crash.zip)

**Comment by JGRennison** [comment]
Thanks for this. It should be fixed now.

**Comment by kiwitreekor** [comment]
Thanks :)
