### ISSUE TITLE
Very large (8192x8192) screenshots are stored as large files, unusable with <32-64 GB RAM.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#151]
## Version of OpenTTD
jgrpp-0.34.2

## Expected result
If only there was an option that made it so very large screenshots (those that would normally be gigabytes in size), are stored as multiple files, where each file represents a quadrant (or smaller if the map's large enough) of the whole screenshot. This could potentially also allow for multithreading the screenshot process (especially for top-down screenshots).

## Actual result
Very large screenshots are stored as single files that are very big (multiple gigabytes), which can lead to being unable to even use them outside of services like Gigapan or cases where you have 32-64 GB RAM or more.

## Steps to reproduce
1. Load up an 8,192x8,192 map.
2. Take a full-map screenshot.
3. File size: 9 GB (M4J Network), can't be opened unless you have more than 32 GB RAM.

**Comment by JGRennison** [comment]
This problem is also apparent in trunk, I think that it'd be more suitable to direct any changes there.
A 4k x 4k full map screenshot is also too large for practical purposes.

Multi-threaded rendering is not practical given the overall architecture.

That said, just disabling the feature entirely for overly large map sizes where the output is not useful anyway would probably be a more pragmatic solution.

**Comment by James103** [comment]
Maybe add an option that allows you to take a (minimap) screenshot of a selected partial area of the map, instead of the whole map? For example, a minimap screenshot that encompasses just the 1024x1024 (or 2048x2048) area surrounding the central capital of the whole map. Useful for when you aren't on a 4K monitor, but you need a large screenshot of the map (such as 1024x1024 or 2048x2048 or even more)

**Comment by sam-cross** [comment]
I like the idea of segmenting into multiple files.

**Comment by James103** [comment]
Closing as unlikely to happen in practice.
