### ISSUE TITLE
Fix some typographical errors in comments

### ISSUE THREAD

**Issue by techgeeknz** [JGRennison/OpenTTD-patches#153]
## Version of OpenTTD
JGRPP ea06a0670d

## Expected result
Some spelling mistakes were found while familiarising myself with the source.

## Actual result
The spelling mistakes are fixed in the attached patch.

## Steps to reproduce

[fix_typos.diff.txt](https://github.com/JGRennison/OpenTTD-patches/files/4684965/fix_typos.diff.txt)

**Comment by JGRennison** [comment]
Thanks, this is applied now
