### ISSUE TITLE
SpringPP will soon start overlapping with the official branch, potentially causing problems in save/load

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#156]
## Version of OpenTTD
The bug will occur once a new savegame version (or two) is pushed to OpenTTD's official `master` branch, and then starting once you rebase the patch pack to said `master` branch. See OpenTTD/OpenTTD#8116

## Expected result
The enum compiles correctly, and save/load correctly distinguishes between SpringPP and the official branch.

## Actual result
There is a small but non-zero change that the enum may not compile, resulting in a broken build. Even if the build does succeed, save/load will not be able to distinguish SpringPP from the official master branch based on the savegame version alone, and it may end up handling some very new official release savegames (such as one from OpenTTD 1.11.0) as well as patchpack savegames (SpringPP in this case) incorrectly.

The offending enum is as follows, assuming `SLV_NEXT_VERSION` is the next version that is merged into the official branch, and similar for `SLV_VERSION_AFTER_NEXT`:
```
enum SaveLoadVersion : uint16 {
	...
	SLV_ENDING_YEAR,                        ///< 218  PR#7747 v1.10 Configurable ending year.
	SLV_NEXT_VERSION,                       ///< 219  PR#???? Next saveload version
	SLV_VERSION_AFTER_NEXT,                 ///< 220  PR#???? Version after next saveload version

	SL_MAX_VERSION,                         ///< 221  Highest possible saveload version

	SL_SPRING_2013_v2_0_102 = 220, // Duplicate entries mapping to the same value
	SL_SPRING_2013_v2_1_108 = 221, // Duplicate entries mapping to the same value
	SL_SPRING_2013_v2_1_147 = 222,
	SL_SPRING_2013_v2_3_XXX = 223,
	SL_SPRING_2013_v2_3_b3 = 224,
	SL_SPRING_2013_v2_3_b4 = 225,
	SL_SPRING_2013_v2_3_b5 = 226,
	SL_SPRING_2013_v2_4 = 227,
	SL_TRACE_RESTRICT_2000 = 2000,
	SL_TRACE_RESTRICT_2001 = 2001,
	SL_TRACE_RESTRICT_2002 = 2002,
	SL_JOKER_1_19 = 278,
	SL_JOKER_1_20 = 279,
	SL_JOKER_1_21 = 280,
	SL_JOKER_1_22 = 281,
	SL_JOKER_1_23 = 282,
	SL_JOKER_1_24 = 283,
	SL_JOKER_1_25 = 284,
	SL_JOKER_1_26 = 285,
	SL_JOKER_1_27 = 286,
	SL_CHILLPP_201 = 201,
	SL_CHILLPP_232 = 232,
	SL_CHILLPP_233 = 233,
};
```

## Steps to reproduce
Load a savegame saved in the official OpenTTD version 1.11.0 or higher.

**Comment by JGRennison** [comment]
This is not a problem. The code to distinguish SpringPP and ChillPP savegames from overlapping trunk savegame versions already exists. Take a look at `SlXvCheckSpecialSavegameVersions`.

**Comment by techgeeknz** [comment]
I don't see any JGRPP-specific IDs in `saveload.h`; so I'm curious; how does JGRPP resolve this issue between itself and trunk for its own savegames?

**Comment by JGRennison** [comment]
> I don't see any JGRPP-specific IDs in `saveload.h`; so I'm curious; how does JGRPP resolve this issue between itself and trunk for its own savegames?

The savegame version is | with SAVEGAME_VERSION_EXT (0x8000). The actual version data is written into a new chunk: SLXI.

See: https://github.com/JGRennison/OpenTTD-patches/blob/jgrpp/src/saveload/extended_ver_sl.cpp

**Comment by James103** [comment]
This is fixed in the official branch as per OpenTTD/OpenTTD#8116.
