### ISSUE TITLE
Cargo-based town growth computation can overflow

### ISSUE THREAD

**Issue by Yourself** [JGRennison/OpenTTD-patches#157]
## Version of OpenTTD
0.34.3

## Expected result
No integer overflow in town growth rates.

Line 3730 in town_cmd.cpp can overflow `uint32`.

Example numbers:
Normal town growth rate (`_settings_game.economy.town_growth_rate == 0`)
90% cargo growth dependency (`_settings_game.economy.town_growth_cargo_transported == 90`)
417/547 Passengers last month
172/303 Mail last month

For a town with 5 active stations and not currently funded the base grow count is 100. With normal town growth, the growth_multiplier is 1, so m will be right-shifted once making it 50.

inverse_m = 85899345;
passenger_ratio_fix15 = 24980;
mail_ratio_fix15 = 18600;
cargo_ratio_fix16 = 43580;
cargo_dependent_part = (cargo_ratio_fx16 * inverse_m * 90) >> 16 = 5140905928; // This overflows when assigning to cargo_dependent_part.

This causes town growth rates to behave very erratically.

**Comment by JGRennison** [comment]
Thanks for debugging this, should be fixed now.
