### ISSUE TITLE
In-game date in statusbar when loading TTD/TTO savegames is 1920 years earlier than expected.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#159]
## Version of OpenTTD
jgrpp-0.34.4

## Expected result
Loading TTO/TTD savegames, such as [#3601 - TRT01.zip](https://github.com/OpenTTD/OpenTTD/files/4573788/3601.-.TRT01.zip), should properly convert the year in the statusbar by adding 1920 to the year on load.

## Actual result
Loading TTO/TTD savegames do not convert the years. For example, a TTD savegame saved in 2070 loads as year 150 in jgrpp-0.34.4, but as 2070 in any official OpenTTD version.

## Steps to reproduce
1. Load the attached savegame.
2. Notice the in-game date in the statusbar (in this case, year 150).
3. Notice the in-game date in the cheat window / anywhere else (year 2070).
4. Use cheats to change the in-game date.
5. Notice that the in-game date in the statusbar is now the correct value.

**Comment by JGRennison** [comment]
Thanks, this should be fixed now.
