### ISSUE TITLE
Assertion failed at lines 464-465 of kdtree.hpp (when generating long and skinny maps)

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#160]
## Version of OpenTTD
jgrpp-0.34.4

## Expected result
The map generates as expected.

## Actual result
The game asserts here:
https://github.com/JGRennison/OpenTTD-patches/blob/27b92c352626d3318e2220e7b0d9269aa06c3329/src/core/kdtree.hpp#L465

If I reverse the map dimensions, the game instead asserts here:
https://github.com/JGRennison/OpenTTD-patches/blob/27b92c352626d3318e2220e7b0d9269aa06c3329/src/core/kdtree.hpp#L464

Upon clicking through the warning, the game closes itself without displaying a crash message. Crash info is still generated.
[crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/4829957/crash.zip)

## Steps to reproduce
1. Set the map generation settings as shown:
![image](https://user-images.githubusercontent.com/37945304/85682815-43f79180-b692-11ea-85fc-45b5471f0828.png)
2. Click "Generate".
3. Crash

**Comment by JGRennison** [comment]
Thanks, fixed in 15c600d64f9548c2a1130eb161bc9d86e06b1aef.
