### ISSUE TITLE
Game Crash Multiple Times

### ISSUE THREAD

**Issue by M4JGaming** [JGRennison/OpenTTD-patches#162]
## Version of OpenTTD
v0.34.4

## Expected result

Game running smoothly
![crash-20200627T021045Z](https://user-images.githubusercontent.com/59756187/85912496-d3cd4500-b824-11ea-9846-8f1150c1d7c7.png)

## Actual result
Game crashes on multiple occasions at roughly the same point. Recently, the Class 313, 315 and 317 NewGRF was added to the game, although the notes stated this NewGRF no longer caused crashes with JGRPP. Even after removing the NewGRF the game still crashed. Attached is the crash log as well as a screenshot of the game when the crash occured

## Steps to reproduce
[crash-20200627T021045Z.log](https://github.com/JGRennison/OpenTTD-patches/files/4839830/crash-20200627T021045Z.log)

**Comment by M4JGaming** [comment]
Update: Tried loading the emergency save, game ran for roughly 5 minutes then crashed again.

**Comment by JGRennison** [comment]
Could you also upload a savegame?
For the time being I'd suggest closing the departures window.

**Comment by M4JGaming** [comment]
I can't upload the saves here as GitHub doesn't accept .sav files and if I zip them the file size is too big.

I'll try closing the departures window and see if that works.

**Comment by M4JGaming** [comment]
Update #2: Closing departures window stopped the game crashing

**Comment by JGRennison** [comment]
Fixed in 0.35.0, 0.35.1
