### ISSUE TITLE
Finance window only expands one digit at a time

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#164]
## Version of OpenTTD
Working in: master-20200701
Broken in: jgrpp-0.34.4

## Expected result
Like in master, the finances window expands immediately to fit the very large amount of money present in the following savegame.

## Actual result
The finances window only expands one digit at a time, taking upwards of a minute to fit a full 2^63-1 money value.

## Steps to reproduce
1. Load the attached savegame.
2. Open your company's finances window.

## Savegame
[Gronnway Transport, 363576-09-15.zip](https://github.com/OpenTTD/OpenTTD/files/4861520/Gronnway.Transport.363576-09-15.zip)
(This savegame contains a single company with maxed-out (2^63-1) cash and company value, triggering the above bug.)

**Comment by JGRennison** [comment]
Thanks, this should be fixed now.
