### ISSUE TITLE
Suggestion: Improved breakdowns require servicing

### ISSUE THREAD

**Issue by Yourself** [JGRennison/OpenTTD-patches#168]
## Version of OpenTTD
0.34.3

## Expected result
Non-critical breakdowns are treated as requiring servicing so a slow train doesn't soldier on

## Actual result
Non-critical breakdowns result in slow vehicles clogging up routes until their normal maintenance period is up. 

## Steps to reproduce
N/A

This is actually a feature I'd like to work on myself but I wanted to get some feedback first about it since I'm not familiar with the intent or history behind the improved breakdowns feature. It looks like it's intentional that the non-critical breakdowns don't flag the vehicle as requiring service. This is somewhat annoying to deal with either requiring regular unskippable depot visits or mitigating the effect of slow trains with carefully designed passing sidings.

I have two ideas for features I'd like to add here:
* A setting that allows all non-critical breakdowns to require servicing.
- OR -
* A setting where non-critical breakdowns are only treated as requiring servicing for explicit maintain at depot orders (so a vehicle with a non-critical breakdown will only go for servicing at the next maintenance order in its list).

Of these I prefer the second option from a game play perspective, but architecturally it's a little more involved as the game currently doesn't distinguish between different types of "needing service".

**Comment by JGRennison** [comment]
At the moment, non-critical breakdowns only affect the vehicle for the duration of the breakdown, whereas critical breakdowns also reduce the maximum speed after the breakdown.
If vehicles were sent for servicing after a non-critical breakdown, by the time they got there the breakdown would likely be over and they'd be at full speed. This would be very disruptive in your first option.
