### ISSUE TITLE
Some conditional order strings should be splitted by condition

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#172]
## Version of OpenTTD
jgrpp-0.3x.x

## Explaination
At [here](https://github.com/JGRennison/OpenTTD-patches/blob/763a2826b60e0bcafa2ec3e65c6cf4560f5f6cf4/src/order_gui.cpp#L917), ``OCV_CARGO_ACCEPTANCE``, ``OCV_CARGO_WAITING`` are treated in the one _else_ block.
This makes me hard to translate some conditional order.

See this string please. I'll focus on three {STRING}s in the end:
```
STR_ORDER_CONDITIOAL_CARGO :Jump to order {COMMA} when {STRING} {STRING} {STRING}
```   
   
   
 1. **Accepted cargo** (``OCV_CARGO_ACCEPTANCE``)
 It becomes "Next station / accepts / Passengers" in english, for example.
 It should be "다음 역**이** / 승객**을** / 받을 때" in korean. Keep in mind the **bold** letters.

 1. **Wating cargo** (``OCV_CARGO_WAITING``)
 It becomes "Next station / has / Passengers" in english, for example.
 It should be "다음 역**에** / 승객**이** / 있을 때" in korean. Keep in mind the **bold** letters, again.
  (``다음 역 = Next station``, ``승객 = Passengers``, ``받을 때 = (when) accepts``, ``있을 때 = (when) has``)

As you can see above, Korean uses different bold letters([josa](https://en.wikipedia.org/wiki/Korean_postpositions)) for the same {STRING}. So I can't easily determine whic of translation of "Next station" would be either "다음 역이" or "다음 역에"

I think this problem is occured since many conditional order type is treated by [this one _else_ block](https://github.com/JGRennison/OpenTTD-patches/blob/763a2826b60e0bcafa2ec3e65c6cf4560f5f6cf4/src/order_gui.cpp#L917).
So, I think some conditions/strings should be splitted, such as ``STR_ORDER_CONDITIONAL_CARGO`` into two: ``STR_ORDER_CONDITIONAL_CARGO_WATING`` and ``STR_ORDER_CONDITIONAL_CARGO_ACCEPTED``.

**Comment by JGRennison** [comment]
I agree that splitting those seems the best solution.

I think it might be technically possible to do it with the gender/case system, but as gender looks to be already used for final vowel/consonant it would a bit convoluted.

**Comment by JGRennison** [comment]
It seems like the "next station" part could also be inlined into the STR_ORDER_CONDITIONAL_CARGO_ACCEPTANCE/STR_ORDER_CONDITIONAL_CARGO_WAITING string. I can't see that there will be a need to substitute some other value.

**Comment by JGRennison** [comment]
Is something like 05dc785f1 workable?

**Comment by telk5093** [comment]
I was also wondered why "Next station" is not inlined even though it is only used at STR_ORDER_CONTIONAL_CARGO.
Looks fine for me.

**Comment by JGRennison** [comment]
Thanks, that's merged now.
