### ISSUE TITLE
Suggestion: Option to ignore zoning, date, and other restrictions when funding houses

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#177]
## Version of OpenTTD
jgrpp-0.34.4

## Expected result
There should be an option that skips certain (sometimes arbitrary) checks when building a house in the scenario editor.
When this option is enabled,
* The date check is skipped. All houses can be built in all years/eras, even if the house is normally too old or too modern.
* The "only one allowed per town" limit check is skipped, allowing you to have multiple stadiums or churches per town.
* The town zone check is skipped, allowing you to build an office or park on the outskirts of any town (or even in the wilderness).
* The GRF-based check is skipped, allowing you to bypass NewGRF-specific restrictions such as those imposed by JapanSet, Total Town Replacement Set, and Improved Town Layouts.

Note: A house built outside of any town zone will look for the nearest town and associate itself with that town.

## Actual result
There is no such option. Funding houses in scenario editor always follows the same restrictions as if the game were randomly generating the houses (i.e. must be in certain town zones, must set date to specific year range, and similar).

## Steps to reproduce
1. Enter scenario editor.
2. Build some towns.
3. Enable setting: "Limitations > Allow funding buildings"
4. Click "Land Generation" then "House Selection".
5. Try building some houses.
6. Notice the different error messages.

## Relevant code
https://github.com/JGRennison/OpenTTD-patches/blob/efaf935cbf9fbcab7b0549af47d38a4bedf36c37/src/town_cmd.cpp#L2699-L2713

**Comment by JGRennison** [comment]
This is added now.

"Limitations > Allow funding buildings" does not have any impact on the scenario editor, this is to control use of the town "fund new buildings" action in game.

**Comment by JGRennison** [comment]
The latest release has these in.
