### ISSUE TITLE
Help Wanted: Trying to compile the latest version of JGR (0.35.1) on a docker container, and getting a different version in return

### ISSUE THREAD

**Issue by Olionkey** [JGRennison/OpenTTD-patches#178]
Version of openttd that I am trying to compile is JGR 0.35.1

Expected result is jgr being compiled to version jgrpp-0.35.1

Actual result is jgr being compiled to version jgrpp-0.35.1-Hbf3b7d6d
Am unsure what is causing this version of jgr being compiled, an older version (0.34.4) compiled with out an issue. But something is causing the addition of the string after the version and have no clue why.
Any help would be helpful, thank you.

Trying to compile on Ubuntu 18.04 docker instance, using this script.
``` 
#!/bin/bash

apt-get update

apt install -y cmake curl build-essential wget unzip pkg-config libsdl1.2-dev git zlib1g-dev liblzo2-dev liblzma-dev libfontconfig-dev libicu-dev libfluidsynth-dev uuid-dev

cd /tmp

wget https://github.com/JGRennison/OpenTTD-patches/archive/jgrpp-0.35.1.tar.gz -O jgrpp.tar.gz

tar -xzvf jgrpp.tar.gz

rm jgrpp.tar.gz

cd /mnt/server

rm CMakeCache.txt

cmake /tmp/OpenTTD-patches-jgrpp-0.35.1 -DOPTION_DEDICATED=true

make

chmod +x ./openttd

mv usr/share/games/openttd/* ./

mv usr/games/openttd ./

wget https://cdn.openttd.org/opengfx-releases/0.6.0/opengfx-0.6.0-all.zip -O opengfx.zip

unzip opengfx.zip 

tar --strip-components=1 -C baseset/ -xvf opengfx*.tar

rm open*zip open*tar open*gz debian-binary open*deb

[ -f /home/container/openttd.cfg  ] || curl https://raw.githubusercontent.com/parkervcp/eggs/master/tycoon_games/openttd/openttd.cfg > openttd.cfg
```

**Comment by James103** [comment]
Related to (possible duplicate of) #67

Have you tried running `git checkout jgrpp-0.35.1` before compiling?

**Comment by JGRennison** [comment]
This looks like an issue computing the source checksum due to locale/sorting issues. The suffix is because the source looks like it has been modified.
For now I'd suggest using a git checkout instead.
`git clone -b jgrpp-0.35.1 --depth 1 https://github.com/JGRennison/OpenTTD-patches.git /tmp/OpenTTD-patches-jgrpp-0.35.1`

This should be fixed by the next release.

**Comment by Olionkey** [comment]
It seems that doing git checkout fixed the issue. thanks for the help.
