### ISSUE TITLE
No Mac OS bundle generated via build.sh

### ISSUE THREAD

**Issue by flow23** [JGRennison/OpenTTD-patches#180]
## Version of OpenTTD
jgr 0.35.1

## Expected result
OpenTTD.app in build folder

## Actual result
No OpenTTD.app only openttd executable in build folder, which works.
I found a PackageBundle.cmake which should generated the bundle.
But somehow it doesn't work.

## Steps to reproduce
./build.sh

**Comment by JGRennison** [comment]
Running `cpack` after you've built it, should create a bundle.

**Comment by flow23** [comment]
CPack: Create package using Bundle
CPack: Install projects
CPack: - Run preinstall target for: openttd
CPack: - Install project: openttd []
CPack: Create package
CPack: - package: bundles/openttd-jgrpp-0.35.1-macosx.dmg generated.
CPack: - checksum file: bundles/openttd-jgrpp-0.35.1-macosx.dmg.sha256 generated.
