### ISSUE TITLE
Template Replacement - Train is partially cutoff

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#186]
## Version of OpenTTD
jgrpp-0.36.0

## Expected result
No pixels are cut off in the template train replacement GUI.

## Actual result
A couple pixels are cut off the bottom of each train in the template replacement GUI.

## Steps to reproduce
1. Create a new map. Make sure that you are in the 2010s or later to ensure that all Monorail vehicles are available.
2. Build a depot and buy any tram to enable the template replacement option.
3. Go to the "list of company's trains" window for your company, then select the template replacement option.
4. In the template replacement GUI, select "New", select "New Template Vehicle".
5. In the vehicle purchase window, select "Millenium Z1" and add a few of these locomotives to the template.
6. Close the vehicle purchase window, close the "Create/Edit Template Vehicle" window, and take a look at the newly created template consisting of some Millenium Z1s.
![image](https://user-images.githubusercontent.com/37945304/92294324-c7362e80-eef0-11ea-9ff8-93da237ff556.png)

**Comment by JGRennison** [comment]
Fixed in v0.37.0
