### ISSUE TITLE
Template Replacement - No error message when adding wagon to template fails

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#187]
## Version of OpenTTD
jgrpp-0.36.0

## Expected result
If adding a wagon to a template replacement train fails, the corresponding error message should be shown.

## Actual result
If adding a wagon to a template replacement train fails, no error message is shown.

## Steps to reproduce
1. Install and load the NewGRF "JapanSet3: Trains".
2. Create a new map. Make sure that you are in the 2050s or later to ensure that all vehicles are available.
3. Build a depot and buy any train to enable the template replacement option.
4. Go to the "list of company's trains" window for your company, then select the template replacement option.
5. In the template replacement GUI, select "New", then select "New Template Vehicle".
6. Add "0 Series Shinkansen" (or any other Shinkansen) to the template.
7. Scroll down and try adding any steam engine or normal wagon to the template. This fails, but no error message is shown.
8. Build a Shinkansen depot. buy 2x "0 Series Shinkansen" (you may need to increase your available cash to do so), and try dragging them next to each other. An error message "Can't move vehicle... Multiple unit coaches only" will appear.

**Comment by JGRennison** [comment]
Fixed in v0.37.0
