### ISSUE TITLE
Compiler warning with JGRPP 0.37.0

### ISSUE THREAD

**Issue by auge8472** [JGRennison/OpenTTD-patches#193]
## Version of OpenTTD

JGRPP 0.37.0

## Expected result

No compiler warning.

## Actual result

I get a warning when compiling `company_cmd.cpp`.

~~~
.../src/company_cmd.cpp:1193:28: warning: comparison is always true due to limited range of data type [-Wtype-limits]
  if (_loaded_local_company >= COMPANY_FIRST && _loaded_local_company < MAX_COMPANIES && Company::IsValidID(_loaded_local_company)) {
      ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
~~~

Compiled JGRPP under Ubuntu 18.04. The error doesn't occur during compile run of [the current master of OpenTTD](https://github.com/OpenTTD/OpenTTD/commit/348c231e12d87c106bd1ab3c9d7a5ecdab6863d8). The resulting program *seems* to run without problems.

**Comment by JGRennison** [comment]
That warning is very pedantic, it's not something to worry about. I'll see about getting rid of it shortly.
