### ISSUE TITLE
Conditional orders only point to the first 256 orders in a vehicle's order list

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#198]
## Version of OpenTTD
jgrpp-0.38.0

## Expected result
Conditional orders can point to all up to 65,534 orders in the vehicle's order list.

## Actual result
Conditional orders can only point to the first 256 orders in the vehicle's order list. Additionally, there are rare cases where the game may crash due to complications involving a full order list (65,534 orders) and inserting and removing several conditional orders.

## Steps to reproduce
1. Load the first savegame: [crash-20201017T071608Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/5395146/crash-20201017T071608Z.zip)
2. It takes about a minute to load the savegame, followed by an immediate crash: [crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/5395152/crash.zip)
3. Load the second savegame: [test-64k-orders-one-vehicle.zip](https://github.com/JGRennison/OpenTTD-patches/files/5395161/test-64k-orders-one-vehicle.zip)
4. Open up the order list of Road Vehicle 1, and scroll to the middle of the list.
5. Select an order in the middle of the list. Delete that order (e.g. order 2000).
6. With the new auto-selected order, insert a conditional jump order.
7. Point it somewhere else in the middle of the list (e.g. order 4000).
8. Notice that it instead points somewhere within the first 256 orders (e.g. order 160)

**Comment by James103** [comment]
The game still crashes (jgrpp-0.39.0) when loading the crash savegame attached in the initial post: [crash-20201109T180137Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/5512457/crash-20201109T180137Z.zip)
Why is that?

**Comment by JGRennison** [comment]
It worked fine on my machine, I've done some more testing with a lower stack limit and found some more.

**Comment by James103** [comment]
When testing in jgrpp-0.39.1, the savegame loads and runs correctly. This issue can be closed.
