### ISSUE TITLE
Suggestion: Stop vehicle expenses while it is waiting in depot due to timetable

### ISSUE THREAD

**Issue by modreoci** [JGRennison/OpenTTD-patches#202]
## Version of OpenTTD
0.38.1

## Expected result
Not to charge money for vehicle operation while it is waiting in depot due to timetable.

## Actual result
Money expenses are continuously charged even vehicle is de facto not on duty (stopped in depot due to timetable).

**Comment by JGRennison** [comment]
This is added now, it'll be in the next release.

**Comment by modreoci** [comment]
Bingo... It's great... Good job ;-) THNX
