### ISSUE TITLE
Normal road cargo stops not working

### ISSUE THREAD

**Issue by kmai-universe** [JGRennison/OpenTTD-patches#205]
When playing with 0.39 patch, the normal non-drivethrough stops can't be used. If you buy a mail truck for example and try to send it to the stop you get an error message saying "this vehicle can't go to this station".

It doesn't matter what cargo type I try.

Drive through stops work fine!

In multiplayer the same happens for the other players.

**Comment by James103** [comment]
Have you tried reproducing this without any NewGRFs, to guarantee that no articulated road vehicles exist in your game?

**Comment by kmai-universe** [comment]
No, but we tried with two different road vehicle sets with the same result.

Can a newgrf make it so only one of the cargo bus stops work? Right now we just use the drive through one as a quick fix.

Now that I think about it, I actually think they work if they are alone. The bug appears if they are combined with for example a train station. I will have todo some more testing tomorrow and report back.

**Comment by embeddedt** [comment]
Articulated road vehicles don't work in the old-style cargo stops, so you would need to reproduce this with a non-articulated vehicle (ideally a vanilla one) to be sure the bug exists.

**Comment by kmai-universe** [comment]
I can confirm that it does work with normal non articulated vehicles! Did not know about that limitation. You can close this ticket.

Thanks for the help and clarification!
