### ISSUE TITLE
MacOS: User directory ignored, but only when run as app bundle

### ISSUE THREAD

**Issue by khavik** [JGRennison/OpenTTD-patches#208]
## Version of OpenTTD
```OpenTTD version:
 Version:    jgrpp-0.37.0-50-g34a6445e77 (0)
 NewGRF ver: 1b006d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Oct 11 2020 00:55:46
 Defines:    WITH_UCONTEXT WITH_BITMATH_BUILTINS WITH_OVERFLOW_BUILTINS WITH_DL WITH_DEMANGLE WITH_SIGACTION WITH_DBG_GDB WITH_UCONTEXT NDEBUG TTD_ENDIAN=TTD_LITTLE_ENDIAN UNIX WITH_PNG WITH_ZLIB WITH_LIBLZMA WITH_LZO WITH_FREETYPE WITH_ICONV WITH_COCOA ENABLE_COCOA_QUARTZ WITH_PERSONAL_DIR WITH_SHARED_DIR WITH_SSE WITH_ASSERT _SQ64

Operating system:
 Name:     Mac OS X
 Release:  10.15.7
 Machine:  Intel x86-64h Haswell
 Min Ver:  1090
 Max Ver:  101500
 Compiler: clang 12.0.0 (clang-1200.0.32.2) "Apple LLVM 12.0.0 (clang-1200.0.32.2)"

Libraries:
 FreeType:   2.10.2
 LZMA:       5.0.5
 LZO:        2.10
 PNG:        1.6.37
 Zlib:       1.2.11
```

## Expected result
Opening the app bundle should start the game normally, respecting user config files and finding all installed graphics etc.

## Actual result
Opening the app bundle produces this with a well-populated user directory:
<img width="752" alt="Screenshot 2020-12-21 at 23 39 48" src="https://user-images.githubusercontent.com/38088012/102828798-ded4ec80-43e5-11eb-8db9-02d9bf1dbd1d.png">
Clicking the button “Yes, download the graphics” briefly spawns a download progress window, which immediately fails and disappears, silently, leaving only the background canvas.

The game **works properly** when running the loading script `OpenTTD.app/Contents/MacOS/OpenTTD` or running the executable `OpenTTD.app/Contents/Resources/openttd` directly.

## Steps to reproduce
Open app bundle either from the Finder, or using commandline: `open OpenTTD.app`, etc.

## Notes
App permissions in the OS (disk access) seem correct, to the best of my knowledge. Upstream stable and nightly work correctly.

**Comment by JGRennison** [comment]
It may be worth updating your checkout to a more recent version (git pull, etc.).

I'm not aware of any reason why this should behave differently from upstream.
I will investigate, but for the most part there is not much that I can do about Apple-specific issues.

**Comment by vincentkoevoets** [comment]
I don't think I have any deep technical insight, but I could try to help you troubleshoot this. I build MacOS bundles too and everything works just fine, so there must be something wrong somewhere with your setup.

**Comment by khavik** [comment]
> It may be worth updating your checkout to a more recent version (git pull, etc.).
@JGRennison Oops, somehow I ran the wrong version when posting this yesterday. Note to self: get more sleep.
Anyway, still doesn’t work on the current version:

```OpenTTD version:
 Version:    jgrpp-0.39.1-37-g8ac436f50 (0)
 NewGRF ver: 1b006d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Dec 21 2020 23:03:42
 Defines:    WITH_UCONTEXT WITH_BITMATH_BUILTINS WITH_OVERFLOW_BUILTINS WITH_DL WITH_DEMANGLE WITH_SIGACTION WITH_DBG_GDB WITH_UCONTEXT NDEBUG TTD_ENDIAN=TTD_LITTLE_ENDIAN UNIX WITH_PNG WITH_ZLIB WITH_LIBLZMA WITH_LZO WITH_FREETYPE WITH_ICONV WITH_COCOA ENABLE_COCOA_QUARTZ WITH_PERSONAL_DIR WITH_SHARED_DIR WITH_SSE WITH_ASSERT _SQ64

Operating system:
 Name:     Mac OS X
 Release:  10.15.7
 Machine:  Intel x86-64h Haswell
 Min Ver:  1090
 Max Ver:  101500
 Compiler: clang 12.0.0 (clang-1200.0.32.2) "Apple LLVM 12.0.0 (clang-1200.0.32.2)"

Libraries:
 FreeType:   2.10.4
 LZMA:       5.0.5
 LZO:        2.10
 PNG:        1.6.37
 Zlib:       1.2.11
```

**Comment by khavik** [comment]
> I don't think I have any deep technical insight, but I could try to help you troubleshoot this. I build MacOS bundles too and everything works just fine, so there must be something wrong somewhere with your setup.

@vincentkoevoets Thanks! That would be great—I only have this one system, so otherwise I wouldn’t really be able to compare my setup to anything. Do you have any idea what the culprit could be?

**Comment by khavik** [comment]
All right, I modified the bundle startup script to enable debugging and logging.
Starting the bundle gives this:

```
dbg: [misc] /Applications/OpenTTD.app/Contents/Resources/ added as search path
dbg: [misc] /Users/<username>/Documents/OpenTTD/ added as search path
dbg: [misc] /Library/Application Support/OpenTTD/ added as search path
dbg: [misc] /Applications/OpenTTD.app/Contents/Resources/ added as search path
dbg: [misc] /Applications/OpenTTD.app/Contents/Resources/ added as search path
dbg: [misc] /Users/<username>/Documents/OpenTTD/ found as config directory
dbg: [misc] /Users/<username>/Documents/OpenTTD/ found as personal directory
dbg: [misc] Scanning for tars
dbg: [misc] Scan complete, found 0 files
```

Starting the executable directly gives this:
```
dbg: [misc] /Users/<username>/Documents/OpenTTD/ added as search path
dbg: [misc] /Library/Application Support/OpenTTD/ added as search path
dbg: [misc] /Applications/ added as search path
dbg: [misc] /Applications/OpenTTD.app/Contents/Resources/ added as search path
dbg: [misc] /Users/<username>/Documents/OpenTTD/ found as config directory
dbg: [misc] /Users/<username>/Documents/OpenTTD/ found as personal directory
dbg: [misc] Scanning for tars
dbg: [misc] Found tar '/Users/<username>/Documents/OpenTTD/content_download/baseset/NightGFX-1.0.0.tar' with 10 new files
dbg: [misc] Found tar '/Users/<username>/Documents/OpenTTD/content_download/baseset/OpenSFX-0.2.3.tar' with 5 new files
dbg: [misc] Found tar '/Users/<username>/Documents/OpenTTD/content_download/baseset/NightGFX-1.1.0.tar' with 10 new files
dbg: [misc] Found tar '/Users/<username>/Documents/OpenTTD/content_download/baseset/OpenGFX-0.5.2.tar' with 10 new files
dbg: [misc] Found tar '/Users/<username>/Documents/OpenTTD/content_download/baseset/OpenGFX-0.5.5.tar' with 10 new files
dbg: [misc] Found tar '/Users/<username>/Documents/OpenTTD/content_download/baseset/4f474658-OpenGFX-0.6.0.tar' with 10 new files
dbg: [misc] Scan complete, found 6 files

```

**Comment by vincentkoevoets** [comment]
This is strange indeed... It finds the directories in both cases, but it does not find the tars from the bundle. Like I said, I'm not nearly skilled enough to know where to begin, but we can retrace and compare our steps together to see if somewhere maybe we do something different. I'm thinking maybe we should take this somewhere else, do you have any instant messaging app? Like Whatsapp or Signal or something? Would be more convenient and faster also.

**Comment by pete-evans** [comment]
I had exactly the same problem running a completely new install of vanilla 1.10.3 straight from openttd.org. I was able to resolve this in System Preferences > Security & Privacy. Then on the Privacy tab, under Files and Folders I had to re-allow OpenTTD access to the Documents folder.

PS - I'd much rather use JGR than vanilla but can't compile it myself. Any chance you can share a recent bundle?

**Comment by khavik** [comment]
All right, I finally had some time to fiddle with this again today, and I was able to get it up and running again!

The issue was related to permissions, for sure.
Even though the app was reported in Security & Privacy to have file access, this permission seems to have been associated only with the vanilla executable. Directly resetting the entry in the privacy database by running `tccutil reset SystemPolicyAllFiles org.openttd.openttd`, etc., failed to actually reset the permissions but produced this error message:

`tccutil: executable_is_endpoint_security_client failed for path file:///Applications/OpenTTD.app/Contents/MacOS/openttd with error: code object is not signed at all`

This pointed to the vanilla version, which I proceeded to delete. Still no dice. Running `tccutil` again revealed _another_ executable, this time, sitting in an old build directory, a version that I had run in place for troubleshooting purposes. For some reason, this was given precedence in the MacOS privacy database over the much newer jgrpp version in `/Applications`! The mind boggles.
To finally solve the problem, I had to delete (not just throw in the Trash) every single executable providing the bundle ID `org.openttd.openttd` that had been executed at some point in time.

After this whole ceremony, the OpenTTD entry in the privacy database finally went away, allowing me to add a new entry. Now everything works just fine, even running jgrpp and vanilla in parallel.

So, from what I’ve been able to gather, the whole problem came down to the MacOS privacy database system being _confused_. Maybe it had to do with multiple, (unsigned?) bundles with the same bundle ID being installed? I’m not familiar enough with the system to say.

Could this issue be prevented by assigning a new bundle ID for the jgrpp version? Or would this introduce new problems that I haven’t thought of yet?

Anyway, I hope this helps anyone with the same problem. Feel free to close the issue if there’s no need to discuss bundle IDs. :)

**Comment by khavik** [comment]
> PS - I'd much rather use JGR than vanilla but can't compile it myself. Any chance you can share a recent bundle?

@pete-evans Sure thing! Give this a go:
[openttd-jgrpp-0.40.2-167-g19b7ecf95-macos-amd64.dmg.zip](https://github.com/JGRennison/OpenTTD-patches/files/6037172/openttd-jgrpp-0.40.2-167-g19b7ecf95-macos-amd64.dmg.zip)

**Comment by JGRennison** [comment]
I've changed the Mac bundle ID in the build config. I haven't built or done any testing of this though.

**Comment by pete-evans** [comment]
Thanks @khavik - it worked! Can't wait to jump in
