### ISSUE TITLE
Separate interest rate setting into 3 different settings

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#209]
## Version of OpenTTD
jgrpp-0.39.1 (and also latest master as of 2020-12-26)
Originally based off on [OpenTTD/OpenTTD#8429 (comment)](https://github.com/OpenTTD/OpenTTD/discussions/8429#discussioncomment-241289)

## Expected result
In place of the old interest rate setting, there should be the following 3 settings:
* Loan interest rate
* Cost inflation rate
* Income inflation rate

Having these settings will allow greater control over loan interest and inflation. For example, Instead of having loan interest be at 4%, you could have it be at 50% making it not as worthwhile to keep taking out loans to build new profitable routes and making for more challenging play. At the same time, the inflation rate could be set to 10% (both costs and incomes), which increases the difficulty further by effectively soft-capping the real value of your money and forcing you to continually make investments in order to stay profitable.

## Actual result
There is only the old interest rate setting available which controls both loan interest and inflation. The divergence between costs and incomes is currently fixed (hard-coded) to grow over time with income inflation being 1 percentage point less than cost inflation.

## Steps to reproduce
1. Look into Advanced Settings for the loan interest rate, and notice that only that setting is present and not the other two that I proposed.
2. Turn on inflation, open CTRL+ALT+C, and fast-forward. Notice that costs are increasing faster than income.

**Comment by VacuumBreather** [comment]
I support this feature, however "you could have it be at 50% making it not as worthwhile to keep taking out loans to build new profitable routes" makes no sense :D That's the point of having a reasonable interest rate in real life, so you CAN take a loan and make something productive and pay interest to the investor. That's how economy works :D That's the point of investing money into a company. There's zero issues having a loan and pay interest on it, if your company makes 10 times the revenue. That's how it works in real life as well.

So while I agree to this setting, it should be limited to reasonable amounts. 50% interest is completely unrealistic, even 10% is pushing it. If people want to play without a loan they can already limit the maximum loan amount. No reason to crank up the interest rate to unrealistic levels.

However splitting the interest rate of loan, cost and income inflation makes sense.

**Comment by James103** [comment]
A reasonable starting point for the min and max values for the proposed settings would be (subject to change):
* Loan interest rate: Min 0%, Max 10%
  - This covers almost all traditional bank loans and some other forms of credit.
  - Most credit cards have interest rates higher than 10% APR (oftentimes around 15-25% APR based on economic conditions and credit rating), but they also have more flexibility in terms of credit management. If these lines of credit are to be covered as well, the upper limit on loan interest may be increased to 30%.
* Inflation rate (both costs and incomes): Min 0%, Max 10%
  - This covers most countries, especially those that have a stable economy.
  - Deflation and hyperinflation both have existed in the real world, but those concepts might be too much for the average player to handle and/or they may break the game balance.

**Comment by James103** [comment]
I found a better alternative to this issue and posted it in #415. It involves Game Scripts being able to control inflation at any time, rather than more settings.

Loan Interest can already be made custom with a Game Script as follows:
* Every month, at the start of the month, for every company, check if the company needs to pay custom loan interest.
* If so, reimburse the company for the default loan interest and pay the custom interest.

Use cases of custom loan interest:
* Interest rate less than 2% or more than 4% (the latter is common in some areas)
* Variable interest rate
* Different interest rate per company based on their performance
* Being paid interest (in small amounts) based on their net value

If #415 is implemented, this issue can be closed since all relevant use cases for it can already be achieved.

**Comment by James103** [comment]
Closing as all relevant use cases for this proposal are already possible with GS (custom loan interest was already possible before, while inflation control was just added recently).
