### ISSUE TITLE
Crash on removing bridge/tunnel signal

### ISSUE THREAD

**Issue by goodgerster** [JGRennison/OpenTTD-patches#214]
## Version of OpenTTD

`jgrpp-0.40.0`

## Expected result

Signals can be added to, modified on, and removed from bridges and tunnels

## Actual result

* Adding a signal to a bridge with the signal tool in path mode results in a path signal at one end, followed by a string of bidirectional vanilla signals
* `Ctrl+Click` on the bridge head does nothing
* Attempting to remove a signal from a bridge or tunnel crashes the game with the following written out to disk:
  * [crash-20210204T102259Z](https://user-images.githubusercontent.com/9383058/106879840-f210f280-66db-11eb-98e4-50310780d3f2.png) (PNG)
  * [crash-20210204T102259Z.log](https://github.com/JGRennison/OpenTTD-patches/files/5924956/crash-20210204T102259Z.log)
  * [crash-20210202T222623Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/5924995/crash-20210202T222623Z.zip) (zipped sav because GitHub)

## Steps to reproduce

Seems obvious, really…

Cheers, Jon.

**Comment by embeddedt** [comment]
There were some commits made to the jgrpp  branch that may have fixed this; have you tried building a copy from there?

**Comment by JGRennison** [comment]
This should be fixed now, sorry about that.

**Comment by goodgerster** [comment]
Thank you :)
