### ISSUE TITLE
Remove 3rd party mingw32 threads library?

### ISSUE THREAD

**Issue by joestringer** [JGRennison/OpenTTD-patches#216]
Whenever I compile this patchpack, I see the following warning printed spuriously during the build:

```
src/3rdparty/mingw-std-threads/mingw.thread.h:389:17: note: ‘#pragma message: This version of MinGW seems to include a win32 port of pthreads, and probably already has C++11 std threading classes implemented, based on pthreads. These classes, found in namespace std, are not overridden by the mingw-std-thread library. If you would still like to use this implementation (as it is more lightweight), use the classes provided in namespace mingw_stdthread.’
  389 | #pragma message "This version of MinGW seems to include a win32 port of\
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  390 |  pthreads, and probably already has C++11 std threading classes implemented,\
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  391 |  based on pthreads. These classes, found in namespace std, are not overridden\
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  392 |  by the mingw-std-thread library. If you would still like to use this\
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  393 |  implementation (as it is more lightweight), use the classes provided in\
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  394 |  namespace mingw_stdthread."
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

These days however, the minimum compiler must build C++17:

https://github.com/JGRennison/OpenTTD-patches/blob/jgrpp/COMPILING.md#supported-compilers

Does it make sense to keep the 3rd party mingw-std-threads library?

**Comment by JGRennison** [comment]
The version of MinGW shipped by the distro I'm using (Ubuntu 20.04) doesn't include std::thread (or at least I've not been able to get it to work), but otherwise supports C++17 just fine.
Building with std::thread on MinGW is so problematic that I think that it's still prudent to include this library.

I don't really want to have the opposite issue where if I do remove it I'll get bug reports about people being unable to build the project, which are rather more difficult to resolve.

Which version are you using?

**Comment by embeddedt** [comment]
In that case, how about defining [`MINGW_STDTHREAD_REDUNDANCY_WARNING`](https://github.com/JGRennison/OpenTTD-patches/blob/b7a1750863ba81e3ee88c290c618276551d5cc64/src/3rdparty/mingw-std-threads/mingw.thread.h#L388) to hide the warning?

**Comment by JGRennison** [comment]
That should be hidden now.

**Comment by joestringer** [comment]
Cool, makes total sense, no need to remove if it's not broken. This was more of a quick question on whether the branch is unnecessary older code, and the answer is clearly no :). I'm using mingw toolchain for what it's worth.

**Comment by joestringer** [comment]
:100: much quieter build, compiles & runs well.
