### ISSUE TITLE
Suggestion: Block signal at no track reserve state

### ISSUE THREAD

**Issue by nirakan** [JGRennison/OpenTTD-patches#222]
## Version of OpenTTD
jgrpp-0.40.3

Goodday sir. Can you try to edit an signal at normal state (No train on the track) from 'green' to 'red' refer to real world signal at a normal state when no train behide is indicated red.

Thankyou ~*

**Comment by JGRennison** [comment]
It sounds like you want a path signal (PBS), instead of a block signal.

There is some info here on how these work: https://wiki.openttd.org/en/Manual/Signals#path-signals
