### ISSUE TITLE
Save loading fails with Renewed World Disorder game script enabled on Linux

### ISSUE THREAD

**Issue by TheSocietyMan** [JGRennison/OpenTTD-patches#224]
## Version of OpenTTD
jgrpp-0.40.4 generic linux build

## Expected result
Save loading works with[ Renewed World Disorder](https://bananas.openttd.org/package/game-script/4e525744) script enabled

## Actual result
Game loading fails with the message "Game Load Failed (undefined string)"

The following is console output when attempting to load a save
`dbg: [script] english:11: error: String name 'STR_TOWNBOX_CAT_4' is used multiple times`
`dbg: [script] english:20: error: String name 'STR_CARGOCAT_LABEL_4' is used multiple times`
`dbg: [script] english:28: error: String name 'STR_SB_CARGOCAT_2' is used multiple times`
`dbg: [script] english:30: error: String name 'STR_SB_CARGOCAT_5' is used multiple times`
`dbg: [script] english:31: error: String name 'STR_SB_CARGOCAT_5' is used multiple times`
`dbg: [sl] Game Load Failed`
`(undefined string)`

Game script debug log isn't showing anything unusual

## Steps to reproduce
1. Launch jgrpp-0.40.4 generic linux build
2. Generate a new game with New World Disorder script enabled
3. Save the game and then attempt to load the save file

Could not reproduce this issue with the win64 build.
Tried to reproduce with the deb package, but I'm having some dependency issues and I'm not too familiar with the package format. Though one thing I know is that package versions in .deb have to start with a number, so the package is broken, requiring the user to extract, edit DEBIAN/control and repackage it before installing, [here's an example](https://github.com/Chocobozzz/PeerTube/issues/686). I'll try to look into the .deb package later.

**Comment by James103** [comment]
Ideally, are you able to post the full script (tar or zip) file that you're trying to activate when loading the savegame? If so, can you please do that?

**Comment by TheSocietyMan** [comment]
Just checked and I'm running version 6.

@James103 [here](https://www.tt-forums.net/download/file.php?id=212658)'s a download link, straight from the project's site.

**Comment by JGRennison** [comment]
Would you able to attach the problematic save, I haven't been able to reproduce any issue from saves that I've generated.

**Comment by TheSocietyMan** [comment]
Sure, disabled all newgrfs and generated a fresh file.
[savefile.zip](https://github.com/JGRennison/OpenTTD-patches/files/6111877/savefile.zip)

**Comment by JGRennison** [comment]
This should be fixed by 4361a6d, it seems the optimiser in the version of gcc used to compile the generic build managed to take advantage of the undefined behaviour to break loading of certain strings out of the save.
