### ISSUE TITLE
Linux: Installing in a custom location no longer works

### ISSUE THREAD

**Issue by lcd047** [JGRennison/OpenTTD-patches#225]
## Version of OpenTTD
`jgrpp-0.40.4`

## Expected result
I'm trying to compile and install `jgrpp-0.40.4` on Linux Slackware, in a way that it doesn't interfere with the official OpenTTD releases.  The following incantation used to work up to `jgrpp-0.40.2`:
```sh
mkdir _build && \
cd _build && \
cmake .. \
	-DCMAKE_INSTALL_PREFIX=/usr/local \
	-DCMAKE_INSTALL_DATADIR=share/games \
	-DBINARY_NAME=openttd_jgr && \
make -j8 && \
make install
```
It installed a binary named `openttd_jgr` in `/usr/local/games`, data went in `/usr/local/share/games/openttd_jgr`, running the binary actually started the program, and life was good.
## Actual result
Binary and data are installed in `/usr/local`, and running the binary bails out with the message `Error: No available language packs (invalid versions?)`.  Life without OpenTTD JGR sucks. :smile:

Help please?

**Comment by JGRennison** [comment]
It could be related to this? https://github.com/OpenTTD/OpenTTD/pull/8629

I don't use `make install` at all for any variant of OpenTTD on my machines.
It'll run just fine out of the build folder and this avoids the issues from running multiple versions.

**Comment by lcd047** [comment]
Yup, adding `-DCMAKE_INSTALL_BINDIR=/usr/local/games` to the `cmake` command line fixes the problem.  Thank you!
