### ISSUE TITLE
Add: When custom bridge heads are enabled, allow building road stops on bridge tile ends.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#229]
## Version of OpenTTD
jgrpp-0.40.4

## Expected result
When custom bridge heads are enabled, you should be able to build road stops on bridge tile ends (creating foundations as necessary since a road stop occupies the full tile). This can be used to, for example, place road stops closer to train stations than what's normally possible.

Note that if this is implemented, you should only be able to build road stops as a custom bridge head if the road stop is oriented parallel to the bridge itself (perpendicular orientation would attempt to build a road stop on a T-junction tile which is not allowed).

I was originally going to suggest allowing road stops to be built on bridge spans, but that seemed too infeasible despite the added possibilities.

## Actual result
Even when custom bridge heads are enabled, you are unable to build a road stop as a custom bridge head, failing with the error message "Flat land required" for parallel orientations or "Must demolish bridge first" for perpendicular orientations.

## Steps to reproduce
1. Enable custom bridge heads.
2. Build a bridge where one of the ends is a flat road on a sloped surface.
3. Try building a road stop.

**Comment by JGRennison** [comment]
I can say with confidence that this isn't going to happen in the foreseeable future.

This isn't compatible with the way that bridges, custom bridge heads, and stations/road stops are implemented, or their map array representations.
See also: https://htmlpreview.github.io/?https://github.com/JGRennison/OpenTTD-patches/blob/jgrpp/docs/landscape.html https://htmlpreview.github.io/?https://github.com/JGRennison/OpenTTD-patches/blob/jgrpp/docs/landscape_grid.html
