### ISSUE TITLE
Error when compiling the patchpack in Linux

### ISSUE THREAD

**Issue by auge8472** [JGRennison/OpenTTD-patches#23]
When I compile the sources in Ubuntu 16.04, I get an error in `src/os/unix/crashlog_unix.cpp`. The game runs nevertheless, when compiled.

~~~
[SRC] Compiling os/unix/crashlog_unix.cpp
~/…/src/os/unix/crashlog_unix.cpp: In function ‘void HandleCrash(int, siginfo_t*, void*)’:
~/…/src/os/unix/crashlog_unix.cpp:571:22: warning: format not a string literal and no format arguments [-Wformat-security]
   printf(abort_reason);
                      ^
~~~

Do you need further informations?

**Comment by JGRennison** [comment]
This is a minor error on my part, the conditions are such that there are no
ill effects though.
Thanks for letting me know. I will fix it shortly.
