### ISSUE TITLE
Windows Xp Error

### ISSUE THREAD

**Issue by dimaspaf14** [JGRennison/OpenTTD-patches#235]
## Version of OpenTTD
0.40.5

## Expected result
Running correctly like opentdd does

## Actual result
Error(bruh)

## Steps to reproduce
1.Extract
2.Play

##Screenshots
![1617611620461784929967](https://user-images.githubusercontent.com/71385492/113554953-512fac80-9624-11eb-833c-d5c5ff7c487f.jpg)

**Comment by dimaspaf14** [comment]
If the screenshot was a mesh, the the text is:
"The procedure entry point wcsncpy_s could not be located in the dynamic link library msvcrt.dll"

**Comment by JGRennison** [comment]
I'm fairly sure that the upstream 1.11 binaries don't support Windows XP either.

I can look into it in due course, but Windows XP is well out of support from MS and unsupported upstream now.

**Comment by embeddedt** [comment]
https://github.com/OpenTTD/OpenTTD/issues/8593#issuecomment-762804789

Vista is apparently the minimum version now.

**Comment by dimaspaf14** [comment]
Yes, already test it and cant run at all (original Openttd)

**Comment by dimaspaf14** [comment]
> I'm fairly sure that the upstream 1.11 binaries don't support Windows XP either.
> 
> I can look into it in due course, but Windows XP is well out of support from MS and unsupported upstream now.

What is the last version of openttd jgrpp for win xp?

**Comment by JGRennison** [comment]
I don't have access to a working instance of Windows XP at present.
You could try some old versions from here: https://github.com/JGRennison/OpenTTD-patches/releases

I seem to remember that some users also on old systems posted Windows XP builds on the forums, but I now cannot find any of these.

**Comment by dimaspaf14** [comment]
Last original openttd version that support win xp was 1.10.3

**Comment by dimaspaf14** [comment]
Maybe i found what version for win xp user, the original openttd version was 1.10.3.
for openttd jgrpp is 0.39.2.

Because original was released on 2020, the same way jgrpp is released. The next original was 1.11 was build on 2021, so i can say that 0.39.2 version of jgrpp was the right version for win xp user,  can someone pin this?, maybe this was usefull for some people :D

**Comment by dimaspaf14** [comment]
What is mingw labeled release @JGRennison?

**Comment by JGRennison** [comment]
> What is mingw labeled release @JGRennison ?

MinGW is a compiler for Windows, so these are Windows builds.
