### ISSUE TITLE
Change: Increase maximum station spread setting from 64 to 255

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#236]
## Version of OpenTTD
jgrpp-0.40.5

## Expected result
The maximum station spread is ideally 255 tiles, allowing you to build out even the biggest and most realistic freight terminals and rail yards in a single station.

## Actual result
The maximum station spread is limited to 64 tiles. Under realistic scenarios, you may end up having to build a station that exceeds 64 tiles in one direction. As the max station spread is 64 tiles, that will force you to split the station into multiple (2, 3, or even more) parts, which may result in added complexity when scheduling train orders as well as forcing you to schedule additional shuttles to transfer cargo between one part and another part.

Note that hacking the setting value for "Maximum station spread" and forcing it over the normal maximum, and setting it to a value of 200 tiles, does allow you to build stations that are that long, though there may be unexpected stability issues with such a high station spread.

See [this YouTube video](https://youtu.be/lP35orAQQhE?t=365) for another explanation of the actual result.

## Steps to reproduce
1. Try increasing "Maximum station spread" beyond 64. The value gets capped at 64.
2. Build a station that is 64 tiles long.
3. Try extending the station an additional tile. That will fail with "station too spread out".
4. Somehow increase "Maximum station spread" to 200 tiles.
5. Try extending the station an additional title. This time, the action succeeds and the station is 65 tiles long.

**Comment by JGRennison** [comment]
64 is more than enough really. I don't think that it's reasonable to keep increasing this.
It's worth remembering that in the original TTD, maps were 256x256. Having an entire map's worth covered by a single station seems a bit silly, and sort of defeats the point of using vehicles to transport things.
