### ISSUE TITLE
Wrong console helptext for ``train_braking_model`` variable

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#240]
## Version of OpenTTD
jgrpp-0.40.5

## Expected result
``Current value for 'train_braking_model' is: '0' (min: 0, max: 1)``

## Actual result
``Current value for 'train_braking_model' is: '0' (min: 0, max: 0)``
![image](https://user-images.githubusercontent.com/10726524/114402281-a0567e00-9bde-11eb-8bfd-d351fabad3d1.png)

## Steps to reproduce
Type ``set train_traking_model`` in console

**Comment by James103** [comment]
What is the console output from `set train_traking_model` provided that you run `set train_traking_model 1` beforehand (setting it to "Realistic")?

**Comment by telk5093** [comment]
It is ``Current value for 'train_braking_model' is: '1' (min: 0, max: 0)``
![image](https://user-images.githubusercontent.com/10726524/114405152-5a4ee980-9be1-11eb-940f-562ca31114dd.png)

**Comment by JGRennison** [comment]
Thanks, this should be fixed now.
