### ISSUE TITLE
Game crashing by a NewGRF House?

### ISSUE THREAD

**Issue by KamikaziF** [JGRennison/OpenTTD-patches#243]
## Version of OpenTTD
OpenTTD JGRPP 0.41.0
## Expected result
When opening the save file, it should open normally
## Actual result
The game shows this error window and then proceeds to crash
![image](https://user-images.githubusercontent.com/38037802/115297716-d0f96300-a15c-11eb-878a-3de856325815.png)

## Steps to reproduce
1. Open the game
2. Open this save file (and the NewGRFs)
[autosave.zip](https://github.com/JGRennison/OpenTTD-patches/files/6338863/autosave.zip)

**Comment by JGRennison** [comment]
This is fixed and will be in the next release.
In the meantime, the attached savegame should have the issue removed.

[Forward Connections, 2053-04-01.sav.zip](https://github.com/JGRennison/OpenTTD-patches/files/6339391/Forward.Connections.2053-04-01.sav.zip)
