### ISSUE TITLE
Schedule dispatch: "Delay" and "Reset Last Dispatched" buttons are not disabled if vehicle not owned by your company.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#244]
## Version of OpenTTD
jgrpp-0.41.0

## Expected result
The "Delay" and "Reset Last Dispatched" buttons are disabled if the vehicle is not owned by your company.

## Actual result
The "Delay" and "Reset Last Dispatched" buttons are not disabled if the vehicle is not owned by your company. Clicking those buttons still generates an error message saying that the vehicle is owned by another company.

## Steps to reproduce
1. Create a new game, which starts up the first company.
2. Using the first company, build/buy a vehicle and give it some orders.
3. Start up and switch to a second company.
4. Open the vehicle's Orders, then Timetable, then Scheduled Dispatch.
5. Try clicking on the "Delay" and "Reset Last Dispatched" buttons.

**Comment by JGRennison** [comment]
Thanks, this should be fixed now.
