### ISSUE TITLE
No error message subtitle if no bridge type available for target length < max bridge length

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#246]
## Version of OpenTTD
jgrpp-0.41.0
Does not happen in trunk (official release 1.11.0)

## Expected result
The error message should appear with the subtitle "...bridge too long".

## Actual result
The error message does not have a subtitle.

## Steps to reproduce
1. Install and load the NewGRF "Expensive, Short, and Slow Bridges" (pb_bridge.grf).
2. Also install and load an early vehicle NewGRF (such as eGRVTS 2).
3. Set "Max bridge length" to 64 tiles or more.
4. Start a game in between 1890 and 1950.
5. Try to build a bridge greater than ~14 tiles long. It will fail but the error message will not have a subtitle.

Related to https://github.com/OpenTTD/OpenTTD/issues/8221

**Comment by JGRennison** [comment]
Thanks, this is fixed now.
