### ISSUE TITLE
Suggestion: Yellow signal graphic on realistic train braking

### ISSUE THREAD

**Issue by kiwitreekor** [JGRennison/OpenTTD-patches#247]
![image](https://user-images.githubusercontent.com/24273113/115964720-bbbb7480-a560-11eb-8d6d-ff438c085755.png)

If realistic train braking is enabled, multiple green signals are shown. But in my opinion graphics would be more realistic if some of the green signals are changed to yellow signals (just eyecandy...).

**Comment by kiwitreekor** [comment]
![signals_pbs](https://user-images.githubusercontent.com/24273113/115985626-afc6c580-a5e7-11eb-8e59-41b3cdbee593.png)
![light-generic](https://user-images.githubusercontent.com/24273113/115985627-b5bca680-a5e7-11eb-9ec8-bcfdd9356c30.png)

OpenGFX style 4-aspect signals graphics

**Comment by VacuumBreather** [comment]
The graphics are really the problem. There's existing signal graphics sets out there that don't support this.. if it could be manipulated somehow without dependency on a specific set...

**Comment by embeddedt** [comment]
Here's an idea (a bit naive): search for all greenish pixels on the signal, and adjust them to be more yellow.

**Comment by VacuumBreather** [comment]
Unfortunately there might be other green stuff on there than just the lights... in principle I'm sure this could be done. But it's hard to find something that doesn't break certain graphics. Now if the lights had been a specially reserved space on the color palette.. that would be different.

**Comment by JGRennison** [comment]
> ![signals_pbs](https://user-images.githubusercontent.com/24273113/115985626-afc6c580-a5e7-11eb-8e59-41b3cdbee593.png)
> ![light-generic](https://user-images.githubusercontent.com/24273113/115985627-b5bca680-a5e7-11eb-9ec8-bcfdd9356c30.png)
> 
> OpenGFX style 4-aspect signals graphics

Thanks for this. I've included the block-signal part of this into a GRF here: https://github.com/JGRennison/multi-aspect-signals-grf.

**Comment by JGRennison** [comment]
This is in the most recent release.
