### ISSUE TITLE
Game crash when selecting "Parent" in industry's NewGRF debug window

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#248]
## Version of OpenTTD
jgrpp-0.41.0

## Expected result
When clicking the "Parent" button in the NewGRF property inspect window for a given industry, the game should not crash regardless of whether or not (industry) NewGRFs are used.

## Actual result
When clicking the "Parent" button in the NewGRF property inspect window for a given industry, the game crashes.
[crash-20210424T223607Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/6370881/crash-20210424T223607Z.zip)

Note that such a crash only occurs for industries provided by the base game. If the industries are provided by a NewGRF (most industry NewGRFs should do), clicking "Parent" on their NewGRF property inspect windows does not crash.

## Steps to reproduce
1. Do not have any NewGRFs active.
2. Start a new game, making sure to have some industries.
3. Click on one of the industries.
4. Open the NewGRF property inspect window for the industry.
5. In the NewGRF property inspect window, click "Parent". The game crashes.
6. Restart the game and activate an industry NewGRF.
7. Repeat steps 2-5. The game should not crash.

**Comment by JGRennison** [comment]
Thanks, this is fixed now.
