### ISSUE TITLE
Crash when trying to demolish airport (assertion failed)

### ISSUE THREAD

**Issue by Lippur** [JGRennison/OpenTTD-patches#252]
[crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/6375209/crash.zip)

## Version of OpenTTD
1.11.1 with 0.41.1 patches. Windows 10 19042.928.

## Steps to reproduce
I tried to demolish an (empty) airport, this crashed the game. I reloaded and tried with a different airport, it crashed again.
In the attached save, the red company has two airports, both of which I tried to demolish.

```
Crash reason:
 Exception:  E1212012
 Location:   00007FFD36644B59
 Message:    Assertion failed at line 936 of /home/jgr/openttd/jgrpp/src/command.cpp: _docommand_recursive == 0
```

**Comment by JGRennison** [comment]
This is fixed in the most recent release now.
