### ISSUE TITLE
Possible issue with "Group by"/"Sort by" columns in station cargo list

### ISSUE THREAD

**Issue by embeddedt** [JGRennison/OpenTTD-patches#253]
## Version of OpenTTD

jgrpp-0.41.0

## Expected result

The column should be approximately as wide as the containing text.

Screenshot from OpenTTD nightly 20210430:

![vanilla](https://user-images.githubusercontent.com/42941056/116749760-699aa900-a9cf-11eb-897a-abfdb6118278.png)

## Actual result

The column is wider than it needs to be on JGRPP. My educated guess is that the initial window size is bigger than vanilla, but the layout logic isn't taking this into account.

Screenshot from JGRPP-0.41.0:

![jgr](https://user-images.githubusercontent.com/42941056/116749814-7c14e280-a9cf-11eb-8009-596e6a05e6a4.png)

Note that the `Via-Destination-Source` text could fit without problems if the column wasn't this wide.

## Steps to reproduce

1. Start a new game.
2. Create a rail station.
3. Click the station.

## Additional context

My font settings in `openttd.cfg` are:

```
small_font = DejaVu Sans
medium_font = DejaVu Sans, Bold
large_font = DejaVu Serif, Bold
mono_font = DejaVu Sans Mono, Bold
small_size = 12
medium_size = 12
large_size = 16
mono_size = 12
small_aa = true
medium_aa = true
large_aa = true
mono_aa = false
```

**Comment by JGRennison** [comment]
Thanks, this is fixed now.
