### ISSUE TITLE
[Suggestion] Add to homebrew casks

### ISSUE THREAD

**Issue by unbeatable-101** [JGRennison/OpenTTD-patches#257]
https://github.com/Homebrew/homebrew-cask

It'll make it easy for people to update and/or check for updates by running `brew upgrade --greedy` or `brew upgrade [Whatever you name it]`

**Comment by James103** [comment]
Suggested package name: `openttd-jgrpp` (for consistency with `CPACK_DEBIAN_PACKAGE_NAME`)

**Comment by JGRennison** [comment]
I'm not an Apple user and so could not use or test this myself, but I've got no objections to you adding a package for this on there.

**Comment by unbeatable-101** [comment]
Submitted: https://github.com/Homebrew/homebrew-cask/pull/105747

**Comment by unbeatable-101** [comment]
Update, it'll be added as `jgrennison-openttd`

**Comment by unbeatable-101** [comment]
It has been added
