### ISSUE TITLE
Assertion failed at line 578 of road_cmd.cpp (inspecting tile)

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#258]
When inspecting tile 877x171 in the attached savegame, the game crashes: 
[crash-20210515T095803Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/6485398/crash-20210515T095803Z.zip)
From #256: [crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/6479754/crash.zip)

To be more specific, the following assert gets triggered:
https://github.com/JGRennison/OpenTTD-patches/blob/f3e0507c549de90d1073124403763482bb8cade1/src/road_cmd.cpp#L578

This is because the tile being referenced actually has no road on it despite looking like it has both road and tram on it. With the tile being isolated,
![image](https://user-images.githubusercontent.com/37945304/118356590-973d3180-b53b-11eb-9b1c-8631f3d22ce4.png)

## Version of OpenTTD
```
OpenTTD version:
 Version:    jgrpp-0.41.1 (0)
 NewGRF ver: 1c006d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: May  8 2021 11:12:26
 Defines:    NDEBUG WITH_BITMATH_BUILTINS WITH_OVERFLOW_BUILTINS WITH_DEMANGLE WITH_BFD0 WITH_DBGHELP TTD_ENDIAN=TTD_LITTLE_ENDIAN WITH_PNG WITH_ZLIB WITH_LIBLZMA WITH_LZO WITH_ZSTD WITH_OPENGL WITH_PERSONAL_DIR WITH_SSE WITH_ASSERT UNICODE _UNICODE WITH_UNISCRIBE _SQ64

Operating system:
 Name:     Windows
 Release:  10.0.19041 ()
 Compiler: GCC 9.3.0 "9.3-win32 20200320"
```

## Steps to reproduce
1. Load the crash save game or the save game from #256.
2. Inspect the tile at 0x2AF6D (877 x 171) or attempt a `CmdLandscapeClear` on that exact tile.
3. The game crashes.

**Comment by JGRennison** [comment]
It's difficult to determine how the tile got into the invalid state it is now.
Given that the issue in #256 could in principle result in random memory corruption this doesn't necessarily indicate that there is an additional bug. I check the various code paths where road tile states are handled though.

In the meantime, building a road or tram road stop over the tile restores the tile to a valid state without triggering an assert.

**Comment by deraffe** [comment]
Since I just ran into this same issue, yes, it's very likely that the bug from #256 caused corrupted tiles.
