### ISSUE TITLE
"General error" when connecting to server to Linux, same config works on Windows server

### ISSUE THREAD

**Issue by Linkandzelda** [JGRennison/OpenTTD-patches#262]
I started up a server on Ubuntu 20.04 using both a freshly compiled version of 0.41.2 and the release .deb. However none of my clients can connect.

```
dbg: [net] [tcp/game] sent packet type 14 (SERVER_WELCOME) to client 2, status: 4 (AUTHORIZED)
dbg: [net] [tcp/game] sent packet type 15 (SERVER_CLIENT_INFO) to client 2, status: 4 (AUTHORIZED)
dbg: [net] [tcp/game] received packet type 16 (CLIENT_GETMAP) from client 2, status: 4 (AUTHORIZED)
dbg: [net] [tcp/game] received packet type 43 (CLIENT_ERROR) from client 2, status: 6 (MAP)
dbg: [net] non-joined client 2 reported an error and is closing its connection (general error) (5, 7, 15)
dbg: [net] Closed client connection 2
dbg: [net] [tcp/game] sent packet type 18 (SERVER_MAP_BEGIN) to client 2, status: 6 (MAP)
```

Using the same configuration on the same version with Start Server on Windows allows clients to connect.

**Comment by Linkandzelda** [comment]
I found the problem, this happens when the `client_name` under the `[network]` setting on the server is empty. I changed it to `server`, and was able to connect using the client. Seems a bit odd though that this would cause such a "General error".

**Comment by James103** [comment]
Are you able to reproduce this with the latest [OpenTTD nightly](https://www.openttd.org/downloads/openttd-nightlies/latest.html) (2021-05-28 as of the time of writing)?

**Comment by JGRennison** [comment]
Thanks for tracking this down. It had already been reported and fixed upstream in https://github.com/OpenTTD/OpenTTD/issues/9243.
This is now applied in 62e3bfd68
