### ISSUE TITLE
Excessive recursion creating/destroying AI companies during script `exec`ution causes game crash

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#263]
Attached is the latest crash.dmp from reproducing in 0.41.2, the crash.log files from 0.41.1 and 0.41.2, and the script file that was `exec`uted to reproduce the crash. Clicking "Emergency Save" results in "Save Failed" instead of an actual emergency save.
[crash-ai-recursion.zip](https://github.com/JGRennison/OpenTTD-patches/files/6564515/crash-ai-recursion.zip)

`-d script9sl4` log at time of crash:
```
dbg: [misc] [squirrel] Failed to compile 'C:\Users\james\Documents\OpenTTD jgrpp\openttd-jgrpp-0.41.2-windows-win64\ai\compat_0.7.nut'
dbg: [script] [1] [E] Failed to load API compatibility script
dbg: [script] Error compiling / running API compatibility script: C:\Users\james\Documents\OpenTTD jgrpp\openttd-jgrpp-0.41.2-windows-win64\ai\compat_0.7.nut
dbg: [script] The script died unexpectedly.
dbg: [sl] Game Save Failed
File not writeable
```

## Version of OpenTTD
jgrpp-0.41.1 and jgrpp-0.41.2

I could not get this to crash in `20210528-master-gce1c60699a` though, it just finishes the script normally (though it may take a few minutes).

## Steps to reproduce
1. Create a file named `recursion.txt` with the following contents and place it in your OpenTTD installation's working directory (typically `C:\Users\[user name]\Documents\OpenTTD` on Windows).
2. Start OpenTTD.
3. Click "Check Online Content" and download "IdleMoreMore" from BaNaNaS.
4. Start a new map or load an existing save game.
5. Run `exec recursion.txt`

## Contents of `recursion.txt`
```mcfunction
startai idlemoremore
stopai 2
exec recursion.txt
startai idlemoremore
stopai 2
exec recursion.txt
```
(repeat the last 3 lines if the above is insufficient to crash)

**Comment by JGRennison** [comment]
This should be resolved by 2606f5409a711a5e17dce61bec75fa2d77e584c6
