### ISSUE TITLE
Bug Report: Can't join dedicated server if server is started from scratch.

### ISSUE THREAD

**Issue by erinacio** [JGRennison/OpenTTD-patches#265]
## Version of OpenTTD
jgrpp-0.41.2 on Arch Linux

## Expected result
Dedicated server can still be joined from scratch.(i.e. from empty config or default configs only, vanilla OpenTTD 1.11.2 behavior).

## Actual result
Client aborted connection to such server, without any explicit indication about what went wrong.

## Steps to reproduce

1. `docker run --rm -it -p 3979:3979 -p 3979:3979/udp erinacio/openttd-jgrpp:0.41.2 -D`
    - Dockerfile at: https://github.com/erinacio/openttd-jgrpp-docker/blob/0.41.2/Dockerfile
2. Start a new client and join the server at localhost:3979.
3. Client aborts connection. Server gots `CLIENT_ERROR`.
4. Set server name to something else in console, like: `name server`.
5. Now the server can be connected.

-----

This issue is dicovered when I'm testing my docker image for openttd-jgrpp. Seems that it's caused by client side checking server's "client name". The server's "client name" is always empty when started without any explicit configuration, which won't pass client side check, so connection will always fail.

In `src/network/network_client.cpp`

```cpp
NetworkRecvStatus ClientNetworkGameSocketHandler::Receive_SERVER_CLIENT_INFO(Packet *p)
{
    // several lines omitted
    if (!NetworkIsValidClientName(name)) return NETWORK_RECV_STATUS_MALFORMED_PACKET;
    // several lines omitted
}
// hundreds of lines omitted
bool NetworkIsValidClientName(const std::string_view client_name)
{
	if (client_name.empty()) return false;
	if (client_name[0] == ' ') return false;
	return true;
}
```

**Comment by embeddedt** [comment]
This might potentially be a duplicate of #262?

**Comment by erinacio** [comment]
> This might potentially be a duplicate of #262?

Yes, seems to be a duplicate. I noticed the commit, but didn't check it carefully and thought it was for client side. Thanks for figuring out.
