### ISSUE TITLE
Date Field has not enough room for wall clock plus full date

### ISSUE THREAD

**Issue by VacuumBreather** [JGRennison/OpenTTD-patches#269]
Title says it all
![Date](https://user-images.githubusercontent.com/61427715/121504775-8f5d9980-c9e2-11eb-8734-4a3c469f60bd.jpg)

**Comment by JGRennison** [comment]
Should be fixed by 704eac82203df14876d01f4f54d1349b8d0378de, c2762de4e4169ef6cf5b3bc7f8bdaae5dc5be439
