### ISSUE TITLE
Crash when a company is deleted

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#276]
[This file](https://github.com/JGRennison/OpenTTD-patches/files/6649831/server_2.zip) contains three sets of crash logs and saves while I running dedicated server.
I've checked these:
 * It is fine at 1.11.2 stable
 * Crashes regardless of using whether new map or a scenario
 * Crashes if I delete a company via console
 * Crashes if a company was autocleaned

## Version of OpenTTD
jgrpp-0.41.3

## Steps to reproduce
1. Open a (dedicated) server by using the save
2. Make some empty companies
3. Delete an empty company in console (eg. ``reset_company 2``)

**Comment by JGRennison** [comment]
This one has already been fixed, it is this issue: https://github.com/OpenTTD/OpenTTD/issues/9348

It will be in the next release:
