### ISSUE TITLE
Bug Report - question mark instead of ship

### ISSUE THREAD

**Issue by geby** [JGRennison/OpenTTD-patches#289]
## Version of OpenTTD

WIN 10 Home 19043.1052 + JGRpp 0.41.2
## Expected result

See ship in "First ship arrives to" pop-up.
## Actual result

Game shows instead a question mark as the sprite would be missing.
![question mark](https://user-images.githubusercontent.com/5877852/122717663-386e8480-d26c-11eb-9cb0-7dc8bb3faa4d.png)

## Steps to reproduce

1. Open attached save as non-dedicated server.
[question mark.zip](https://github.com/JGRennison/OpenTTD-patches/files/6684554/question.mark.zip)
2. Go somewhere away from Fishing Grounds.
3. Connect to the server as client, prefarably with a Red + Yellow CCs (tested with this combination, while server host had blue + blue)
4. Go to some Fishing Grounds, build ship depot nearby.
5. Buy "Marstein Freighter" ship and send it to fully load fish at Fishing Grounds.
6. Make sure server host is far away.
7. Wait for ship to arrive to station.
8. Look at host's game screen.
9. See the news pop-up about first ship at station.

**Comment by geby** [comment]
This needs in my opinion more investigating, for example if it can happen with other ships or different NewGRF list. Feel free to investigate.

**Comment by geby** [comment]
I tried to reproduce it with no NewGRFs, however it has not happened to me there. Maybe it has something to do with 1CC vs 2CC or with Oil rig vs Fishing Grounds...

**Comment by JGRennison** [comment]
Thanks, this should be fixed by bf0158d8f1f704cc4bd614c40242cd7b1ee21440

**Comment by geby** [comment]
Hi, it seems you probably forgot to close this issue. Closing it now.
