### ISSUE TITLE
Station rating tooltip disappears

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#298]
## Version of OpenTTD
jgrpp-0.42.2

## Expected result
Station rating tooltip keeps displaying when "Show tooltip" setting is "Right click".

## Actual result
Does not.
![station rating tooltip issue](https://user-images.githubusercontent.com/10726524/125292572-8d7a5380-e35d-11eb-9d41-7b33a041bc8e.gif)

## Steps to reproduce
1. Set ``Settings > Interface > General > Show tooltips`` as ``Right click``
2. Right click the station rating
3. Tooltip does not appear, sometimes it appears just a fleeting moment but mostly it does not appear.

**Comment by JGRennison** [comment]
This should be fixed in 0.42.3
