### ISSUE TITLE
Bug Report - Can't change to company 1 in multiplayer in a certain situation

### ISSUE THREAD

**Issue by audunmaroey** [JGRennison/OpenTTD-patches#301]
## Version of OpenTTD
JGRPP - 0.42.0
Windows 10 - build 19043.1110

## Expected result
I successfully join Company 1

## Actual result
Nothing

## Steps to reproduce
1 Create a game with several companies
2 Join a company other that Company 1
3 Save the game.
4 Abandon game
5 Start a new multiplayer with the save from step 3
6 Try to Join Company 1

As a workaround you can join a different company than Company 1 (if you have more than 2 companies in your save). After that you can join company 1 without any issue.

**Comment by James103** [comment]
Do you get any error messages displayed in the GUI or log when you try to join the company? If so, can you please post them here? You might want to try setting up a dedicated server and running it with `openttd -d 9`.
