### ISSUE TITLE
Bug Report - RV depot problem (see description)

### ISSUE THREAD

**Issue by geby** [JGRennison/OpenTTD-patches#302]
## Version of OpenTTD

JGRpp 0.42.2 WIN 10 (sorry, had an unnoticed typo there)
## Expected result

RV no. 1 from this savegame
[depot bug.zip](https://github.com/JGRennison/OpenTTD-patches/files/6864270/depot.bug.zip)
should not state, he is going explicitely (as I have Shift clicked on depot mark) to the tram depot, instead it should throw a message "it cannot go there"...
## Actual result

RV enters adjacent depot of another company and behaves it was his destination. (the another company has sharing off)

## Steps to reproduce

1. Open the savegame.
2. Unpause the game.
3. Observe RV no. 1 stated destination and actual destination.
4. If he does not have a destination, shift-click a depot icon and tell him to go to the tram depot.

**Comment by JGRennison** [comment]
Thanks, this should be fixed in the next release.
