### ISSUE TITLE
Bug Report about critical synchronization Error

### ISSUE THREAD

**Issue by redbeanarea** [JGRennison/OpenTTD-patches#305]
## Version of OpenTTD
JGRPP 0.42.2, macOS Big Sur 11.4 (with apple silicon)

## Expected result
freezing while playing with multiplayer

## Actual result
 synchronization error message appears, the game goes out as the main. so I can't play opened JGRPP with my friends.

## Steps to reproduce
 Start JGRPP 0.42.2 with computer which installed macOS 11.4 and this needs Wi-fi connection. After you join a multiplayer server, play some minutes, so you'll experience critical error. ( I played this game with Korean, but I expect this error will appear English(US) too.

Please solve this serious problem. I beg you.
[archieve.zip](https://github.com/JGRennison/OpenTTD-patches/files/6930021/archieve.zip)

**Comment by James103** [comment]
Does this occur with **any** compatible multiplayer server or just specific servers? If it's just specific servers, can you please list which ones? Also, can you please try testing this with a locally hosted multiplayer server as soon as possible?

**Comment by redbeanarea** [comment]
> Does this occur with **any** compatible multiplayer server or just specific servers? If it's just specific servers, can you please list which ones? Also, can you please try testing this with a locally hosted multiplayer server as soon as possible?

I played with a server name '[KOR] 대중교통 커뮤니티-tcafe 공식 서버#1'. I played at this server with my old windows PC, but that hadn't occurred that error. And I tried to play my friend's locally hosted server, but I experienced same error.
