### ISSUE TITLE
Bug Report - train slowing (a lot) down at level crossing with realistic braking

### ISSUE THREAD

**Issue by Sinas128** [JGRennison/OpenTTD-patches#310]
## Version of OpenTTD

jgrpp-0.42.2
## Expected result

I expected the train to go on at full speed (or slightly reduced after a block signal in front of a crossing)
## Actual result

The train deaccelerates to like 40 kmph
## Steps to reproduce

Idk how to reproduce it but it happens mutiple times at the same location.
I think when a bus just leaves the level crossing, and a train approaches.
![image](https://user-images.githubusercontent.com/88989774/129763739-bf412e74-86e7-48c7-b855-0c17cf7b8a38.png)

**Comment by JGRennison** [comment]
Could you upload the savegame?
It's not really possible to look at speed-related issues from a static screenshot.

That said, moving the signal to be in front of the level crossing instead of after it may be worth trying.

**Comment by Sinas128** [comment]
[https://drive.google.com/drive/folders/1_QwQ96YhGDfjipWxGwzyrjV1l45j7tDF?usp=sharing](url)
This only happens rarely, and it may be that ive been ''lucky'' to see it happen twice
I was too late on saving when it happend twice, so you might be stuck watching a level crossing.
(its the fast tracks)

**Comment by JGRennison** [comment]
This should mitigate the issue.
In the fullness of time this feature ought to be improved, but it's not something that I can address at the moment.

**Comment by JGRennison** [comment]
This is in the most recent release.
