### ISSUE TITLE
Crash Report - loading CZTR ground into JGR

### ISSUE THREAD

**Issue by Sinas128** [JGRennison/OpenTTD-patches#311]
## Version of OpenTTD

JGRpp 0.42.2
## Steps to reproduce

Loading the CZ GROUND 2.0.0 file

I can not provide a crash file because it crashes before the world is loaded.

![image](https://user-images.githubusercontent.com/88989774/129911508-e7164b6d-ee0d-4a6c-9abf-cc8f643ad82b.png)
As you can see, the game tries to load in the buildings into the menu screen, and then stops loading. It just gets stuck.

I'm unsure wheter this is caused by the grf or my settings. (no game scripts were used)

**Comment by embeddedt** [comment]
Cannot reproduce with https://github.com/JGRennison/OpenTTD-patches/commit/b8d5113c5a90d59972d5c6461978bedfde2458a0 and the following settings:

![screenshot](https://user-images.githubusercontent.com/42941056/129914760-76c45203-f2b2-4974-adcb-53690066003b.png)

![screenshot_1](https://user-images.githubusercontent.com/42941056/129914789-854b4c1f-7164-428a-8ca7-77a58d490102.png)

**Comment by Sinas128** [comment]
![image](https://user-images.githubusercontent.com/88989774/129915546-170ff4b7-f49c-4aaf-9d08-5bc2d291f85e.png)
I seem to be able to instantly reproduce
I will reinstall 42.2 to see if it does anything

**Comment by Sinas128** [comment]
Ive reinstalled 42.2, and even to 42.3, it still happens

**Comment by JGRennison** [comment]
I can't reproduce anything with those GRFs here.

Are you sure that there isn't a crash log generated? Crashing during map generation should not mean that no files are generated.
Which platform are you running on, could you post your config?

**Comment by Sinas128** [comment]
I cant find any crash logs regarding this.
I'm running on windows 10 64x

**Comment by Sinas128** [comment]
I reinstalled, everything, begin to end.
its fixed
