### ISSUE TITLE
(Suggestion) More improvements in template replacement window

### ISSUE THREAD

**Issue by qamil95** [JGRennison/OpenTTD-patches#312]
Hi! Thank You for adding #299 into master!
I have some more suggestions regarding template replacement window:

1. In Create/Edit Template Vehicle, some useful information is missing. Could you add Byuing Cost (it is displayed after clicking OK in Available Templates), and running cost for full train (this is displayed nowhere in template window)?
1. If you buy normal train and use cargo filter for wagons, it will show refitted capacity (and show buy and refit button). However, in template replacement, "default" cargo is used regardless of filter set.
![obraz](https://user-images.githubusercontent.com/19841000/130067219-f497ceb6-f9c0-4322-99c6-d37cfeb93a78.png)
Not sure if it's fixable easily, because standard "replace vehicles" dialog behaves the same way.
1. Is there possibility to "buy train defined in template", other than "buy any train, create group for it and start replacing"?

Regards and Thank You for your work!
Kamil

**Comment by JGRennison** [comment]
These should be sorted in the next release.

On 3, there is a current workaround:
If you edit the template, you can clone the train shown in the edit window. You can then cancel the template edit.

**Comment by JGRennison** [comment]
This is fixed in the most recent release.
