### ISSUE TITLE
Bug Report - routing restriction button + bulldozer button = remove signal

### ISSUE THREAD

**Issue by geby** [JGRennison/OpenTTD-patches#313]
## Version of OpenTTD

WIN 10 JGRpp 0.42.2

## Expected result

I expect, that with the cog wheel button (the one used to set the routing restrictions) it is impossible to build/remove signals. 

## Actual result

While it is not possible to build with that button clicked, removing signals is actually possible.
## Steps to reproduce

Try to build signal with the routing restrictions button and then remove signal with both bulldozer and restrictions buttons clicked.

**Comment by JGRennison** [comment]
This will be fixed in the next release. The remove and routing restriction buttons are mutually exclusive now.
