### ISSUE TITLE
Trains stuck in Depot "heading for" next station (not waiting for free path, not lost)

### ISSUE THREAD

**Issue by dylansan** [JGRennison/OpenTTD-patches#316]
## Version of OpenTTD
JGR 0.42.3

## Expected result
Train leaves the depot and proceeds to the station in its orders.

## Actual result
Train remains in station, with status "heading for [next station]" and does not move. All trains in the depot have the same problem. Other trains are unable to route to this depot.

## Steps to reproduce
In the uploaded save, I have simplified the track layout and train orders for debugging purposes. There is one train in the Depot with orders to go to Montégut. It is "heading for Montégut" but will not move. Another train is stopped near a platform at Montégut station.

- The train in the depot will not move. Stopping, reversing, or changing the orders of the train has no effect.
- If the train in the depot is stopped, and the train at Montégut is sent to Depot N1, it is unable to enter the depot.
- If the train in the depot is deleted, the other train still cannot enter.
- If the depot is deleted and replaced in the same position, the train can enter as expected. This indicates that the depot itself may be the issue, not the train or the pathfinding, but I am not familiar with the code.

[Crémieux Transport, 1876-07-28 BUG REPORT DEPOT STUCK.zip](https://github.com/JGRennison/OpenTTD-patches/files/7071004/Cremieux.Transport.1876-07-28.BUG.REPORT.DEPOT.STUCK.zip)

**Comment by JGRennison** [comment]
The depot tile is reserved, as if another train has reserved a route into the depot. Unfortunately you can't see this when the depot is facing north-west or north-east.
Using the ignore signals button and then the reversing the train back into the depot should clear this, the train should then be able to reserve a path.
Do you remember if you were doing anything specific around the depot when the problem first occurred?

**Comment by dylansan** [comment]
As I mentioned on discord, I believe the train causing this problem had used a "reverse behind" signal, and I may have manually reversed it around the same time. I was able to get the train to leave the station and it then continued at 30mph in the "reversing" state until I manually reversed it again.

On a related note, I had also noticed some long trains getting momentarily lost when passing the reversing signal, until they finished turning around. I believe it was because there was another signal after it that the train had to pass in order to reverse. Adding an extra tile in between fixed it.

Here's the original file where I encountered the issue if it helps diagnose anything.
[Crémieux Transport, 1876-07-07.zip](https://github.com/JGRennison/OpenTTD-patches/files/7071132/Cremieux.Transport.1876-07-07.zip)

**Comment by JGRennison** [comment]
I've been able to reproduce this.
If there is a reservation heading into the depot, and another train inside the depot, pressing the reverse button on the train inside the depot removes the reservation of the train coming into the depot, and leaves the depot itself reserved, which blocks the depot as seen in your save. This issue is also present in trunk, so I will submit a bug report upstream in a bit.

**Comment by JGRennison** [comment]
Upstream bug report: https://github.com/OpenTTD/OpenTTD/issues/9520

**Comment by JGRennison** [comment]
This is fixed in the most recent release.
