### ISSUE TITLE
want to translate this patch to Russian

### ISSUE THREAD

**Issue by RIS2000** [JGRennison/OpenTTD-patches#319]
Hello!
Thanks for a great extensions for a great game!

I would like to make a translation to Russian language of missing strings.
How can i do this ?

**Comment by Gugui322** [comment]
You can clone the repository and edit the [russian language file](https://github.com/JGRennison/OpenTTD-patches/blob/jgrpp/src/lang/russian.txt). You will only need permission to make a merge.

**Comment by RIS2000** [comment]
i looked in russian.txt and there is no strings what i see untranslated in game (
![untranslated](https://user-images.githubusercontent.com/30177105/132993560-62b9def1-57fa-4252-a0a8-f054a5052225.png)

**Comment by JGRennison** [comment]
Missing strings are not present in the file at all. Currently you would need to compare russian.txt with english.txt and add the missing strings that way.
I'm aware that that is not ideal, I will see if I can find a way to automate that process a bit.

**Comment by RIS2000** [comment]
Thanks for the clarification. I thought so, but decided to ask just in case.
