### ISSUE TITLE
jgrpp-0.23.0.diff fails to apply at -r 27698

### ISSUE THREAD

**Issue by cpeosphoros** [JGRennison/OpenTTD-patches#32]
On linux:
```
svn checkout svn://svn.openttd.org/trunk openttdtest
cd openttdtest
svn update -r 27698
patch -p0 < jgrpp-0.23.0.diff 
```

Results:
```
patching file .ottdrev-vc
patching file Makefile.bundle.in
patching file Makefile.in
patching file Makefile.src.in
patching file README.md
patching file config.lib
Hunk #2 FAILED at 175.
Hunk #4 succeeded at 510 (offset -2 lines).
Hunk #5 succeeded at 1061 (offset -26 lines).
Hunk #6 succeeded at 1073 (offset -26 lines).
.
.
.
Hunk #23 succeeded at 3569 (offset -12 lines).
Hunk #24 succeeded at 3898 (offset -12 lines).
1 out of 24 hunks FAILED -- saving rejects to file config.lib.rej
.
.
.
Hunk #28 succeeded at 1245 (offset -12 lines).
Hunk #29 succeeded at 1343 (offset -12 lines).
patching file projects/openttd_vs140.vcxproj.filters
can't find file to patch at input line 3565
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: projects/openttd_vs141.vcxproj
|===================================================================
|--- projects/openttd_vs141.vcxproj	(revision 27968)
|+++ projects/openttd_vs141.vcxproj	(working copy)
--------------------------
File to patch: 
```

Cloning the git and compiling it works, but then I cannont apply any other patches, since it doesn't have a svn head to update against.

**Comment by JGRennison** [comment]
The patch is against 27968, but you've checked out 27698. This looks like a typo in the revision number which you're using.

You can apply other patches to a git checkout. You can use git checkout, git commit and git merge as necessary.
That said unless the patches are trivial you will probably run into problems attempting to do so, regardless of which version control system that you're using.

**Comment by topjor** [comment]
@JGRennison, You made a typo in the jgrpp-changelog.md file
(last line of 0.23.0 changes):
`Bump trunk base from r27963 to r27698.`

**Comment by JGRennison** [comment]
Thanks, I've updated the changelog to fix that.

**Comment by JGRennison** [comment]
This is a bit redundant as the SVN upstream is disappearing. So I'll close this.
