### ISSUE TITLE
Error message has incorrect chunk header: "SXLI chunk is unexpectedly present"

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#320]
## Version of OpenTTD
e7480620afd06b34f75a0fb7554bfb3e800ad87c (in source code)

## Expected result
The error message "Broken savegame - SXLI chunk is unexpectedly present" should instead be "Broken savegame - **SLXI** chunk is unexpectedly present". The chunk is SLXI, not SXLI.

## Actual result
https://github.com/JGRennison/OpenTTD-patches/blob/e7480620afd06b34f75a0fb7554bfb3e800ad87c/src/saveload/extended_ver_sl.cpp#L536-L540

## Steps to reproduce
Check the source code using the link above.

**Comment by JGRennison** [comment]
Thanks, this is fixed now
