### ISSUE TITLE
Documentation for Asymmetric (Nearest) and Asymmetric (Equal)

### ISSUE THREAD

**Issue by benjamin-kirkbride** [JGRennison/OpenTTD-patches#321]
It is not clear what each of these do, and how they compare to the base "Asymmetric" distribution model. From reading the commit (https://github.com/JGRennison/OpenTTD-patches/commit/e7a916d2cec55dac60f7d944a58bff8839ea240d) I get the impression that it has something to do with distance? But I'm not sure.

**Comment by JGRennison** [comment]
Asymmetric (equal) mode attempts to distribute cargo such that the same amount of cargo arrives at each accepting station.
Broadly each accepting station gets an equal fraction of the total supply into the network.
This is mainly intended for supply cargoes such as in FIRS.

Asymmetric (nearest) mode sends all cargo to whichever accepting station is nearest.

**Comment by benjamin-kirkbride** [comment]
@JGRennison Gotcha, and how does that differ from the "vanilla" Asymmetric mode?

**Comment by JGRennison** [comment]
Vanilla asymmetric distributes cargo according to the "Effect of distance on demands" setting.
Broadly, closer stations gets more cargo, those further away get less.
