### ISSUE TITLE
Patch inclusion request: The Clipboard (aka Copy & Paste)

### ISSUE THREAD

**Issue by cpeosphoros** [JGRennison/OpenTTD-patches#33]
Hi there,

This is an amazing pack and I love playing with it.

I couldn't however, as many as I tried, integrate it with The Clipboard (https://www.tt-forums.net/viewtopic.php?f=33&t=45488&start=200) patch.

Any chances you could integrate it yourself? I think it would be a great addition to the gameplay.

Thanks.

**Comment by JGRennison** [comment]
This one has been asked before. I'm not keen on it personally, and integrating it would require significant effort. The code cannot be dropped in as-is.

**Comment by KeldorKatarn** [comment]
Last time I checked the code it looked really messy and every report on it I've read calls it "very buggy". The thing is also of questionable use when you can't save any templates to disk. I mean I have certain station layouts that I'd love to just plop down but... for this to be REALLY useful it would have to be greatly expanded.

**Comment by letharion** [comment]
I'd also like to see this integrated, or at least the patch working with this version of ttd.

Unfortunately I'm not familiar with the OpenTTD codebase, and my cpp is a bit rusty as well, so even though I'll try, it'll be hard. If anyone is interesting in collaborating on the task, I'd like to give it a try though.
