### ISSUE TITLE
(Suggestion) add a function to build newgrf's building during game

### ISSUE THREAD

**Issue by Cyanhld** [JGRennison/OpenTTD-patches#331]
Now, if a player wants to build a city building he or she wants during the game, he or she has to convert the game into a scenario file, build a building, and convert it back into a game file. However, it is expected that this hassle will be reduced by adding the ability to build buildings during games like objects to the next update. Although I don't know how to code, I'm just suggesting it, but I expect it to draw a good response.

**Comment by James103** [comment]
See #194

**Comment by Cyanhld** [comment]
I've read the post. However, it was not known whether this function was updated. Will this function be updated?

**Comment by James103** [comment]
The same text as the original post still applies to my current proposal. I've gone ahead and updated the version to reflect that.

**Comment by Cyanhld** [comment]
I checked the contents. Thank you so much.
