### ISSUE TITLE
[Bug]: unexpected unloading of just loaded train

### ISSUE THREAD

**Issue by jchylik** [JGRennison/OpenTTD-patches#337]
### Version of OpenTTD

v0.44 

### Expected result

Firstly, I really liked the previous version. In the current version. the trains is set to "fully load any cargo" and go to the next station. In this case the cargo is iron ore, and the next station is receiving (next to the steel mill).

### Actual result

After being fully loaded, the train starts unloading and then leaves.
The cargo (iron ore) remains in the station. And the cargo distribution information is showing that this cargo is intended to head to the station next to the steel mill. 
![screenshot_unloading_bug](https://user-images.githubusercontent.com/49030099/142721678-10622c6a-8c63-4ea0-b812-262c125d6f89.png)

### Steps to reproduce

1. start a new game
2. build a station next to iron ore mine with station next to steel mill
3. send a train with iron ore hopper to fully load in mine station and then go to the mill station 
4. observe how train waits to be fully loaded and then unload before leaving

**Comment by JGRennison** [comment]
This is from 71c39dc8, you're running a more recent version than 0.44.

The non-stop flag is missing from your order list and I'd forgotten about those types of orders, generally they should not be used. This will be fixed shortly.
