### ISSUE TITLE
[Bug]: "Failed to stop at" message shown even when successfully stopped there.

### ISSUE THREAD

**Issue by geby** [JGRennison/OpenTTD-patches#346]
### Version of OpenTTD

JGRPP 0.44.0

### Expected result

Do not show message when train "fails" to stop at start/middle of platform when train stops there later.

### Actual result

The message pops after passing the regular stop place, but train stops sometimes right after, sometimes later.

### Steps to reproduce

[autosave3.zip](https://github.com/JGRennison/OpenTTD-patches/files/7777185/autosave3.zip)

1. Open Save. (same file as in #345 )
2. Look inside of vehicle lists for Blue company's train no. 7 and open small Vehicle Info window.
3. Unpause.
4.  Wait until it comes at big drive-through station. (at my end it always produced the same breakdown when aproaching that station)
5. After #345 happens that train is too late to stop at middle of platform, so message pops out, but train stops successfully at that station.

**Comment by JGRennison** [comment]
With various changes to realistic braking, this appears to be solved now.
Can you re-open if you're still having problems with more recent versions.
