### ISSUE TITLE
[Suggestion] Increase Waypoint Limit

### ISSUE THREAD

**Issue by EratoNysiad** [JGRennison/OpenTTD-patches#349]
Hey,

I regularly play on an eyecandy heavy game, and this means that we have many station NewGRFs loaded. There seems to be a Waypoint limit of ~256 though, which we pretty much always hit every time we start a new game, meaning we have to play around with the NewGRFs that are loaded. It would be nice if we could have more waypoints.

The real solution here is to have waypoint categories but that's not how it's coded.

Thanks

**Comment by Quast65** [comment]
Ran into the same issue ;-)
(also reached the max number of 255 GRF's too... )

**Comment by JGRennison** [comment]
This is in the most recent release now.

**Comment by Quast65** [comment]
Thank you!
