### ISSUE TITLE
Compiling 0.45.0 on Fedora

### ISSUE THREAD

**Issue by KeepinItRail** [JGRennison/OpenTTD-patches#355]
### Version of OpenTTD
JGRPP 0.45.0

### Expected result
Compiling JGRPP. Was able to compile previous versions successfully in Fedora.

### Actual result
Errors obtained when running cmake .. including
```
CMake Warning at cmake/InstallAndPackage.cmake:195 (message):
  Unknown Linux distribution 'fedora' from /etc/os-release found for
  packaging; can only pack to a txz.  Please consider creating a Pull Request
  to add support for this distribution.
Call Stack (most recent call first):
  CMakeLists.txt:458 (include)
```

[CMakeError.log](https://github.com/JGRennison/OpenTTD-patches/files/7821852/CMakeError.log)
[CMakeOutput.log](https://github.com/JGRennison/OpenTTD-patches/files/7821853/CMakeOutput.log)

See cmake logs attached

### Steps to reproduce
Commands I use to compile are:
  ```
  git clone https://github.com/JGRennison/OpenTTD-patches.git Applications/jgrpp-latest
  ```
  Then
  ```
  cd Applications/jgrpp-latest
  git checkout jgrpp-0.45.0
  mkdir build
  cd build
  cmake ..
  make
  ./openttd
  ```

**Comment by JGRennison** [comment]
This warning should not prevent the build from succeeding. As far as I aware packaging to an RPM has not been implemented in any previous version either.
Were there any build errors after this?

**Comment by KeepinItRail** [comment]
Added below what the Terminal returns which isn't too long as it happens pretty early. 

I checked  ZSTD, Allegro and SDL2 which I see mentioned, but I seem to have them.
```
[john@fedora build]$ dnf list --installed zstd
Installed Packages
zstd.x86_64                                                      1.5.1-4.fc35                     @updates
[john@fedora build]$ dnf list --installed allegro
Installed Packages
allegro.x86_64                                                4.4.3.1-6.fc35                  @fedora
[john@fedora build]$ dnf list --installed sdl2
Installed Packages
SDL2.x86_64                                                   2.0.18-3.fc35                    @updates
```
Cmake is 
cmake.x86_64                                                 3.22.1-5.fc35     

### Terminal read-out

[john@fedora build]$ cmake ..
-- Could NOT find ZSTD (missing: ZSTD_LIBRARY ZSTD_INCLUDE_DIR) (Required is at least version "1.4")
-- Could NOT find Allegro (missing: Allegro_LIBRARY Allegro_INCLUDE_DIR) 

CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:58 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:58 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


STATUS,No SDL2main lib not found, I hope you don't need it..
-- Could not find Fcitx (Fcitx is OPTIONAL)
-- Could NOT find Grfcodec (missing: GRFCODEC_EXECUTABLE NFORENUM_EXECUTABLE) 
-- Option Package Dependencies - OFF
-- Option Dedicated - OFF
-- Option Install FHS - ON
-- Option Use assert - ON
-- Option Use threads - ON
-- Option Use NSIS - OFF
-- PNG found -- -DWITH_PNG -- PNG::PNG
-- ZLIB found -- -DWITH_ZLIB -- ZLIB::ZLIB
-- LIBLZMA found -- -DWITH_LIBLZMA -- LibLZMA::LibLZMA
-- LZO found -- -DWITH_LZO -- /usr/include /usr/include -- /usr/lib64/liblzo2.so /usr/lib64/liblzo2.so
CMake Warning at cmake/LinkPackage.cmake:23 (message):
  ZSTD not found; compiling OpenTTD without ZSTD is not recommended
Call Stack (most recent call first):
  CMakeLists.txt:330 (link_package)


-- Fluidsynth found -- -DWITH_FLUIDSYNTH -- /usr/include /usr/include -- /usr/lib64/libfluidsynth.so /usr/lib64/libfluidsynth.so
-- SDL2 found -- -DWITH_SDL2 -- SDL2::SDL2
-- FREETYPE found -- -DWITH_FREETYPE -- Freetype::Freetype
-- Fontconfig found -- -DWITH_FONTCONFIG -- Fontconfig::Fontconfig
-- ICU_i18n found -- -DWITH_ICU_I18N --   -- /usr/lib64/libicui18n.so;/usr/lib64/libicuuc.so;/usr/lib64/libicudata.so 
-- OpenGL found -- -DWITH_OPENGL -- (via SDL2)
-- SSE found -- -DWITH_SSE --   --  
CMake Warning at cmake/InstallAndPackage.cmake:195 (message):
  Unknown Linux distribution 'fedora' from /etc/os-release found for
  packaging; can only pack to a txz.  Please consider creating a Pull Request
  to add support for this distribution.
Call Stack (most recent call first):
  CMakeLists.txt:458 (include)


-- Configuring incomplete, errors occurred!
See also "/home/john/Applications/jgrpp-latest/build/CMakeFiles/CMakeOutput.log".
See also "/home/john/Applications/jgrpp-latest/build/CMakeFiles/CMakeError.log".

**Comment by KeepinItRail** [comment]
Retried to compile 0.44.2, which was successful before, and it now gets the same errors.

So I downgraded cmake to 3.22.1-3, in case it was the latest cmake version that is causing it, but no difference there either. However, it may have released after I had 0.44.2 already working on an even older version of cmake.

Anyway, the generic from the Assets works, so that can be used, but hopefully it's something that resolves. You'll have a much better idea than me what it might be, but I'm suspecting cmake.

![image](https://user-images.githubusercontent.com/74462886/148398021-593be6c6-3951-4672-9e5e-e439e82e0cc6.png)

**Comment by JGRennison** [comment]
You may need to install -devel packages as well.
I presume that the base packages are just binaries without sources.

**Comment by KeepinItRail** [comment]
Installing the -devel packages removes the errors about ZSTD and Allegro

**SDL2::SDL2main** seems to be the focus of what it's complaining about, in addition to the unknown Linux distribution 'fedora'.

Terminal:

[john@fedora build]$ cmake ..
CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:42 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:58 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


CMake Error at /usr/lib64/cmake/SDL2/SDL2Config.cmake:58 (get_target_property):
  get_target_property() called with non-existent target "SDL2::SDL2main".
Call Stack (most recent call first):
  CMakeLists.txt:129 (find_package)


STATUS,No SDL2main lib not found, I hope you don't need it..
-- Could not find Fcitx (Fcitx is OPTIONAL)
-- Could NOT find Grfcodec (missing: GRFCODEC_EXECUTABLE NFORENUM_EXECUTABLE) 
-- Option Package Dependencies - OFF
-- Option Dedicated - OFF
-- Option Install FHS - ON
-- Option Use assert - ON
-- Option Use threads - ON
-- Option Use NSIS - OFF
-- PNG found -- -DWITH_PNG -- PNG::PNG
-- ZLIB found -- -DWITH_ZLIB -- ZLIB::ZLIB
-- LIBLZMA found -- -DWITH_LIBLZMA -- LibLZMA::LibLZMA
-- LZO found -- -DWITH_LZO -- /usr/include /usr/include -- /usr/lib64/liblzo2.so /usr/lib64/liblzo2.so
-- ZSTD found -- -DWITH_ZSTD -- /usr/include /usr/include -- /usr/lib64/libzstd.so /usr/lib64/libzstd.so
-- Fluidsynth found -- -DWITH_FLUIDSYNTH -- /usr/include /usr/include -- /usr/lib64/libfluidsynth.so /usr/lib64/libfluidsynth.so
-- SDL2 found -- -DWITH_SDL2 -- SDL2::SDL2
-- Allegro found -- -DWITH_ALLEGRO -- /usr/include /usr/include -- /usr/lib64/liballeg.so /usr/lib64/liballeg.so
-- FREETYPE found -- -DWITH_FREETYPE -- Freetype::Freetype
-- Fontconfig found -- -DWITH_FONTCONFIG -- Fontconfig::Fontconfig
-- ICU_i18n found -- -DWITH_ICU_I18N --   -- /usr/lib64/libicui18n.so;/usr/lib64/libicuuc.so;/usr/lib64/libicudata.so 
-- OpenGL found -- -DWITH_OPENGL -- (via SDL2)
-- SSE found -- -DWITH_SSE --   --  
CMake Warning at cmake/InstallAndPackage.cmake:195 (message):
  Unknown Linux distribution 'fedora' from /etc/os-release found for
  packaging; can only pack to a txz.  Please consider creating a Pull Request
  to add support for this distribution.
Call Stack (most recent call first):
  CMakeLists.txt:458 (include)


-- Configuring incomplete, errors occurred!
See also "/home/john/.local/share/Trash/files/jgrpp-latest.2/build/Applications/jgrpp-latest/build/CMakeFiles/CMakeOutput.log".
See also "/home/john/.local/share/Trash/files/jgrpp-latest.2/build/Applications/jgrpp-latest/build/CMakeFiles/CMakeError.log".

**Comment by embeddedt** [comment]
This is probably unrelated, but it looks a bit strange that your build appears to be running out of the trash can (`.local/share/Trash/files` is in the build path). I don't think that causes this but I assume it's not what you want.

**Comment by JGRennison** [comment]
The error is coming from /usr/lib64/cmake/SDL2/SDL2Config.cmake which is presumably part of the cmake or SDL2 package.
This isn't part of the OpenTTD source. This suggests that your local installation is broken somehow.

**Comment by KeepinItRail** [comment]
Must have been a recent update to either of those that has broken it, given it worked before.

Thanks for the help

**Comment by KeepinItRail** [comment]
This has now resolved after an SDLT2 update this week! Able to compile successfully.
