### ISSUE TITLE
[Crash]: Instant crash of OpenTDD when using another GFX than OpenGFX

### ISSUE THREAD

**Issue by swtimmer** [JGRennison/OpenTTD-patches#358]
### Version of OpenTTD

jgrpp-0.45.0, OSX

### Steps to reproduce

Installed JGR fresh. Whenever I try to use another GFX than the OpenGFX one (abase for example) I get an instant crash. 

### Upload crash files

[Uploading Archive.zip…]()

**Comment by swtimmer** [comment]
Reinstalled classic OpenTDD to test, with that version the game runs as expected.

**Comment by JGRennison** [comment]
Does the most recent upstream nightly work? https://www.openttd.org/downloads/openttd-nightlies/latest

There have been some recent changes to do with OSX touchbars.

The crash zip upload does not seem to have worked, could you try attaching it again?

**Comment by swtimmer** [comment]
[Archive.zip](https://github.com/JGRennison/OpenTTD-patches/files/7844783/Archive.zip)

**Comment by swtimmer** [comment]
Crash file of the nightly
[Archive.zip](https://github.com/JGRennison/OpenTTD-patches/files/7844796/Archive.zip)

**Comment by JGRennison** [comment]
Thanks, I've forwarded this on to: https://github.com/OpenTTD/OpenTTD/issues/9788
