### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by KeldorKatarn** [JGRennison/OpenTTD-patches#36]
These might be small improvements you can import:

https://github.com/KeldorKatarn/OpenTTD_PatchPack/commit/6aca18d18252f1c2f6d4a215999b7d7afb7df813

https://github.com/KeldorKatarn/OpenTTD_PatchPack/commit/a834d3cd452fe28e2c32fb953d41c0bd0ce20494

The cached YMD date is ESPECIALLY useful on arctic maps where the game CONSTANTLY calculates the YMD in GetSnowLine(). Profiler reported the game spending a ton of time in just the date to YMD conversion function. No point in doing that thousands of time per tick if it only changes every day and we calculate a YMD whenever we change the date anyway to the the current year and month. Why not store the entire thing. A further improvement might be to get rid of _cur_year and _cur_month since they're a bit redundant now. but that's just code cleanup.

**Comment by JGRennison** [comment]
Thanks for these.
