### ISSUE TITLE
[Crash] String 0x8963 is invalid. You are probably using an old version of the .lng file.

### ISSUE THREAD

**Issue by kedzior3** [JGRennison/OpenTTD-patches#368]
![image](https://user-images.githubusercontent.com/82472233/152614626-2eb9c1b9-12b7-4f4e-8a8b-38da01161c24.png)
The new timetable system have an outdated entrys in .lng files, and crashes sometimes after I click on Sheduled Dispatch, or if I assign schedule.

Crashes in English, and Polish version too.
/0.46.0 @ Windows 10 x64.

**Comment by JGRennison** [comment]
This most likely means that you've not unzipped all the files in the release zip, but are using some from a previous version.

I'd suggest unpacking *all* of the files from the release zip into an empty directory to see if that resolves the issue.

**Comment by kedzior3** [comment]
Firstable, I unpacked ALL files from release zip, even with LNG folder, but this problem still exists.

**Comment by JGRennison** [comment]
Actually this is a bug, not an issue with the lang files sorry.

The string handling in the scheduled dispatch window was wrong when the scheduled dispatch schedule was assigned to a depot. This is fixed now and will be in the next release.
