### ISSUE TITLE
[Bug]: Some scheduled dispatch dropdowns do not make sure that the text is always visible.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#369]
### Version of OpenTTD

jgrpp-0.46.0

### Expected result

The dropdown renders white text on a black background when clicking, as shown:
![image](https://user-images.githubusercontent.com/37945304/152617086-aba2431c-aa12-4617-b343-b83f589b0323.png)

### Actual result

The dropdown renders black text on a black background, making it impossible to see the text of the entry being selected:
![image](https://user-images.githubusercontent.com/37945304/152617165-2faa296e-5e89-4008-bed2-79f5b5488e4d.png)

### Steps to reproduce

1. Build or use an existing (train or bus) network.
2. Create a new vehicle or select an existing vehicle.
3. Order the vehicle to go to some stations, if the vehicle has no orders.
4. Open the Scheduled Dispatch window.
5. Click "Enable".
6. Click "Manage Schedule".
7. Click one of the dropdown entries.
8. Notice that the text remains black on a black background, instead of the expected white text on black background.

**Comment by JGRennison** [comment]
This is fixed in the most recent release
