### ISSUE TITLE
[Bug]: Polyline rail tool does not check if bridge is rail or not

### ISSUE THREAD

**Issue by wpi3** [JGRennison/OpenTTD-patches#371]
### Version of OpenTTD

0.46.0, macOS 11.5.1

### Expected result

The polyline rail tool should continue at the tile where the last railway track is built.

### Actual result

The polyline rail tool starts at a road bridge/tram bridge/aqueduct.

### Steps to reproduce

1. Build some rail track using any rail tool
2. Build a road bridge (or a tram bridge/aqueduct)
3. Use the polyline rail tool to build more tracks. It continues at the bridge built in step 2 rather than the track built in step 1.

Note: Building tunnels does not seem to cause such problem.

**Comment by JGRennison** [comment]
Thanks, this will be fixed in the next release

**Comment by JGRennison** [comment]
This is fixed in the most recent release now
