### ISSUE TITLE
[Bug]: Local authority zone GUI button

### ISSUE THREAD

**Issue by wpi3** [JGRennison/OpenTTD-patches#372]
### Version of OpenTTD

0.46.1, macOS 11.5.1

### Expected result

- The zone button in the local authority GUI should function the same as in vanilla OpenTTD 12.1, i.e. synchronous with the town zones in the main view.
- For consistency with the coverage button in the town GUI, the main view should be updated when the local authority GUI is closed, and the town zones would be turned off.

### Actual result

- Clicking on the zone button toggles the local authority zones in the main view, but the GUI does not update to reflect the button status until about one second later.
- Unlike the coverage button, when closing the local authority GUI, town zones are still shown.
- The town zones display state is independent of the button state in GUI, and is instead related to clicking on that button.

### Steps to reproduce

1. Open the town GUI of some town.
2. Click on the "Local authority" button in the bottom left to open the local authority GUI.
3. Toggle the town zones with the button in the top right of the local authority GUI. (Both turning on and off the town zones have this problem with the delay.)
4. Wait for a few seconds and toggle the town zones again.
5. Turn on town zones, then close the local authority GUI. The town zones are still being shown.

**Comment by JGRennison** [comment]
The button not being redrawn is fixed now, that'll be in the next release.

The zone overlay remaining when the window is closed is intentional. This is the same as vanilla.

**Comment by JGRennison** [comment]
This is fixed in the most recent release now
