### ISSUE TITLE
[Bug]: Trains can get stuck going extremely slow (in Tunnels) [Realistic Braking]

### ISSUE THREAD

**Issue by TimetravelerDD** [JGRennison/OpenTTD-patches#373]
### Version of OpenTTD

0.46.1 on Windows 10 (21H1)

### Expected result

Trains in a Tunnel would go at their maximum speed if the way ahead is clear (using the Realistic Braking model)

### Actual result

Trains can sometimes get stuck at a ridiculously low speeds (e.g. 31 km/h or 25 km/h) and jam up the whole network.
It appears it happens mostly (only?) in signaled tunnels and bridges. When they leave the tunnel they return to normal speed.
By stopping the trains and let them go again it can help to clear up the jam but it will happen again eventually.

### Steps to reproduce

1. Load the attached savegame and search the big tunneled hill in the middle of the network marked by a sign (between Westerwald and Oberfeld). Notice the slow trains traveling south though the tunnel. As soon as they leave the tunnel they speed up again
2. It also happens occasionally at other spots at the network e.g. the Westerwald Ring-Metro or Anderbach Mainstation
3. It seems to happen during high congestion

[Anderbach Transport, 1994-08-02_SLOWDOWN.zip](https://github.com/JGRennison/OpenTTD-patches/files/8104825/Anderbach.Transport.1994-08-02_SLOWDOWN.zip)

**Comment by JGRennison** [comment]
I'd suggest turning off the "train speed adaptation" setting.
At present the speeds for this are only recorded and applied at normal rail signals (i.e. not bridges and tunnels), and in general it works best with simple networks. I will see what I can do about this in due course.

Also, it's not really necessary to use that when realistic braking is also enabled.

**Comment by TimetravelerDD** [comment]
Dear JGRennison,
thank you for your analysis – the setting indeed is a complete "Gamechanger" and worked instantly :-)

The only weird side effect is that the trains now constantly change speed up and down ever so slightly, however it doesn't bother me unless I am actually watching the speedometer.

I appreciate your idea for the workaround and your time to even fix it permanently! Your contributions make this already great game so much more enjoyable. ❤
