### ISSUE TITLE
cannot run on windows 11

### ISSUE THREAD

**Issue by toenismeier** [JGRennison/OpenTTD-patches#376]
Following error message in a blue box: "This app can't run on your PC. To find a version for your PC, check with the software publisher." Both JGR and Openttd are the latest build.
![Screenshot 2022-03-18 144801](https://user-images.githubusercontent.com/101820756/159014641-69482d7a-26fa-4c22-bb48-539af9f46c66.png)

**Comment by JGRennison** [comment]
You're probably not running an ARM64 machine, I'd suggest trying again with the "win64" download.

**Comment by toenismeier** [comment]
It's a little bit emberathing, but I've downloaded the arm version. Thank you!
