### ISSUE TITLE
[Bug]: No way to enable PRE signals in Signal Selection menu panel

### ISSUE THREAD

**Issue by modreoci** [JGRennison/OpenTTD-patches#377]
### Version of OpenTTD

0.47.0-1 Linux

### Expected result

To show all possible signals in Signal Selection menu.

### Actual result

It appears only simple BLOCK and PATH signals without PRE signals (see attached screenshot) even it is enabled in config. No icon to toggle signals menu items like in the vanilla game...
![2022-03-23_22-30](https://user-images.githubusercontent.com/10616435/159801225-0b42b492-3a6c-47a9-a71a-9f4b53a1b5d5.png)

### Steps to reproduce

1. Start new or load saved game
2. Click on Railway Construction menu item
3. Click on Signal Selection menu item
4. Showing incomplete menu without PRE signals and icon to toggle items...

**Comment by JGRennison** [comment]
It looks like you are using realistic braking.
This mode differs in several ways from the original braking model, in particular pre-signals and two-way signals are not permitted.
See the train braking model setting for details, or here for more information: https://github.com/JGRennison/OpenTTD-patches/wiki/Realistic-braking

**Comment by modreoci** [comment]
Yes... now it works. THNX ;-)
