### ISSUE TITLE
[Bug]: Build river tooltip does not match actual behaviour

### ISSUE THREAD

**Issue by wpi3** [JGRennison/OpenTTD-patches#378]
### Version of OpenTTD

0.47.1

### Expected result

It is suggested to be possible to build river diagonally with ctrl, both in-game and in scenario editor, as the two share the same string `STR_WATERWAYS_TOOLBAR_CREATE_RIVER_TOOLTIP` saying "Place rivers. Ctrl selects the area diagonally."

### Actual result

It is only possible to build rivers diagonally in scenario editor but not in-game, contrary to what the tooltip suggests

### Steps to reproduce

(see above)

**Comment by JGRennison** [comment]
Thanks, this will be fixed in the next release.

**Comment by VacuumBreather** [comment]
Wouldn't it be better to add diagonal river building than fixing the tooltip? ;)
