### ISSUE TITLE
[Bug]: Scheduled Dispatch window does not update properly when enabling first time

### ISSUE THREAD

**Issue by wpi3** [JGRennison/OpenTTD-patches#380]
### Version of OpenTTD

0.47.1 (but this is an issue since the feature is added in 0.46.0), macOS 11.5.1

### Expected result

The "Enable" button in Scheduled Dispatch should enable the UI

### Actual result

The UI is only usable after pressing "Enable" and then closing and reopening the window.

### Steps to reproduce

1. Set up a train with some orders
2. Turn off Auto Separation if it is enabled (If it is not turned off, only the "Add" button is available in step 4, otherwise everything is the same)
3. Open the Scheduled Dispatch window
4. At this point there are two available buttons, "Enable" and "Add", and shows "No Schedules".
 5a. Click "Enable"
    6. The "Next" button is available, but it is still "No Schedules". The orders UI would show that there is one schedule.
    7. Clicking "Next" does nothing
    8. Clicking "Add" would add a new schedule as shown in the orders UI
    9. Clicking "Enable" simply disables the UI and reenabling it would go back to step 5a
 5b. Click "Add"
    6. The "Next" button is available, but it is still "No Schedules"
    7. Clicking "Enable" would go to step 5a, except that the number of schedules shown in the orders UI is the number of times the "Add" button is clicked.

In any of these cases, the scheduled dispatch UI becomes available only after enabling it (i.e. the "enable" button is toggled on) and then closing and reopening the window.

**Comment by JGRennison** [comment]
Thanks, it seems that this only doesn't work for multiplayer clients which is why I had not been able to reproduce any issue previously. This should be fixed now.
