### ISSUE TITLE
[SUGGESTION] UI Windows should retain last set size and position.

### ISSUE THREAD

**Issue by A-mak88** [JGRennison/OpenTTD-patches#381]
When I open my newgrf window I resize it to take up a sizable portion of the screen, after I load a game and return to menu the UI changes I made to the newgrf window have defaulted and I am forced to repeat the action.

If possible I would very much appreciate persistence on various UI's to the form as set by the user. Perhaps with a small 'reset ui' button on the main menu just in case.

Thank you for the incredible client, every openttd fan I suggest it to switches straight to it.

**Comment by JGRennison** [comment]
This is already implemented in the base game. In the top-right corner of the NewGRF window is the default size button.

You can hover over the button to get usage instructions:
* Click to return the window to the default size
* Ctrl-click to set the current size as the default
