### ISSUE TITLE
[Bug]: Grass does not grow back under trees

### ISSUE THREAD

**Issue by VacuumBreather** [JGRennison/OpenTTD-patches#386]
### Version of OpenTTD

Windows 10, JGRPP 0.47.2

### Expected result

After demolishing a tile, grass grows back even if the tile has a tree.

### Actual result

If you put a tree on a brown demolished tile, the grass never grows back.

### Steps to reproduce

1. Demolish two tiles
2. Put a tree on one of the tiles while it still has the brown tile graphics
3. Accelerate the game
4. Watch 'grass grow back' on the tile without the tree and the tree tile remaining brown forever

**Comment by JGRennison** [comment]
It seems that this only occurs if tree growth and spread are turned off. Should not be too hard to fix.

**Comment by VacuumBreather** [comment]
I did not deactivate growth or spread. However my growth is set to the slowest setting. So I guess it could grow back, just EXTREMELY slow, like the trees. Maybe the grass should be independent of tree growth speed then.

**Comment by JGRennison** [comment]
That should be done now
