### ISSUE TITLE
[Suggestion]: Make measuring tool available in zoomed out viewport

### ISSUE THREAD

**Issue by VacuumBreather** [JGRennison/OpenTTD-patches#388]
### Version of OpenTTD

Windows 10, JGRPP 0.47.2

### Expected result

Measuring great distances should be much easier if it could be used in max zoomout.

### Actual result

Right now as soon as the viewport switches from the normal rendering to the zoomed out viewport rendering modes, the measuring tool can no longer be used. this forces constant "zoom in - click - zoom out - find other point - zoom in - click" chains. Measuring large distances is really awkward this way and seems not in line with the available larger map sizes.

### Steps to reproduce

Zoom out and try using the measuring tool

**Comment by JGRennison** [comment]
This should work now
