### ISSUE TITLE
[Bug]: Realistic braking does not slow in advance when train has multiple speed limits

### ISSUE THREAD

**Issue by xsrvmy** [JGRennison/OpenTTD-patches#389]
### Version of OpenTTD

0.47.2, Archlinux

### Expected result

Train will slow down in advance when it needs to slow down for a varying speed limit

### Actual result

Train will slow down for track speed limit changes, but not for train speed limit changes based on track type.
(Can this cause crashes?)

### Steps to reproduce

1. Start a game with the vacuum train GRF
2. Build a very long vacuum train track. Change a short section in the middle to normal maglev.
3. Run a train on the track where the speed in open air maglev is less than 750kph
4. Note that the train will slow down before the maglev section down to 750 as indicated by the track type, then jump instantly to lower speed from the train.

Another example is the high speed trains in Iron Horse 2

**Comment by JGRennison** [comment]
I wasn't previously aware that NewGRF authors had started doing this.
In the general case it's not possible to predict what NewGRFs will do, but in the simple case it should be possible to detect this behaviour and predict the speed the NewGRF will apply.

Even if not handled this is not capable of causing train crashes.

**Comment by JGRennison** [comment]
This is in the most recent release now
