### ISSUE TITLE
Endless loop in VehicleRoute drawing when conditional orders form a cycle.

### ISSUE THREAD

**Issue by KeldorKatarn** [JGRennison/OpenTTD-patches#39]
Endless loop in vehicle route drawing if conditional orders form a cycle (in the simplest form, a conditional order skipping to itself)

https://github.com/KeldorKatarn/OpenTTD_PatchPack/commit/680ddba875208b09160908ad03064b542193df4e

**Comment by JGRennison** [comment]
I was still able to get an infinite loop by having a conditional order which branched to another conditional which branched to itself.
I will look into writing some code to handle this case (Floyd's cycle detection algorithm, or a visited set perhaps?).

**Comment by KeldorKatarn** [comment]
Indeed that would be another trigger for the crash. Question is.. is this critical enough to do a fancy algorithm or just put a limit on the loop and call it done for. I mean.. all that happens is the line doesn't refresh properly for loops which won't make a whole lot of graphical sense anyway? This only triggered for me because of an intermediate stage. I doubt any such cycle would make sense as orders proper, so this state will only exist during order editing... 
But I'll look into it again too.

**Comment by KeldorKatarn** [comment]
This should do it? https://github.com/KeldorKatarn/OpenTTD_PatchPack/commit/ac1c26f5fe942ef47c664ff71000053d874a6008

**Comment by JGRennison** [comment]
This seems to resolve it, thanks for the fix.
