### ISSUE TITLE
[Bug]: Ctrl-click on trains from other companies does not stop the train, when infrastructure sharing is on

### ISSUE THREAD

**Issue by wpi3** [JGRennison/OpenTTD-patches#392]
### Version of OpenTTD

0.47.2, macOS 11.5.1

### Expected result

Company A should be able to stop company B's trains that are running on company A's track, either by ctrl-clicking on the train or stopping them in the vehicle gui.

### Actual result

Only the second method (clicking on the bottom bar of the vehicle gui) would stop the train. Ctrl-clicking the train opens the vehicle gui instead.

### Steps to reproduce

1. Turn on infrastructure sharing
2. Run some trains from company B that are on company A's track
3. When in company A, ctrl-click company B's trains
4. The train would not stop
5. Open the vehicle gui of the train and click the bottom bar
6. The train would stop

**Comment by JGRennison** [comment]
This should be fixed in the next release now
