### ISSUE TITLE
[Bug]: `<unnamed>.UniscribeRun::total_advance` may be used uninitialized

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#394]
### Version of OpenTTD

PR #393

### Expected result

No such warnings.

### Actual result

Warning: `'<unnamed>.UniscribeRun::total_advance' may be used uninitialized [-Wmaybe-uninitialized]`
System: msys2 (MINGW32, i686, x86_64)
https://github.com/JGRennison/OpenTTD-patches/blob/322363b6eaeb634492d415f024e616532a2f3a72/src/os/windows/string_uniscribe.cpp#L37

### Steps to reproduce

Build OpenTTD-jgrpp on msys2 (MINGW32, i686, x86_64), and notice the resulting warning.
Alternatively, check https://github.com/JGRennison/OpenTTD-patches/pull/393/files

**Comment by JGRennison** [comment]
Fixed in 0ed30d02
