### ISSUE TITLE
[Bug]: Version detection problem when compiling on Linux

### ISSUE THREAD

**Issue by lcd047** [JGRennison/OpenTTD-patches#395]
### Version of OpenTTD

0.47.3, Linux

### Expected result

Version in the final binary should be 0.47.3.

### Actual result

Veesion in the final binary is `--g`.

### Steps to reproduce

Up to 0.47.1 this incantation used to produce binaries with proper version:
```sh
mkdir _build && \
cd _build && \
cmake .. \
	-DCMAKE_INSTALL_PREFIX=/usr/local \
	-DCMAKE_INSTALL_BINDIR=/usr/local/games \
	-DCMAKE_INSTALL_DATADIR=share/games \
	-DPERSONAL_DIR=.openttd \
	-DCMAKE_BUILD_TYPE=RelWithDebInfo \
	-DBINARY_NAME=openttd_jgr && \
make && \
make install
```
This no longer seems to work, the version in game is `--g`.  Help please?

**Comment by JGRennison** [comment]
Which distro is this?

Are you using git or a tarball?

Does the first line of the output of `cmake  -P cmake/scripts/FindVersion.cmake` have a correct version.

**Comment by lcd047** [comment]
> Which distro is this?

A heavily modified Slackware.

> Are you using git or a tarball?

I'm compiling from `git`.

> Does the first line of the output of `cmake -P cmake/scripts/FindVersion.cmake` have a correct version.

It does, but it also tries to write to the root of filesystem:
```
$ cmake -P cmake/scripts/FindVersion.cmake
-- Version string: jgrpp-0.47.3, Release: 0.47.3
-- Generating rev.cpp
CMake Error: Could not open file for write in copy operation /rev.cpp.tmp
CMake Error: : System Error: Permission denied
CMake Error at cmake/scripts/FindVersion.cmake:186 (configure_file):
  configure_file Problem configuring file
```

**Comment by JGRennison** [comment]
rev.cpp will be written to `_build/generated/rev.cpp` during the build.

It may be that something about your setup is non-standard enough for some part of the build script not to work. I can't really give any more conclusive answers from here.

You may want to try temporarily removing the .git directory so that version detection can be done for the included version information file instead.

**Comment by lcd047** [comment]
> You may want to try temporarily removing the .git directory so that version detection can be done from the included version information file instead.

Hmm, this actually worked.

As it turns out, the problem was me checking out the source as my user, but compiling it as `root` (yeah, I'm reckless like that).  That worked fine in the past, but recent versions of `git` insist not to work if the repository is not owned by the current user.

So the solution is either (1) don't compile as `root` (preferred :smile:), or (2) add the source directory to `root`'s `safe.directory` for `git`.

Thanks for helping me getting to the bottom of all this.
