### ISSUE TITLE
[Suggestion] Hotkey for switching order to 'via'

### ISSUE THREAD

**Issue by EratoNysiad** [JGRennison/OpenTTD-patches#398]
I have to frequently change an order from to to via,
![image](https://user-images.githubusercontent.com/10280358/173601516-00f23bac-cd30-4772-b886-66f91bb4286c.png)
It would be nice to have a hotkey for that like these:
`nonstop = H
fullload = J
unload = K`
It can be unset by default, that's fine.

Thanks in advance.

**Comment by JGRennison** [comment]
I've added this now, it'll be in the next release
