### ISSUE TITLE
[Crash]: Destroying airports with vehicles on airport tiles, deletes tracks, stations and/or roads and then crashes the game.

### ISSUE THREAD

**Issue by EratoNysiad** [JGRennison/OpenTTD-patches#399]
### Version of OpenTTD

0.47.3

### Steps to reproduce

1. Download an airport NewGRF like North Korean Aviation Set, or OpenGFX+ Airports.
2. These airports are missing some tiles, such that eyecandy can be placed. This is generally speaking safe. Place a train there.
3. Now delete the airport with the train still on it. Tada! If not stopped, the train will crash the game instantly.
![image](https://user-images.githubusercontent.com/10280358/174055709-e6b7c2d4-1dc6-4d14-b042-f9df91fea76c.png)

This does **not** happen in the basegame, where tiles with vehicles on them don't get deleted.

### Upload crash files

[Crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/8918234/Crash.zip)

**Comment by James103** [comment]
Can reproduce in JGRPP 0.47.3, but not in master (2022-06-11 nightly).
Also crashes if a road vehicle, ship, or other non-aircraft is on a tile within the footprint of the station.

Additionally, this can be used to remove industry and other protected tiles, creating ghost industries (industries that exist in the map data but that don't have associated tiles).
