### ISSUE TITLE
[Bug]: Many build errors on non-Linux systems

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#401]
### Version of OpenTTD

PR #400 (base commit: 10b415bf10212fe90a6cbc0a21d548d0722ddefa)

Note that the below errors started appearing in commits starting with 6e4c4b35e7e677eca379e381d863e7d493233dc5 (as found using git blame).

### Expected result

No such build errors. OpenTTD-jgrpp compiles successfully on Windows, Mac, Linux, and Emscripten.

### Actual result

On non-Linux systems, the compilation of OpenTTD-jgrpp fails with the following errors:

Errors found related to this code on Windows, MacOS, and Emscripten:
https://github.com/JGRennison/OpenTTD-patches/blob/10b415bf10212fe90a6cbc0a21d548d0722ddefa/src/newgrf_newsignals.cpp#L21
* `'_new_signal_styles' uses undefined class 'std::array<NewSignalStyle,15>'`
* `'_new_signal_styles': redefinition; different basic types`
* `implicit instantiation of undefined template 'std::array<NewSignalStyle, 15>'`

---

Error in this line on Windows: `'[': illegal for class`
https://github.com/JGRennison/OpenTTD-patches/blob/10b415bf10212fe90a6cbc0a21d548d0722ddefa/src/newgrf_newsignals.cpp#L32

---

The code inside the following for loop (more specifically lines 1528, 1532, 1536, 1537, and 1539) has many errors when compiling on Windows:
https://github.com/JGRennison/OpenTTD-patches/blob/10b415bf10212fe90a6cbc0a21d548d0722ddefa/src/signal.cpp#L1527-L1544
* `binary '[': 'std::array<NewSignalStyle,15>' does not define this operator or a conversion to a type acceptable to the predefined operator`
* `'HasBit': no matching overloaded function found`

### Steps to reproduce

Compile OpenTTD-jgrpp on non-Linux systems.

**Comment by JGRennison** [comment]
Fixed in c1b54f1c
