### ISSUE TITLE
[Crash]: Loading Save

### ISSUE THREAD

**Issue by ryanhund** [JGRennison/OpenTTD-patches#402]
### Version of OpenTTD

JGRPP 0.47.3, Windows 10

### Steps to reproduce

Tried to load attached save

### Upload crash files

[crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/8987445/crash.zip)

**Comment by JGRennison** [comment]
Thanks, this is fixed now and will be in the next release.

Loadable savegame attached:
[Deutsche Bahn, 2865-08-21.sav.zip](https://github.com/JGRennison/OpenTTD-patches/files/8987840/Deutsche.Bahn.2865-08-21.sav.zip)

**Comment by ryanhund** [comment]
Thank you!
