### ISSUE TITLE
[Suggestion] Add vehicle naming scheme: Full group hierarchy

### ISSUE THREAD

**Issue by welles** [JGRennison/OpenTTD-patches#405]
Hi, thanks for the new setting to show the full group name hierarchy, it's great!
Could you maybe also add a vehicle naming scheme that includes the full group hierarchy, so a default vehicle name would be something like "Group 1  / Group 2 / Group 3 #⁠1"?

**Comment by JGRennison** [comment]
Implemented in most recent release
