### ISSUE TITLE
[Suggestion]: Route step is not readable if use custom font config

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#410]
### Version of OpenTTD

jgrpp-0.48.1

### Expected result

Expected (in English):
![image](https://user-images.githubusercontent.com/10726524/185584085-13f09087-370d-42b9-ae3f-0e726507340b.png)

### Actual result

Actual (in Korean):
![image](https://user-images.githubusercontent.com/10726524/185582031-f3ebbb5b-30d2-4bca-97de-12b7fc5f36e2.png)
(It is actually ``507 ST`` and ``508 ST``)

When using ``Show the vehicle's route steps`` with enabled, the game shows order's number as the screenshot above shows.
But if use custom font settings (like CJK language) it clips when the order's number has more than 3 digits.
So I can't recognize the number easily.

It doesn't matter it is English or CJK, this issue occurs when using custom font config.

It would be great if white box is bigger according to its context text.

### Steps to reproduce

1. Edit ``openttd.cfg`` like this:
```
[misc]
(...)
small_font = Gulim
medium_font = Gulim
large_font = Gulim
mono_font = Gulim
small_size = 12
medium_size = 12
large_size = 16
mono_size = 12
small_aa = false
medium_aa = false
large_aa = false
mono_aa = false
```
2. Open the game

**Comment by JGRennison** [comment]
Should be fixed now
