### ISSUE TITLE
[Bug]: Error- Could Not Load Savegame (while attempting to join server)

### ISSUE THREAD

**Issue by debiankingGitHub** [JGRennison/OpenTTD-patches#412]
### Version of OpenTTD

0.48.1

### Expected result

Joining a server (... quite basic)

### Actual result

message could not load savegame, server side shows 'client failed to load map', booted to start screen.
in the console, it prints dbg:[desync] network client recalculating signal states and/or signal style mapping, this is likely to cause desyncs

### Steps to reproduce

1)Compile On Ubuntu Mate (latest release) with cmake and libsdl2-dev, plus all the apt dependencies of openttd
2) install base graphics from ottd website 
3) join attempt ... any server. I have tested bot local and online servers, with the same issue

**Comment by James103** [comment]
1. Does this happen without any NewGRF, AI, or GS installed on the client or server?
2. Can you please post the output from running `openttd -d desync9sl9net9` and reproducing if possible?

**Comment by JGRennison** [comment]
You may find it easier to use a precompiled deb for whichever release of Ubuntu you are using: https://github.com/JGRennison/OpenTTD-patches/releases

What does `./openttd -Z` output?

**Comment by debiankingGitHub** [comment]
> 1. Does this happen without any NewGRF, AI, or GS installed on the client or server?
> 2. Can you please post the output from running `openttd -d desync9sl9net9` and reproducing if possible?

Their is no additions to the game, other than opengfx
[output.txt](https://github.com/JGRennison/OpenTTD-patches/files/9438297/output.txt)

**Comment by debiankingGitHub** [comment]
> You may find it easier to use a precompiled deb for whichever release of Ubuntu you are using: https://github.com/JGRennison/OpenTTD-patches/releases
> 
> What does `./openttd -Z` output?

This is a response to JGRennison
here is the output from the terminal
[output 2.txt](https://github.com/JGRennison/OpenTTD-patches/files/9438311/output.2.txt)

**Comment by debiankingGitHub** [comment]
S

**Comment by JGRennison** [comment]
> > What does `./openttd -Z` output?
> 
> This is a response to JGRennison here is the output from the terminal [output 2.txt](https://github.com/JGRennison/OpenTTD-patches/files/9438311/output.2.txt)

Nearly all the nominally optional dependencies seem to be missing.
At absolute minimum you should have liblzma as well, if you want to be able to load anyone else's savegames.
CMake should warn you that these are missing.

The error message when connecting to the server is misleading, it should state clearly what the problem is.
