### ISSUE TITLE
[Suggestion]: Allow Game Scripts to read and set the inflation income and cost factor

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#415]
### Version of OpenTTD

jgrpp-0.48.1 on Windows 10, 64-bit

### Expected result

A Game Script should be able to read the exact inflation income and cost factors and change them at any time.
This acts as if the cheat to set them was used, except done automatically via scripting.

Example use cases:
* Varying inflation rate
* Inflation rate different from loan interest rate
* Inflation rate less than 2% (possibly negative) or more than 4%

This is a better alternative (IMO) to the last two settings proposed in #209.

### Actual result

The inflation income factor can be approximated in a Game Script by reading and permanently saving the price of X units of cargo delivered Y tiles at the start of the game, then reading the same price sometime later and taking the ratio.
The inflation cost factor can be approximated in a Game Script by reading and permanently saving the price of clearing a tile of water at the start of the game, then reading the same price sometime later and taking the ratio.
Neither can be modified solely by a Game Script. The ratios read may be inaccurate and suddenly change without notice.

### Steps to reproduce

1. Notice the inflation income and cost factors can be read and written to directly using the cheats window.
2. Notice the same can't be done via a Game Script.

**Comment by JGRennison** [comment]
Are you intending to write a gamescript that would usefully use this, incidentally?

**Comment by James103** [comment]
I may or may not use these new functions in a full-fledged and polished Game Script, but will most likely use these functions to try some ideas I have for game scripts.

**Comment by JGRennison** [comment]
Above commits should allow this.

**Comment by James103** [comment]
Closing as this is implemented in the latest release (JGRPP 0.48.2).
