### ISSUE TITLE
[Bug]: Template Replacement may fail with 'not enough cash' if company's bank balance ≥ 2^31 (mod 2^32)

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#419]
### Version of OpenTTD

jgrpp-0.48.1 on Windows 10, 64-bit

### Expected result

Template Replacement should succeed regardless of the company's bank balance if the company is able to automatically replace the existing vehicle with a copy/realization of the template.

### Actual result

Suppose a company has a bank balance of £3,000,000,000 and an active Template Replacement session in progress.
The vehicle's existing value is negligible and it costs £250,000 to realize a copy of the template.
When a vehicle from that company is attempted to be replaced, the template replacement operation may fail, thinking the company has not enough funds to do it. This may be caused by some of the monetary values being casted to signed 32-bit integers instead of the required 64 bits.

### Steps to reproduce

1. Load the attached save.
2. Make sure 'Advice / information on company's vehicles' news setting is set to "Full" or "Summary".
3. Unpause and wait.
4. Notice "Autorenew failed on [train], (money limit)" shows up in the news feed despite the company having over 10000x the required funds.

[Choo Choo Cult, 2038-02-10.zip](https://github.com/JGRennison/OpenTTD-patches/files/9504176/Choo.Choo.Cult.2038-02-10.zip)

**Comment by JGRennison** [comment]
This isn't actually about money. The error message is the wrong one entirely.

The template is not buildable because your template is a consist of maglev locomotives with ordinary railway wagons, which isn't buildable in the depots that you are using for autoreplace.

**Comment by James103** [comment]
Thanks! I fixed the template and now all relevant trains get replaced properly.
