### ISSUE TITLE
[Suggestion]: Combine some of the buttons at the bottom of the advanced purchase window

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#421]
### Version of OpenTTD

jgrpp-0.48.1

### Expected result

The advanced railway vehicle purchase window should have a single set of buttons as follows:
* 'Buy Locomotive' OR 'Buy Wagon'
* 'Hide Locomotive' OR 'Hide Wagon'
* 'Rename Locomotive' OR 'Rename Wagon'

Which set in the above ('Locomotive' or 'Wagon') is active depends on which column the user last clicked in the window. If the user last clicked somewhere in the locomotives column, the buttons will purchase/hide/rename the selected locomotive, while if the user last clicked somewhere in the wagon column, the buttons will purchase/hide/rename the selected wagon.

If there's significant interest for both the proposal and what's currently implemented (as described below), an advanced setting may be added to switch between the two.

### Actual result

The advanced railway vehicle purchase window has two sets of buttons, as follows:
* 'Buy Locomotive'
* 'Hide'
* 'Rename'
* 'Buy Wagon'
* 'Hide'
* 'Rename'

The first set acts on locomotives and is placed at the bottom of the locomotive column, while the second set acts on wagons and is placed at the bottom of the wagon column.

### Steps to reproduce

1. Enable the advanced vehicle purchase window.
2. Open it, such as by clicking "Available Trains" or clicking the button to buy new railway vehicles found in any depot window.
3. Notice there's two sets of buttons, as described above.
4. Notice that for some users, it's easy to accidentally click on "Buy Locomotive" while looking at the wagon column and thinking the user had hit "Buy Wagon", and vice versa.

See https://github.com/JGRennison/OpenTTD-patches/pull/287#issuecomment-1241831274, especially the second paragraph down.

**Comment by JGRennison** [comment]
This has been implemented
