### ISSUE TITLE
[Crash]: crash dump error. openttd shutdown.

### ISSUE THREAD

**Issue by koreapohang** [JGRennison/OpenTTD-patches#422]
### Version of OpenTTD

0.48.1, windows 10 64bit

### Steps to reproduce

![bug shutdown](https://user-images.githubusercontent.com/113115753/189421570-1a93ef16-45ea-48a3-860c-76ef214353d4.png)

error message

error!
Assertion failed at line 154 of
/home/jgr/openttd/jgrpp/src/strings_func.h:
this->HasTypeInformation()

### Upload crash files

[OpenTTD crashdump shutdown.zip](https://github.com/JGRennison/OpenTTD-patches/files/9537965/OpenTTD.crashdump.shutdown.zip)

**Comment by JGRennison** [comment]
This is already fixed by https://github.com/JGRennison/OpenTTD-patches/commit/62ffa130c029aa1db8e69f38609ead15de10c2eb. See issue #420.

**Comment by koreapohang** [comment]
> This is already fixed by https://github.com/JGRennison/OpenTTD-patches/commit/62ffa130c029aa1db8e69f38609ead15de10c2eb. See issue #420.


Thank you ^^
