### ISSUE TITLE
[Crash]: Crash when creating a new company in a multiplayer game

### ISSUE THREAD

**Issue by downy1205** [JGRennison/OpenTTD-patches#424]
### Version of OpenTTD

JGRPP 0.48.2, Window 10

### Steps to reproduce

When creating a new company in a multiplayer game

### Upload crash files

[crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/9541839/crash.zip)

**Comment by James103** [comment]
1. Do you have a favorite company manager face saved?
2. Do you have the corresponding crash.log? If so, can you please post it here?

**Comment by telk5093** [comment]
Maybe [ad9d593](https://github.com/JGRennison/OpenTTD-patches/commit/ad9d593a51ddb087dceb8882ed2ff82a0af8a482) would fix this issue (crash when create a new company)

**Comment by JGRennison** [comment]
Fixed in the most recent release
