### ISSUE TITLE
[Suggestion]: Add `ScriptCompany::GetYearlyExpenses(company, expenses_type, year)`

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#425]
### Version of OpenTTD

jgrpp-0.48.2 on Windows 10, 64-bit

### Expected result

There should be a way for AI/GS to read the values of the various accounting items shown in the finance window for the current year, last year, and the year prior.

Example use cases (scenario goal ideas):
* A scenario where the goal is to earn at least £1,000,000 or 10 times the amount spent on running costs for a given vehicle type (whichever is higher), for all 4 vehicle types (rail, road, air, and ship).
* Goal: Make £1,000,000,000 in 30 years or less by spending no more than £100,000,000 total on construction and new vehicles.
* From a scenario's description: "If you turn my company around and get it profitable, I will let you free. If, beforehand, I lose ten mil to the loan sharks, you will be forever stuck on my island"

(In the title, the name of the function and its arguments are subject to change)

### Actual result

There is no way (that I know of) for AI/GS to quickly read off the values of the various accounting items shown in the finance window for the current year, last year, and the year prior.

It may be possible to get the amount of profit from each of the four vehicle types by looping over all vehicles a company owns, but that's at least $O(n)$ in the number of vehicles.

Loan Interest can be approximated by taking the current loan at the end of each month, multiplying it by the interest rate, then dividing by 12 to convert from a yearly amount to a monthly amount.

Property Maintenance can be approximated by reading the current monthly costs for all of the infrastructure the company owns.

There is no other way I know of to get "Construction" or "New Vehicles" without a lot of additional work.

### Steps to reproduce

1. Notice a player can check the financial window to see a breakdown of income and expenses per vehicle type, infrastructure, new vehicles, construction, etc.
2. Notice the same can't be easily checked by an AI or Game Script.

**Comment by JGRennison** [comment]
I've implemented a method along these lines

**Comment by James103** [comment]
Closing as the feature is implemented.
