### ISSUE TITLE
[Bug]: No SFX

### ISSUE THREAD

**Issue by prekliatygulas** [JGRennison/OpenTTD-patches#429]
### Version of OpenTTD

OpenTTD 12.2 - JGRPatch - v0.48.2

### Expected result

No SFX

### Actual result

I installed JGR patch into my OpenTTD steam folder and I can't hear SFX sounds of locomotives and building tracks etc.
Music is working, but SFX is not.

### Steps to reproduce

1. Game SFX works without JGR patch.
2. I install JGR patch.
3. SFX stops working after installing JGR patch.

**Comment by James103** [comment]
Try doing the following:
* Restore your OpenTTD install on Steam to its original form by doing a verification check on it from the Steam client.
* Install JGRPP into its own folder and run it from there (you may want to add it as a Non-Steam Game).

**Comment by prekliatygulas** [comment]
Hello,
I tried it and it didn't helped. I also tried downloading the game from official website, downloading SFX using Online Content service and it's not working as well.

**Comment by prekliatygulas** [comment]
Okay, it's working now. I tried to download 32-bit version instead of 64-bit and It's working now. Thank you for your help. Have a nice day.
