### ISSUE TITLE
The hash lookup-table for tunnels is not updated when a new savegame is loaded in afterload.

### ISSUE THREAD

**Issue by KeldorKatarn** [JGRennison/OpenTTD-patches#43]
See title for the problem.
Fix: https://github.com/KeldorKatarn/OpenTTD_PatchPack/commit/bb4ab067804139c7e7ff213b9b82c010c8f3fac6

**Comment by JGRennison** [comment]
I don't think that this is an issue in this repo, as UpdateIndexes is called in Load_TUNN() in my branch but not in yours. I will check in more detail a bit later.

**Comment by KeldorKatarn** [comment]
Then I don't see where it happens. You check for the feature and if it's missing you do something, if it's there you don't. If you update the indices you do it somewhere else.

**Comment by KeldorKatarn** [comment]
I'm such an idiot. I added that section by hand and of course I added it to Save_TUNN instead of Load_TUNN because I read the diff wrong :P
