### ISSUE TITLE
[Bug]: Can't demolish protected houses with Magic Bulldozer cheat when playing as AI company

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#430]
### Version of OpenTTD

jgrpp-0.48.2 on Windows 10, 64-bit

### Expected result

When a (human) player joins an AI company and then attempts to demolish a church building from ITL Houses, the action should succeed and the building should be demolished, assuming the Magic Bulldozer cheat is enabled.

### Actual result

When a (human) player joins an AI company and then attempts to demolish a church building from ITL Houses, the action errors with no good explanation.

When the same (human) player joins a non-AI company and attempts to demolish the same church building from ITL Houses, the action succeeds and the building is removed, assuming the Magic Bulldozer cheat is enabled.

### Steps to reproduce

1. Start a new game with ITL Houses enabled.
2. Enable the magic bulldozer cheat.
3. Attempt to demolish a church building from ITL Houses and notice it succeeds (assuming enough cash is available).
4. Start an AI company.
5. Use the switch company cheat to join the AI company.
6. Attempt to demolish a church building from ITL Houses and notice it always fails.

**Comment by JGRennison** [comment]
This is the correct behaviour, it's not a bug.

See: bit 1 of https://newgrf-specs.tt-wiki.net/wiki/Action0/Houses#Extra_Flags_.2819.29 and https://newgrf-specs.tt-wiki.net/wiki/Callbacks#Protect_building_conditionally_.28143.29
