### ISSUE TITLE
[Bug]: Infrastructure sharing expenses are per vanilla day

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#435]
### Version of OpenTTD

jgrpp-0.48.4 on Windows 10, 64-bit

### Expected result

Infrastructure sharing costs should be calculated per scaled day if the day length factor is not set to 1, leaving net yearly costs the same regardless of the day length factor.

A setting value of 100 should be interpreted as £100 per day regardless of the day length factor.

For example, if a road vehicle stops on a road stop owned by another company, and the toll for doing so is £100 per day, and the day length factor is 5, then the monthly charges should be £3,000 instead of £15,000.

Alternatively, the existing behavior can be left as it is, with some additional text for clarification.

### Actual result

Infrastructure sharing costs are calculated per vanilla day regardless of the day length factor.
This increases the resulting costs as the day length factor increases.

For example, with a day length factor of 20, a setting value of 100 is interpreted as £2,000 per day, but it is still shown as £100 per day. With a day length factor of 100, a setting value of 100 is interpreted as £10,000 per day, but it is still shown as £100 per day.

At high day length factors, setting a value that should be reasonable may cause infrastructure sharing costs alone to exceed revenue for some companies that would otherwise be very profitable, in games that heavily use infrastructure sharing.

A workaround is to further reduce the values of the relevant settings, setting them to what you want the "toll per scaled day" value to be divided by the day length factor. This may not always be possible for high day length factors, since the result may not always be an integer at least 1.

### Steps to reproduce

1. Create a game with a high day length factor and that heavily uses infrastructure sharing, such as the one on a server held by a user named "MainLine45" on the official OpenTTD discord server.
2. Notice that in some cases, infrastructure sharing costs alone may exceed revenue for one or more companies, even when the daily fees are set to be conservative values.

See https://discord.com/channels/142724111502802944/142726408400011265/1026127760030179529

**Comment by JGRennison** [comment]
I've already spoken in detail with the user in question about their save. The profitability issues are not caused by infrastructure sharing costs (the company in question would be losing money even with infrastructure sharing costs set to zero).

I disagree that costs should be scaled by the day length, as then it is necessary to manually tune these values in the opposite direction to changes the day length.

I will write some explanatory text for these settings in due course.
