### ISSUE TITLE
[Crash]: Plane and Ship slot release order crashes the game

### ISSUE THREAD

**Issue by Lorith** [JGRennison/OpenTTD-patches#438]
### Version of OpenTTD

jgrpp-0.48.3, both chromebook (linux) and Win7

### Steps to reproduce

1: Build an airport of boat depot
2: Buy a plane or boat
3: (optional) Open aircraft/ship management tab, then slots window, and add a slot
4: Set any, or no orders, then add "release slot"
5: Click on the "Release slot: undefined" to try to set the slot
6: Crash

Road vehicles work fine, for some reason, and obviously, so do trains.

### Upload crash files

[CrashFiles.zip](https://github.com/JGRennison/OpenTTD-patches/files/9711221/CrashFiles.zip)

**Comment by JGRennison** [comment]
Thanks for reporting this, this is fixed and will be in the next release

**Comment by Lorith** [comment]
Thanks for the quick fix, that will help a lot with how I do things.

**Comment by JGRennison** [comment]
This is in the most recent release now
