### ISSUE TITLE
Remove multiplayer NewGRF limit

### ISSUE THREAD

**Issue by KeldorKatarn** [JGRennison/OpenTTD-patches#44]
I THINK I've achieved that here: https://github.com/KeldorKatarn/OpenTTD_PatchPack/commit/c778e5344080268c0d47310a4c4ea0458a9c1ad8

If you find any issues with it, let me know please. My Coop Video partner and I will put it to the test this Saturday. So far it seems to work fine. I don't think there's any problem with loading this many NewGRFs in MP, the issue was always communicating what to load to the client BEFORE the game. Once the game is on, this should no longer be any issue. Unless there's some really crazy command somewhere that I missed.

I think this is a pretty big deal to a lot of players so I think it's something worthy to add to your version and cooperate on to make it work the best.

(Btw I have no idea why differently versioned packages are maintained in the code. The game will completely refuse to connect to any server/client that doesn't have the EXACT same game version running, so what's the point of that. A client might be able to receive info of an older version server yes, but why would that even matter, it'll immediately report "version missmatch" and not even display that information. So that entire versioning seems redundant and pointless. I can't see this lockstep client server architecture ever working with client and server not using the same protocol version, so in my opinion that could be deleted. Client and Server already compare versions and if they don't understand eachother's packages they disconnect anyway.

I'm usually not much involved with network programming but.. what also confuses me is.. why are "packets" handled in the TCP code. From my understanding one of the main advantages of TCP over UDP is that it's so high level you can treat it like a filestream and let TCP worry about how to turn the data into packets to send over the wire. Maybe it's just bad wording for a "clearly defined set of data" but... still confused me at first. Seems a bit low level for TCP.

**Comment by JGRennison** [comment]
This looks very interesting, it may time me a bit of time to properly go through it all. I agree that it is worth developing/adding.

On the protocol versions (and adding a new version), one other place where the server info is read is in the public listing of multi-player servers, as displayed on the website: https://www.openttd.org/en/servers .
It would be useful for that still to work if feasible, though that might require some liaison with the site admins.
One other minor issue is in version numbering, if trunk later decide to do their own unrelated update there would be two incompatible NETWORK_GAME_INFO_VERSION = 5, which is best avoided. Picking some number which trunk won't reach for a fair while might be better. It may be worth liaising with trunk in some way.

Packets refer to framing of records/messages, not to how the single stream is split into TCP packets.
Many data formats use the term packet to refer to discrete records within the stream (typically length-prefixed or with start/end frame markers), that's fairly standard terminology.

**Comment by KeldorKatarn** [comment]
The latest commit should fix it.
