### ISSUE TITLE
[Bug]: Touchbar doesn't work on Mac

### ISSUE THREAD

**Issue by vvolodin** [JGRennison/OpenTTD-patches#442]
### Version of OpenTTD

v0.48.5

### Expected result

Buttons on touchbar showing up and working.

### Actual result

Touchbar is dark and empty.

### Steps to reproduce

1. Launch the game on mac

**Comment by JGRennison** [comment]
This feature is currently disable because it causes crashes, see https://github.com/OpenTTD/OpenTTD/issues/9876 and related issues.

When this is fixed and tested/verified upstream (https://github.com/OpenTTD/OpenTTD/pull/10060) it will be re-enabled.

**Comment by vvolodin** [comment]
Ah, I see, makes sense. Funnily enough, openttd is the ONLY app I'm actually using this feature of my macbook in :)

**Comment by JGRennison** [comment]
This is re-enabled in the most recent release (0.49.0).
