### ISSUE TITLE
[Bug]: Warning in `stdafx.h` when compiling on msys2

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#446]
### Version of OpenTTD

PR #445

### Expected result

No such warnings

### Actual result

Warning: `format '%u' expects argument of type 'unsigned int', but argument 3 has type 'long long unsigned int' [-Wformat=]`
System: msys2 (MINGW32, i686 or x86-64)
Line: https://github.com/JGRennison/OpenTTD-patches/blob/41b9d74280c2fcf9d208163d86f957ad0aea17c0/src/stdafx.h#L305

### Steps to reproduce

Compile OpenTTD on msys2 (MINGW32, i686 or x86-64).

**Comment by JGRennison** [comment]
This is fixed now
