### ISSUE TITLE
[Bug]: Network-Sync Error in Multiplayer

### ISSUE THREAD

**Issue by Wulfestwulf** [JGRennison/OpenTTD-patches#447]
### Version of OpenTTD

JGRPP 0.49.0

### Expected result

Connect to a multiplayer server running the same version without getting de-synced and kicked

### Actual result

Connecting to a multiplayer server resulted in everyone getting de-synced with the error (Network-Sync error) 

### Steps to reproduce

1. Join someone else's server on the same version
2. Get the network-sync error!

**Comment by James103** [comment]
Do you have the logs from the desync? If so, can you please post them here?

**Comment by Wulfestwulf** [comment]
No, I do not have the logs sadly. They were deleted when I switched back to vanilla to play with my friends and I didn't think to post them

**Comment by JGRennison** [comment]
If you do find some desync logs or saves from the client or server feel free to re-open this.
