### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kedzior3** [JGRennison/OpenTTD-patches#452]
### Version of OpenTTD

OpenTTD jgrpp-0.49.1 @ Windows10 Home

### Expected result

Very long time for loading main windows screen.

### Actual result

In comparition with 0.45.1, new versions before 0.48 and newer, has loading very long time - a 5 minutes from click on OpenTTD.exe to show main window.
I don't know, why it is, but it's very frustrating, because my Windows's load time is so much quicker than this.

0.45.1 is the last version of jgrpp's, whitch loaded very quickly - a less than 4 seconds.

Lenovo Z50-70 @ Windows 10 Home / Samsung SSD 870 QUO 1TB

### Steps to reproduce

Click on the OpenTTD.exe
Waiting for show the main window.
Waiting...
Still waiting...
After 5 minutes... wow, yes, it's working.

**Comment by JGRennison** [comment]
There isn't anything significant changed between version 0.45.1, and the next release after that, 0.46.0, which appears likely to cause such an issue. Is there anything particular or unusual about your setup?

If you have hardware acceleration enabled, I'd suggest trying with it switched off.
Check that you've downloaded the right version for your machine/OS type, most likely 64 bit (not ARM).

**Comment by kedzior3** [comment]
>  Is there anything particular or unusual about your setup?
I didn't change the settings. This is fresh version, I only unzip from openttd-jgrpp-0.49.1-windows-win64.zip to new folder. Nothing else.
EDIT: v.0.46.1 64bit and other newer else versions has the same problem in my laptop. And problem was in hardware acceleration Enabled in default settings.

Why this option is ALWAYS active in 0.46 and newer?

**Comment by JGRennison** [comment]
The hardware acceleration feature was added by upstream/vanilla OpenTTD. It's not something of mine.
For most users there is a small performance improvement. Probably there is something wrong with your graphics card and/or drivers causing OpenGL to misbehave.
