### ISSUE TITLE
[Bug]: Departure boards broken by implicit orders

### ISSUE THREAD

**Issue by cake-pie** [JGRennison/OpenTTD-patches#456]
### Version of OpenTTD

JGRPP 0.49.2 / Ubuntu Jammy

### Expected result

Departure boards work correctly with trains that have implicit orders (i.e. have orders that are not non-stop, thus calling at intermediate stops along the way.

### Actual result

At a station with upcoming trains that have implicit orders, departure boards get broken. Entries will display correctly until it encounters the first entry that involves implicit orders -- that entry just gets shown repeatedly, filling up the remainder of the board. This is the observed behavior regardless of whether arrivals/departures/both are being displayed.

### Steps to reproduce

1. Load this attached save file [implicit orders break departure boards.zip](https://github.com/JGRennison/OpenTTD-patches/files/10143174/implicit.orders.break.departure.boards.zip)
2. Verify departure board of the central station works with Train 1 running
3. Start Train 2 -- it has implicit orders
4. Note that departure board functionality breaks, fills with Train 2 (destination WT), while Train 1 only sometimes making an appearance (when it is the first entry)
5. Start Train 3, which also has implicit orders
6. Notice how the departure board is filled with either Train 2 or Train 3 (destination ST) -- depending on which one is sooner

**Comment by JGRennison** [comment]
Thanks for reporting this, this should be improved in the next release.

**Comment by cake-pie** [comment]
Thanks for prompt fix!
