### ISSUE TITLE
[Bug]: Cost of building/demolishing signals on bridges/tunnels

### ISSUE THREAD

**Issue by cake-pie** [JGRennison/OpenTTD-patches#458]
### Version of OpenTTD

JGRPP 0.49.2 / Ubuntu Jammy

### Expected result

The cost of building (or demolishing) signals on bridges or tunnels should generally be proportional to the number of signals needed (with maybe some small constant overhead fixed costs)

### Actual result

Cost is purely decided by bridge length and does not take into account the signal spacing. 
![TunnelBridgeSignalCosts](https://user-images.githubusercontent.com/28502722/205493704-7723238f-dac1-4363-8e80-a3e8b6f35357.png)

### Steps to reproduce

1. Build a bridge and a length of normal straight track of same length (13 is convenient, or in general N+1 where N is a highly composite number with many divisors)
2. Compare costs of building/demolishing signals at various signal spacing settings

**Comment by JGRennison** [comment]
This should be fixed in the next release.
