### ISSUE TITLE
[Crash]: Segfault on launch

### ISSUE THREAD

**Issue by goodgerster** [JGRennison/OpenTTD-patches#459]
### Version of OpenTTD

e64707587080e020a5dc002e4d34a3d1d31b9a08 on Fedora 36

### Steps to reproduce

On launch, segfaults about a second after opening a blank X11 window.

### Upload crash files

[crash-20221206T154139Z.log](https://github.com/JGRennison/OpenTTD-patches/files/10167925/crash-20221206T154139Z.log)
I don't see a `crash.dmp` and there's no `crash.sav` written. `crash.png` is all black, same as the short-lived X11 window.

**Comment by goodgerster** [comment]
Update: the crash does _not_ occur in the absence of my `openttd.cfg`.
[openttd.cfg.zip](https://github.com/JGRennison/OpenTTD-patches/files/10168029/openttd.cfg.zip) (zipped because github)

**Comment by JGRennison** [comment]
This should be fixed now

**Comment by goodgerster** [comment]
It is, thanks.
