### ISSUE TITLE
Train reservation through bridges/tunnels issue

### ISSUE THREAD

**Issue by KeldorKatarn** [JGRennison/OpenTTD-patches#46]
Regarding train reservations on bridges and tunnels there was still a bug.

Sometimes when a train already reserved onto or even beyond a bridge and then canceled that reservation for any reason (signal palcement in front of it, reversing, track removed etc), the reservation wasn't properly cleared on or beyond the bridge. Also sometimes a train leaving the front of the bridge would clear a reservation behind it on the other bridge end, that was made by a different train.

This commit SHOULD fix everything in that regard: 
https://github.com/KeldorKatarn/OpenTTD_PatchPack/commit/e2c4fb517d1064b163d8f2b0627506d785ffb3ed

**Comment by JGRennison** [comment]
Thanks for this, I've applied it with some minor adjustments, I'll do some more testing soon,
