### ISSUE TITLE
[Bug]: Shadow is drawn for select box at the industry chain window

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#460]
### Version of OpenTTD

jgrpp-0.50.0

### Expected result

No shadowes

### Actual result

![image](https://user-images.githubusercontent.com/10726524/208231702-5f2b7b7d-58e4-45be-93e1-d29368479190.png)

As shown as above.
Please let me know that if it is not a JGRPP feature.

### Steps to reproduce

1. Open Industry chain window
2. Click "All industries"

**Comment by JGRennison** [comment]
This is fixed now, it'll be in the next release.
