### ISSUE TITLE
[Bug]: Misaligned text in details window for articulated road vehicles

### ISSUE THREAD

**Issue by Strubbelkopp** [JGRennison/OpenTTD-patches#466]
### Version of OpenTTD

jgrpp-0.50.0

### Expected result

It seems like some text in the details window of articulated road vehicles is misaligned, since it covers the vehicle preview image

### Actual result

The text in the middle is drawn over the preview image and also not aligned to the top, like it is for other vehicles
![Fuham Transport, 2101-01-18](https://user-images.githubusercontent.com/66599825/209454742-ebf67c0c-5c33-4232-b523-383d7c7a42b5.png)

### Steps to reproduce

1. Install Road Hog 1.4.1 & build an articulated road vehicle (like the Speedwell Box Truck)
2. Open the details window

**Comment by James103** [comment]
Same issue as https://github.com/OpenTTD/OpenTTD/issues/10260 (as far as I can tell)

**Comment by JGRennison** [comment]
Should be fixed in the most recent release
