### ISSUE TITLE
[Bug]: Scheduled dispatch mass departure slot adding doesn't wrap around midnight; adds nothing instead

### ISSUE THREAD

**Issue by EratoNysiad** [JGRennison/OpenTTD-patches#467]
### Version of OpenTTD

0.50.0

### Expected result

![image](https://user-images.githubusercontent.com/10280358/209566599-744de394-2088-4277-8436-bbee20b840ed.png)
I expect that adding departure slots like this will add hourly slots from 21:01 to 5:01.

### Actual result

![image](https://user-images.githubusercontent.com/10280358/209566685-7a7a0c82-5dbe-4b24-948c-040c2aaa6a3c.png)
Not 1 departure slot is added.

### Steps to reproduce

1. Take a train of choice, and attempt to add a departure slot by control clicking
2. have the end time be before the start time

**Comment by JGRennison** [comment]
This should be implemented now
