### ISSUE TITLE
[Crash]: Link Graph Tooltips?

### ISSUE THREAD

**Issue by Montandalar** [JGRennison/OpenTTD-patches#468]
### Version of OpenTTD

jgrpp-0.50.0.54-g546ad0b43

### Steps to reproduce

Crash happened despite no obvious input. The stack trace seems to indicate link graph tooltips (the mouseover on a stop when the cargo flow legend is enabled?), which is JGR-only feature as best I know. Haven't been able to reproduce so far, but hopefully it's something obvious. The save uses some German characters with umlauts in town and stop names in case it matters, but the rendering of these usually occurs just fine.

### Upload crash files

[crash20221227T130306Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/10308408/crash20221227T130306Z.zip)

**Comment by JGRennison** [comment]
Thanks for reporting this, it should be resolved now.

**Comment by Montandalar** [comment]
I was able to reproduce it once on the old build and not at all on the new one, so I'll take your word for it. Thanks :)
