### ISSUE TITLE
[Bug]: Depot "Click to start all" button doesn't work in other companies' depots (infrastructure sharing)

### ISSUE THREAD

**Issue by 2TallTyler** [JGRennison/OpenTTD-patches#469]
### Version of OpenTTD

jgrpp-0.50.1

### Expected result

When Infrastructure Sharing is enabled and I am allowed to build vehicles in another company's depot, the green flag "start all vehicles" button starts all of my vehicles in the depot.

### Actual result

The button does nothing.

### Steps to reproduce

1. Buy a vehicle in another company's depot
2. Click on the "start all" green flag in the depot GUI
3. Observe that nothing happens

**Comment by JGRennison** [comment]
Thanks, this is fixed and will be in the next release
