### ISSUE TITLE
crashlog.cpp compilation failure under GCC 7.3.1

### ISSUE THREAD

**Issue by cagelight** [JGRennison/OpenTTD-patches#47]
```
In file included from /data/prog/OpenTTD-patches/src/crashlog.cpp:29:0:
/data/prog/OpenTTD-patches/src/language.h:108:8: error: ‘Collator’ does not name a type; did you mean ‘UCollator’?
 extern Collator *_current_collator
```
After doing `./configure` and `make`

**Comment by HanFox** [comment]
The error looks the same as this one which was related to icu61 not gcc (at the time of the issue Arch Linux was already using GCC7.3.1): https://github.com/JGRennison/OpenTTD-patches/issues/34

This has also already been fixed upstream: https://github.com/OpenTTD/OpenTTD/commit/19076c24c1f3baf2a22d1fa832d5688216cf54a3

Maybe when @JGRennison gets time he can rebase against a newer trunk.

**Comment by JGRennison** [comment]
I've merged in the new trunk repo which includes the fix.
Can you let me know whether this compiles correctly for you now?
Thanks.

**Comment by JGRennison** [comment]
Thanks, I'll close this one then.
