### ISSUE TITLE
[Bug]: Difference in Depot Button behaviour depending on setting state

### ISSUE THREAD

**Issue by NyanGoat** [JGRennison/OpenTTD-patches#470]
### Version of OpenTTD

jgrpp-0.26.0 - jgrpp-0.50.1

### Expected result

Clicking the depot button normally should have the same default behaviour with and without "Show go to depot/hangar and sell feature" enabled.

### Actual result

Behaviour is different with the feature disabled and enabled.

With it Enabled, a current depot order is skipped if depot button is clicked.
With it Disabled, a current depot order is changed to stop in depot order.

### Steps to reproduce

Load attached savegame, game is paused with Train 1 having current service order at depot.
[depot_behaviour.zip](https://github.com/JGRennison/OpenTTD-patches/files/10340406/depot_behaviour.zip)

Enable "Show go to depot/hangar and sell feature" in settings.
Click depot button, it skips to the station order.

Reload save
Disable "Show go to depot/hangar and sell feature" in settings.
Click depot button, it changes from "service at depot" order to "heading to depot" order and then stops there.

**Comment by NyanGoat** [comment]
Had time to do some more tests, the sell depot order feature was introduced in 0.26.0, so tested in 0.25.2 and 0.26.0.

In 0.25.2:
No sell depot feature, clicking button makes vehicle go to depot and stop when it has a current depot order.

In 0.26.0:
Clicking button with sell feature disabled shows same behaviour as in 0.25.2 and Vanilla OpenTTD, the order changes from service at depot, to heading to depot, and train stops.

Clicking button with sell feature enabled shows same behaviour as in 0.50.1, where the vehicle then skips the current depot order and proceeds to the next destination.

--
As it has been how the button has functioned since day one with the feature enabled, I am uncertain if this should be classified as a bug, or if it was done like this due to f.ex the sell feature kicking in if it did the default behaviour of going to depot and stopping.

The text for the setting does state "When enabled, the behaviour of the vehicle go to depot button is changed.", so it might be intended, but needs to be clarified better in the setting info perhaps in that case.

**Comment by JGRennison** [comment]
I've adjusted the setting help text to be less vague.

**Comment by NyanGoat** [comment]
Pulled the newest master, jgrpp-0.50.1-61-g9cff3666a, and tested it locally and works as expected here.
Did not notice anything out of the ordinary when testing some scenarios, so closing this :)
