### ISSUE TITLE
[Bug]: openttd.exe size difference in release version on GH versus locally built version

### ISSUE THREAD

**Issue by NyanGoat** [JGRennison/OpenTTD-patches#471]
### Version of OpenTTD

openttd-jgrpp-0.50.1 (and earlier versions)

### Expected result

I noticed while testing #470 that my locally built version was a lot smaller than the bundled version here on Github.

These were my results when building locally:
Size of openttd.exe (RelWithDebInfo) should be about 13,6MB.
Size of openttd.exe (Debug) should be about 44,1MB.

Vanilla OpenTTD binaries from official site:
12.2: 10.4MB
13.0-RC1: 12.9MB

### Actual result

Size of openttd.exe bundled in [jgrpp-0.50.1-windows-win64](https://github.com/JGRennison/OpenTTD-patches/releases/download/jgrpp-0.50.1/openttd-jgrpp-0.50.1-windows-win64.zip) is 117MB.

Previous versions are also larger than expected.
0.48.5 is 69.0MB, and 0.49.0 jumps to 113.5MB.

![image](https://user-images.githubusercontent.com/109810800/211127077-79ba0491-a66c-4568-8655-650b8c8dd06b.png)

### Steps to reproduce

Download jgrpp-0.50.1 from GH and compare size of binary against locally built variant.

**Comment by JGRennison** [comment]
The Windows builds on github are built with additional debug information so that crash logs from Windows users are usable for diagnosing faults. The increased size is deliberate, though it should not be quite that large.

**Comment by JGRennison** [comment]
Fixed in most recent release
