### ISSUE TITLE
[Bug]: Day Length Factor changing Scheduled DS times

### ISSUE THREAD

**Issue by quaintlongjay** [JGRennison/OpenTTD-patches#472]
### Version of OpenTTD

Windows 10

### Expected result

Apparently changing the day length factor in an existing save game should not change the in-game clock or scheduled DS anymore. However, at least in my case it does. I was trying to slow down the calendar (month and year).
If it is the reason, this save game was created probably around the 0.40 to 0.45 versions of JGR.

### Actual result

Ticks per Minute should be the setting that changes the length of in game minutes and along with that any active scheduled DS. However in the screenshots added you can see that changing the day length factor also moves up the times already set in the scheduled dispatch menu.
IMAGE 1
![image](https://user-images.githubusercontent.com/120314522/212120939-a4fa703d-0b77-4153-bddf-4e2eb946775f.png)

IMAGE 2 (result after increasing the day length factor)
![image](https://user-images.githubusercontent.com/120314522/212121284-177f8470-265c-4699-9de1-400d642569d8.png)

 

### Steps to reproduce

I'm not sure whether this is somehow only happening on my save-game but just in case I will attach it here.
[cheese.zip](https://github.com/JGRennison/OpenTTD-patches/files/10403624/cheese.zip)

1. Load attached save game
2. Open settings to day length factor
3. Open any scheduled dispatch
4. Change the day length factor up or down
5. Watch the times increase or decrease but not the space between them
6. interesting

**Comment by JGRennison** [comment]
This should be fixed in the next release

**Comment by quaintlongjay** [comment]
Thank you
