### ISSUE TITLE
[Crash]: crash when loading a old save

### ISSUE THREAD

**Issue by qq1137167425** [JGRennison/OpenTTD-patches#473]
### Version of OpenTTD

jgrpp-0.50.1, Windows 11 Pro 64-bit (10.0, Build 22623) (22621.ni_release.220506-1250)

### Steps to reproduce

1. Load a old save created on 0.37.0.
2. The game crash.

### Upload crash files

[log.zip](https://github.com/JGRennison/OpenTTD-patches/files/10417245/log.zip)

**Comment by JGRennison** [comment]
Thanks for the report, this will be fixed in the next release.
