### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bootmii** [JGRennison/OpenTTD-patches#475]
### Version of OpenTTD

jgrpp-0.50.2, Windows 11

### Expected result

Zooming far out enough to get the minimap shows the minimap industry view if you have the default set to Industry.

### Actual result

Zooming far out enough to get the minimap shows the minimap cargodist view by default, even if you have the default set to Industry.

### Steps to reproduce

1. set your Enhanced Zoom default view to Industry.
2. start or join a new game

**Comment by bootmii** [comment]
This bug also existed in 0.50.1.

**Comment by JGRennison** [comment]
Thanks for reporting this, this is fixed and will be in the next release.
