### ISSUE TITLE
[Bug]: Station Graphics bug

### ISSUE THREAD

**Issue by JukjeonWani** [JGRennison/OpenTTD-patches#479]
### Version of OpenTTD

jgrpp 0.50.2, windows 11

### Expected result

0.50.2
![KakaoTalk_20230128_234500318](https://user-images.githubusercontent.com/88026704/215300811-eed6325d-5602-41e5-92dd-27c40867fa6d.png)
![KakaoTalk_20230128_234559104](https://user-images.githubusercontent.com/88026704/215300813-5f13ca27-1887-4947-9050-caa717515379.png)

### Actual result

0.50.1
![image](https://user-images.githubusercontent.com/88026704/215300831-92d45fb4-b210-4969-aca6-87d953e2ee68.png)
![image](https://user-images.githubusercontent.com/88026704/215300869-e9bbeb15-abcd-483f-b849-72ca4a510e9b.png)

### Steps to reproduce

Station Graphics bug

Unconditionally.

**Comment by telk5093** [comment]
Used NewGRF:
 1. ``Indutrial Stations Renewal 1.0.2``
 2. ``Kiwitree Station Set v1.2.1``

I can also reproduce this issue in 0.50.2, seems fine with 13.0-RC2.

**Comment by JGRennison** [comment]
Thanks, this is fixed and will be in the next release.
