### ISSUE TITLE
CargoPacketList list->deque switch from 2016 caused crashes in some cases.

### ISSUE THREAD

**Issue by KeldorKatarn** [JGRennison/OpenTTD-patches#48]
This commit
https://github.com/JGRennison/OpenTTD-patches/commit/a422cb67530c132d7573c113ad4cd9ff1a9d95cd

caused several crashes on my end since some cargoaction/vehiclecargopacket operations do stuff with iterators that was valid for a list iterator but the same operation invalidates deque iterators.
I fixed that (I think) here:

https://github.com/KeldorKatarn/OpenTTD_PatchPack/commit/f749230714e9abb39f940e3a26de3bacfe327ba9

I tried to revert the commit and go back to a list but then loading a savegame completely failed. I'm not exactly sure why. Looking at your load save code for these lists, shouldn't the savegame look identical whether a deque or list was saved? The size of the list and then the individual elements?
Switching from list to deque worked just fine for loading old savegames but switching back corrupts the vehicles whos cargo I'm loading... any ideas? Also please double check my fixes since these were HARD to reproduce crashes so I hope I fixed them all and there isn't another somewhere or I accidentally messed up the semantics here. But there's no way to get this to work with a deque iterator without copying the deque so you operate on an unmodified one.

Reroute was an issue because the action() that is called on the packet pushes another element to the front of the list. That is legal for a std::list and won't destroy the iterator (even says so in the comment on that action) but for a deque it invalidates the iterator, that's what caused the crash on that one.

The Reassign thing I fixed preemptively. I never saw that crash but also never saw the code get triggered. If it gets executed it has to crash. That can't work with iterators of a deque. There's no way of modifying the list while iterating except for the erase method without invalidating the iterator.

**Comment by JGRennison** [comment]
That was careless of me to miss those.
Thanks for pointing it out and for the patch.
I've applied a slightly different fix, which ought to have a lower performance cost (though I haven't measured anything yet).
I've done some basic testing with AddressSanitizer, but haven't found any issues with the fix applied yet.

**Comment by KeldorKatarn** [comment]
I'll test this implementation later. I think I still have a savegame that is known to crash 100% if this isn't fixed.

**Comment by JGRennison** [comment]
This should be fixed now.
