### ISSUE TITLE
[Bug]: Some NewGRFs have vehicle names clipping behind purchase window sprites in new games

### ISSUE THREAD

**Issue by EratoNysiad** [JGRennison/OpenTTD-patches#483]
### Version of OpenTTD

0.50.3

### Expected result

![image](https://user-images.githubusercontent.com/10280358/217248510-e3076757-177c-400f-adfe-9634c7644cfa.png)
When loading a new game with RIMS, NATS, JP+ MUs and a variety of other vehicle newgrfs, I expect the purchase window to have text not clipping through the purchase window sprites.

### Actual result

![image](https://user-images.githubusercontent.com/10280358/217248269-377c5021-8489-47bf-a82d-3da0abe594ea.png)
Text clips through the purchase window sprites.

This does not happen when newgrfs are reloaded or when loaded in the latest version of OpenTTD, 13.0

### Steps to reproduce

Open a new game with RIMS, NATS or JP+ Multiple Units.
Open the "Available Trains" window
Profitn't

**Comment by JGRennison** [comment]
Should be sorted now

**Comment by JGRennison** [comment]
Fixed in most recent release
