### ISSUE TITLE
[Crash]: rendering travel time in timetable GUI from waypoint to counter change

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#485]
### Version of OpenTTD

jgrpp-0.50.3 on Windows 10, 64-bit

### Steps to reproduce

1. Build a train depot, some track, and a waypoint.
2. Purchase a train.
3. Setup a counter.
4. Setup the train's orders like so: "1: Go via [waypoint]", "2: Change counter: [any counter] to [any value]"
5. In the timetable GUI for the train, attempt to set a travel time from order 1 (go via waypoint) to order 2 (change counter).
6. Upon confirming, the value is successfully entered (as shown in the crash save) but the game crashes.

### Upload crash files

[crash-20230218T025401Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/10772945/crash-20230218T025401Z.zip)

`NOT_REACHED` triggered here: https://github.com/JGRennison/OpenTTD-patches/blob/50a48b1264b14e1d42b938e694c39df60669761c/src/order_gui.cpp#L1144

**Comment by JGRennison** [comment]
This should be resolved now

**Comment by JGRennison** [comment]
Fixed in most recent release
