### ISSUE TITLE
[Bug]: No dump file is generated on crash on Windows

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#486]
### Version of OpenTTD

jgrpp-0.50.3 on Windows 10, 64-bit

### Expected result

On game crash, a dump file should be generated just like in vanilla.

### Actual result

A dump file is not generated when the game crashes, unlike vanilla and (as far as I can tell) older versions of this patchpack.

The last version I can recall producing a dump file on crash is no earlier than jgrpp-0.48.2 and no later than jgrpp-0.50.0.

### Steps to reproduce

Crash the game e.g. by following reproduction steps in https://github.com/JGRennison/OpenTTD-patches/issues/485.

**Comment by JGRennison** [comment]
This is deliberate. The dump files are not useful.
Changed in: a8d5e5669653c394ec78ff35525f5aea29476253
