### ISSUE TITLE
Problem with "jump to order" command when using "waiting cargo amount"?

### ISSUE THREAD

**Issue by NicholasRB** [JGRennison/OpenTTD-patches#487]
I'm thinking somewhere along the way in development here these 2 commands related to the "jump to" schedule command broke. The train gets stuck in an infinite loop, even when the inputs say it shouldn't be.

Here is a video of what is going on:
https://www.youtube.com/watch?v=OwlGbXhLeJQ

**Comment by James103** [comment]
These conditional orders should work, but may not be possible to insert (as far as I can tell) with the current feature set of JGRPP 0.50.3.

> Jump to order 4 when Engineering Supplies at Irvington Interchange is more than 0 crates
> Jump to order 1 when Engineering Supplies at Irvington Interchange is less than 3,000 crates

**Comment by NicholasRB** [comment]
> 

Ah okay. Thanks for the info there. I was wondering why this was happening.

**Comment by JGRennison** [comment]
You are using the wrong conditional order. It does next make sense to set the via parameter to be the same as the next station you're testing the cargo of. Just unset the via or use the actual station you want to check the cargo via.

**Comment by NicholasRB** [comment]
Thank you Rennison for answering this. I've been trying to figure it out for idk how long now and that now fixed it. I sometimes think that talking directly to the devs of stuff at this point is best as my word do I always seem to get too many wrong answers for stuff...

**Comment by JGRennison** [comment]
Waiting cargo orders have been changed so that this shouldn't be an issue any more
