### ISSUE TITLE
[Crash]: Failed assertion in cargopacket.h

### ISSUE THREAD

**Issue by Locchan** [JGRennison/OpenTTD-patches#488]
### Version of OpenTTD

0.50.3 dedicated server on Linux (Rocky Linux 9)

### Steps to reproduce

Not really sure, crashed on other players while I was offline.

### Upload crash files

[crash-20230222T185731Z.tar.gz](https://github.com/JGRennison/OpenTTD-patches/files/10813307/crash-20230222T185731Z.tar.gz)

**Comment by JGRennison** [comment]
The crash files that you've uploaded don't seem to match the issue title?

In any case the crash that you've uploaded the files for is the same as #485, which is already fixed and will be in the next release.

**Comment by JGRennison** [comment]
Fixed in most recent release

**Comment by Locchan** [comment]
> The crash files that you've uploaded don't seem to match the issue title?
> 
> In any case the crash that you've uploaded the files for is the same as #485, which is already fixed and will be in the next release.

Hm, I'm pretty sure I've replaced the wrong tarball with the right one like within an hour of creating the issue and your comment is older than that.

Anyways, the right crash log/savefile is in my initial issue post (as of now). You can look into it to make sure it's actually fixed.
The crash itself is not something that's reoccuring though.

**Comment by JGRennison** [comment]
I am not sure how your save got into this state. I will look into this further in due course.

In the meantime, perhaps it'd be worth upgrading to the most recent version if you encounter this again.

**Comment by Locchan** [comment]
> In the meantime, perhaps it'd be worth upgrading to the most recent version if you encounter this again.

Yea, I upgraded the server to the latest version.
I'm planning on running my open server 24/7 on the latest version (with auto upgrades). I'll provide saves and logs for any crashes I encounter.
