### ISSUE TITLE
[Crash]: Assertion failed at line 100 of /home/jgr/openttd/jgrpp/src/strings_func.h: size <= parent.GetDataLeft()

### ISSUE THREAD

**Issue by miziobighouse** [JGRennison/OpenTTD-patches#489]
### Version of OpenTTD

JGR's Patchpack version 0.51.0 Windows 11 64x

### Steps to reproduce

Open Settings > set to expert > Expand All > Scroll Down and crashes

### Upload crash files

![crash-20230225T161935Z](https://user-images.githubusercontent.com/126344457/221368011-29248372-8d97-42b5-8c0d-088ed837d2a8.png)
[crash-20230225T161935Z.log](https://github.com/JGRennison/OpenTTD-patches/files/10831682/crash-20230225T161935Z.log)

**Comment by miziobighouse** [comment]
> Settings to Advanced*

**Comment by JGRennison** [comment]
This has already been fixed (86aeb16f55939c959fe71886d606d617513cd460), it'll be in the next release

**Comment by miziobighouse** [comment]
okok, thank you. If it can be of any help it crashes when having settings in Expert and going to Environment > Towns.

> This has already been fixed ([86aeb16](https://github.com/JGRennison/OpenTTD-patches/commit/86aeb16f55939c959fe71886d606d617513cd460)), it'll be in the next release

**Comment by benjamin-kirkbride** [comment]
Having the same issue, any idea when the next release will be @JGRennison? Is building from source easy to do in the meantime?

**Comment by JGRennison** [comment]
In about 30 minutes

**Comment by benjamin-kirkbride** [comment]
@JGRennison thanks! loving the pack!
