### ISSUE TITLE
[Crash]: Assertion failure when closing the game

### ISSUE THREAD

**Issue by merni-ns** [JGRennison/OpenTTD-patches#490]
### Version of OpenTTD

JGRPP 0.50.3, Windows 11

### Steps to reproduce

AFAIK all I did after opening the save was resizing the window to be thin on one side of the screen (as I was drawing a map of my services and using the game window as reference), and occasionally moving the viewport around with the arrow keys. When I clicked the X to close the game, it crashed.

**Note that I have added/modified vehicle and station NewGRFs in the running game.**

I did not find any "crash.dmp", I uploaded whatever files were there (.png, .log, .sav).

### Upload crash files

[OpenTTD.zip](https://github.com/JGRennison/OpenTTD-patches/files/10861904/OpenTTD.zip)

**Comment by JGRennison** [comment]
It looks like you resized the window to be smaller than the query window to confirm exiting the game.
This should be fixed in the next release.

**Comment by JGRennison** [comment]
Fixed in most recent release
