### ISSUE TITLE
[Bug]: cannot purchase land diagonally

### ISSUE THREAD

**Issue by negativeExponent** [JGRennison/OpenTTD-patches#494]
### Version of OpenTTD

OpenTTD jgrpp-0.51.1 @ Void Linux

### Expected result

Pressing ctrl, you should be able to drag and purchase land in multiple tiles instead of just one tile at a time.

### Actual result

you can only purchace one tile at a time.

### Steps to reproduce

1. start a new game.
2. purchase land diagonally.

**Comment by stormcone** [comment]
Please check the "Permit purchasing land" setting under "limitations".

**Comment by negativeExponent** [comment]
hmm ok. so its a feature. thanks.
