### ISSUE TITLE
[Bug]: Autosave in Settings (not Game Options) is mangled

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#496]
### Version of OpenTTD

jgrpp-0.51.1

### Expected result

``Custom intervals (days)``
``Custom intervals (realtime minutes)``

### Actual result

![image](https://user-images.githubusercontent.com/10726524/224471624-bdf5e371-2651-4182-9271-5915feea7f63.png)

### Steps to reproduce

``Custom intervals`` option in Settings (not in Game Options) is somehow mangled.

1. Open Settings
2. Search as ``auto``

**Comment by JGRennison** [comment]
Should be fixed now.
