### ISSUE TITLE
[Suggestion] Picker/eyedropper tool

### ISSUE THREAD

**Issue by EmperorJake** [JGRennison/OpenTTD-patches#498]
Many other building games have a picker tool, that lets you instantly select any object on the map and immediately open the tool to build that object. Factorio is a good example of this, as well as Cities Skylines (via a mod) and Augustus (open source reimplementation of Caesar III)

A similar tool for OpenTTD would be especially beneficial in GRF-heavy games with lots of objects and tracktypes buried in menus. It would greatly streamline the building process.

Ideally the tool would have a hotkey such as R (easy to reach and currently it does nothing) which opens a tool similar to the query tool. Then you click on anything on the map, and it instantly opens the relevant building menu with that item selected.

**Comment by JGRennison** [comment]
[61e9c30](https://github.com/JGRennison/OpenTTD-patches/commit/61e9c3084f544be8017361ca80f7f32f9ec624fd) ought to cover this use case?

**Comment by EmperorJake** [comment]
Yesssss, this works so well, thanks very much :)
