### ISSUE TITLE
[Bug]: Water does not spread in the scenario editor

### ISSUE THREAD

**Issue by JohnFranklin523** [JGRennison/OpenTTD-patches#499]
### Version of OpenTTD

JGRPP 0.51.1, Windows 11

### Expected result

In the scenario editor, when lowering the land to sea level with open access to the sea, or demolishing a part of the sea to land, water should spread and flood the land.

### Actual result

Water does not spread. This does not happen in games, but does happen in the scenario editor.
![image](https://user-images.githubusercontent.com/117081939/225218396-ed9bbad1-1e8e-44dc-a34b-f9d93cf2fe31.png)

### Steps to reproduce

1. Go to the scenario editor.
2. Load a heightmap that has sea.
3. Demolish a tile of sea.
4. Wait, but nothing happens.

**Comment by JGRennison** [comment]
Already fixed here: https://github.com/JGRennison/OpenTTD-patches/commit/088cc201860834b2c4d850930d2c78ea8bc854ef

**Comment by JohnFranklin523** [comment]
Thanks, and sorry for my ignorance in C++ language.
