### ISSUE TITLE
Town growth overflow

### ISSUE THREAD

**Issue by KeldorKatarn** [JGRennison/OpenTTD-patches#50]
https://github.com/KeldorKatarn/OpenTTD_PatchPack/commit/e49c1b9e7ee037d02711ed62d41349a7f8d86b47

This has the potential to overflow the growth rate with daylength patches. I had to change growth counter and growth rate to Ticks (int32) to fix my game. I don't know how your DAY_TICKS work, but mine are scaled for daylength since I want the town growth rate to still be in days even if the days are longer. Once the town growth is either much more than 'grow every 365 days' OR daylength is set to more than 2 this will massively overflow.

**Comment by KeldorKatarn** [comment]
This commit fixes it on my side: https://github.com/KeldorKatarn/OpenTTD_PatchPack/commit/481a1ccbe5ec932ae43ef53419e50aeb766004b5

You may have to adjust depending on how your DAY_TICKS is defined. Mine are scaled, yours I believe are still 74. If you have DAY_TICKS == 74 then you MAY want to think about reworking this entire town growth thing because the towns would grow unscaled, which would be weird or unwanted by some players. But that's up to you. either way, something describing Ticks should be of datatype Ticks anyway. uint16 was fine when it was scaled by another value but now that it represents ingame ticks in needs to be the same datatype.

**Comment by KeldorKatarn** [comment]
Also holy hell... are my eyes lying to me or was the uint16 growth_rate previously saved as a int16. That's a HUGE data loss. That makes this even worse.

**Comment by KeldorKatarn** [comment]
Nevermind this for now, there's still some bugs in this I need to find... why did I even cherry pick this... sigh

**Comment by JGRennison** [comment]
I'm not scaling town growth by the day length, so the effective growth rate in player/real time is divided by the day length. I don't think that this issue affects my patchpack, but I'll look into it.
In general my approach for day length is that is that everything except vehicles, vehicle-related accounting, and tile animations is slowed relative to player/real time.

**Comment by KeldorKatarn** [comment]
I still think it's an issue that something that describes "ticks" is not only not the same data size as Ticks, but even of a different signed character. I don't see the point in that and it can only cause issues.
