### ISSUE TITLE
[Bug]: Departure board station list doesn't scroll when paused

### ISSUE THREAD

**Issue by merni-ns** [JGRennison/OpenTTD-patches#505]
### Version of OpenTTD

JGRPP 0.50.3

### Expected result

The list of "Calling at" stations scrolls (if there are more than can fit on a single line), regardless of the game being paused. And if the game is in fast forward, the scrolling still happens at the same rate.

### Actual result

If the game is paused, the list doesn't scroll. Also, if the game is fast forwarded, the scrolling speeds up.

### Steps to reproduce

1. Have a train which calls at enough stations, that the "Calling at" list on the departure board cannot fit on one line and scrolls.
2. Pause the game.
3. Open the departure board which shows such a train.
(Steps 2 and 3 can be done in reverse order too.)

**Comment by JGRennison** [comment]
This is fixed now, it will be in the next release
