### ISSUE TITLE
[Suggestion]: Option to lessen the effect of very long delivery times on cargo payments

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#506]
### Version of OpenTTD

Since https://github.com/OpenTTD/OpenTTD/pull/10596

### Expected result

An option should be added to lessen the effect of very long delivery times on cargo payments, such that cargo older than around 10-20 minutes (real time) still receive a good payment upon final delivery, almost the same as in vanilla.

### Actual result

Cargo payment rates reduce with the amount of time cargo is in transit all the way until a penalty hardcap is reached after around 10-20 minutes of real time. https://github.com/OpenTTD/OpenTTD/pull/10596 converts this hardcap to a softcap, meaning coal that is 1 hour old upon delivery return a payment much lower compared to coal that is 20 minutes old upon delivery (instead of them being almost the same) and same for passengers.

For example, setting a day length factor of 120 and sending coal on a 3-game-day trip will cause the deliverer to receive a very low payment, made even lower (by several times) by the linked PR.

### Steps to reproduce

Update to a nightly version post-https://github.com/OpenTTD/OpenTTD/pull/10596, then build a passenger or freight network such that passengers or freight must make multiple transfers to get to their destination (e.g. local bus in city A -> tram -> intercity train -> tram/metro -> local bus in city B). For better effect, do this at a long day length factor.

**Comment by JGRennison** [comment]
I doubt that a setting is necessary here, there is no significant issue with https://github.com/OpenTTD/OpenTTD/pull/10596.

**Comment by James103** [comment]
A better alternative may be to have a setting to change the speed of cargo aging, making it slower (or faster). For example, large-scale networks built for realism may need slower cargo aging to remain profitable, while some scenarios may have faster cargo aging for additional challenge.

**Comment by CharlieAtlas** [comment]
I am pretty sure there is a script or newGRF that does this.  I see one called BaseCosts that i think it is it.  Or altered costs and prices.

**Comment by JGRennison** [comment]
Implemented in [e26bea6](https://github.com/JGRennison/OpenTTD-patches/commit/e26bea6ce4d438fb2d200736351f033c8cfd1040)/v0.53.2
