### ISSUE TITLE
[Crash]: When one company goes bankruptcy or resetting any company

### ISSUE THREAD

**Issue by JohnFranklin523** [JGRennison/OpenTTD-patches#511]
### Version of OpenTTD

JGRPP 0.53.0, Windows 11

### Steps to reproduce

1. Open dedicated server console.
2. Load a save game with at least one company.
3. Reset any company (according to the crash log, better with vehicles).
4. Game crashes.

### Upload crash files

[crash-20230423T183144Z.log](https://github.com/JGRennison/OpenTTD-patches/files/11310503/crash-20230423T183144Z.log)

**Comment by JGRennison** [comment]
This looks like a combination of https://github.com/OpenTTD/OpenTTD/issues/10707 and https://github.com/JGRennison/OpenTTD-patches/commit/1350e23e29a695690a926c13599e0b66abf5e928.

This will be fixed in the next release.

**Comment by galang2222** [comment]
I don't know if this is the right place to post but my friend's multiplayer game has the same problem at first when he tried to reset a company, but now the game crashes every time it autosaves.
[crash-20230425T152509Z.log](https://github.com/JGRennison/OpenTTD-patches/files/11324295/crash-20230425T152509Z.log)

**Comment by JGRennison** [comment]
This looks to be the same issue.
I think I will have to do the next release earlier than planned.

**Comment by JGRennison** [comment]
This is fixed in the most recent release
