### ISSUE TITLE
[Issue]: GUI doesn't show separate un-electrified and electrified railway lines

### ISSUE THREAD

**Issue by mmarkkozo** [JGRennison/OpenTTD-patches#513]
### Version of OpenTTD

OpenTTD jgrpp-0.53.1, macOS 13.2.1

### Expected result

Using U&ReRMM 2 1.5 NewGRF in vanilla OpenTTD shows separate forms of railway lines - both electrified and un-electrified. I am also using NNGT 0.9.0 BETA NewGRF in conjunction and in vanilla version of the game no issues occur.

### Actual result

After installing OpenTTD-patches, version 0.53.1, game GUI no longer provides me with the options for electrified railroads to build. Building stations with un-electrified railways will still for some reason allow electricity-driven rolling stock into stations as long as the railways proceeding up to it are electrified beforehand.
<img width="1012" alt="Screenshot 2023-05-03 at 03 11 55 PM" src="https://user-images.githubusercontent.com/132566773/236181768-53d39709-46c3-4ec6-b4f1-36f68bd1b0df.png">

### Steps to reproduce

1. Download U&ReRMM 2 NewGRF in vanilla OpenTTD
2. Create a new world and build both electrified and un-electrified railway lines
3. Save the game
4. Download JGRPP patched version of OpenTTD
5. Load the saved game

**Comment by JGRennison** [comment]
Which vanilla version are you using? I can't reproduce any issue with the above steps and 13.1.
It may be useful if you could upload the savegame which is showing the issue.

**Comment by mmarkkozo** [comment]
Below is the list of the NewGRF sets I am also using together with the aforementioned sets.
I no longer remember which vanilla version was it that I was using exactly, but it was a 1.12.x; most probably it was version 1.12.2
<img width="344" alt="Screenshot 2023-05-04 at 02 03 02 PM" src="https://user-images.githubusercontent.com/132566773/236198214-b5ce9f82-5791-48f9-a303-4039f0263c01.png">
<img width="344" alt="Screenshot 2023-05-04 at 02 03 19 PM" src="https://user-images.githubusercontent.com/132566773/236198281-bdff593b-bd1c-47b5-a978-10f5f7cdbb37.png">
[Plunfingway Transport.sav.zip](https://github.com/JGRennison/OpenTTD-patches/files/11397193/Plunfingway.Transport.sav.zip)

**Comment by JGRennison** [comment]
It seems that this is because there are no vehicle GRFs which define engines for those railtypes, and those railtypes are not otherwise made available. Probably the railtype GRF is not coded correctly.

As a workaround, add another rail vehicle GRF to the NewGRF list (e.g. Iron Horse 2 with the "extra railtypes" parameter disabled).

**Comment by mmarkkozo** [comment]
Added Iron Horse 2, disabled the "extra railtypes" parameter and the rail types have appeared back. After removing this NewGRF set the rail types have remained.

After re-loading the game, the rail types have not disappeard

Safe to say, the issue has been solved. Thank you!:)

<img width="697" alt="Screenshot 2023-05-04 at 03 30 55 PM" src="https://user-images.githubusercontent.com/132566773/236219950-482830d3-6829-4961-939d-9e74d1df7b10.png">
