### ISSUE TITLE
Missing sprites

### ISSUE THREAD

**Issue by stebbo63** [JGRennison/OpenTTD-patches#514]
### Version of OpenTTD

0.50.0 onwards

### Expected result

no message

### Actual result

I am getting the following message.  I only noticed it after I upgraded to 0.50.0 a while ago, but it's still there with the latest 0.53.2

The message is on the opening menu and says "The currently selected base graphics set is missing 16 sprites.  Please check for updates for the baseset."   The game plays ok.

I don't get this message on the official OpenTTD.

### Steps to reproduce

1. Load the game.

**Comment by James103** [comment]
Which base graphics set are you using? Does the message appear with the latest official OpenGFX?

**Comment by stebbo63** [comment]
Hi James,

thanks for the response.  I am using the zbase graphics set.  It does not appear if I set the graphics set to OpenGFX.

However, the official version of OpenTTD does not complain about the zbase graphic set.

Regards,
Chris.

**Comment by JGRennison** [comment]
This message is not a problem and can be ignored, it just means that more graphics have been added since the baseset that you are using was last updated.

**Comment by stebbo63** [comment]
Hi James,

thanks for that.  

Cheers,
Chris.
