### ISSUE TITLE
[Bug]: Unable to resize "Routing Restrictions - Slot Management" window

### ISSUE THREAD

**Issue by zenofile** [JGRennison/OpenTTD-patches#515]
### Version of OpenTTD

openttd-jgrpp-0.53.2-linux-generic-amd64

### Expected result

When trying to resize the slot management window, the window should change width and height accordingly.

### Actual result

The window can only be made taller but not wider. When trying to change the width, nothing happens, which makes it impossible to read longer slot names with a larger font.

### Steps to reproduce

1. Enable the `Advanced routing restrictions` feature
2. Open the vehicle list, e.g., for trains
3. Select `Manage list`
4. Select `Manage slots`
5. Try to resize the window and change its width

**Comment by JGRennison** [comment]
This should be fixed in the next release

**Comment by zenofile** [comment]
Resizing works now, but there seems to be a drawing issue with the bottom right half of the window. The right vehicle list is smaller than the left slot list and the remaining space seems to be glitched.

![screen](https://github.com/JGRennison/OpenTTD-patches/assets/2056412/7ffce180-e96b-4ba9-aa29-34c9e9e7aada)

**Comment by JGRennison** [comment]
That should be resolved now
