### ISSUE TITLE
[Bug]: Deleting middle track of "Multi track railway level crossing" can lead to stuck crossing lights

### ISSUE THREAD

**Issue by matematysek** [JGRennison/OpenTTD-patches#517]
### Version of OpenTTD

0.53.2 WIN 11

### Expected result

When splitting level crossing (for example when rebuilding rails) at time when a train crosses it and whole crossing is closed down, open the half with no allocated path across it.

### Actual result

On the half with no train coming across the lights stay on until next train comes across. The track is not allocated.

### Steps to reproduce

[crossing bug.zip](https://github.com/JGRennison/OpenTTD-patches/files/11472577/crossing.bug.zip)
1. load the savegame
2. delete the short track that ends with company land "signs"
3. observe

**Comment by JGRennison** [comment]
This should be fixed in the next release
