### ISSUE TITLE
[IME] Unable to input Korean

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#52]
It is unable to input korean text in 0.24.0
0.23.0 works fine.
(Copy & Paste works, though)

**Comment by JGRennison** [comment]
Which OS/platform are you running on?

**Comment by telk5093** [comment]
@JGRennison I'm using Windows 10 Pro (64bit)

**Comment by JGRennison** [comment]
Can you clarify how exactly it doesn't work, is it some problem with the IME?

**Comment by telk5093** [comment]
Korean users switch their input mode between Korean and English by pressing Kor/Eng key([refer here](http://cfile27.uf.tistory.com/image/1212D2164ADC8B134A2E50)).
I cannot enter the korean input mode when I press Kor/Eng key.

**Comment by telk5093** [comment]
It seems it works at 0.25.0

**Comment by JGRennison** [comment]
Thanks for letting me know, I'll close this now.
