### ISSUE TITLE
[Suggestion] Show railtype colour of tunnels/bridges in smallmap

### ISSUE THREAD

**Issue by merni-ns** [JGRennison/OpenTTD-patches#522]
In the smallmap, and the map view that you get when zooming out greatly, there is an option (Interface > Viewports > Map mode > Show bridges and Show tunnels) to show bridges/tunnels. But, this just shows a much thinner line than the normal tracks, and in a single colour. It doesn't respect the different colours that different railtypes can use, if the transport routes mode is selected. Further, the line for tunnels is almost invisible.

Could the bridge/tunnel lines be made more prominent and coloured in the colour for that railtype (when using the transport routes mode)?

Screenshot is with U&ReRMM 2 1.5 and the rail types are Modern electrified line (dark blue), Modern high-speed electrified line (lighter blue) and Branch line (grey).
![Screenshot 2023-05-24 193444](https://github.com/JGRennison/OpenTTD-patches/assets/66267867/4b80a6be-ef33-4f55-a599-ac167769c0a4)

**Comment by JGRennison** [comment]
Bridges/tunnels should use the rail type colour now.
Using a thick line is somewhat problematic as that is the same as normal track and there is usually something else in the space which is bridged over or tunnelled beneath.
I've added a hotkey to toggle the slope setting, you can also change it from the settings window.
