### ISSUE TITLE
[Bug]: Can't "Reload AI" on Game Script

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#523]
### Version of OpenTTD

jgrpp-0.53.3 on Windows 10, 64-bit

### Expected result

With `ai_developer_tools` enabled, one can "Reload AI" on the Game Script in the script debug window, like they can in prior versions.

### Actual result

Regardless of the value of `ai_developer_tools`, "Reload AI" is always greyed out when the Game Script is selected in the script debug window.

### Steps to reproduce

1. Run `set ai_developer_tools true`
2. Download, install and activate any Game Script.
3. Start a new game.
4. Open the "AI/Game Script Debug" window.
5. Select the Game Script to view its log.
6. Try clicking "Reload AI"
7. Nothing happens.

This may be caused by a merge error here: https://github.com/JGRennison/OpenTTD-patches/blob/d6b8fc9fe8a1f20d75b384d364be88fbb2fee20c/src/script/script_gui.cpp#L1109

### Workaround
With `ai_developer_tools` enabled, open "Game Script Settings" then select the same or a different Game Script to reload it.

**Comment by JGRennison** [comment]
Should be sorted now
