### ISSUE TITLE
[Bug]: Loan interest paid at end of quarter is accounted in next quarter's expenses, not this quarter.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#524]
### Version of OpenTTD

jgrpp-0.53.3 on Windows 10, 64-bit

### Expected result

For example,
* When loan interest for December 2022 is paid, the interest is accounted for in yearly totals for 2022 and quarterly operating expenses for Q4 2022.
* When loan interest for March 2023 is paid, the interest is accounted for in yearly totals for 2023 and quarterly operating expenses for Q1 2023.
* When loan interest for May 2023 is paid, the interest is accounted for in yearly totals for 2023 and quarterly operating expenses for Q2 2023.

### Actual result

* When loan interest for December 2022 is paid, the interest is accounted for in yearly totals for 2022, but the interest is accounted for in Q1 2023, one quarter later than intended. This causes a discrepancy in accounting between the reported yearly expenses and quarterly expenses.
* When loan interest for March 2023 is paid, the interest is accounted for in yearly totals for 2023, but the interest is accounted for in Q2 2023, one quarter later than intended. In this case, the yearly and quarterly totals are consistent but the reported accounting is still not entirely accurate.
* When loan interest for May 2023 is paid, the interest is accounted for in yearly totals for 2023 and quarterly operating expenses for Q2 2023. In my eyes, this is entirely accurate; loan interest paid for the months in a given quarter should be accounted for in that quarter.

### Steps to reproduce

1. Start a new game in the year 2022.
2. Use the money cheat to give yourself £10 million and repay the loan (the money cheat and £25 monthly fee goes in "Other" which is not counted in quarterly operating expenses).
3. In December 2022, take out a £10,000 loan.
4. Wait until January 2023, then repay the loan.
5. Check the finance window and notice the loan interest is there, while the operating profit remains flat at £0.
6. Wait until March 2023, then take out another £10,000 loan.
7. Wait until April 2023, then repay the loan.
8. Check the operating profit graph and notice the loan interest from December is what's causing the negative profit in Q1 2023, not Q4 2022.
9. Wait until May 2023, then take out a third £10,000 loan.
10. Wait until June 2023, then repay the loan.
11. Wait until July 2023, then check the operating profit graph. Notice the loan interest from May is accounted for in Q2 2023 as expected, on top of the loan interest from March.

This may be a vanilla bug; if so, a similar report will be created upstream.

Screenshot with the erroneous accounting (expected: 3 collinear points at the -£16 mark - one at Q4 2200, another at Q1 2201 and a third at Q2 2201):
![image](https://github.com/JGRennison/OpenTTD-patches/assets/37945304/b0ea819e-e313-42ad-9c9d-7fc9dca8e39b)

**Comment by JGRennison** [comment]
This ought to resolve the issue
