### ISSUE TITLE
[Bug]: Output of console command `debuglevel` without arguments is truncated

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#525]
### Version of OpenTTD

Originally found in: jgrpp-0.53.3 on Windows 10, 64-bit
Last max `debuglevel` string length increase: 3182cbb33210f7c783099d6d88acc12e0f29ef0b

### Expected result

The output of the console command `debuglevel` should not be truncated.

(Ideally the function should be rewritten to use C++-style strings instead of the current C-style.)

### Actual result

The output of the console command `debuglevel` is truncated at 150 characters, causing the debug level for `console` (and other categories after) to not be visible in the output. This is caused by there being additional debug categories not in vanilla.

Caused by:
https://github.com/JGRennison/OpenTTD-patches/blob/326d0c329c9a830544f68d0bdd329e83428593d2/src/debug.cpp#L319

### Steps to reproduce

Run the console command `debuglevel`.

**Comment by JGRennison** [comment]
Should be fixed now
