### ISSUE TITLE
[Crash]: Assertion failed at line 444 of newgrf_gui.cpp: this->clicked_dropdown

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#527]
### Version of OpenTTD

jgrpp-0.53.3 on Windows 10, 64-bit

### Steps to reproduce

1. Download and install a NewGRF with a parameter that is a dropdown.
2. Move the NewGRF to the active list.
3. Select it and click "Set parameters".
4. Click a dropdown.
5. Click the highlighted NewGRF from step 3.
6. Click "Set parameters" again.
7. Click a line item in the dropdown.
8. Game crashes.

### Upload crash files

[crash-20230601T190319Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/11628635/crash-20230601T190319Z.zip)

**Comment by JGRennison** [comment]
Should be fixed now
