### ISSUE TITLE
[Bug]: GS with the `IsDeveloperOnly` flag set aren't avaliable from game start until a `rescangame`

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#528]
### Version of OpenTTD

jgrpp-0.53.3 on Windows 10, 64-bit

### Expected result

Game Scripts with the `IsDeveloperOnly` flag set can be selected for new maps immediately after starting up the game.
If such a Game Script is selected to start up on new maps, that script should continue to start up on new maps after a restart.

### Actual result

After starting up the game, Game Scripts with the `IsDeveloperOnly` flag set can't be selected until the console command `rescangame` is executed.
If such a Game Script was selected to start on new maps, restarting the game means new maps will start without a Game Script.

### Steps to reproduce

1. Create a Game Script.
2. In the script's `info.nut`, set the developers-only flag by adding in the line `function IsDeveloperOnly() { return true; }`
3. Run: `set ai_developer_tools 1`
4. Run: `rescangame`
5. Notice that, assuming the script's `info.nut` compiles, the developers-only script is available to pick for new maps.
6. In "Game Script Settings", select the developers-only script.
7. Restart the game.
8. Notice that the developers-only script is no longer available to pick for new maps, even though it is listed in `list_game` output.
9. Check "Game Script Settings" and notice the developers-only script is no longer selected to start on new maps.
10. Run: `rescangame`
11. Notice the developers-only script is now available to pick for new maps again.

**Comment by JGRennison** [comment]
Should be resolved now
