### ISSUE TITLE
Replace Vehicle patch not working with some newgrf trains(dbsetxl)

### ISSUE THREAD

**Issue by Octtoc** [JGRennison/OpenTTD-patches#53]
Hello,
I have problems when using the new patched replace vehicle feature with some newgrf vehicles for example dbsetxl, nars is working correctly. when i want to create a new template then select the ice1 and then press ok the ice1 isn't in the available templates tab and cannot be selected. I have searched a little bit in the code but can't find anything.

**Comment by JGRennison** [comment]
If you have multiple rail types, you may need to change which one is currently selected in the drop-down at the bottom to see the template.

**Comment by JGRennison** [comment]
Needing to select the rail type should no longer be an issue as of v0.25.0
