### ISSUE TITLE
[Bug]: The first town of a map is ignored during public roads generation.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#530]
### Version of OpenTTD

jgrpp-0.53.3 on Windows 10, 64-bit

### Expected result

The first town of a map should be connected to other towns during generation of public roads.

### Actual result

The first town of a map is effectively ignored by the public roads generation algorithm, causing it to not be connected a majority of the time, even on small and flat maps with little water and regardless of the existence of a clear path to another town.

The town may still end up connected if it happens to lie along the route of a road between other towns on the network.

### Steps to reproduce

In the Scenario Editor:
1. Place down some towns.
2. Click "Build public roads"
3. The first town that is placed is not always connected by the algorithm.

In game:
1. Create and start a script that prints the town with ID 0: `ScriptLog.Info(ScriptTown.GetName(0))`
2. Center the viewport on that town.
3. Notice a majority of the time it is not connected to other towns with public roads.

**Comment by JGRennison** [comment]
This should be sorted now.
Also the `show_town_window` console command is an easier way to get the town by ID.
