### ISSUE TITLE
[Bug]: The spinners for the inflation factor cheats are misaligned (shifted down).

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#533]
### Version of OpenTTD

jgrpp-0.53.3 on Windows 10, 64-bit

### Expected result

The spinners for the inflation factor cheats should be aligned with the other spinners and buttons in the cheat window.

### Actual result

The spinners for the inflation factor cheats are approximately 3 pixels down from where they should be.
![image](https://github.com/JGRennison/OpenTTD-patches/assets/37945304/1bcf7ee8-163f-457e-8f6d-e2ca046dccb4)

### Steps to reproduce

In any singleplayer game, open the cheats window.

**Comment by JGRennison** [comment]
Should be resolved now
