### ISSUE TITLE
[Suggestion]: Option to increase the limit of the give money command 

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#537]
### Version of OpenTTD

jgrpp-0.53.3 on Windows 10, 64-bit

### Expected result

Server admins should be able to allow players to give other companies up to billions of pounds (or more) per invocation of the 'give money' command, reducing command spam for large money transfers.

### Actual result

The give money command is still limited to £20 million, even though the command now theoretically supports 64-bit values in vanilla and the next JGRPP release.

### Steps to reproduce

1. Try to give another company more than £20 million in a single 'give money' command.
2. Only the first £20 million is transferred.

This is reproducible in singleplayer and multiplayer.

**Comment by JGRennison** [comment]
The limit is removed in the most recent release
