### ISSUE TITLE
[Bug]: The station listing becomes overly wide in games with the "AXIS" NewGRF

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#539]
### Version of OpenTTD

jgrpp-0.53.3 on Windows 10, 64-bit

### Expected result

The 'list of cargoes' bar at the top of the station list window should be split in two (or more) rows when the sum of the lengths of the abbreviations of the cargo types exceeds a threshold value. This allows the station list to be not so overly wide.

### Actual result

When a new game is started with the AXIS NewGRF, the station list takes up over three-quarters the width of a 1920x1080 display, and that's using OpenGFX with 1x interface scale and English language. Running at 1440p with 2x interface scale, with a font other than the spritefont, or in a language not written with the Latin Alphabet, the same station listing window takes up more than the width of the screen.

### Steps to reproduce

1. Start a new game with the AXIS NewGRF, or any other NewGRF which provides 64 cargoes, each with 4-letter abbreviations (not to be confused with cargo labels). The baseset and many other NewGRFs provide cargoes with 2-letter abbreviations.
2. Open the station listing window.
3. Notice that even with default settings the window takes up a large amount (75 to over 100%) of the width of the display. This is entirely due to the bar with all the cargo abbreviations.

**Comment by James103** [comment]
On further inspection, this appears to be a vanilla issue, as pointed out in https://github.com/OpenTTD/OpenTTD/issues/9933#issuecomment-1793442892.

**Comment by JGRennison** [comment]
This is fixed by https://github.com/OpenTTD/OpenTTD/pull/11552
