### ISSUE TITLE
[Bug]: "Vehicle ageing" listed under real time in "Daylength" article when it is actually in game time.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#540]
### Version of OpenTTD

jgrpp-0.53.3 on Windows 10, 64-bit

### Expected result

"Vehicle aging" is listed in the list of the items that stay the same in calendar time in the ["Daylength" article](https://github.com/JGRennison/OpenTTD-patches/wiki/Day-length), as increasing the day length slows down ageing of vehicles.

### Actual result

"Vehicle ageing" is listed in the list of items that stay the same in real time in the "Daylength" article, even though vehicle aging is tied to calendar time.

Changing this in-game will break games where capital expenses, including the cost of new vehicles, are increased to compensate for day length, as vehicles will need to be replaced relatively more frequently compared to the speed of calendar progress.
Furthermore, changing this in-game will cause lifetime vehicle cost calculations to be off by a factor, part of which is proportional to the day length factor.

### Steps to reproduce

Check the "Daylength" article and notice "Vehicle ageing" is listed in the list of items that stay the same in real time.
Run the game at a high daylength factor, purchase some vehicles and notice they age in sync with the calendar.

**Comment by JGRennison** [comment]
Thanks, I've updated the wiki.
