### ISSUE TITLE
[Crash]: Immediately on opening

### ISSUE THREAD

**Issue by merni-ns** [JGRennison/OpenTTD-patches#542]
### Version of OpenTTD

JGRPP 0.54.0, Windows 11

### Steps to reproduce

Crashed immediately on starting it.

### Upload crash files

No files seem to have been generated.
![image](https://github.com/JGRennison/OpenTTD-patches/assets/66267867/452aa2c9-b8f5-4d7b-a12f-8846c860c747)

**Comment by rosareven** [comment]
Same here. Windows 10 win-64

**Comment by JGRennison** [comment]
This will be fixed in the next release, which will be fairly shortly.
