### ISSUE TITLE
[Crash]: Assertion failed at line 120 of industry_cmd.cpp: thistype < NUM_INDUSTRYTYPES

### ISSUE THREAD

**Issue by AkipTsaqif** [JGRennison/OpenTTD-patches#543]
### Version of OpenTTD

0.54.0

### Steps to reproduce

1. Update the game by replacing old version
2. Direct crash even before the game gets opened

### Upload crash files

There is no crash log produced. What i have is just a screenshot of the crash error:
![ottderr](https://github.com/JGRennison/OpenTTD-patches/assets/40765825/3117bc56-b8cc-4b61-a868-e711b726c57e)

**Comment by AkipTsaqif** [comment]
Here is my industry NewGRFs incase it is caused by NewGRF:

![ottdind](https://github.com/JGRennison/OpenTTD-patches/assets/40765825/d01ceeae-bac0-424d-8c29-49756a05bf90)

**Comment by JGRennison** [comment]
This will be fixed in the next release (cb6f6f94e628c2acc8ed50cd199fec0bbba6e14f), which will be fairly shortly.
