### ISSUE TITLE
Plan tool creating weird effects for other players

### ISSUE THREAD

**Issue by StarRaid** [JGRennison/OpenTTD-patches#55]
I've noticed in multiplayer that randomly the construction tool (railway, station, depot etc.) that I have open will close itself, even when I step away from the keyboard. I found that when someone was to draw a new line on their plans using the plan tool it coincides with this random gui error. This has been an issue I've experienced since I started using JGRPP nearly 2 years ago. Not sure what other information might be helpful (never done an issue report on GitHub before), but if you want anything more on this just ask.

**Comment by JGRennison** [comment]
Thanks for reporting this. Which version are you using?
I've not been able to reproduce anything so far and I haven't found anything that looks wrong in the plans code.
Are there are any other actions that other players were taking that might have occurred at a similar time?
If it happens again, a savegame from shortly afterwards might be helpful.

**Comment by JGRennison** [comment]
This should have been fixed in 0.27.0 by improvements to the plan code.
If you notice the issue again, please feel free to comment or reopen.
