### ISSUE TITLE
[Bug]: No sound with linux-generic-amd64 builds

### ISSUE THREAD

**Issue by tyrone-sudeium** [JGRennison/OpenTTD-patches#552]
### Version of OpenTTD

openttd-jgrpp-0.52.0+. Arch Linux.

### Expected result

When running with `-ddriver=1` in version 0.51.1 or earlier, the sound works, with this printed out:

```
dbg: [driver] Successfully probed sound driver 'sdl'
```

### Actual result

When running with `-ddriver=1` in version 0.52.0 and up (including latest), there is no sound, and it prints this error:

```
dbg: [driver] Probing sound driver 'sdl' failed with error: dsp: No such audio device
```

### Steps to reproduce

Simply run `./openttd -ddriver=1` from `openttd-jgrpp-0.52.0-linux-generic-amd64.tar.xz` (or any version newer) and you'll notice there's no sound, and the above mentioned error message. Note that I've also tried latest upstream `openttd-13.3-linux-generic-amd64` and it does not exhibit this issue, so I imagine there's some issue with your build pipelines (specifically around compiling SDL?), hence opening an issue here instead of upstream :wink:.

I also do not encounter this problem when I compile from source.

**Comment by JGRennison** [comment]
The upstream nightlies don't appear to work either, I will forward this upstream in a bit

**Comment by JGRennison** [comment]
This has been fixed upstream so should be in the next release

**Comment by YellowOnion** [comment]
New to this patch, what sort of time frame is it till next release?

**Comment by JGRennison** [comment]
It's usually between 1 and 4 weeks between releases
