### ISSUE TITLE
[Bug]: Bee Rewards goal destinations in goal list became invisible after update to latest

### ISSUE THREAD

**Issue by matematysek** [JGRennison/OpenTTD-patches#553]
### Version of OpenTTD

0.54.2 WIN 11

### Expected result

Players can see the generated goals so they know what to deliver to industries

### Actual result

Players can see only the money reward, rest (for example "Deliver 12 000 tons of Coal to Flefingbridge Power Plant") is invisible. This happened after a new start after short game time. Before that they were alligned to wrong side.

### Steps to reproduce

[goal_list.zip](https://github.com/JGRennison/OpenTTD-patches/files/11803260/goal_list.zip)
1. Load the save
2. Click on the goal list button
3. See
![McIntosh   Co , 1974-05-05](https://github.com/JGRennison/OpenTTD-patches/assets/107941900/8d3e2fb9-2373-4169-b698-5e15b79d2238)

**Comment by JGRennison** [comment]
This is fixed now, it'll be in the next release.
