### ISSUE TITLE
[Bug]: When taking a screenshot in the map, the screenshot file is saved as only a black screen. 

### ISSUE THREAD

**Issue by laniardic** [JGRennison/OpenTTD-patches#554]
### Version of OpenTTD

0.54.2, Windows 10

### Expected result

When taking a screenshot in the map of world, the screenshot file will display a whole of the map. 

### Actual result

Screenshot file is created normally, but it is saved as only a black screen not the map.
![2023-06-21 224819](https://github.com/JGRennison/OpenTTD-patches/assets/134047245/fdb745fc-cb51-4e13-9388-5e572b8279d6)

### Steps to reproduce

1. Load game or execute scenario editor
2. Click on the "Display map" button of main menu bar
3. Click on the "Map of world"
4. Take a screenshot
5. Check the screenshot file in the OpenTTD folder
![2023-06-21 225049](https://github.com/JGRennison/OpenTTD-patches/assets/134047245/c7aa91d5-6da4-4f67-a2b6-cfdbc7055dd4)

**Comment by JGRennison** [comment]
This is fixed now, it'll be in the next release
