### ISSUE TITLE
[Bug]: Certain vehicles are missing from the buying list with xUSSR NewGRFs

### ISSUE THREAD

**Issue by merni-ns** [JGRennison/OpenTTD-patches#558]
### Version of OpenTTD

JGRPP 0.54.2, Windows 11

### Expected result

All available vehicles being displayed in the purchase list. 
Screenshot from trunk version 13.2.1:
![image](https://github.com/JGRennison/OpenTTD-patches/assets/66267867/e654b810-888e-41aa-a06d-ccc532f3a05b)

### Actual result

Some vehicles are not displayed in the purchase list. 
Screenshot from JGRPP:
![image](https://github.com/JGRennison/OpenTTD-patches/assets/66267867/a24c0224-6301-4c4c-bc76-144f55b70e86)

From [Discord](https://discord.com/channels/142724111502802944/1117438986357571635/1123564664333279262):

> [15:35] Merni:
> It works fine in trunk (13.2.1) though, so maybe a JGRPP related issue
> [16:14] OP Simo333:
> Looks like it. JGR separates locomotives and wagons and since only head cars coded as locomotives now - only they are shown. *MU wagons in other hand doesn't seem to show up as their head category is in locomotive list.

### Steps to reproduce

1. Use the latest version of xUSSR set. Source at https://www.github.com/George-VB/xussrset ; compiled GRFs at https://disk.yandex.ru/d/IbmQKHTDa9dFZQ/main . Start a new game with all those GRFs loaded.
2. Open a vehicle purchase menu after ~1960 and try to purchase any DMU/EMU train with separate motor car and trailing cars.
3. Observe that only the motorised cars are availabe in JGRPP.

**Comment by JGRennison** [comment]
This should be sorted now, it'll be in the next release
