### ISSUE TITLE
[Crash]: Game crashed when clicking train timetable

### ISSUE THREAD

**Issue by jotakob** [JGRennison/OpenTTD-patches#559]
### Version of OpenTTD

JGR 0.54.2

### Steps to reproduce

1. Joined a multiplayer game
2. Clicked on a train (Tokyo Bay Transport, NM 1)
3. Checked its timetable

Tried it a second time, crashed again.
I rejoined the server afterwards and made a save, which is attached

### Upload crash files

[crash-20230630T232822Z.log](https://github.com/JGRennison/OpenTTD-patches/files/11923712/crash-20230630T232822Z.log)
![crash-20230630T232822Z](https://github.com/JGRennison/OpenTTD-patches/assets/10233378/9153e957-19d0-4eaf-9b61-372211c28a39)
[Minatsu & Hamagata Railway, 1900-11-08.zip](https://github.com/JGRennison/OpenTTD-patches/files/11923720/Minatsu.Hamagata.Railway.1900-11-08.zip)

**Comment by JGRennison** [comment]
It seems that the dispatch schedule was removed, but it is still referenced by the first order for some reason.
The arrival/departure time prediction was trying to use the missing dispatch schedule.
If you remove and re-add the first order, it should no longer crash.

**Comment by JGRennison** [comment]
This cause should be resolved now, it'll be in the next release
