### ISSUE TITLE
[Bug]: after updating icu to v73.2-1 the game does not start 

### ISSUE THREAD

**Issue by Amenia1999** [JGRennison/OpenTTD-patches#561]
### Version of OpenTTD

0.54.2-1

### Expected result

The game opens

### Actual result

openttd-jgrpp: error while loading shared libraries: libicui18n.so.72: cannot open shared object file: No such file or directory

### Steps to reproduce

1. use Arch Linux
2. upgrade the whole system
3. try to launch the game

**Comment by Amenia1999** [comment]
Downgrade the icu is not possible, my system wont boot-

**Comment by JGRennison** [comment]
I'd suggest downloading the generic Linux build or compiling it yourself, until the AUR author resolves the issue

**Comment by alfagamma7** [comment]
@Amenia1999 , kindly refer to this comment by the maintainer on AUR : https://aur.archlinux.org/packages/openttd-jgrpp#comment-805684 .
This is a known issue with icu. Remove and rebuild the package again via makepkg or any aur helper you might be using.
