### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kiyokiii** [JGRennison/OpenTTD-patches#563]
### Version of OpenTTD

0.54.2, Arch Linux

### Expected result

Compiling the patch pack

### Actual result

In file included from /home/username/OpenTTD-patches/src/script/api/../../network/core/core.h:15,
                 from /home/username/OpenTTD-patches/src/script/api/../../network/core/packet.h:17,
                 from /home/username/OpenTTD-patches/src/script/api/../../network/core/tcp.h:16,
                 from /home/username/OpenTTD-patches/src/script/api/../../network/core/tcp_coordinator.h:16,
                 from /home/username/OpenTTD-patches/src/script/api/../../network/network_internal.h:14,
                 from /home/username/OpenTTD-patches/src/script/api/../../network/network_admin.h:13,
                 from /home/username/OpenTTD-patches/src/script/api/script_admin.cpp:13:
/home/username/OpenTTD-patches/src/script/api/../../network/core/../../newgrf_config.h:175:26: error: ‘optional’ is not a member of ‘std’
  175 |         std::vector<std::optional<GRFParameterInfo>> param_info; ///< NOSAVE: extra information about the parameters
      |                          ^~~~~~~~
/home/username/OpenTTD-patches/src/script/api/../../network/core/../../newgrf_config.h:20:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
   19 | #include "3rdparty/md5/md5.h"
  +++ |+#include <optional>
   20 | #include <map>
/home/username/OpenTTD-patches/src/script/api/../../network/core/../../newgrf_config.h:175:35: error: template argument 1 is invalid
  175 |         std::vector<std::optional<GRFParameterInfo>> param_info; ///< NOSAVE: extra information about the parameters
      |                                   ^~~~~~~~~~~~~~~~
/home/username/OpenTTD-patches/src/script/api/../../network/core/../../newgrf_config.h:175:35: error: template argument 2 is invalid
/home/username/OpenTTD-patches/src/script/api/../../network/core/../../newgrf_config.h:175:51: error: expected unqualified-id before ‘>’ token
  175 |         std::vector<std::optional<GRFParameterInfo>> param_info; ///< NOSAVE: extra information about the parameters
      |                                                   ^~
make[2]: *** [CMakeFiles/openttd.dir/build.make:104: CMakeFiles/openttd.dir/src/script/api/script_admin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1108: CMakeFiles/openttd.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

### Steps to reproduce

mkdir build
cd build
cmake ..
make

**Comment by JGRennison** [comment]
This should be resolved now

**Comment by Kiyokiii** [comment]
Fixed, thank you!
