### ISSUE TITLE
Installing to Raspberry PI

### ISSUE THREAD

**Issue by Khenyer** [JGRennison/OpenTTD-patches#57]
Hi, i tried to intall the 0.25.1 version, but it isn't worked. I installed like, i did it with the oldest versions, but now, i can't do it.

>[SRC] Compiling saveload/game_sl.cpp
[SRC] Compiling saveload/gamelog_sl.cpp
[SRC] Compiling saveload/goal_sl.cpp
[SRC] Compiling saveload/group_sl.cpp
[SRC] Compiling saveload/industry_sl.cpp
[SRC] Compiling saveload/labelmaps_sl.cpp
[SRC] Compiling saveload/linkgraph_sl.cpp
[SRC] Compiling saveload/map_sl.cpp
In file included from /root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/map_sl.cpp:20:0:
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h: In member function ‘void MemoryDumper::RawWriteUint16(uint16)’:
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:224:29: error: expected ‘;’ before ‘)’ token
   this->buf[0] = GB(v, 8, 8));
                             ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:225:29: error: expected ‘;’ before ‘)’ token
   this->buf[1] = GB(v, 0, 8));
                             ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h: In member function ‘void MemoryDumper::RawWriteUint32(uint32)’:
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:235:30: error: expected ‘;’ before ‘)’ token
   this->buf[0] = GB(v, 24, 8));
                              ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:236:30: error: expected ‘;’ before ‘)’ token
   this->buf[1] = GB(v, 16, 8));
                              ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:237:29: error: expected ‘;’ before ‘)’ token
   this->buf[2] = GB(v, 8, 8));
                             ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:238:29: error: expected ‘;’ before ‘)’ token
   this->buf[3] = GB(v, 0, 8));
                             ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h: In member function ‘void MemoryDumper::RawWriteUint64(uint64)’:
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:248:30: error: expected ‘;’ before ‘)’ token
   this->buf[0] = GB(v, 56, 8));
                              ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:249:30: error: expected ‘;’ before ‘)’ token
   this->buf[1] = GB(v, 48, 8));
                              ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:250:30: error: expected ‘;’ before ‘)’ token
   this->buf[2] = GB(v, 40, 8));
                              ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:251:30: error: expected ‘;’ before ‘)’ token
   this->buf[3] = GB(v, 32, 8));
                              ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:252:30: error: expected ‘;’ before ‘)’ token
   this->buf[4] = GB(v, 24, 8));
                              ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:253:30: error: expected ‘;’ before ‘)’ token
   this->buf[5] = GB(v, 16, 8));
                              ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:254:29: error: expected ‘;’ before ‘)’ token
   this->buf[6] = GB(v, 8, 8));
                             ^
/root/OpenTTD-patches-jgrpp-0.25.1/src/saveload/saveload_buffer.h:255:29: error: expected ‘;’ before ‘)’ token
   this->buf[7] = GB(v, 0, 8));
                             ^
Makefile:231: recipe for target 'saveload/map_sl.o' failed
make[1]: *** [saveload/map_sl.o] Error 1
make[1]: Leaving directory '/root/OpenTTD-patches-jgrpp-0.25.1/objs/release'
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 1
root@raspberrypi: ~/OpenTTD-patches-jgrpp-0.25.1# cd bin
root@raspberrypi: ~/OpenTTD-patches-jgrpp-0.25.1/bin# dir
ai  baseset  data  game  lang  scripts
root@raspberrypi: ~/OpenTTD-patches-jgrpp-0.25.1/bin#

**Comment by JGRennison** [comment]
Looking at it, the code for ARM and similar platforms is wrong. I will push
a fix when I am home tomorrow evening.
