### ISSUE TITLE
[Suggestion] Move list of objects to new category when picker tool is used

### ISSUE THREAD

**Issue by EratoNysiad** [JGRennison/OpenTTD-patches#572]
Currently when you select an object with the picker tool, the menu stays exactly the same, which is fine if you typed something in 
![image](https://github.com/JGRennison/OpenTTD-patches/assets/10280358/c6d38f8c-bd48-49fd-aa4f-efcc5e4dad98)

I would like it if the list of objects would scroll to where the object you've picked is.
![image](https://github.com/JGRennison/OpenTTD-patches/assets/10280358/5b14caae-f4cc-4bbd-a0c7-1e0626acb776)

This makes it easier to then navigate to similar objects, which tend to be in adjacent categories.

Alternatively, make it a separate thing, so you can set it to do this if you hold shift or whatever.

**Comment by JGRennison** [comment]
This will be in the next release
