### ISSUE TITLE
[Bug]: Train Bundled locomotives are transferred to passenger car groups.

### ISSUE THREAD

**Issue by evepoi** [JGRennison/OpenTTD-patches#573]
### Version of OpenTTD

0.54.3, 0.54.4

### Expected result

The content that worked well in the previous version should work well even after updating the game version.

### Actual result

Everything was normal in the 0.54.2 version.
After updating more than 0.54.3 there is an error that the bundled locomotive groups are classified into passenger car groups.
If it's not stuck, the group is loose.

### Steps to reproduce

The train bundle feature has been supported since 0.53.0. The GRF implemented with this feature appears as a passenger car group in versions 0.54.3 and above. Whether it's a locomotive or a carriage..

**Comment by JGRennison** [comment]
This is probably because the GRF incorrectly mixes wagons and locomotives in the same variant group.

See: https://github.com/JGRennison/OpenTTD-patches/issues/558

The dual pane build window can be turned off if they need to be shown together.
