### ISSUE TITLE
[Crash]: picker tool when attempting to pick a bus stop

### ISSUE THREAD

**Issue by JakMel** [JGRennison/OpenTTD-patches#575]
### Version of OpenTTD

jgrpp 0.54.4 - Win64

### Steps to reproduce

1. Build a bus/lorry station.
2. Click on it with a picker tool.

### Upload crash files

[crash_picker-tool-on-bus-stop.zip](https://github.com/JGRennison/OpenTTD-patches/files/12103039/crash_picker-tool-on-bus-stop.zip)

**Comment by JGRennison** [comment]
This will be fixed in the next release
