### ISSUE TITLE
[Crash]: Trams available in roadtype depot (may be issue with NewGRFs and not the game?)

### ISSUE THREAD

**Issue by Gadg8eer** [JGRennison/OpenTTD-patches#578]
### Version of OpenTTD

jgrpp-0.54.4

### Steps to reproduce

0. Start new game
1. Build a depot of the "SmartStreet" or "SmartRoad" type.
2. Click to build vehicles
3. Several trams are inexplicably showing up in a roadtype depot
4. (Optional) Try to build a tram in the roadtype depot to trigger crash conditions

### Upload crash files

[crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/12155682/crash.zip)

https://perma.cc/8MXM-5QPR (NewGRFs used, overwrite two of them with the ones in the zip file below to test the newer version in a fresh game save)

[overwrite_the_older_grf_versions_with_this.zip](https://github.com/JGRennison/OpenTTD-patches/files/12158028/overwrite_the_older_grf_versions_with_this.zip)

**Comment by JGRennison** [comment]
This should be fixed in the most recent release
