### ISSUE TITLE
Languages are broken

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#58]
![image](https://user-images.githubusercontent.com/10726524/41204740-81727d00-6d23-11e8-8833-3606f9a2ce4c.png)

 * 0.25.1

It was not my issue, I'm just delivering this issue instead.
Languages are broken as you can see above for some users. (it's fine for me, though)

I was thought it would occur by my language or font setting(korean), but english is also broken.
The screenshot above is english.

When I zip my OpenTTD(JGRPP) directory (which works very fine for me) and send it to him who experiences this issue as it is, then he experiences this issue.

I have also no idea what this issue is occured from where.
If you have any idea where this issue is concerned, please tell me then I will tell him again.

**Comment by JGRennison** [comment]
As these users running on Windows, and if so, which version?
I notice that trunk has recently made some changes to font rendering (switching from ICU to Uniscribe) on windows, and these changes were merged into 0.25.1

**Comment by telk5093** [comment]
They arre using Windows 10, 64bit, RS4

**Comment by JGRennison** [comment]
Do they have particular fonts set in their openttd.cfg config file?
It may be worth removing and/or changing those and seeing if the problem persists.

**Comment by telk5093** [comment]
I think some users are still experiencing this issue.
In my case, I configure the font settings to represent korean font, and most korean users too.
(And it is quite impossible to run openttd game itself unless set the fonts in openttd.cfg)

**Comment by JGRennison** [comment]
Would you be able to attach a configuration file which reproduces the issue?
Does this also occur with recent trunk?
