### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by kimjostars** [JGRennison/OpenTTD-patches#581]
### Version of OpenTTD

JGRPP 0.54.4/Win10

### Steps to reproduce

save run

### Upload crash files

[crash-20230731T050609Z.log](https://github.com/JGRennison/OpenTTD-patches/files/12211746/crash-20230731T050609Z.log)
[crash-20230731T051821Z.log](https://github.com/JGRennison/OpenTTD-patches/files/12211747/crash-20230731T051821Z.log)
[crash-20230731T052017Z.log](https://github.com/JGRennison/OpenTTD-patches/files/12211752/crash-20230731T052017Z.log)
[crash-20230731T052158Z.log](https://github.com/JGRennison/OpenTTD-patches/files/12211753/crash-20230731T052158Z.log)
[crash-20230731T052429Z.log](https://github.com/JGRennison/OpenTTD-patches/files/12211754/crash-20230731T052429Z.log)

**Comment by JGRennison** [comment]
This looks to be the same as #580.
Have you been using the date cheat?

**Comment by kimjostars** [comment]
yes i used cheats.(It may be unnatural because I used a translator.)
