### ISSUE TITLE
[Bug]: [Scenario editor] "Many random towns" does not check for duplicate town names

### ISSUE THREAD

**Issue by wpi3** [JGRennison/OpenTTD-patches#583]
### Version of OpenTTD

0.54.4

### Expected result

An error message should appear when there are insufficient/identical town names, similar to the other generate town buttons.

### Actual result

Towns with duplicate town names are generated.

### Steps to reproduce

1. Open scenario editor
2. Click "many random towns" in the town generation menu (do so for multiple times if the GRF supplies large amount of town names)
3. Save the scenario and play it. Open the town list and sort by name. There should be town names that are duplicates of each other.

**Comment by JGRennison** [comment]
I've forwarded this upstream as https://github.com/OpenTTD/OpenTTD/issues/11164

**Comment by JGRennison** [comment]
Fixed in the most recent release
