### ISSUE TITLE
[Suggestion]: Changing the Cargo payment system

### ISSUE THREAD

**Issue by wnsgk0710** [JGRennison/OpenTTD-patches#585]
When I play multiplayer games with “Cargo Distribution” and “Infrastructure Sharing” settings on, I think the current cargo payment system makes it hard to make profit.
As you know, when using CargoDist, the final vehicle on the route receives adjusted cost.
It is okay without IS, but if setting this option on, there is a problem.

For example, Company A have made Line X, which is high speed line within City 1 and City 2. And Company B have made Line Y, which is commuter line connects cities near by the terminal station(City 2) of Line X.

Although the operator is different, the current system does not distinguish companies, just calculates fees at once. As a result, Company A gets huge amount of profit but Company B goes into the red.

When the total transportation system gets more complex and each line is become connected each other, almost every companies make a loss.

So, I suggest to separate each company at calculating cargo payment.
For example, Let‘s say there are some passengers traveling from City 1 to the City at the line Y.
Then after using Line X and getting of at City 2, Company A receives the fee only for Line X. And Company B also receives there own fee only for Line Y.

If changed like this, It can prevent to make a loss when the lines of different companies are connected each other, I think.

**Comment by JGRennison** [comment]
This issue was fixed more than five years ago: 9000d74f3c80edb9d325bb6980f9391b14c9ab93
Total income is suitably distributed between the various companies involved.
