### ISSUE TITLE
[Bug]: Compilation Error

### ISSUE THREAD

**Issue by Kiyokiii** [JGRennison/OpenTTD-patches#586]
### Version of OpenTTD

jgrpp-0.54.5-11-g3ec633e63

### Expected result

building successfully

### Actual result

`In file included from /home/username/OpenTTD-patches/src/script/api/../../command_aux.h:14,`
`                 from /home/username/OpenTTD-patches/src/script/api/../../league_cmd.h:13,`
`                 from /home/username/OpenTTD-patches/src/script/api/script_league.cpp:17:`
`/home/username/OpenTTD-patches/src/script/api/../../command_func.h:86:54: error: ‘std::function’ has not been declared`
`   86 | char *DumpCommandLog(char *buffer, const char *last, std::function<char *(char *)> flush);`
`      |                                                      ^~~`
`/home/username/OpenTTD-patches/src/script/api/../../command_func.h:86:67: error: expected ‘,’ or ‘...’ before ‘<’ token`
`   86 | char *DumpCommandLog(char *buffer, const char *last, std::function<char *(char *)> flush);`
`      |                                                                   ^`
`make[2]: *** [CMakeFiles/openttd.dir/build.make:580: CMakeFiles/openttd.dir/src/script/api/script_league.cpp.o] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:1108: CMakeFiles/openttd.dir/all] Error 2`
`make: *** [Makefile:166: all] Error 2`

### Steps to reproduce

`mkdir build`
`cd build`
`cmake ..`
`make`

**Comment by James103** [comment]
What OS are you trying to compile on?

**Comment by Kiyokiii** [comment]
Arch Linux

**Comment by JGRennison** [comment]
Can you try it again now

**Comment by Kiyokiii** [comment]
seems to be fixed now, thank you
