### ISSUE TITLE
[Bug]: View change

### ISSUE THREAD

**Issue by alex256z** [JGRennison/OpenTTD-patches#597]
### Version of OpenTTD

jgrpp-0.55.2 on Windows 10, 64-bit

### Expected result

Pressing "Center the main view on location" should change view on that location permanently, but..

### Actual result

..moving mouse with RMB pressed teleports view to previous camera position.

Same problem with any buttons, that centers view on something

### Steps to reproduce

1. Create new game
2. Select city/industry/station
3. Press "Center the main view on city/industry/station location"
4. Press RMB and move mouse

**Comment by JGRennison** [comment]
This is fixed in the most recent release
