### ISSUE TITLE
[Crash]: "NOT_REACHED triggered at line 267 of /src/gfx_layout.cpp"

### ISSUE THREAD

**Issue by wpi3** [JGRennison/OpenTTD-patches#598]
### Version of OpenTTD

0.55.3, Mac OS 11.7 Big Sur

### Steps to reproduce

1. Use the font "Pingfang TC" in openttd.cfg (or other "high-res" CJK fonts such as "Hiragino Sans").
2. Open a savegame, then open a text edit box (e.g. rename town, rename group).
3. Switch to the "Cangjie - Traditional" input method editor.
4. Type a capital letter so that the IME recognises the input as not intended for the normal IME input but for English alphabet. The IME input box should appear on the screen.
5. Type the sequence `ff` or `fi`. The game crashes when the second character is typed with the message "NOT_REACHED triggered at line 267 of /src/gfx_layout.cpp".

Presumably the crash is due to the IME precomposing a ligature character for ff or fi (or perhaps other ligatures as well), which is then read into the text field, but the game fails to process said ligature character.

Note: Vanilla OpenTTD 13.4 does not crash when the same above steps are replicated.

### Upload crash files

[crash-20230925T154703Z.log](https://github.com/JGRennison/OpenTTD-patches/files/12717296/crash-20230925T154703Z.log)

**Comment by JGRennison** [comment]
This seems similar to #596, https://github.com/OpenTTD/OpenTTD/issues/11291 and various other upstream issues.

I have no way of verifying/testing this on macos but will look into it.

**Comment by JGRennison** [comment]
Should be fixed in the most recent release
