### ISSUE TITLE
Crash in wine

### ISSUE THREAD

**Issue by ecolortest** [JGRennison/OpenTTD-patches#60]
*** OpenTTD Crash Report ***

Crash at: Sat Jun 23 10:24:45 2018
In game date: 0-01-01 (0, 0)

Crash reason:
 Exception: C0000005
 Location:  0063ACFF
 Message:   <none>

OpenTTD version:
 Version:    jgrpp-0.23.0 (0)
 NewGRF ver: 18006d40
 Bits:       32
 Endian:     little
 Dedicated:  no
 Build date: Feb 10 2018 11:26:59
 Configure:  ./configure --host=i686-w64-mingw32 --prefix=/home/jgr/mingw32/ CFLAGS=-I/home/jgr/mingw32/include -D__MINGW64__ LDFLAGS=-L/home/jgr/mingw32/lib --without-sdl --without-icu --with-lzo2=/home/jgr/mingw32/lib/liblzo2.a

Stack trace:
 0020A4F0 00000000 00000000 02D1CEFC 02D1CE90 00000000 02D1CEA0 02D1CF8C
 02D1CFC0 00207D18 02D1CF68 00817944 004DD46A 02D1CE20 00207D18 00132B80
 0000000C 00000000 00000000 004B6EAD 00000000 00000002 00000000 004DCB2B
 00000001 00207D18 00207CC8 004DBA63 4000004D 00000002 02D1CF38 40930DFB
 00110060 00110000 00000010 0020A4C4 02D1CFC0 00000000 00000000 00000000
 0000000C 00000000 4000004D 00132B80 00000017 00000015 00000002 00000000
 0000E602 00000000 00207D18 0000000C 00000002 00000000 00000001 00000000
 00000000 0000000A 00000000 037F0C7F 02D1D000 00000021 000000FF 02D1D8B4
 00000000 00000821 000000FF 004DBF3C 0000000B 00000001 00000000 00000001
 00000000 00000001 00207D18 02D1DB1C 00000001 00000000 00000050 00000000
 02D1D000 00A5BB80 00B0DDDC 02D1CFD0 004DBF45 02D1CF70 01838FC0 02D1D7FF
 002082D8 00000001 00000004 02D1D000 00000000 02D1D000 000000FF 004DBFF2
 00000002 00000015 00000002 02D1D000 00000000 00000001 00000000 00000000
 4D8C81EE 69737369 6720676E 68706172 00736369 00000000 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 00000000 42C7A2A4 00000000 00000000 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000

Registers:
 EAX: 00000000 EBX: 00000002 ECX: 00000000 EDX: 00000002
 ESI: 0000387C EDI: 000002D3 EBP: 00000000 ESP: 02D1CE60
 EIP: 0063ACFF EFLAGS: 00010202

 Bytes at instruction pointer:
 0F B6 46 10 39 C3 75 64 85 ED 0F 84 31 01 00 00 89 6C 24 50 83 C4 3C 89

Operating system:
 Name:     Windows
 Release:  5.1.2600 (Service Pack 3)
 Compiler: GCC 5.3.1 "5.3.1 20160211"

Configuration:
 Blitter:      32bpp-anim
 Graphics set: none (4294967295)
 Language:     Z:\Users\okansp\Downloads\openttd-custom-jgrpp-0.23.0-MINGW-win32\lang\english_US.lng
 Music driver: none
 Music set:    none (4294967295)
 Network:      no
 Sound driver: none
 Sound set:    none (4294967295)
 Video driver: win32

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 0):

Libraries:
 FreeType:   2.6.0
 LZMA:       5.2.1
 LZO:        2.09
 PNG:        1.5.23
 Zlib:       1.2.8

Module information:
 Z:\Users\okansp\Downloads\openttd-custom-jgrpp-0.23.0-MINGW-win32\openttd.exe handle: 00400000 size: 32002342 crc: CA7C725A date: 2018-02-10 02:28:20
 C:\windows\system32\ntdll.dll handle: 40900000 size: 2468 crc: FB718EBA date: 2018-04-28 23:35:38
 C:\windows\system32\KERNEL32.dll handle: 7b810000 size: 1677836 crc: 5C7A04F3 date: 2018-04-28 23:35:32
 C:\windows\system32\advapi32.dll handle: 427f0000 size: 2488 crc: 72E51CA9 date: 2018-04-28 23:35:36
 C:\windows\system32\gdi32.dll handle: 428f0000 size: 16152 crc: 661CC3ED date: 2018-04-28 23:35:34
 C:\windows\system32\imm32.dll handle: 42bb0000 size: 2468 crc: BE40FCE4 date: 2018-04-28 23:35:33
 C:\windows\system32\user32.dll handle: 42bf0000 size: 227780 crc: 941BABED date: 2018-04-28 23:35:35
 C:\windows\system32\version.dll handle: 42fe0000 size: 2484 crc: 9EE4EBDF date: 2018-04-28 23:35:34
 C:\windows\system32\msvcrt.dll handle: 43000000 size: 2456 crc: C4AE7B9B date: 2018-04-28 23:35:38
 C:\windows\system32\shell32.dll handle: 43170000 size: 1416672 crc: 984DAC8F date: 2018-04-28 23:35:36
 C:\windows\system32\shlwapi.dll handle: 43550000 size: 19932 crc: 83F20744 date: 2018-04-28 23:35:35
 C:\windows\system32\comctl32.dll handle: 43650000 size: 178076 crc: 4455CF90 date: 2018-04-28 23:35:34
 C:\windows\system32\winmm.dll handle: 43880000 size: 475744 crc: ECB2054F date: 2018-04-28 23:35:32
 C:\windows\system32\ole32.dll handle: 43990000 size: 19576 crc: FFCF05CB date: 2018-04-28 23:35:37
 C:\windows\system32\rpcrt4.dll handle: 43d00000 size: 2472 crc: 6810D2D7 date: 2018-04-28 23:35:36
 C:\windows\system32\msacm32.dll handle: 43e50000 size: 22744 crc: 56ED9DAA date: 2018-04-28 23:35:34
 C:\windows\system32\ws2_32.dll handle: 43e90000 size: 2476 crc: 1318FF5D date: 2018-04-28 23:35:35
 C:\windows\system32\winemac.drv handle: 44120000 size: 1032 crc: 2FE56CE0 date: 2018-04-28 23:35:37
 C:\windows\system32\uxtheme.dll handle: 44390000 size: 2448 crc: 9443403E date: 2018-04-28 23:35:38
 C:\windows\system32\iphlpapi.dll handle: 45830000 size: 2480 crc: A6A82B86 date: 2018-04-28 23:35:33
 C:\windows\system32\psapi.dll handle: 457b0000 size: 2500 crc: AA22BDD2 date: 2018-04-28 23:35:37

---- gamelog start ----
---- gamelog end ----

Command Log:
 Showing most recent 0 of 0 commands

*** End of OpenTTD Crash Report ***

Decoded stack trace:

*** End of additional info ***

Device: MacBook Pro 13-inch early 2011
Processor: 2.3 Ghz Intel core i5
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 3000 512 MB
Storage: 525 GB SSD Sata Drive

**Comment by JGRennison** [comment]
There have been several bugs which can cause crashes which have been fixed since 0.23.0, it may be worth trying again with a newer version.
If the issue persists some more information on what occurred before the crash, or a savegame which shows the issue, would be useful.

**Comment by ecolortest** [comment]
it crash will do startup

**Comment by ecolortest** [comment]
i has download new version but its crash again:

*** OpenTTD Crash Report ***

Crash at: Sun Jun 24 12:11:36 2018
In game date: 0-01-00 (0, 0)

Crash reason:
 Exception: C0000005
 Location:  0064055F
 Message:   <none>

OpenTTD version:
 Version:    jgrpp-0.25.2 (0)
 NewGRF ver: 19000000
 Bits:       32
 Endian:     little
 Dedicated:  no
 Build date: Jun 13 2018 02:14:01
 Configure:  ./configure --host=i686-w64-mingw32 --prefix=/home/jgr/mingw32/ CFLAGS=-I/home/jgr/mingw32/include -D__MINGW64__ LDFLAGS=-L/home/jgr/mingw32/lib --without-sdl --without-icu --with-lzo2=/home/jgr/mingw32/lib/liblzo2.a

Stack trace:
 00000005 02D8CF8C 02D8CF68 00208448 00208448 00000000 00208448 004DF701
 02D8CEBC 00000010 02D8CF20 408D6A81 00110000 00000002 0020ECA0 00132C58
 0000000C 00000000 00000000 004B772D 00000000 00000002 00000000 004DD81B
 00000001 00208448 0020ECA8 004DC753 4000004D 00A70DD0 00B23854 02D8CF50
 004DFE04 02D8CE80 00000000 0020ECA0 0020ECA8 0000082D 00000000 00000000
 0000000C 00000000 4000004D 00132C58 00000017 00000015 00000002 00000000
 00000000 00000000 00208448 0000000C 00000002 00000000 00000001 00000000
 00000000 0000000A 00000000 037F0C7F 02D8D000 0000002D 000000FF 02D8D8B4
 00000000 0000082D 000000FF 004DCC2C 0000000B 00000001 00000000 00000001
 00000000 00000001 00208448 02D8DB1C 00000001 00000000 00000050 00000000
 02D8D000 00A70DD0 00B237E4 02D8CFD0 004DCC35 02D8CF70 018500A0 02D8D7FF
 00208498 00000001 00000004 02D8D000 00000000 02D8D000 000000FF 004DCCE2
 00000002 00000015 00000002 02D8D000 00000000 00000001 00000000 00000000
 4D8E81EE 69737369 6720676E 68706172 00736369 00000084 00000000 00D201B2
 00000000 00000000 42B9DA29 42C1F58B 42C89754 42BD3987 02D8D3A8 42BD39A6
 00000000 42C204A4 A73C5846 409014C9 00000005 02D8D120 00000040 00010078
 00010078 00010078 A73C3F12 A757BF3E 00000003 02D8D0DC 00000000 42C0F067
 02D8D120 02D8D0DC 02D8D0F8 42C30CD4 42C918B0 00010078 02D8D0C8 42C303DA
 00010078 00000084 00000000 00D201B2 42C89754 00000001 42B9DA29 00000000
 42C918B0 00010078 02D8D108 42C30D1E 006D21B0 00010078 00000084 00000000
 00D201B2 7FFC0000 42B9DC99 42C212A4 42C89754 00000001 42B9DC99 42C336B4
 FFFF0025 7FFC0044 02D8D158 42C337D1 00010078 00000084 00000000 00D201B2
 02D8D1AC 006D21B0 42B9DA29 42C1F58B 42C89754 000000D2 000001B2 42C899C8
 00000000 42C204A4 02D8D168 00000084 00010078 00000000 02D8D1C8 42BF3A7E

Registers:
 EAX: 00000000 EBX: 00000002 ECX: 00000000 EDX: 00000002
 ESI: 0000387C EDI: 000002D3 EBP: 00000000 ESP: 02D8CE60
 EIP: 0064055F EFLAGS: 00010202

 Bytes at instruction pointer:
 0F B6 46 10 39 C3 75 64 85 ED 0F 84 31 01 00 00 89 6C 24 50 83 C4 3C 89

Operating system:
 Name:     Windows
 Release:  5.1.2600 (Service Pack 3)
 Compiler: GCC 5.3.1 "5.3.1 20160211"

Configuration:
 Blitter:      32bpp-anim
 Graphics set: none (4294967295)
 Language:     Z:\Users\okansp\Downloads\openttd-custom-jgrpp-0.25.2-MINGW-win32\lang\english_US.lng
 Music driver: none
 Music set:    none (4294967295)
 Network:      no
 Sound driver: none
 Sound set:    none (4294967295)
 Video driver: win32

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 0):

Libraries:
 FreeType:   2.6.0
 LZMA:       5.2.1
 LZO:        2.09
 PNG:        1.5.23
 Zlib:       1.2.8

Module information:
 Z:\Users\okansp\Downloads\openttd-custom-jgrpp-0.25.2-MINGW-win32\openttd.exe handle: 00400000 size: 32521213 crc: 596EB4B4 date: 2018-06-12 17:15:00
 C:\windows\system32\ntdll.dll handle: 408a0000 size: 2468 crc: FB718EBA date: 2018-04-28 23:35:38
 C:\windows\system32\KERNEL32.dll handle: 7b810000 size: 1677836 crc: 5C7A04F3 date: 2018-04-28 23:35:32
 C:\windows\system32\advapi32.dll handle: 427a0000 size: 2488 crc: 72E51CA9 date: 2018-04-28 23:35:36
 C:\windows\system32\gdi32.dll handle: 42890000 size: 16152 crc: 661CC3ED date: 2018-04-28 23:35:34
 C:\windows\system32\imm32.dll handle: 42b60000 size: 2468 crc: BE40FCE4 date: 2018-04-28 23:35:33
 C:\windows\system32\user32.dll handle: 42b90000 size: 227780 crc: 941BABED date: 2018-04-28 23:35:35
 C:\windows\system32\version.dll handle: 42f80000 size: 2484 crc: 9EE4EBDF date: 2018-04-28 23:35:34
 C:\windows\system32\msvcrt.dll handle: 42fa0000 size: 2456 crc: C4AE7B9B date: 2018-04-28 23:35:38
 C:\windows\system32\shell32.dll handle: 43110000 size: 1416672 crc: 984DAC8F date: 2018-04-28 23:35:36
 C:\windows\system32\shlwapi.dll handle: 434f0000 size: 19932 crc: 83F20744 date: 2018-04-28 23:35:35
 C:\windows\system32\comctl32.dll handle: 435f0000 size: 178076 crc: 4455CF90 date: 2018-04-28 23:35:34
 C:\windows\system32\winmm.dll handle: 43830000 size: 475744 crc: ECB2054F date: 2018-04-28 23:35:32
 C:\windows\system32\ole32.dll handle: 43930000 size: 19576 crc: FFCF05CB date: 2018-04-28 23:35:37
 C:\windows\system32\rpcrt4.dll handle: 43cb0000 size: 2472 crc: 6810D2D7 date: 2018-04-28 23:35:36
 C:\windows\system32\msacm32.dll handle: 43df0000 size: 22744 crc: 56ED9DAA date: 2018-04-28 23:35:34
 C:\windows\system32\ws2_32.dll handle: 43e40000 size: 2476 crc: 1318FF5D date: 2018-04-28 23:35:35
 C:\windows\system32\winemac.drv handle: 440d0000 size: 1032 crc: 2FE56CE0 date: 2018-04-28 23:35:37
 C:\windows\system32\uxtheme.dll handle: 44530000 size: 2448 crc: 9443403E date: 2018-04-28 23:35:38
 C:\windows\system32\iphlpapi.dll handle: 47300000 size: 2480 crc: A6A82B86 date: 2018-04-28 23:35:33
 C:\windows\system32\psapi.dll handle: 45490000 size: 2500 crc: AA22BDD2 date: 2018-04-28 23:35:37

---- gamelog start ----
---- gamelog end ----

Recent news messages:

Command Log:
 Showing most recent 0 of 0 commands

*** End of OpenTTD Crash Report ***

Decoded stack trace:

*** End of additional info ***

**Comment by ecolortest** [comment]
the game only create crash.log only

**Comment by ecolortest** [comment]
Fixed: the probem because this: https://wiki.openttd.org/Cross-compiling_for_Windows#OpenTTD_crashes_on_startup_on_WINE 

after do that the openttd can run it

**Comment by auge8472** [comment]
One question. Why one wants to run the game with Wine instead of running it in the OS itself?

**Comment by ecolortest** [comment]
> One question. Why one wants to run the game with Wine instead of running it in the OS itself?

Because i cant compile openttd, its always fail if compile it, so im running at wine
