### ISSUE TITLE
[Crash]: Crash (client only) after hitting "home" or "end" in chat

### ISSUE THREAD

**Issue by longtomjr** [JGRennison/OpenTTD-patches#600]
### Version of OpenTTD

JGR 0.55.3

### Steps to reproduce

I cannot reproduce the issue on my side - but this is what I recall from when it crashed

1. I was typing up a message, and hit arrow keys to scroll between the characters in chat.
2. I hit "home" or "end" (i might have missed the button and pressed both, not 100% sure)
3. Game crashed

### Upload crash files

[crashreport.zip](https://github.com/JGRennison/OpenTTD-patches/files/12774718/crashreport.zip)

(I don't have a dmp file, or I am not looking in the right place.)

**Comment by JGRennison** [comment]
This is the same general issue as #596, #598.
This should hopefully be already fixed for the next release.

**Comment by JGRennison** [comment]
Should be fixed in the most recent release
