### ISSUE TITLE
Crash on “Cancel Servicing/Send …”

### ISSUE THREAD

**Issue by khavik** [JGRennison/OpenTTD-patches#61]
Reproducible by choosing “Cancel Servicing/Send …” (ADI_CANCEL_DEPOT) in the dropdown menu of a shared orders window. The relevant code in vehicle_gui.cpp appears not to contain instructions to handle said case.

[crash_cancelservicing.zip](https://github.com/JGRennison/OpenTTD-patches/files/2156955/crash_cancelservicing.zip)

Currently on 0.25.2-43-g79ca5c8b7. (Compiled with clang-6.0.0 on MacOS 10.13.5, but I would assume that this bug is present on any OS.)

**Comment by JGRennison** [comment]
Thanks, the fix for this will be in the next release.
