### ISSUE TITLE
[Bug]: Jammed trains due to train speed adaptation

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#613]
### Version of OpenTTD

jgrpp-0.55.3

### Expected result

No traffic jams for trains behind proceeding one.

### Actual result

Trains behind the first train are jammed when:
1. ``train_speed_adaptation`` is ``on``
2. There were lots of stopped trains and the first train just is started to go.
3. The first train move forward fastly, while the proceedings are jammed due to the slow speed until pass 1~2 signals.

### Steps to reproduce

**GIF:**
![image](https://cdn.discordapp.com/attachments/919788785217179738/1177198667887804456/1.gif)

**Savefile:**
https://cdn.discordapp.com/attachments/919788785217179738/1177198668265308180/bug.sav?ex=6571a2b1&is=655f2db1&hm=33fd771648383b6fcfb88bad6311a88dd5420a9b7b93c7b534254a017b9a7163&
(Note that this map's size is 4096x8192)

Take a look the blue trains of the company #11 around ``2451, 5326``

(Just for note:) JGR said in Discord:
> I'm not that original author of it, and don't use it myself, but it presumably works nicely with particular playing styles

**Comment by JGRennison** [comment]
This should be somewhat improved in the next release.

In the case of this save the uneven signal spacing does not help though. e.g. where Company 11, Train 42 is.

**Comment by telk5093** [comment]
> uneven signal spacing does not help though.

I also commented the exact saying to the owner of the company #11.
And sounds nice that improvements! 👍

**Comment by JGRennison** [comment]
This should be better in the most recent release, fee free to re-open if not
