### ISSUE TITLE
[Problem] Broken savegame

### ISSUE THREAD

**Issue by kedzior3** [JGRennison/OpenTTD-patches#614]
### Version of OpenTTD

jgrpp-0.56.0 and 0.55.3, Windows 10

### Expected result

Hello,
I'm angry with my map I'm create for nearly 2 years, but now it's broken, because in OpenTTD jgrpp-0.54.3 and the new 0.56 there is a bug, and every backup savegame from my game are NOT WORKING NOW!

I need work on this map, but I even know which town are broken, because there is no programs to correct, or delete broken cities to rescue my savegame.

### Actual result

![obraz_2023-11-28_220639183](https://github.com/JGRennison/OpenTTD-patches/assets/82472233/0feb6654-6f67-445a-8f4c-e67c4e4a0567)

### Steps to reproduce

[PL2048x2048_PK_2023_11_21__01-50_openttd_jgrpp-055-3.zip](https://github.com/JGRennison/OpenTTD-patches/files/13493147/PL2048x2048_PK_2023_11_21__01-50_openttd_jgrpp-055-3.zip)

**Comment by JGRennison** [comment]
See also: https://github.com/OpenTTD/OpenTTD/pull/11513
