### ISSUE TITLE
[Bug]: ctrl+RMB on a train with multiple cargo types displays only one 

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [JGRennison/OpenTTD-patches#616]
### Version of OpenTTD

jgrpp-0.56.0

### Expected result

Ctrl+rmb works the same as in the vanilla game - displays the capacity for each type of cargo.
![изображение](https://github.com/JGRennison/OpenTTD-patches/assets/115672237/2c5cd735-c9f5-4863-9a63-8eb5b5b668b1)

### Actual result

ctrl+rmb displays the correct number of vehicles, but only one cargo – the last by the filter list. 
![изображение](https://github.com/JGRennison/OpenTTD-patches/assets/115672237/63d1e0cc-05b1-454d-b702-d3819ec35286)
Different cargo is displayed in different languages.
![изображение](https://github.com/JGRennison/OpenTTD-patches/assets/115672237/bd8f96e1-f87f-418b-88e3-1285937516a3)

### Steps to reproduce

1. Build a train with several types of wagons
2. Ctrl + right mouse button on the first wagon

**Comment by JGRennison** [comment]
Thanks, this should be fixed in the next release
