### ISSUE TITLE
[Crash]: v0.56.0 crashes on almalinux 8

### ISSUE THREAD

**Issue by Penta0308** [JGRennison/OpenTTD-patches#617]
### Version of OpenTTD

v0.56.0, Almalinux 8.9

### Steps to reproduce

Downloaded linux tar and ran `./openttd -D` and immediately crashed.

Built from code and did the same thing, got the same thing.

### Upload crash files

Crash files are from downloaded executables.

[crash-20231208T151657Z.log](https://github.com/JGRennison/OpenTTD-patches/files/13616377/crash-20231208T151657Z.log)

**Comment by JGRennison** [comment]
Thanks for reporting this.
This bug has been fixed (291daa92204889b2f5115c8df2524ec805f0fd0d) it'll be in the next release.
It's a bug when the configuration file isn't already fully populated.
