### ISSUE TITLE
[Bug]: Wrong displaying of station sprites in JGRPP 0.56.1

### ISSUE THREAD

**Issue by auge8472** [JGRennison/OpenTTD-patches#618]
### Version of OpenTTD

JGRPP 0.56.1, Ubuntu 22.04, Linux generic build

### Expected result

Normal displaying of station sprites. See the following screenshots taken in JGRPP 0.56.0.

![NewStations station hall in JGRPP 0.56.0](https://github.com/JGRennison/OpenTTD-patches/assets/1734660/a7d63b57-7e48-4763-ad40-563b861caabe)

![NewStations station building in JGRPP 0.56.0](https://github.com/JGRennison/OpenTTD-patches/assets/1734660/ce296afa-17d0-456e-8703-7a5822276108)

### Actual result

Station sprites get partially displayed in wrong order. See the following screenshots taken in JGRPP 0.56.1. These are the same stations as in the previous screenshots. In the second screenshot I experimented a bit. The right building is a separate building of the same station, the doubled left building is the building, broken by the game version itself.

![NewStations station building in JGRPP 0.56.1](https://github.com/JGRennison/OpenTTD-patches/assets/1734660/2d7fb113-c66a-416d-bd77-899d1d8b5cab)

![NewStations station hall in JGRPP 0.56.1](https://github.com/JGRennison/OpenTTD-patches/assets/1734660/c69985c0-78a4-4910-9398-83085f703a86)

### Steps to reproduce

You'll need the following NewGRFs:

- NewStations v0.6 14.08.2014
- SwissTownNames r13 (available in BaNaNaS)

Load the following savegame in the ZIP file: [St. Gallen Testgame, 23 Apr 1950.sav](https://github.com/JGRennison/OpenTTD-patches/files/13695926/St.Gallen.Testgame.23.Apr.1950.zip)

**[edit]:** The provided savegame is reduced to the affected station NewGRF (where I saw the issue) and especially made for testing the issue. The screenshots above was taken in another game.

**Comment by JGRennison** [comment]
Thanks, this will be fixed in the next release.

You can type `set_newgrf_optimiser_flags 1` in the console in the meantime to make this go away.

**Comment by auge8472** [comment]
> Thanks, this will be fixed in the next release.

Thank you.

> You can type `set_newgrf_optimiser_flags 1` in the console in the meantime to make this go away.

Yes, this made it. 😀👍

**Comment by auge8472** [comment]
As this issue is solved, I'll close it.
