### ISSUE TITLE
[Bug]: Signal is open despite slot being taken

### ISSUE THREAD

**Issue by vtual** [JGRennison/OpenTTD-patches#620]
### Version of OpenTTD

0.56.1 Windows 10

### Expected result

Train should be stopped at signal with "acquire restriction or wait at signal" restriction when the slot is taken.

### Actual result

Instead the signal is open

### Steps to reproduce

Load the save game : [JTCo, 15 Oct 1903 bug.zip](https://github.com/JGRennison/OpenTTD-patches/files/13797585/JTCo.15.Oct.1903.bug.zip)
One train is coming from the south west and should be stopped as the slot is already taken, but instead the signal is open.

By the way Japanese trains should run on the left but got confused hehe.
Thanks for the patch pack and happy new year! :)

**Comment by JGRennison** [comment]
The signal has ended up being marked as unconditionally reserve-through.
This is probably because it was in a previous signal program, but the flag was incorrectly not removed.
As a temporary fix you can add and then remove a reserve through action to the end of the program.

**Comment by vtual** [comment]
Thanks, it works now!
