### ISSUE TITLE
[Bug] Font rendering is ugly on Linux

### ISSUE THREAD

**Issue by man-of-eel** [JGRennison/OpenTTD-patches#622]
I like to use OpenTTD with these settings:
```
small_font = Tahoma
medium_font = Tahoma, Bold
large_font = Times New Roman
mono_font = 
small_size = 0
medium_size = 0
large_size = 0
mono_size = 0
small_aa = false
medium_aa = false
large_aa = false
mono_aa = false
```

On upstream it looks nice, but on JGRPP the letter spacing is all messed up and it's annoying to read.
| Upstream | JGRPP |
|---|---|
| ![image](https://github.com/JGRennison/OpenTTD-patches/assets/86927456/b5005f48-b3a9-4ed9-af3e-90dd15427fc1) | ![image](https://github.com/JGRennison/OpenTTD-patches/assets/86927456/a4539292-3893-4d59-99fb-7023bd5633fa) |

I'm playing on Arch Linux and for upstream I'm using the [Arch package](https://archlinux.org/packages/extra/x86_64/openttd/), and for JGRPP I'm using the [AUR package](https://aur.archlinux.org/packages/openttd-jgrpp).

I thought this might be something to do with the font size since it looks slightly bigger with AA enabled but setting `medium_size = 13` in both versions it still looks the same. I think it's the hinting mode being set wrong (maybe full instead of slight) but I couldn't find where that was set in the code. [Full hinting has been broken for a few years](https://github.com/harfbuzz/harfbuzz/issues/2394#issuecomment-626219078) and it remember it looking fine in Ubuntu 18.04 which is from before the change.

**Comment by JGRennison** [comment]
I don't have any control of the AUR package.
I'd suggest trying with the generic Linux build from here: https://github.com/JGRennison/OpenTTD-patches/releases/tag/jgrpp-0.56.2, or compiling yourself with suitable font rendering libraries installed.

**Comment by man-of-eel** [comment]
> compiling yourself with suitable font rendering libraries installed
That's what the AUR package does, it fetches the source code from here and compiles it (click on View PKGBUILD). FWIW i tried the generic build and it's still there

Happy new year by the way :) I kind of forgot what day it was until i posted it

**Comment by JGRennison** [comment]
From what I can gather from the issue you linked and the other issues linked from it, there is nothing at all that I can do about this issue.
I'd suggest using a different set of fonts.

**Comment by man-of-eel** [comment]
Turns out this is an upstream bug, not sure how I missed it. Compiling OpenTTD 13.4 there's no bug but latest git it's there. Guess I'll tell em
