### ISSUE TITLE
[WIKI] Another Slot example for Goods Passing Loop

### ISSUE THREAD

**Issue by MeirionHughes** [JGRennison/OpenTTD-patches#626]
Something that I thought might be interesting / useful for other people - basically a way to allow faster trains stuck behind a slower freight to pass them. 

![slow passing loop](https://github.com/JGRennison/OpenTTD-patches/assets/3584509/e2d8938f-8427-4df0-8583-d13d78aa8381)

This is an example of a passing loop to enable faster trains to be given priority over slower trains. The loop is setup such that if the slot has been acquired and if the train's max-speed is slower than some defined threshold, then it is routed into the side track. This side track holds the train until the slot is released. The signal that triggers whether to acquire the slot must be far enough away to allow enough time for the slower train to be routed.

**Comment by JGRennison** [comment]
I can add an example along these lines to the wiki.
This particular design can deadlock if you have too many slow trains followed a fast close enough together, so I'll modify it a bit before I use it as an example.

**Comment by JGRennison** [comment]
This has been a bit delayed, but I've added an example along these lines here: https://github.com/JGRennison/OpenTTD-patches/wiki/Signalling#example-5-diverting-slow-trains-into-a-siding-to-allow-fast-trains-behind-to-overtake
