### ISSUE TITLE
How to add road vehicles to slots?

### ISSUE THREAD

**Issue by Nrgte** [JGRennison/OpenTTD-patches#627]
So I'm trying to experiment with slots and there is a nice order to remove a vehicle from a slot, but I haven't found a way to add a vehicle to a slot. Basically what I'm trying to do is only have a certain amount of road vehicles in an area to prevent dead locks.

But I only found the option to remove vehicles from slots, but not add them once they enter a station or as an order.

It would also be nice to increase or decrease the amount of slots depending on how many goods are waiting at a station.

**Comment by JGRennison** [comment]
The vehicle in slot conditional order has modes to try to acquire a slot, and then jump if the vehicle is/isn't in the slot.
There isn't a non-conditional version of this because if a slot is already full, the vehicle won't be able to acquire it.

It isn't possible to dynamically change the capacity of a slot, however you could do something with the waiting cargo amount conditional order.

**Comment by Nrgte** [comment]
Where is the option to aquire a slot in the conditional order jump? The conditional order can only jump to an order depending on a condition. It can't set a condition. At least I don't see anything like this.

**Comment by JGRennison** [comment]
![slot](https://github.com/JGRennison/OpenTTD-patches/assets/3910080/741b2b65-7f19-4ae8-8a2a-a781ead96111)

See also: https://github.com/JGRennison/OpenTTD-patches/wiki/Signalling#slots

**Comment by Nrgte** [comment]
Thanks a lot. I play with the language set to german and the translation of "Vehicle in slot" is a not very accurate in german, so I totally missed that.

**Comment by JGRennison** [comment]
No problem. I can update the translation files if there's a better way to put it?

https://github.com/JGRennison/OpenTTD-patches/blob/jgrpp/src/lang/extra/german.txt#L21
https://github.com/JGRennison/OpenTTD-patches/blob/jgrpp/src/lang/extra/german.txt#L1334

**Comment by Nrgte** [comment]
I'd just write "Zug im Slot" and "Fahrzeug im Slot". "Zeitfenster" translates to time window and suggests it has something to do with the time tables.

Also it would be nice if there was a straight order to add a vehicle to a slot, similar to the one to remove a vehicle from the slot. That way it would be really easy to just put a waypoint at a chokepoint and make them add and remove when they go through there.

**Comment by JGRennison** [comment]
OK, I've changed that.

I'll have a look at adding a non-conditional order to try to acquire a slot.

**Comment by JGRennison** [comment]
041f36d56542e914704661f8d5acf7da9591515f should do the trick

**Comment by Nrgte** [comment]
Thanks a lot. I'll make sure to try it out with the next build.
