### ISSUE TITLE
[Crash]: Conditional order jump counter

### ISSUE THREAD

**Issue by mmtunligit** [JGRennison/OpenTTD-patches#629]
### Version of OpenTTD

jgrpp-0.46-rc2, Windows 10

### Steps to reproduce

1. Selected "counter value" in a conditional order jump
2. Crash
3. The save works, but the order says jump to order X when undefined (in red) is equal to zero
4. clicking on that order crashes the game again
5. Only way to remove the order is to sell the vehicle

### Upload crash files

[OpenTTD crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/13940013/OpenTTD.crash.zip)

**Comment by JGRennison** [comment]
This was fixed already in 0.49.2.
0.46-rc2 is a rather dated non-release version, what's the reason for still using this now?

**Comment by mmtunligit** [comment]
Haven’t played in a while and am bad at remembering to update (and never
remember how) thanks for letting me know!
