### ISSUE TITLE
Improper work with building waypoints

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#63]
![image](https://user-images.githubusercontent.com/10726524/43363273-4dbc706c-933c-11e8-9a48-1e6db7c18562.png)

* **Version:** 0.26.0

It is impossible to build waypoints in a certain direction such as either NS or ES.
For instance, in my case, it is impossible to build a waypoint at the red circled rail and possible at the blue one from the above screenshot.

**Comment by JGRennison** [comment]
It's related to an issue with the rail type increase in trunk, see https://github.com/OpenTTD/OpenTTD/pull/6868#pullrequestreview-141317975 .
I will sort out merging a fix soon.

**Comment by JGRennison** [comment]
This has been fixed.
