### ISSUE TITLE
[Bug]: Can't start custum AI on a dedicated

### ISSUE THREAD

**Issue by Chico0008** [JGRennison/OpenTTD-patches#632]
### Version of OpenTTD

0.52.1

### Expected result

Playing solo on local, or event from the server via XDisplay, server can use custom Ai Citylife, or TownCars without any problem.
But, when launching on dedicated, AI crash

### Actual result

actual result, when custom AI start : 
[code]
dbg: [script] No suitable AI found, loading 'dummy' AI.
dbg: [script] The script died unexpectedly.
[/code]

### Steps to reproduce

Launch game graphically on a linux server specifying a conf file
./openttd -c ./test.conf
make your configuration, download and ad Citylife AI, and grf needed (generic car, etecandy vehicle)
start a game, after a few minutes, Citylife Ai come to play and work normally (build some road, add generic vehicle to town)

quit game, so the test.conf file is written.

launch a dedicated server : openttd -D -c ./test.conf
then join the serveer with another copenttd client
when ai comes to play : not working

it doesn't crash the game, just the AI won't work.

**Comment by JGRennison** [comment]
There have been some fixes related to search paths since then, so it may be testing whether this still doesn't work as expected with the most recent version

**Comment by JGRennison** [comment]
Feel free to re-open this if it is still on problem on more recent releases.
