### ISSUE TITLE
[Crash]: Resizing world map window with cargo link graph selected crashes

### ISSUE THREAD

**Issue by slhurst** [JGRennison/OpenTTD-patches#633]
### Version of OpenTTD

JGR patch pack 7a5e8dd991b105813e76d7f2afdc4da72e71ece0

### Steps to reproduce

1. Start new game
2. Open world map viewer
3. Select cargo flow button
4. Click on bottom right to resize world map window
5. Boom

### Upload crash files

[crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/14016508/crash.zip)

**Comment by slhurst** [comment]
Git bisect pointed the finger at 7a5e8dd991b105813e76d7f2afdc4da72e71ece0 - i.e. it's not in the latest release

**Comment by JGRennison** [comment]
Thanks for letting me know about this. Bit careless of me, I keep forgetting about the smallmap window.
This should be fixed now.

**Comment by slhurst** [comment]
Fluke that I found it really but seems fine now :+1:
