### ISSUE TITLE
[Bug]: Add Hotkey For Vehicles In Tunnels Transparency

### ISSUE THREAD

**Issue by JordanW9232** [JGRennison/OpenTTD-patches#634]
### Version of OpenTTD

0.56.2, Windows 11

### Expected result

I want to be able to set a hotkey for toggling transparency for vehicles in tunnels.

### Actual result

There is no existing hotkey for this in the hotkeys.cfg file, and is therefore not configurable. When one is added, I suggest naming it "transparency_tunnels" and defaulting it to Ctrl+0.

### Steps to reproduce

1. Locate your "OpenTTD" folder
2. Look for a hotkey named "transparency_tunnels" in the hotkeys.cfg file.
3. No such hotkey exists

**Comment by JGRennison** [comment]
This is added now
