### ISSUE TITLE
[Bug]: "Highest resolution sprites" setting does not work on sprite-font

### ISSUE THREAD

**Issue by merni-ns** [JGRennison/OpenTTD-patches#635]
### Version of OpenTTD

JGRPP 0.56.2, Windows 11

### Expected result

When setting "Highest resolution sprites to use" as 1x, the sprite font is also restricted to 1x sprites. This is the correct behaviour in OpenTTD 13.4.

### Actual result

The sprite font uses high-resolution sprites irrespective of the setting. Left is OpenTTD 13.4, right is JGRPP 0.56.2.

![image](https://github.com/JGRennison/OpenTTD-patches/assets/66267867/7b467d96-2dd3-4df5-bfe4-c307517cf47b)

### Steps to reproduce

1. Install "OpenGFX2 Classic" from bananas.
2. Set "Highest resolution sprites to use" to 1x.
3. Activate OpenGFX2 Classic base graphics set.
4. Observe the difference in the font between OpenTTD 13.4 and JGRPP 0.56.2.

**Comment by JGRennison** [comment]
This setting is not supposed to apply to font sprites, see OpenTTD 14.0/master.
