### ISSUE TITLE
[Bug]: Cloned trains from templates are entering every depot. Very unique bug.

### ISSUE THREAD

**Issue by Nrgte** [JGRennison/OpenTTD-patches#636]
### Version of OpenTTD

0.56.2

### Expected result

Today I encountered a super interesting bug. Fortunatelly it's super easy to reproduce.

I created a new train template. Then I clicked on a train depot and clone train. Then I Ctrl clicked the template. It would actually let me create the train. But this train and all other clones of this train have the following bugs:

Minor side-bug: Auto-Separation is not on by default for trains created this way.

Major bug: Trains created this way are entering every train depot on their way. So if you have a train depot next to their target station, they'd enter the depot before entering the station and then after they've loaded they would go into depot again and they'll continue to enter every single depot on their way. Oftentimes they also complain about not finding a path to their destination even though they're right next to it.

### Actual result

See above.

### Steps to reproduce

1. Create a new train template.
2. Open a train depot.
3. Ctrl clone the train template.

**Comment by JGRennison** [comment]
Thanks for letting me know. The service interval was left at 0, you can change it to a different value to not service all the time.
This will be fixed in the next release.
