### ISSUE TITLE
[Bug]: Buying a company through shares announces a company value of £0 in the news.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#637]
### Version of OpenTTD

jgrpp-0.57.0 on Windows 10, 64-bit

### Expected result

Buying a company through shares uses the full value of the company in the news.
For example, if buying a company valued at £1,000,000, the value announced in the news is that amount.

### Actual result

Buying a company through shares uses £0 as the value of the company in the news.
This creates news messages like "Transport company merger! - A has been sold to B for £0!"

### Steps to reproduce

1. Enable shares using the game setting.
2. Start a new map.
3. Start a new AI.
4. Wait a few months or years.
5. Give yourself all needed cash to take over the AI company.
6. Buy 100% shares in the AI company to take it over.
7. Check the news log. Notice the transport company merger message with a value of £0.

**Comment by JGRennison** [comment]
Thanks, this will be fixed in the next release

**Comment by JGRennison** [comment]
Fixed in the most recent release
