### ISSUE TITLE
[Bug]: Adding scheduled dispatch tied to current time

### ISSUE THREAD

**Issue by Floedekage** [JGRennison/OpenTTD-patches#638]
### Version of OpenTTD

jgrpp-0.56.2, Windows 10

### Expected result

When adding a departure slot in the schedule window it should be possible to set the hour and minute from the dropdown to any combination possible.

### Actual result

There seem to be a current bug where, when adding departure slots in the schedule window, when choosing an hour-number from the dropdown the minute-number changes to the current in-game minute and vice-versa.

### Steps to reproduce

1.  Buy a bus and create a route
2.  Enable scheduled dispatch and make a new schedule
3.  Add time slots

**Comment by JGRennison** [comment]
I'll fix this shortly, in the meantime if you enable the "Enter timetable start times as text" setting, you can enter times that way.

**Comment by Floedekage** [comment]
I'm currently just waiting for gameplay to reach desired minute-mark and adding timeslots then, so it's hardly game-breaking

**Comment by JGRennison** [comment]
Fixed in the most recent release
