### ISSUE TITLE
[Bug]: Ships randomly stopping in depot upon refit

### ISSUE THREAD

**Issue by Floedekage** [JGRennison/OpenTTD-patches#639]
### Version of OpenTTD

jgrpp-0.56.2, Windows 10

### Expected result

When a ship is send to depot to be refitted it should do so and keep sailing to next order
![Screenshot 2024-01-30 12 58 28](https://github.com/JGRennison/OpenTTD-patches/assets/2394234/0c53f7df-2a9d-4a50-bdaa-37cb61ecd145)

### Actual result

There seem to be a bug where ships being refitted randomly stops in depot before refit.
(Picture of order list, and that there's no "stop in depot order" above)

### Steps to reproduce

1. buy ship
2. route between two stops
3. after each stop go to depot and refit cargo

**Comment by JGRennison** [comment]
This appears to be the intended functionality.
The vehicle has been stopped because the refit failed, e.g. due to lack of money or other issues.
The news message that comes up when this happens informs you of this.
