### ISSUE TITLE
[Bug]: Available cargo at station is sorted in reverse order

### ISSUE THREAD

**Issue by Floedekage** [JGRennison/OpenTTD-patches#640]
### Version of OpenTTD

jgrpp-0.56.2, Windows 10

### Expected result

When sorting cargo at station by volume it should correspond to the "sort by" ascending/descending option 

### Actual result

Currently seems to be sorted in reverse order
![Screenshot 2024-01-30 12 07 42](https://github.com/JGRennison/OpenTTD-patches/assets/2394234/75c4ac11-a4fe-4ccd-8264-2d3f52e2b4e6)

### Steps to reproduce

1. make station and route to make cargo available, either multiple cargos or multiple destinations
2. sort available cargo by volume

**Comment by JGRennison** [comment]
You need to change the sort mode to "Amount: Waiting" for that behaviour.
