### ISSUE TITLE
[Suggestion] NewGRF signals; sprites for path signals on both sides

### ISSUE THREAD

**Issue by EratoNysiad** [JGRennison/OpenTTD-patches#641]
Currently the NewGRF signal specs only allow you to change the sprites that are already rendered.

I would like to be able to make path signals with sprites on both sides; so I can have stuff both behind and in front of the train, or even have the signals always in the tracks (and thus behind the trains)

**Comment by JGRennison** [comment]
I can take a look into it

**Comment by JGRennison** [comment]
I've added this in 7e0acd6
