### ISSUE TITLE
[Bug]: Speed part of the station rating seems not accurate for ships and aircraft.

### ISSUE THREAD

**Issue by Nrgte** [JGRennison/OpenTTD-patches#645]
### Version of OpenTTD

0.57.0

### Expected result

Not 100% sure this is a bug or I'm understanding something, wrong, but this behavior seems weird.

If the max speed of the last vehicle that picked up a certain cargo type is 42 km/h, I'd expect to show up in the station rating tooltip.

### Actual result

A couple of examples I noticed:

- Ship has a speed of 42 km/h, station rating shows 84 km/h.
- Another ship (Hovercraft has a speed of 112 km/h. Station Rating shows 226 km/h
- Aircraft with a speed of 566 km/h (aircraft speed set to half), shows as max speed of last vehicle of 43 km/h.
- Another Aircraft has a speed of 488 km/h (aircraft speed set to half), shows as max speed of last vehicle of 120 km/h.

To clarify I double checked, that the last vehicle is actually the one in the report.

As far as I can tell road vehicles and trains seem accurate.

### Steps to reproduce

As far as I can tell ships are consitently doubled (maybe intentional).

Aircraft just seem wonky (at least when the aircraft speed is set to half).

**Comment by JGRennison** [comment]
Thanks for this. I've adjusted the tooltip to convert the rating speed back into the corresponding vehicle speed for that vehicle type.
There may be some cases where this doesn't quite match the original vehicle's speed due to rounding and the way the rating updates work, but for the most part it should be as expected.

**Comment by JGRennison** [comment]
Fixed in the most recent release

**Comment by Nrgte** [comment]
I hope it's okay, that I resurrect this issue. The speed part seems fixed, but the percentage still seems wrong (at least for airplanes).

https://i.imgur.com/ZfgNT1I.png

Testing on 0.58.1

Thanks!

**Comment by JGRennison** [comment]
This is just how the rating algorithm works, it doesn't make much sense from an objective point of view but that is how it has worked since the original TTD.

**Comment by Nrgte** [comment]
Ohh okay, I was just going off from the official openttd wiki, which would suggest that an aircraft with a speed over 255 km/h should get a station rating of 17%:

https://i.imgur.com/YtfHBIB.png

So I assume this is a bug in the OG game or the wiki is wrong.

**Comment by JGRennison** [comment]
Aircraft use different speed units for this. You can multiply by 10/128 to get the equivalent value.

**Comment by Nrgte** [comment]
Ahh okay, thank you for the info. I really appreciate this and try to calculate this.
