### ISSUE TITLE
[Crash]: on exit when clicking the X in OpenTTD's terminal window

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#649]
### Version of OpenTTD

jgrpp-0.58.0 on Windows 10, 64-bit

### Steps to reproduce

1. Start the game with `openttd -d`.
2. Use the X in OpenTTD's terminal window (showing the logs) to close the game.
3. The game crashes.

### Upload crash files

[crash-20240210T214123Z.log](https://github.com/JGRennison/OpenTTD-patches/files/14230588/crash-20240210T214123Z.log)
The crash save had a file size of 0 bytes.

**Comment by JGRennison** [comment]
I cannot seem to reproduce this, does it still happen on 0.57.1?

**Comment by James103** [comment]
I can consistently reproduce this on my system in 0.57.1.
[crash-20240211T002640Z.log](https://github.com/JGRennison/OpenTTD-patches/files/14230912/crash-20240211T002640Z.log)

`openttd -Z` does not output anything on my machine.

In step 2, the terminal window I'm referring to is this one created by the OpenTTD process on Windows: 
![image](https://github.com/JGRennison/OpenTTD-patches/assets/37945304/18b09854-26af-4dd6-897e-a2c528c37aa7)

**Comment by JGRennison** [comment]
I can reproduce the issue when music is enabled. I've applied a change which should prevent this.

**Comment by JGRennison** [comment]
Fixed in the most recent release
