### ISSUE TITLE
[Bug]: Incorrect displayed capacities in Available Ships window

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#651]
### Version of OpenTTD

jgrpp-0.57.1 on Windows 10, 64-bit

### Expected result

The capacities displayed in the Available Ships window should match what the ship can actually carry, including both the correct number of sections and capacity of each section.

### Actual result

The capacities displayed in the Available Ships window are incorrect; small ships appear to be able to carry a very large amount and many more types of cargo than they actually do.
![image](https://github.com/JGRennison/OpenTTD-patches/assets/37945304/c3ab973b-5b75-4ed4-8b70-c512501fad47)

### Steps to reproduce

1. Start a new game with Multi-cargo SHARK installed.
2. Open the Available Ships window.
3. Click on each and every ship and notice incorrect capacities for some of the ships.
4. Click the first ship (shown above) and notice capacities beyond the first line are all incorrect.

**Comment by JGRennison** [comment]
This is fixed in the most recent release
