### ISSUE TITLE
[Bug]: `openttd -Z` does not output anything visible/copyable on Windows 10

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#652]
### Version of OpenTTD

jgrpp-0.54.4, 0.56.2, 0.57.0, and 0.57.1 on Windows 10, 64-bit

### Expected result

`openttd -Z` should output version information in a way that can be viewed or copied without needing Linux or special tools besides a terminal.

### Actual result

`openttd -Z` does not give any visible output, regardless of whether it is run from the terminal.

### Steps to reproduce

Run `openttd -Z`.

**Comment by JGRennison** [comment]
A console command to print this information is in the most recent release
