### ISSUE TITLE
[Bug]: cant download music 

### ISSUE THREAD

**Issue by minho2011** [JGRennison/OpenTTD-patches#654]
### Version of OpenTTD

0.57.1

### Expected result

i uninstall old openttd file amd download jgr pack, and try to install openmsx.

### Actual result

openmsx dosent download, and there is no music tar file

### Steps to reproduce

1.delete old openttd file
2.download jgr pack
3.tries to download openmsx

**Comment by minho2011** [comment]
i solve it in use original to download it and open in jgr, but how to do in only jgr?

**Comment by JGRennison** [comment]
See: https://github.com/OpenTTD/OpenTTD/issues/12041
This is already fixed for the next release
