### ISSUE TITLE
[Bug]: In wallclock mode, the current calendar year is used as the period in the finance window.

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#657]
### Version of OpenTTD

jgrpp-0.58.0 on Windows 10, 64-bit

### Expected result

In wallclock mode, the current economic period should be used as the period in the finance window, making it always count 1, 2, 3, etc.

### Actual result

In wallclock mode, the current calendar year is used as the period. This breaks proper display of finance statistics, especially when calendar time is slowed down.

### Steps to reproduce

Set Timekeeping units to Wallclock, Calendar progress speed to Frozen, then start a new game. Then open the finance window, wait 20-30 minutes and notice the current period's financial stats keep resetting instead of rolling over.

**Comment by JGRennison** [comment]
Should be resolved in the most recent release
