### ISSUE TITLE
[Bug]: Train with timetabled depot stop does not stay for configured time

### ISSUE THREAD

**Issue by michaelsmithson** [JGRennison/OpenTTD-patches#658]
### Version of OpenTTD

0.58.0 on windows 10 (10.0.19045)

### Expected result

I have a timetable set up with a depot stop for a number of days. I expect it to stay in the depot for that number of days. I was seeing this expected behaviour working fine on 0.57.1.

### Actual result

I have seen a couple of behaviours:
1. The train never leaves the depot ever again
2. Or the train leaves immediately after entering the depot without waiting for the configured number of days.

### Steps to reproduce

[Timetable Test.zip](https://github.com/JGRennison/OpenTTD-patches/files/14395955/Timetable.Test.zip)

Attached are two save files.
Test 2 has no newgrfs, and is showing the train stuck in the depot. If you skip the current order, then it will do one loop and when it gets back to the depot it doesn't leave again.

Test 1 is showing the 2nd behaviour where the train is leaving the depot immediately rather than waiting the timetabled 30 days. This is using some newgrfs, I wasn't sure they were included the issue, so I have included it anyway.

**Comment by JGRennison** [comment]
Thanks, this should be fixed in the next release.
In the case of test 1, the "nearest depot" order does not find the depot at all because it's behind the vehicle. You should change the order to be for the specific depot.

**Comment by michaelsmithson** [comment]
Thanks! This is working for me in 0.58.1.
