### ISSUE TITLE
[Bug]: Game Script settings have an arbitrary range of values applied to them

### ISSUE THREAD

**Issue by Distortional-Addict** [JGRennison/OpenTTD-patches#659]
### Version of OpenTTD

jgrpp-0.58.0 on Windows 10, 64-bit

### Expected result

Game Script settings should display the selected value, and only that value should be used when starting a new game. jgrpp-0.57.1 displays the expected behavior.

### Actual result

Many Game Script settings now display a range, for example [30, 70] when the inputted value is 50. Then upon starting a new game, a seemingly random value within the displayed range is used.

### Steps to reproduce

Can be seen with Game Scripts "Renewed Village Growth" and "Villages Is Villages", both with and without newGRFs loaded.

**Comment by James103** [comment]
Caused by https://github.com/OpenTTD/OpenTTD/pull/11959.

**Comment by JGRennison** [comment]
I've forwarded this as https://github.com/OpenTTD/OpenTTD/issues/12182

**Comment by JGRennison** [comment]
There's a setting to disable this in the most recent release
