### ISSUE TITLE
[Suggestion] Per original year running cost

### ISSUE THREAD

**Issue by alex256z** [JGRennison/OpenTTD-patches#660]
Is there any way to make option to turn this off in settings? Because this change "**No longer scale displayed running costs by the day length factor, show per original year**" makes big mess when playing in, say, 4x day length and trying to calculate running cost per year.

**Comment by JGRennison** [comment]
I changed it because some players just found this too difficult to understand and kept complaining.
It should be easy enough to make it a setting though.

**Comment by alex256z** [comment]
Thanks alot! 👍😻

**Comment by WenSimEHRP** [comment]
I found that the description of "original year" is quite misleading. Would it be better if we change this to "running cost per economic period?"
