### ISSUE TITLE
[Crash]: Assertion failed at line 395 of /src/roadstop.cpp: this->occupied >= 0

### ISSUE THREAD

**Issue by nk167** [JGRennison/OpenTTD-patches#662]
### Version of OpenTTD

0.58.0 | Windows 10

### Steps to reproduce

1. Create a bus with 4 tasks on it (1 of them is unbunch in garage)
2. Ctrl+Copy that bus 3 times
3. Start them *and wait for UFO to destroy one of them*

### Upload crash files

[crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/14473456/crash.zip)

**Comment by JGRennison** [comment]
Thanks, this should be fixed in the next release
