### ISSUE TITLE
[Bug]: `'initializing'`: conversion from `'u64'` to `'u32'`, possible loss of data

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#664]
### Version of OpenTTD

PR https://github.com/JGRennison/OpenTTD-patches/pull/663

### Expected result

No such warnings

### Actual result

When compiling JGRPP on Windows (windows-latest / x86, windows-latest / x64, windows-2019 / x86 or windows-2019 / x64), the following warning is emitted:
```
'initializing': conversion from 'u64' to 'u32', possible loss of data
```
https://github.com/JGRennison/OpenTTD-patches/blob/230eaabb5ce004c2687b630aea6c5090e936ffaa/src/3rdparty/monocypher/monocypher.cpp#L881

### Steps to reproduce

Compile JGRPP on Windows (windows-latest / x86, windows-latest / x64, windows-2019 / x86 or windows-2019 / x64).

**Comment by JGRennison** [comment]
Should be fixed in recent releases
