### ISSUE TITLE
[Crash]: Crash on one save (server) after disabling "autosave uses real time"

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [JGRennison/OpenTTD-patches#666]
### Version of OpenTTD

jgrpp-0.58.1

### Steps to reproduce

Try to load crash-save using included openttd.cfg
_On the standard openttd.cfg everything works, no crashes_

### Upload crash files

[jgrpp58-1_crash20240312_notrau117.zip](https://github.com/JGRennison/OpenTTD-patches/files/14569243/jgrpp58-1_crash20240312_notrau117.zip)

**Comment by JGRennison** [comment]
Thanks, this is fixed for the next release
