### ISSUE TITLE
[Bug]: Running `help dump_version` also prints the version info report

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#668]
### Version of OpenTTD

Since 58f8971f17d45da3c05f7563eab4121cc5a0500c

### Expected result

Running `help dump_version` should just print the help message "Debug: Dump version info."

### Actual result

Running `help dump_version` prints the help message "Debug: Dump version info," but also the version info report, as if plain `dump_version` was also run.

This is caused by a missing `return true` statement here:

https://github.com/JGRennison/OpenTTD-patches/blob/4200757db3422cebb30196886aa64e0d434ab0c8/src/console_cmds.cpp#L3292-L3294

### Steps to reproduce

Run `help dump_version`.

**Comment by JGRennison** [comment]
Thanks, this will be fixed in the next release
