### ISSUE TITLE
[Crash]: OpenTTD Release v0.58.1 Error Message: Assertion failed at line 738 of /src/gfx.cpp: maxw > 0

### ISSUE THREAD

**Issue by SwissTurbine** [JGRennison/OpenTTD-patches#669]
### Version of OpenTTD

OpenTTD v0.58.1 and Windows 11 Version 22H2 for x64-based Systems

### Steps to reproduce

1. Start (Arctic) game at year 1944 (for example)
2. Play game normally without any problems until 1952
3. Game crashes with error message: Assertion failed at line 738 of /src/gfx.cpp: maxw > 0
4. I tried different setups (less grfs no Scripts etc) but no changes
5. Games still crashes (the error message is always the same)
6. I use a Dell Precision Laptop with good/high specs (48GB Memory) see attached file.
7. If I run the game in fast mode (accelerated to 1300%) it does not crash in 1952
8. The game runs past 1952 without crashing (@1300% acceleration)
9. I have no clue what causes the crash

Laptop Specs:
[Detailed-System-Report.pdf](https://github.com/JGRennison/OpenTTD-patches/files/14618822/Detailed-System-Report.pdf)

### Upload crash files

[crash-20240312T212448Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/14618852/crash-20240312T212448Z.zip)

Sorry I have no crash.dmp file, all I got are in the ZIP Folder

Thank you very much for your help

**Comment by JGRennison** [comment]
The crash.dmp file isn't needed for bug reports here, don't worry about that.

This appears to be a problem with the layout of the engine preview window with one of the GRFs that you're using (HVW trams).

I have forwarded it upstream here: https://github.com/OpenTTD/OpenTTD/issues/12305

**Comment by SwissTurbine** [comment]
Thank you very much for your fast answer. The HVW Trams GRFs (and couple other HVW GRFs) are not important. Do you think deleting these GRFs would solve the crashes? Again thank you for your quick answer.

**Comment by JGRennison** [comment]
Not using the HVW trams GRF in your game should prevent this crash.
I haven't looked at the other HVW GRFs so far. It may be an idea to avoid them in case they have similar issues.

**Comment by SwissTurbine** [comment]
The HVW Trams GRF was the culprit. I run another game without any HVW GRFs and did not encounter any problems. I'm very grateful for your support and wish you a very nice weekend. Best regards from Switzerland, Urs
