### ISSUE TITLE
Builded JGRPP 0.27.1 adds unknown strings after 'jgrpp-0.27.1'

### ISSUE THREAD

**Issue by Penta0308** [JGRennison/OpenTTD-patches#67]
I am compiled jgrpp 0.27.1 on CentOS 7, but I start dedicated server than program add '-5-g2c4d319' after version_string in [version] in  openttd.cfg. so we can't connect the server.

**Comment by JGRennison** [comment]
There have been several changes since 0.27.1 was released, it appears that you've compiled the most recent commit rather than that release.

Try running `git checkout jgrpp-0.27.1` before compiling.

**Comment by Penta0308** [comment]
Oh Thanks
It work
