### ISSUE TITLE
[Bug]: Train flips when carriage attached (related to xussr)

### ISSUE THREAD

**Issue by Sinas128** [JGRennison/OpenTTD-patches#672]
### Version of OpenTTD

JGRpp 0.58.1

### Expected result

xussr has a beautiful system to build consists. 
With this system you can create consists by manually choosing when the headcar, powercar etc comes

![image](https://github.com/JGRennison/OpenTTD-patches/assets/88989774/589517b0-c63b-424a-8d00-d56e1ca96b6c)

Here is an example of a unit created from headcar, car and another headcar

### Actual result

Well not every unit seems to be behave as intented
When constructing a multiple unit, the game sometimes flips a headcar with no way of resolving this.

![image](https://github.com/JGRennison/OpenTTD-patches/assets/88989774/fdc39998-62a2-4f2c-8182-dabddd64e869)

Here is an example of a flipped headcar.

According to George (one of the authors of xussr) this bug does not excist in Openttd 14.0-RC1
But this issue does occur in JGRpp 0.58.1
The DR1A-232 as shown in the image one of the few trains to show this behavior.

### Steps to reproduce

1. Take any of these units

D1-376
D1-671
DR1A-232 
DR1A-305
and 1,5kv S type electric Multiple unit
(Apparently also some electric loco's that are made out of creatable segments but I havent researched which ones yet)

2. Try to create an consist with them

3. The bug should automatically appear

**Comment by JGRennison** [comment]
It would be helpful if you could attach a savegame where it the consist doesn't match what it is that you expect.

It looks OK here, but this GRF is very complicated and I have no idea if I am operating it correctly.

**Comment by JGRennison** [comment]
Actually, not to worry, I think I see what you are getting at now

**Comment by JGRennison** [comment]
Should be fixed now

**Comment by Sinas128** [comment]
I will attach savegame next time 
And I should have mentioned that the bug is replicable in any type of new game

sorry :)
