### ISSUE TITLE
[Bug]: Text shadow issue in the Industry chain window

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#673]
### Version of OpenTTD

jgrpp-0.58.1

### Expected result

No text shadows

### Actual result

![image](https://github.com/JGRennison/OpenTTD-patches/assets/10726524/71b76e75-a3f0-4572-84eb-bb1ec3dad52b)
Maybe this occurs when using custom TTF fonts. I've encountered a similar issue before

### Steps to reproduce

0. (Set some ttf fonts)
1. Open the Industry chain window
2. Click the drop button of ``Link to smallmap``

**+ Edit:**
It seems #460 is occured again

**Comment by JGRennison** [comment]
This should already be fixed by fae9df329e7315e92953e77488acd83af9a29c12

**Comment by telk5093** [comment]
Nice, then I'll close this issue.
