### ISSUE TITLE
[Suggestion] Ability to remove speed restrictions on trains

### ISSUE THREAD

**Issue by Sinas128** [JGRennison/OpenTTD-patches#674]
In a multiplayer some other company was building with speed restrictions, he made a mistake by starting with the speed restriction first and waiting with the ''end speed restriction'' 

My train, going on a roughly 6000 tile journey accidently picked up the speed restriction and wont be seeing any end speed restriction signals for a long while on his journey through various companies

It would be nice to have the ability to manually remove (and maybe even add??) speed restrictions to trains
![image](https://github.com/JGRennison/OpenTTD-patches/assets/88989774/743299f0-44e1-429f-81be-acc0149ae08f)

**Comment by JGRennison** [comment]
This isn't technically difficult, the main issue is where such a button would go.

**Comment by Sinas128** [comment]
Well I had something in mind
Just like in the SD screen
![image](https://github.com/JGRennison/OpenTTD-patches/assets/88989774/f7459eab-a22a-43dd-9df7-001f8e037c68)

![image](https://github.com/JGRennison/OpenTTD-patches/assets/88989774/8d43597c-35bf-463e-ad83-fa7167db6bf9)

A little red cross would be put in front or behind the speed restriction

Considering the little amount damage it does to your network by accidently clicking and the lack of amount of clickable things in the screen, I thought it wouldnt matter too much if it would be added into there

**Comment by JGRennison** [comment]
![image](https://github.com/JGRennison/OpenTTD-patches/assets/3910080/6babc2b3-3454-4de9-8942-d2232077de62)
I decided to go for something slightly different, to also allow setting/changing it.
