### ISSUE TITLE
[Bug]: Sound Stutters in 0.58.2 that weren't there in 0.58.1

### ISSUE THREAD

**Issue by Nrgte** [JGRennison/OpenTTD-patches#680]
### Version of OpenTTD

0.58.2

### Expected result

OpenSFX sound pack works without stuttering.

### Actual result

Stuttering on every sound (even in the main menu). The music is fine.

### Steps to reproduce

Just stimply open the game with OpenSFX Soundpack and the sound stutters in the main menu (as well as all ingame sounds).

This is new in 0.58.2 and didn't occur in 0.58.1.

**Comment by JGRennison** [comment]
This should be fixed for the next release.
In the meantime, if you run openttd as `openttd.exe -s win32:samples=2048` it should work around the issue. The default audio buffer size was changed upstream.

**Comment by Nrgte** [comment]
> This should be fixed for the next release. In the meantime, if you run openttd as `openttd.exe -s win32:samples=2048` it should work around the issue. The default audio buffer size was changed upstream.

Perfect, thank you, that workaround works like a charm.
