### ISSUE TITLE
[Bug]: Mouse position is not correctly calculated in the production chain UI

### ISSUE THREAD

**Issue by Nrgte** [JGRennison/OpenTTD-patches#681]
### Version of OpenTTD

0.58.2

### Expected result

Mouse position is accurate like it was in 0.58.1

### Actual result

Mouse position is slightly higher than the mouse cursor.

### Steps to reproduce

Open up the production chain window and hover over or click on a cargo type. It will show the chain for the cargo type above.

Here is an example: 

![grafik](https://github.com/JGRennison/OpenTTD-patches/assets/131605234/2bb9f8a2-e6ff-46cc-a524-6398bf345463)

I'm hovering over Vehicle Engines and it shows me the tooltip for rubber parts which are 1 above. If I click on it, shows me the chain for rubber parts as well.

The same thing works correctly in 0.58.1:

![grafik](https://github.com/JGRennison/OpenTTD-patches/assets/131605234/21002c5d-0548-46b8-869d-984b2c345b56)

In case it's relevant. I'm using the AXIS industry set.

Thank you for your work!

**Comment by JGRennison** [comment]
Thanks, I've forwarded this upstream as: https://github.com/OpenTTD/OpenTTD/issues/12465

**Comment by Nrgte** [comment]
If I may add a suggestion: I think it would be good if you increased the version number by a minor version rather than a patch version if you're doing an upstream merge.

**Comment by JGRennison** [comment]
Almost every release has at least something merged from upstream

**Comment by Nrgte** [comment]
Ahh I see. I thought you'd only merge after larger upstream updates. Thanks for the clarification.

**Comment by JGRennison** [comment]
Should be fixed in recent releases
