### ISSUE TITLE
[Suggestion/RFC] Remain at station behaviour for road vehicles

### ISSUE THREAD

**Issue by calvin-sykes** [JGRennison/OpenTTD-patches#686]
A recent line in the changelog 

> Fix road vehicles not remaining loading as expected when the next order is for the same station.

broke a pattern I use where road vehicles pull into a drive-through stop, unload, and then turn around just beyond the stop to return to the other side to load. This is useful for preventing vehicles from queuing up with tight timetable headways while also giving them some "recovery time" for late running.

I could change the global "remain at same station" setting but this would break similar recovery time setups for other vehicle types. So what I propose is that if different explicit stopping directions are set for consecutive orders at the same station, then the vehicle will depart even if the setting is enabled. This will keep the fix but let me keep using my [spacebar heating](https://xkcd.com/1172/).

I think it's just a one-line change (calvin-sykes@8f8d635baf3dc1506de206a3378498bedfd020bf), so let me know if this sounds okay and I'll open a PR.

**Comment by JGRennison** [comment]
I don't have any problem with this in principle, but because of the way the orders are processed internally, this is a little fragile. I may adapt your commit a bit for this.

**Comment by JGRennison** [comment]
This is implemented and in the most recent releases
