### ISSUE TITLE
Macos Compilation Error - liblzma not found

### ISSUE THREAD

**Issue by marcus13345** [JGRennison/OpenTTD-patches#69]
This is my first time trying to compile this project from source, so i might be just doing something stupid, so bear with me.

I installed brew, and ran

```
brew install xz
brew install zlib
```

and both commands seemed to return correctly. as well, i can see that `/usr/local/include/lzma` is a symlink to the header files.

however, when i run the `./configure` I still get the error, saying it could not be found:

```
checking translator... no
checking assert... enabled
checking zlib... not found
checking liblzma... not found
WARNING: lzma was not detected or disabled
WARNING: OpenTTD doesn't require lzma, but it does mean that many features
WARNING: (like loading most savegames/scenarios and joining most servers)
WARNING: will be disabled.
 If you want to compile without lzma use --without-lzma as parameter
```

**Comment by JGRennison** [comment]
I'm not familiar with development on Mac, however the OpenTTD wiki here: https://wiki.openttd.org/Compiling_on_Mac suggests also running `brew install lzma`. Maybe try that

**Comment by marcus13345** [comment]
Good idea! unfortunately, i just tried that as well, and it appears that lzma has been fully moved to the xz package.

```
> bre install lzma
. . . . .

Error: No available formula with the name "lzma" 
lzma is now part of the xz formula.
```

**Comment by marcus13345** [comment]
why was this closed, this is still a problem? are other people having success with compiling on mac?

**Comment by JGRennison** [comment]
I'm happy to reopen it if the issue is still there.
Other people have posted Mac builds on the forum thread recently.

**Comment by marcus13345** [comment]
ah, i havent seen them, as i dont use the forum. ill check it out, and test the build again when i get home. ill reopen if there are additional issues. Thanks for the Info 👍
