### ISSUE TITLE
[Crash]: Assertion failed... - autoreplace trains

### ISSUE THREAD

**Issue by darkwaiter** [JGRennison/OpenTTD-patches#692]
### Version of OpenTTD

OpenTTD jgrpp 0.59

### Steps to reproduce

1. load save
2. wait till game attempts train replacement
3. game crashes with message "Assertion failed at line 781 of /scr/autoreplace_cmd.cpp:Train::From(new_head)-> gcache.cached_total_length <= _settings_game.vehicle.max_train_length * TILE_SIZE"

### Upload crash files

[crash-20240509T122221Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/15262243/crash-20240509T122221Z.zip)

**Comment by JGRennison** [comment]
See also: https://github.com/OpenTTD/OpenTTD/issues/12651

**Comment by darkwaiter** [comment]
Thank you all for the hint. Will change the settings...
