### ISSUE TITLE
[Suggestion] Building signals with programming button clicked

### ISSUE THREAD

**Issue by merni-ns** [JGRennison/OpenTTD-patches#694]
When the routefinding restrictions button (gear icon) is clicked, if you click on a tile without any signal, nothing happens.

It would be convenient to be able to place the signal (and maybe instantly open the routefinding restriction window) when the gear icon is active and you click on an empty piece of track. This would remove the need to toggle that icon every time before placing a signal.

**Comment by JGRennison** [comment]
Unexpectedly placing a signal (of what type/orientation?) in this case would seem to me to be very surprising.

For convenience, what you can do now is control-click on signals to open the routefinding restriction window. This doesn't require using the specific tool.
