### ISSUE TITLE
[Crash]: OpenTTD 0.59.1 crashes upon startup

### ISSUE THREAD

**Issue by AnnoyedDecepticon** [JGRennison/OpenTTD-patches#704]
### Version of OpenTTD

0.59.1 / Windows 7 32-bit

### Steps to reproduce

1. Launch game
2. Crash when it reads NewGRFs

### Upload crash files

[crash-20240612T111117Z.zip](https://github.com/user-attachments/files/15803737/crash-20240612T111117Z.zip)

**Comment by AnnoyedDecepticon** [comment]
To add onto this: the game worked fine. I played it normally though I muted all sounds because I had my music player playing in the background. I closed the game and relaunched it only to be greeted with this. I did a reinstall (deleting the folder, adding it back in) and the same thing happened.

**Comment by AnnoyedDecepticon** [comment]
Update: I fixed it. It seems like it's my OpenTTD.cfg file that's causing it to break. I renamed my old OpenTTD folder, copy-pasted all of my NewGRFs and saves to the new one the game generated, and all is well.

**Comment by JGRennison** [comment]
In your openttd.cfg you've set `blitter = "32bpp-sse4"`, you only need to remove this one line

**Comment by AnnoyedDecepticon** [comment]
Ah thanks for the info. Out of curiosity, what does that actually do? I don't remember messing around with any of my graphic settings.

Also, sorry for the dumb thread. I have an OpenTTD game night in about 5 minutes and seeing the game break in front of my eyes was alarming.

**Comment by JGRennison** [comment]
It selects which sprite drawing backend to use. It should work, but it seems that there is bug with this backend when used in 32 bit Windows builds. I should be able to fix it in the next release.
