### ISSUE TITLE
[Desync]: infrastructure cache mismatch when merging or deleting companies 

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#709]
### Version of OpenTTD

jgrpp-0.60.0 on Windows 10, 64-bit

### Steps to reproduce

Load any scenario/save or start a new game, then merge or delete companies such as by the `merge_companies` or `delete_company` commands. An infrastructure cache mismatch warning should be logged from CheckCaches for all remaining companies.
Originally reproduced with the scenario titled "Reddit Game 1735."

### Upload crash files

[inconsistency-20240702T215358Z.zip](https://github.com/user-attachments/files/16074605/inconsistency-20240702T215358Z.zip)

**Comment by JGRennison** [comment]
Should be fixed in the most recent release
