### ISSUE TITLE
[Bug]: Cannot see all types of signal, even when all are enabled.

### ISSUE THREAD

**Issue by ProbablyIdiot** [JGRennison/OpenTTD-patches#717]
### Version of OpenTTD

0.60.2 - Windows 11

### Expected result

Expect to be able to see entry, exit, combo and programmable-pre-signals.

### Actual result

Not able to see all signals.
![image](https://github.com/user-attachments/assets/7af50ce1-8094-409e-bc9a-46e5e98982dc)
![image](https://github.com/user-attachments/assets/9e52fe4d-345d-49be-af43-623d8e10b319)

### Steps to reproduce

1. Install JGR PP
2. Enable all signal-related settings
3. Cannot see signals

**Comment by JGRennison** [comment]
Pre-signals are not compatible with the realistic braking setting, see: https://github.com/JGRennison/OpenTTD-patches/wiki/Realistic-braking
