### ISSUE TITLE
Rename day length factor

### ISSUE THREAD

**Issue by WenSimEHRP** [JGRennison/OpenTTD-patches#719]
Since OpenTTD 14 there is a new wallclock timekeeping mode. Under this mode date no longer have effect on production, and date flow speed is determined by a seperate parameter under wallclock mode. This may bring confusion as day length factor only changes the economic simulation speed, so I think it would be better if it can be renamed to e.g. "Simulation factor."

**Comment by JGRennison** [comment]
I've done a rename here: https://github.com/JGRennison/OpenTTD-patches/commit/767873d10f47adea1862e5204a0e473e6a696a12

I may make some more changes/edits to the texts

**Comment by WenSimEHRP** [comment]
fixed by https://github.com/JGRennison/OpenTTD-patches/commit/767873d10f47adea1862e5204a0e473e6a696a12
