### ISSUE TITLE
help cannot compile it mac

### ISSUE THREAD

**Issue by ecolortest** [JGRennison/OpenTTD-patches#72]
when i want compile 0.29.0, a error has happen when ./confirgure 

configure: error: clang version is too old: Apple LLVM version 10.0.0 (clang-1000.11.45.5), minumum: 3.3

i was install llvm 4.0 from macports but still not working

**Comment by letharion** [comment]
It sounds like the configure script can't find your newer llvm installation, so you'll need to check where it is, and perhaps point configure to it explicitly, probably by setting `CXX` in your env.

**Comment by ecolortest** [comment]
Yeah but im now use wine (64 bit) but is crash while opening openttd without removing exiting openttd.cfg, but if i remove the openttd.cfg, the setting always get reseted


[crash.txt](https://github.com/JGRennison/OpenTTD-patches/files/2732144/crash.txt)

![crash](https://user-images.githubusercontent.com/34646054/50760405-1b67b600-12ab-11e9-81e3-42bb9cbe31ec.png)

**Comment by ecolortest** [comment]
i was do by cxx but this is show up

/Users/USER/OpenTTD_compile/ClangGcc unusable
the CC environment variable is set, but it doesn't seem to be a 'clang++ g++' binary
please redefine the CC/CXX environment to a clang++ g++ binary

**Comment by JGRennison** [comment]
Could you try to compile the most recent commit, this should resolve issues of detecting the clang version.

**Comment by ecolortest** [comment]
thanks, its working :)
