### ISSUE TITLE
[Suggestion] Scheduled Dispatch window sorting

### ISSUE THREAD

**Issue by Yozora3** [JGRennison/OpenTTD-patches#722]
Recently I've opened the world of timetabling, but there's one thing that bothers me, and it's managing trains per hour during peaks.
I think it would be much easier for understanding if slots were viewed individually for every hour.
Here's a rough expected look.

![Untitled-1](https://github.com/user-attachments/assets/80181d9c-316d-46db-a76c-f3a5c3f51504)

This way it would be much easier to do managing, like tagging some slots for sending trains to the yard, or simply comparing 2 dispatch windows.

**Comment by JGRennison** [comment]
This is implemented now, it'll be in the next release.

**Comment by Yozora3** [comment]
You're the best, thank you!
