### ISSUE TITLE
[Crash]: during pathfinding when a bus encounters a junction on an overly long road

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#723]
### Version of OpenTTD

jgrpp-0.60.2 on Windows 10, 64-bit

### Steps to reproduce

1. Have a very long road with no junctions or intersections.
2. Place depots at both ends of the road.
3. Place a junction somewhere along the road.
4. Buy a bus at one of the depots, and order it to go to the other depot.
5. Start the bus.
6. When the bus reaches a junction, the game will crash.

[A Very Long Highway, 2200-01-01.zip](https://github.com/user-attachments/files/16347581/A.Very.Long.Highway.2200-01-01.zip)
Alternatively, start the bus in the attached save and wait for it to reach the junction, as shown below:
![image](https://github.com/user-attachments/assets/34546c25-dac9-4a09-a1eb-57e1676adbbe)

### Upload crash files

[crash-20240723T105159Z.zip](https://github.com/user-attachments/files/16347585/crash-20240723T105159Z.zip)

**Comment by Gadg8eer** [comment]
> ### Version of OpenTTD
> 
> jgrpp-0.60.2 on Windows 10, 64-bit
> 
> ### Steps to reproduce
> 
> 1. Have a very long road with no junctions or intersections.
> 2. Place depots at both ends of the road.
> 3. Place a junction somewhere along the road.
> 4. Buy a bus at one of the depots, and order it to go to the other depot.
> 5. Start the bus.
> 6. When the bus reaches a junction, the game will crash.
> 
> [A Very Long Highway, 2200-01-01.zip](https://github.com/user-attachments/files/16347581/A.Very.Long.Highway.2200-01-01.zip)
> Alternatively, start the bus in the attached save and wait for it to reach the junction, as shown below:
> ![image](https://github.com/user-attachments/assets/34546c25-dac9-4a09-a1eb-57e1676adbbe)
> 
> 
> ### Upload crash files
> 
> [crash-20240723T105159Z.zip](https://github.com/user-attachments/files/16347585/crash-20240723T105159Z.zip)
> 

Did you miss a step? When is the junction added to the no-junction road?

**Comment by JGRennison** [comment]
This should be fixed in the next release
