### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by altheeagle** [JGRennison/OpenTTD-patches#733]
### Version of OpenTTD

0.61.0 Windows 11

### Steps to reproduce

1. Add Routing restrictions to a already build signal
2. Add an if
3. Set  Type Cargo
4. Click on Passengers
![grafik](https://github.com/user-attachments/assets/d61a4e77-c4ef-4333-9d31-ca535cd04fc1)
Game crashes with
![grafik](https://github.com/user-attachments/assets/7c553e4a-20cc-48fa-a0dc-efc875e702d3)

### Upload crash files

[crash-20240825T095315Z.log](https://github.com/user-attachments/files/16739673/crash-20240825T095315Z.log)
![crash-20240825T095315Z](https://github.com/user-attachments/assets/ae8f9025-8714-4fd5-a8ba-2f7a71f40c98)
[crash-20240825T095315Z.zip](https://github.com/user-attachments/files/16739676/crash-20240825T095315Z.zip)

**Comment by JGRennison** [comment]
Thanks, this will be fixed in the next release.
