### ISSUE TITLE
[Bug]: Leveling company owned land adjacent to seawater creates hole in ground with water above sea level

### ISSUE THREAD

**Issue by ExecThTs** [JGRennison/OpenTTD-patches#740]
### Version of OpenTTD

jgrpp-0.61.0, Windows 10

### Expected result

Being able to level company owned land adjacent to water.

### Actual result

Seawater is created on land, above sea level.  
"Land area information" is not considered to be water:  
![image](https://github.com/user-attachments/assets/e3a25ff0-5d6a-41f4-800f-f39f6634b02c)
![image](https://github.com/user-attachments/assets/d20d5918-d165-458c-8bc6-e82c2d2787b8)

### Steps to reproduce

1. Buy land adjacent to seawater:  
![image](https://github.com/user-attachments/assets/7d23870a-ba17-49dc-b1fa-61487ec43153)  
2. Level company owned land:  
![image](https://github.com/user-attachments/assets/c55c4d3e-d88d-4c7c-985c-96c410a1aeb2)  
2.1. Testing if area is indeed seawater by trying to put rails down:  
![image](https://github.com/user-attachments/assets/de7a7df0-ce29-4388-9e47-6d986e6deef9)  
2.2. Destroy part of seawater-on-land (creates canal):  
![image](https://github.com/user-attachments/assets/4b08347b-99f5-49bd-8689-ace29f631899)  
3. Destroy the whole thing to restore land:  
![image](https://github.com/user-attachments/assets/0aec1a7f-0091-44ff-b0ff-e826fa4a0b62)

(I was able to reproduce the issue while disabling all NewGRFs.  
Happens on any tested seed, here's one to confirm: 2061722395  
Generation settings:  
![image](https://github.com/user-attachments/assets/b9747764-23aa-4e0a-aa29-3ad8834a27fa)
)

Edit:  I was *not* able to reproduce it in the vanilla 14.1-windows-win64 release.

**Comment by JGRennison** [comment]
Thanks, this will be fixed in the next release
