### ISSUE TITLE
[Bug]: presignals do not show in UI

### ISSUE THREAD

**Issue by mmtunligit** [JGRennison/OpenTTD-patches#747]
### Version of OpenTTD

jgrpp 0.61.0, win64

### Expected result

I have the "show signal types" set as "all visible" and I expect to see the pre-signals and path signals

### Actual result

I only see the basic block signal, path signals, and the no-entry signal
![image](https://github.com/user-attachments/assets/abb89fcb-7138-42a9-babb-de3c98d3ce24)

### Steps to reproduce

This happens across all savegames, the one here is one I quickly spun up so I can share my exact settings
[example.zip](https://github.com/user-attachments/files/16948467/example.zip)

**Comment by JGRennison** [comment]
See the setting text for the train braking model setting or https://github.com/JGRennison/OpenTTD-patches/wiki/Realistic-braking.
Pre-signals are not compatible with realistic braking.
