### ISSUE TITLE
Trunk Bugfix: GSTown.SetGrowthRate

### ISSUE THREAD

**Issue by Tahvohck** [JGRennison/OpenTTD-patches#75]
There was an issue enforcing the pre-conditions for GSTown.SetGrowthRate(). Review issue https://github.com/OpenTTD/OpenTTD/issues/7112
This will obviously be fixed next time the project is synced with trunk, but I'm unsure of how often that's done.

**Comment by JGRennison** [comment]
I've just done the synchronisation with trunk, and so this fix should be included and able to be tested.
