### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Su1phur** [JGRennison/OpenTTD-patches#755]
### Version of OpenTTD

jgrpp 0.61.0 Win 11

### Steps to reproduce

Unknown. Happened when selecting Cargo in If statement when Signal Programming

### Upload crash files

[crash-20240916T165710Z.zip](https://github.com/user-attachments/files/17016843/crash-20240916T165710Z.zip)

**Comment by JGRennison** [comment]
This is fixed already, see #733.
