### ISSUE TITLE
[Bug]: Automated timetables recording travel times for the current order when the vehicle was sent to the depot

### ISSUE THREAD

**Issue by Vuurniac** [JGRennison/OpenTTD-patches#757]
### Version of OpenTTD

0.62.0, Win10

### Expected result

Whenever vehicles are explicitly sent with a button press to the depot for refurbishment or to stop, the automatic timetable updates should ignore updating the travel time for the current order as it is no longer a valid/real travel time.

### Actual result

Currently automatic timetables record the the time the vehicle spent in the depot due to a "Sent to depot" button command that was issued. When the vehicle is next released to continue it goes to the current order and then updates the travel time, which includes all the time the vehicle spent in the depot. This causes vehicles to suddenly think they are running very early as the travel time becomes unrealistically long. The consequences are that vehicles end up sitting in place for extended periods of time and massive traffic jams form, which in turn, causes other vehicles to update their own timetables with an unrealistic travel time somewhere.

### Steps to reproduce

1. Create a group of a few vehicles with the same order list running to a few stations (Automatic timetables + Scheduled dispatch)
2. After some time, order the group to go to the depot
3. Wait for at least a few minutes of real time
4. Order the group to start
5. Watch for a traffic jam forming somewhere caused by a very long recorded travel time

![image](https://github.com/user-attachments/assets/b4fd6207-79cf-4fd7-a1ab-1abcff123a91)

**Comment by JGRennison** [comment]
Thanks, this should be resolved in the next release.
