### ISSUE TITLE
[Bug]: Can't turn back on "Fund Buildings" setting in savegame

### ISSUE THREAD

**Issue by NicholasRB** [JGRennison/OpenTTD-patches#762]
### Version of OpenTTD

0.62.0

### Expected result

The "Fund Buildings" setting turns back on when toggling it

### Actual result

I toggle it on and after saving, it wipes the setting and sets it back to OFF when I had just turned it ON.

### Steps to reproduce

1. Load any savegame with the setting off. 2. Change it to ON in settings. 3. Load it again and see if it actually changed or not.

**Comment by NicholasRB** [comment]
(Unless this is because of the game script I remembered I'm running: New Renewed Village Growth)

**Comment by JGRennison** [comment]
Yes, this and some other settings are changed by that script.
