### ISSUE TITLE
[Bug]: Town selector in building tools doesn't work again

### ISSUE THREAD

**Issue by kedzior3** [JGRennison/OpenTTD-patches#765]
### Version of OpenTTD

0.62.0

### Expected result

I except possible to place building in optional selector for all avaiable cities, to create clearly correct border areas.

This issue and ideas was told in other topic: https://github.com/JGRennison/OpenTTD-patches/issues/628

### Actual result

For now building selector shows buildings in a row, and I can't build a building for chosen city by hold CTRL button. It has been set up by default nearest city.

### Steps to reproduce

Please bring back a 'Select town' option for buildings.
![obraz_2024-10-12_201501236](https://github.com/user-attachments/assets/1b814a5d-40d3-4b17-b578-d44bb3ad590b)

**Comment by JGRennison** [comment]
The window and implementation were replaced with the upstream implementation when that was merged. 
I can look into reimplementing this in due course.

**Comment by JGRennison** [comment]
This is re-implemented now

**Comment by kedzior3** [comment]
What about implement it to the industries? ;)
