### ISSUE TITLE
Ships not able to dock at the same time to oil field.

### ISSUE THREAD

**Issue by dorobouNeko** [JGRennison/OpenTTD-patches#77]
## Version of OpenTTD
openttd jgrpp-0.29.2
## Expected result
Incoming ship to go around already docked ship(s) and dock next to it
## Actual result
Ship doesn't seem to able to find path and goes in circles until docking spot gets unoccupied
## Steps to reproduce
Ships avoid collisions: On
Forbid 90 turns: On
Pathfinder for ships: YAPF (Recommended)

I'll attach a save file in case i am missing something else. The problem can be spotted at Windwood Field when the oil ship is docked waiting for full cargo and the ship with eng. supplies can't dock at the same time.

edit: removed corrupted savefile

**Comment by JGRennison** [comment]
The savegame archive which you've attached seems to be invalid.
Once unpacked the file is only 45 bytes.

**Comment by dorobouNeko** [comment]
The savefile was corrupted and can't seem to find a game where this is happening. Will upload a save as soon as i find another occurrence of this

**Comment by dorobouNeko** [comment]
[savefile.tar.gz](https://github.com/JGRennison/OpenTTD-patches/files/2895706/savefile.tar.gz)
@ Fort Malbury Field

**Comment by dorobouNeko** [comment]
By the way a quick workaround i found was to put a buoy just next to the ship so it goes to the side of the already docked ship.

**Comment by JGRennison** [comment]
Thanks for the savegame, I've committed a fix which allows the ship to load at the oil rig.
