### ISSUE TITLE
[Bug]: Last vehicle max speed isn't said to be clamped

### ISSUE THREAD

**Issue by jostephd** [JGRennison/OpenTTD-patches#772]
### Version of OpenTTD

jgrpp-0.63.0-2-g73dbed7e2

### Expected result

The "Max speed of last vehicle" should say "643 km/h", or at least "more than 256 km/h".

### Actual result

It says "Max speed of last vehicle: 256 km/h".

That's confusing, because that's not the speed limit of any relevant piece of infrastructure (engine, wagons, track).

### Steps to reproduce

1. Set the `Station ratings tooltip` preference to `Detailed`.
2. Get a Lev4 maglev train to pick up cargo at a station and leave the station.
3. Wait a few seconds for that station to get a cargo rating for that cargo.
4. See what the cargo rating tooltip says.

**Comment by JGRennison** [comment]
This is how the ratings algorithm works, the speed field for this is one byte. The details mode is to display what is recorded and goes into the algorithm.
There isn't any plan to record additional information or make fields wider just for the tooltip.

**Comment by jostephd** [comment]
Thanks for explaining. I understand the speed is capped to 256 km/h because internally it's a `uint8_t`, and I'm not asking to make the field wider just for this. However, is there any chance of rephrasing the tooltip? As it stands it gives the impression that the train's speed is 256 km/h, even though it's actually traveling at over double the speed. Just to change "256 km/h" to "at least 256 km/h" in the tooltip text is what I'm asking.

Actually, for me it said "4.6 tiles/sec", so I didn't even have the hint that something powers-of-two-y was going on...

Anyway, it's not a biggie, feel free to close if you disagree.

**Comment by JGRennison** [comment]
That makes sense, I've made a change along these lines, it'll be in the next release.

**Comment by jostephd** [comment]
Thank you!
