### ISSUE TITLE
[Crash]: Unable to start 0.63 or 0.63.1 on mac 10.15

### ISSUE THREAD

**Issue by cwoodcock** [JGRennison/OpenTTD-patches#774]
### Version of OpenTTD

0.63/0.63.1 - Mac OS X 10.15.7

### Steps to reproduce

Before I get into details worth saying I ran upstream's `20241111-master-gce64d5f5d9` nightly which worked fine.  It is a little ahead of your master branch and a compile flag tweak has appeared in the interim.  So it's probably best to treat this issue as FYI only as it may already be fixed by happy coincidence.  I'll update/close as appropriate whenever a release that includes `e5edfba` lands.

The linker is complaining about a missing core symbol and aborting.

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: __ZTTNSt3__114basic_ofstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Applications/OpenTTD 2.app/Contents/MacOS/openttd
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/OpenTTD 2.app/Contents/MacOS/openttd
```
But it is telling fibs

```
% c++filt __ZTTNSt3__114basic_ofstreamIcNS_11char_traitsIcEEEE
VTT for std::__1::basic_ofstream<char, std::__1::char_traits<char> >
```

### Upload crash files

[ottd_crash.zip](https://github.com/user-attachments/files/17710618/ottd_crash.zip)

**Comment by JGRennison** [comment]
`e5edfba` looks like it is only relevant to clang on Windows/with MSVC, and only changes diagnostic message output. Applying it is unlikely to resolve this issue.
I'll look into this more soon.

**Comment by JGRennison** [comment]
[openttd-jgrpp-0.63.1-H2d531249-macos-universal.dmg.zip](https://github.com/user-attachments/files/17722271/openttd-jgrpp-0.63.1-H2d531249-macos-universal.dmg.zip)
Would you mind testing whether this works?
