### ISSUE TITLE
[Bug]: Can't connect to admin socket

### ISSUE THREAD

**Issue by Tintinfan** [JGRennison/OpenTTD-patches#779]
### Version of OpenTTD

0.63.1

### Expected result

<Buffer 14 00 00 74 65 74 73 75 00 74 65 74 73 75 62 6f 74 00 30 00>
<Buffer 08 00 03 01 ff ff ff ff>
<Buffer 07 00 02 05 00 40 00>
<Buffer 07 00 02 01 00 40 00>

Connects to server admin port with password "tetsu" and admin client name "tetsubot" on versions before 0.63.0

### Actual result

dbg: [net:1] [admin] The admin '' () made an error and has been disconnected: 'not authorized'
dbg: [net:3] [admin] '' () has disconnected

Sadly, no more debug level gives any feedback. The fact the debug didn't even get the admin client name suggests to me that the passed information isn't being understood as it used to be in versions before 0.63?

### Steps to reproduce

Run a dedicated server >=0.63.0
Connect to server admin port

**Comment by JGRennison** [comment]
This is most likely because of https://github.com/OpenTTD/OpenTTD/pull/11878.
See also #771.

If you change `allow_insecure_admin_login` to `true` in the config file the problem should go away.

**Comment by Tintinfan** [comment]
> This is most likely because of [OpenTTD/OpenTTD#11878](https://github.com/OpenTTD/OpenTTD/pull/11878). See also #771.
> 
> If you change `allow_insecure_admin_login` to `true` in the config file the problem should go away.

Oh I feel silly! I searched the main Github for various related words to no avail regarding this problem for a good while. This solved it. Many thanks. :)
