### ISSUE TITLE
[Bug]: Game warned "destroying an important structure" when destroying other companies' stations

### ISSUE THREAD

**Issue by WenSimEHRP** [JGRennison/OpenTTD-patches#784]
### Version of OpenTTD

0.63.1

### Expected result

Game would warn "cannot destroy, owner is ..."

### Actual result

Game warns "Are you sure to destroy an important structure?", which causes confusion.

### Steps to reproduce

1. Start a new game with an AI
2. Try to destroy the AI's station

**Comment by JGRennison** [comment]
This should be fixed in the next release

**Comment by WenSimEHRP** [comment]
Fixed by 97b990c7e20ce4bb6cdca5bbe1ee10a02de72a93
