### ISSUE TITLE
[Bug]: Expenses instead of income. What to do?

### ISSUE THREAD

**Issue by Burinis** [JGRennison/OpenTTD-patches#789]
OpenTTD JGRPP 0.63.2 is installed. CashDrainGS is installed as a game script. There are also many NewGRF (screenshots of the list are attached).
This is the situation: I pick up the outgoing cargo from station A and deliver it to the receiving station B, but instead of income I get expenses. Even without game scripts this cannot be solved. What to do?
[Video](https://youtu.be/wSWXeQsFWtE)
I also read somewhere that the vehicle pays a penalty for slow delivery. How to cancel the fines?
![Снимок экрана (2372)](https://github.com/user-attachments/assets/314a8f5f-75bc-42e2-9800-1bf11125d30c)
![Снимок экрана (2373)](https://github.com/user-attachments/assets/1b2fcc3e-97ab-4d8f-a46f-9c1a0a8e0a17)
![Снимок экрана (2374)](https://github.com/user-attachments/assets/2334329e-1d33-4333-87ef-b2bcb7e55f2b)
![Снимок экрана (2375)](https://github.com/user-attachments/assets/c974a54f-744a-4fc3-b56a-5dc7096ee281)
[save](https://1drv.ms/u/c/0f16cf81badf5a83/EWYWHA4T_NpEsizBZYBiFTIBL9hb_llpZ7d9_U2jrY96Uw?e=yRzjqn)

**Comment by JGRennison** [comment]
You are using the "buy, process, sell" NewGRF which specifically makes the payment for this cargo negative. If this is not what you want you should not use this GRF.
In general you probably don't needs this many GRFs and you should check what each of them do.

**Comment by Burinis** [comment]
> You are using the "buy, process, sell" NewGRF which specifically makes the payment for this cargo negative.

Okay, I've already started a new game, having previously deleted this NewGRF, and the problem is solved: the income has become stable.
