### ISSUE TITLE
[Bug]: Industries no longer produce or accept any cargo when loading an old save

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#794]
### Version of OpenTTD

JGRPP 0.63.2 on Windows 10, 64-bit

### Expected result

Industries in the attached savegame continue to produce and accept the correct cargoes.

### Actual result

Industries in the attached savegame no longer produce or accept any cargo, and will close within two months/minutes of loading. Any industries built after loading produce and accept the correct cargoes.

### Steps to reproduce

Load the attached savegame, open the window for any of the industries on the map, and wait two months/minutes.
[crash20241227133016.zip](https://github.com/user-attachments/files/18260658/crash20241227133016.zip)

**Comment by JGRennison** [comment]
This should be fixed in the next release
