### ISSUE TITLE
Compile warning for japanese.txt

### ISSUE THREAD

**Issue by auge8472** [JGRennison/OpenTTD-patches#80]
## Version of OpenTTD

JGRPP 0.30.1

## Expected result

No compile warning or error

## Actual result

Got a compile warning for japanese.txt.

```
[LANG] Compiling language japanese
/home/auge/Projekte/OpenTTD-patches/src/lang/japanese.txt:1804: warning: STR_LIVERY_CAPTION: Param idx #0 '<empty>' doesn't match with template command 'COMPANY'
```

I report this here because you mentioned a japanese translation in [the development thread on tt-forums.net](https://www.tt-forums.net/viewtopic.php?f=33&t=73469) I didn't notice before. Is it new?

## Steps to reproduce

Compile the PP under Ubuntu 16.04.6.

**Comment by JGRennison** [comment]
The issue is in the text from the translator, which was added relatively recently. It was minor enough that I'd just been ignoring it so far.
I've modified the text now in 99055c22cb73202cfa0c0c4ab3b56a2b6386d1cc so that the warning should go away.

**Comment by auge8472** [comment]
I compiled 0.31.0 today and the warning has gone.
