### ISSUE TITLE
./Confirgure not working in mac 0.30.1

### ISSUE THREAD

**Issue by ecolortest** [JGRennison/OpenTTD-patches#81]
Version of OpenTTD: 0.30.1

help its not working compile ./configure in mac its show error

WARNING: The path contains a non-alphanumeric character that might cause
         failures in subsequent build stages. Any failures with the build
         will most likely be caused by this.
./configure: line 44: .: /Users/okansp/OpenTTD-patches-jgrpp: is a directory
./configure: line 71: set_default: command not found
./configure: line 72: detect_params: command not found
./configure: line 73: check_params: command not found
./configure: line 74: save_params: command not found
./configure: line 75: make_cflags_and_ldflags: command not found
./configure: line 147: 
	{  }
	/^(	*)#end/  { if (deep == skip) { skip -= 1; } deep -= 1; next; }
	/^(	*)#else/ { if (deep == skip) { skip -= 1; } else if (deep - 1 == skip) { skip += 1; } next; }
	/^(	*)#if/   {
		gsub("	", "", $0);
		gsub("^#if ", "", $0);

		if (deep != skip) { deep += 1; next; }

		deep += 1;

		if ($0 == "ALLEGRO"     && "" == "")      { next; }
		if ($0 == "SDL"         && "" == "")          { next; }
		if ($0 == "PNG"         && "" == "")          { next; }
		if ($0 == "OSX"         && "" != "OSX")               { next; }
		if ($0 == "OS2"         && "" != "OS2")               { next; }
		if ($0 == "DEDICATED"   && "" != "1")   { next; }
		if ($0 == "AI"          && "" == "0")          { next; }
		if ($0 == "COCOA"       && "" == "0")         { next; }
		if ($0 == "HAIKU"       && "" != "HAIKU")             { next; }
		if ($0 == "WIN32"       && "" != "MINGW" &&
		                 "" != "CYGWIN" && "" != "MSVC") { next; }
		if ($0 == "MSVC"        && "" != "MSVC")              { next; }
		if ($0 == "DIRECTMUSIC" && "" == "0")  { next; }
		if ($0 == "FLUIDSYNTH"  && "" == "" )         { next; }
		if ($0 == "USE_XAUDIO2" && "" == "0")       { next; }
		if ($0 == "USE_THREADS" && "" == "0")       { next; }
		if ($0 == "USE_SSE"     && "" != "1")           { next; }

		skip += 1;

		next;
	}
	/^(	*)#/ { next }
	/^$/ { next }
	/\.h$/ { next }
	/\.hpp$/ { next }
	{
		if (deep == skip) {
			gsub("	", "", $0);
			print $0;
		}
	}
: File name too long
./configure: line 149:  { ORS = " " } /\.c$/   { gsub(".c$",   ".o", $0); print $0; }: No such file or directory
./configure: line 150:  { ORS = " " } /\.cpp$/ { gsub(".cpp$", ".o", $0); print $0; }: No such file or directory
./configure: line 151:  { ORS = " " } /\.mm$/  { gsub(".mm$",  ".o", $0); print $0; }: No such file or directory
./configure: line 152:  { ORS = " " } /\.rc$/  { gsub(".rc$",  ".o", $0); print $0; }: No such file or directory
./configure: line 153:  { ORS = " " } { print $0; }: command not found
./configure: line 164: generate_main: command not found
./configure: line 165: generate_lang: command not found
./configure: line 166: generate_settings: command not found
./configure: line 167: generate_grf: command not found
./configure: line 168: generate_src: command not found
WARNING: The path contains a non-alphanumeric character that might cause
         failures in subsequent build stages. Any failures with the build
         will most likely be caused by this.

**Comment by JGRennison** [comment]
I don't have a Mac to test on. Can you confirm that compiling upstream
master/trunk works on your setup?

>

**Comment by ecolortest** [comment]
> I don't have a Mac to test on. Can you confirm that compiling upstream master/trunk works on your setup?
> […](#)

im just compile like this: https://wiki.openttd.org/Compiling_on_Mac_OS_X#Compiling_the_source

**Comment by ecolortest** [comment]
solved: im remove space and work (WARNING: The path contains a non-alphanumeric character that might cause
failures in subsequent build stages. Any failures with the build
will most likely be caused by this.)
