### ISSUE TITLE
Crash on Selecting Download Graphics

### ISSUE THREAD

**Issue by Bureaucromancer** [JGRennison/OpenTTD-patches#83]

**Comment by Bureaucromancer** [comment]
[crash.log](https://github.com/JGRennison/OpenTTD-patches/files/3053111/crash.log)

**Comment by Bureaucromancer** [comment]
Somehow KDE related - was working on Manjaro GNOME yesterday.

**Comment by JGRennison** [comment]
Thanks for reporting this, it should be fixed by 74e5e047242206b3bbca9560b7caef1f969cc0f5

**Comment by Bureaucromancer** [comment]
Confirmed that that's fixed it.

**Comment by JGRennison** [comment]
Thanks
