### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by ZJFishy** [JGRennison/OpenTTD-patches#84]
## Version of OpenTTD
30.2
## Expected result
Demolishing building / buying a train / zooming out
## Actual result
Game crashes
## Steps to reproduce
I'm not sure how to reproduce the crashing, since it seems to be fairly random. This behavior has happened a few times, once when demolishing a building, another time when buying a train, and a third when simply zooming out. Also, these all happened within ~5 minutes of opening the game.

**Comment by dga711** [comment]
Crashing too on version 30.1 (can't compile 30.2 for myself).

Its just random with not much stuff built yet. I'm on Win10 x64.

Only thing I see in the log is: _FATAL: Recursive locking of non-recursive mutex detected. Throwing system exception_

[dumps.zip](https://github.com/JGRennison/OpenTTD-patches/files/3070981/dumps.zip)

**Comment by JGRennison** [comment]
Thanks for reporting this, it should be fixed in 0.30.3
