### ISSUE TITLE
Game crash if click 'Find Server' button

### ISSUE THREAD

**Issue by ecolortest** [JGRennison/OpenTTD-patches#85]
jgrpp-0.30.3

its crash if click find server button in mutiplayer menu

[crash.log](https://github.com/JGRennison/OpenTTD-patches/files/3087801/crash.log)
![crash](https://user-images.githubusercontent.com/34646054/56258880-161cd180-610c-11e9-88fe-eb81a619947b.png)

**Comment by JGRennison** [comment]
This looks similar to the report in this thread: https://www.tt-forums.net/viewtopic.php?p=1220700
Neither crash logs are especially helpful, unfortunately.
I can't reproduce any issue on Linux.

Any chance you could rebuild using:
`CFLAGS="-no-omit-frame-pointer" ./configure --enable-debug`
and try to reproduce the issue again?

Many thanks.

**Comment by ecolortest** [comment]
> This looks similar to the report in this thread: https://www.tt-forums.net/viewtopic.php?p=1220700
> Neither crash logs are especially helpful, unfortunately.
> I can't reproduce any issue on Linux.
> 
> Any chance you could rebuild using:
> `CFLAGS="-no-omit-frame-pointer" ./configure --enable-debug`
> and try to reproduce the issue again?
> 
> Many thanks.

umm. im look that and seem also similar, her version is 1.9.1 so mybe this is a openttd bug not this patch bug???
