### ISSUE TITLE
Content downloader blank after searching for missing content

### ISSUE THREAD

**Issue by spnda** [JGRennison/OpenTTD-patches#86]
## Version of OpenTTD
OpenTTD jgrpp-0.30.3 (earlier versions also apply)

## Expected result
All GRFs/AIs/Scenarios/Heightmaps show up.
![image2](https://cdn.discordapp.com/attachments/442748131898032138/568523478421078016/unknown.png)

## Actual result
There are no items at all shown in the list.
![image](https://cdn.discordapp.com/attachments/442748131898032138/568523151894642698/unknown.png)

Short Video:
https://youtu.be/sIYk_ieEqKE

## Steps to reproduce
1. Click on "Multiplayer"
2. Search for a server which has GRFs, that are not available on BaNaNaS
3. Try to "find missing content online"
4. Click "close"
5. Go to the Online Content Downloader on the Main Menu.

**Comment by Romazoon** [comment]
i would like to add that on my side it works fine ( i tried doing exactly the same and online content worked fine). Though we were 4 on discord trying it (Mczapkie, Pnda, Gwyd and me), and i was the only one not having the problem, so the bug is real, just not happening to everyone apparently.

**Comment by JGRennison** [comment]
I have found something wrong with the content list download/request code (in `void ClientNetworkContentSocketHandler::RequestContentList(ContentVector *cv, bool send_md5sum)`).
It looks like I messed up resolving one of the merge conflicts with all the upstream container changes, I will fix this and see if any more issues were introduced along these lines.
