### ISSUE TITLE
icu 64+ is not supported

### ISSUE THREAD

**Issue by Baldomo** [JGRennison/OpenTTD-patches#87]
## Version of OpenTTD
`aur/openttd-jgrpp 0.30.3-1`
## Expected result
The game starts

## Actual result
The game does not start, with error
`openttd-jgrpp: error while loading shared libraries: libicui18n.so.63: cannot open shared object file: No such file or directory` (i18n is just the first loaded library, all other libs based on `icu` required by the game do not work either)

## Steps to reproduce
Try to start the game with `icu` version 64+ (I have `core/icu 64.1-1` installed)

**Comment by JGRennison** [comment]
I presume that you are using Arch?
Probably when you built the package you were using icu 63.
You'll need to build it again if icu 63 is no longer available as its been replaced with icu 64.

**Comment by Baldomo** [comment]
Yes I'm on Manjaro, I should have specified it. I was wondering wether icu 63 had been already replaced by 64 in the code or not. Thanks for the feedback!
