### ISSUE TITLE
Rebase on icu 58.1

### ISSUE THREAD

**Issue by archlinuxrussian** [JGRennison/OpenTTD-patches#9]
Sorry if this depends on openttd upstream and this is just noise, but I did run into this problem:

When compiling the latest master branch it stops in the provided code:

`luke@Saturn ~/A/OpenTTD-patches (jgrpp)> make
make[1]: Entering directory '/home/luke/Applications/OpenTTD-patches/objs/lang'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/luke/Applications/OpenTTD-patches/objs/lang'
make[1]: Entering directory '/home/luke/Applications/OpenTTD-patches/objs/setting'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/luke/Applications/OpenTTD-patches/objs/setting'
make[1]: Entering directory '/home/luke/Applications/OpenTTD-patches/objs/extra_grf'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/luke/Applications/OpenTTD-patches/objs/extra_grf'
make[1]: Entering directory '/home/luke/Applications/OpenTTD-patches/objs/release'
[SRC] Compiling fontcache.cpp
In file included from /home/luke/Applications/OpenTTD-patches/src/fontcache.cpp:20:0:
/home/luke/Applications/OpenTTD-patches/src/gfx_layout.h:23:36: fatal error: layout/ParagraphLayout.h: No such file or directory
 #include "layout/ParagraphLayout.h"
                                    ^
compilation terminated.
make[1]: *** [Makefile:239: fontcache.o] Error 1
make[1]: Leaving directory '/home/luke/Applications/OpenTTD-patches/objs/release'
make: *** [Makefile:57: all] Error 1
`

Also, when trying to run the game as-is, it shows a dependency on icu 57
`
luke@Saturn ~/A/OpenTTD-patches (jgrpp) [2]> ./bin/openttd 
./bin/openttd: error while loading shared libraries: libiculx.so.57: cannot open shared object file: No such file or directory
`
Again, if this is out of your hands, I apologise for creating extra noise to filter through. Just wanted to let you know about it :)

**Comment by JGRennison** [comment]
I presume you're running this on Arch?
If you've done an upgrade since you last ran ./configure, you may need to run it again. The configure script should detect if you have icu-lx installed, and what version to use.

**Comment by archlinuxrussian** [comment]
Oh. Haha that worked. Sorry for the noise! Thanks though :)
