### ISSUE TITLE
Feature request: Conditional order on amount of waiting of cargo

### ISSUE THREAD

**Issue by dorobouNeko** [JGRennison/OpenTTD-patches#90]
I wanted to make feature request for having conditional orders not just on waiting cargo but specify amount. I wanted to code it myself since it should be similar to the load percentage conditional order but i realized this new feature would need to make a comparison with 2 values, the type of cargo AND the amount. Looking at the code i am not sure how to do this since i think (?) orders store only a single value for conditional orders.
If you prefer this to be posted on the forums let me know.

**Comment by JGRennison** [comment]
Take a look at struct OrderExtraInfo (via Order::extra), and its uses in OCV_SLOT_OCCUPANCY/OCV_TRAIN_IN_SLOT. There are plenty of Order bits available in there which you could use.
I would expect that the most problematic part of this would be modifying the order GUI, as you would conditionally need an extra button for the second value.

**Comment by dorobouNeko** [comment]
I'll see what i can do then. Also this would make the waiting cargo order redundant. Would you prefer this replaces that one?
