### ISSUE TITLE
Latest (0.32.2) can't be compiled under MSVC

### ISSUE THREAD

**Issue by Pannoniae** [JGRennison/OpenTTD-patches#93]
## Version of OpenTTD
0.32.2 and master (tried with both)
## Expected result
The project compiles without errors.
## Actual result
It spews approximately 20 errors mostly related to crashlog_win.cpp/h, complaining about std::string and std::tie not found.
## Steps to reproduce
1. Download 0.32.2 release or master from GitHub
2. Open VS2017 and open the 141.sln in projects
3. Set it to x64/release (although it also doesn't work with debug/x86 but the readme said to switch it on release)
4. Watch it failing to compile

The relevant errors:
8>------ Build started: Project: openttd, Configuration: Release x64 ------
8>tilearea.cpp
8>crashlog_win.cpp
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\tilearea_type.h(68): error C2039: 'tie': is not a member of 'std' (compiling source file ..\src\tilearea.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\stdafx.h(250): note: see declaration of 'std' (compiling source file ..\src\tilearea.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\tilearea_type.h(68): error C3861: 'tie': identifier not found (compiling source file ..\src\tilearea.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\crashlog.h(131): error C2039: 'string': is not a member of 'std' (compiling source file ..\src\os\windows\crashlog_win.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\stdafx.h(250): note: see declaration of 'std' (compiling source file ..\src\os\windows\crashlog_win.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\crashlog.h(131): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\src\os\windows\crashlog_win.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\crashlog.h(131): error C2143: syntax error: missing ',' before '*' (compiling source file ..\src\os\windows\crashlog_win.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\crashlog.h(141): error C2039: 'string': is not a member of 'std' (compiling source file ..\src\os\windows\crashlog_win.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\stdafx.h(250): note: see declaration of 'std' (compiling source file ..\src\os\windows\crashlog_win.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\crashlog.h(141): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\src\os\windows\crashlog_win.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\crashlog.h(141): error C2143: syntax error: missing ',' before '*' (compiling source file ..\src\os\windows\crashlog_win.cpp)
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\os\windows\crashlog_win.cpp(616): error C2511: 'void CrashLog::DesyncCrashLog(const std::string *,std::string *)': overloaded member function not found in 'CrashLog'
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\crashlog.h(18): note: see declaration of 'CrashLog'
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\os\windows\crashlog_win.cpp(618): error C2660: 'CrashLog::MakeDesyncCrashLog': function does not take 2 arguments
8>d:\projects\programming\openttd\openttd-patches-jgrpp-0.31.2\src\crashlog.h(131): note: see declaration of 'CrashLog::MakeDesyncCrashLog' (compiling source file ..\src\os\windows\crashlog_win.cpp)
8>Done building project "openttd_vs141.vcxproj" -- FAILED.
9>------ Skipped Build: Project: regression, Configuration: Debug Win32 ------
9>Project not selected to build for this solution configuration 
========== Build: 6 succeeded, 1 failed, 0 up-to-date, 2 skipped ==========

**Comment by Pannoniae** [comment]
I've tried older versions and they have different errors (but still not compiling)

**Comment by JGRennison** [comment]
Thanks for reporting this, I've pushed a1cf3358fe452886f9063ec5f18545579512f31b, 94f705e45e851e72b81f844b2186d11dce47f4a8. Could you do a pull to include these and try again?
Thanks.

**Comment by Pannoniae** [comment]
Nice! Those errors have disappeared, however a new one has appeared, complaning about lzma (?, it seems to be installed with vcpkg...)

8>crashlog.obj : error LNK2001: unresolved external symbol __imp_lzma_version_string
8>textfile_gui.obj : error LNK2001: unresolved external symbol __imp_lzma_end
8>textfile_gui.obj : error LNK2001: unresolved external symbol __imp_lzma_code
8>textfile_gui.obj : error LNK2001: unresolved external symbol __imp_lzma_auto_decoder
8>saveload.obj : error LNK2001: unresolved external symbol __imp_lzma_easy_encoder
8>D:\Projects\Programming\OpenTTD\JGR-master\projects\..\objs\x64\Release\openttd.exe : fatal error LNK1120: 5 unresolved externals

It's probably because previously it did not get to this stage ;)

**Comment by JGRennison** [comment]
You may need to install liblzma using vcpkg.
The commands here may be useful: https://github.com/OpenTTD/OpenTTD/blob/master/docs/Readme_Windows_MSVC.md#openttd-dependencies

**Comment by Pannoniae** [comment]
It's already installed. All of them.

**Comment by JGRennison** [comment]
This could be related to this fix: https://github.com/OpenTTD/OpenTTD/commit/846fc8fe097689ef2fa1498708b3244fb4ad84ac
I've cherry-picked this commit, could you try compiling again.

**Comment by Pannoniae** [comment]
After fixing the libucrt.lib path in a few places (the solution uses the 8.1 SDK while I use Windows 10), it works.

Thank you <3

**Comment by ras0219-msft** [comment]
I've also opened https://github.com/microsoft/vcpkg/pull/7226 to fix this upstream in vcpkg :)
