### ISSUE TITLE
Save File Corrupted/Won't Open

### ISSUE THREAD

**Issue by twmcmahan** [JGRennison/OpenTTD-patches#94]
## Version of OpenTTD
openttd-custom-jgrpp-0.31.1-MINGW-win64
## Actual result
Save File Corrupted/Won't Open

I've tried all 9 Auto Save files as well.

## Steps to reproduce
Attached Save File & Crash Report
[Full Network.zip](https://github.com/JGRennison/OpenTTD-patches/files/3378963/Full.Network.zip)

[crash dump.txt](https://github.com/JGRennison/OpenTTD-patches/files/3378956/crash.dump.txt)

**Comment by JGRennison** [comment]
This type of corruption should be already resolved in 0.31.2.
I will add some further checks to the next release.

I've attached a fixed savegame which should be loadable in 0.31.1 and later

[Ganingstone Transport, 2070-02-28.sav.zip](https://github.com/JGRennison/OpenTTD-patches/files/3379983/Ganingstone.Transport.2070-02-28.sav.zip)
