### ISSUE TITLE
Cannot configure on Fedora 30, icu-lx couldn't be found

### ISSUE THREAD

**Issue by UntouchedWagons** [JGRennison/OpenTTD-patches#95]
## Version of OpenTTD

0.32-rc1

## Expected result

Unknown

## Actual result

`checking icu-lx... not found`
`configure: error: pkg-config icu-lx couldn't be found`
`configure: error: you supplied '2', but it seems invalid`

## Steps to reproduce

Since upgrading to Fedora 30 I'm not able to configure the JGR patch pack:

`git pull`
`git checkout tags/jgrpp-0.32-rc1`
`./configure --binary-dir=bin --binary-name=openttd-jgrpp --with-sdl --with-zlib --with-liblzma --with-liblzo2 --with-png --with-freetype --with-fontconfig --with-icu`

This configure command fails because it's not able to find the icu-lx package. I've got `libicu-devel` installed. I'm not sure where the "you supplied '2'" comes from.

**Comment by UntouchedWagons** [comment]
Hmm if I leave off `--with-icu` it configures fine, it's able to find the one icu library, but not ixu-lx. I dunno.

**Comment by SJang1** [comment]
Just try ./configure, It worked fine at all for me.
```
checking icu-lx... not found
checking icu-i18n... found
```
