### ISSUE TITLE
Disconnected(desync) when wagon is attached (with NewGRF)

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#97]
## Version of OpenTTD
jgrpp-0.31.4

## Issue
When I buy and attach L0 Shinkansen's passenger coach (Maglev) from RIMS, the multiplay game is disconnected by desync.

## Steps to reproduce
1. Use RIMS newgrf
2. Buy ``L0 Series Shinkansen`` locomotive, it is fine until now.
3. Buy ``L0 - Passenger Coach``, then it is attached to the train in (2), and it disconnects right after.

## Desync files
[desync-client-20190827T134058Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/3546406/desync-client-20190827T134058Z.zip)

**Comment by JGRennison** [comment]
Thanks, this should be fixed now. I will do another release soon.
