### ISSUE TITLE
Line heights are too narrow

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#98]
## Version of OpenTTD
jgrpp-0.32-rc4

## Expected result
![image](https://user-images.githubusercontent.com/10726524/65382992-4a468f00-dd49-11e9-9474-b1700d64c87c.png)

## Actual result
![image](https://user-images.githubusercontent.com/10726524/65382978-22572b80-dd49-11e9-80d4-c77f9e0e729e.png)
![image](https://user-images.githubusercontent.com/10726524/65382983-300cb100-dd49-11e9-99e9-3fb48e508f02.png)

## Steps to reproduce
Change into CJK language or change ``small/medium/large_font`` setting in custom

It seems that it uses the default font sprite's height

**Comment by JGRennison** [comment]
Could you try 0.32-rc5?

**Comment by telk5093** [comment]
Fine, fixed.
