### ISSUE TITLE
Serious fault condition occurred in the game

### ISSUE THREAD

**Issue by timc6896** [JGRennison/OpenTTD-patches#99]
Crashed occurred when trying to remove a signal to a tunnel.  The trains would stop in front of the tunnel with no obstruction ahead.  I tried to remove the tunnel to see if the trains will move forward and this caused the crash.  I've noticed this isn't the only time.  Trains were getting stuck before in other places and when trying to remove the signal always trigger this crash.  Never had this problem before.

*** OpenTTD Crash Report ***

Crash at: Tue Oct 01 20:53:56 2019
In game date: 2426-08-12 (41, 1)
Game loaded at: 2426-08-09 (28, 0), Tue Oct 01 20:53:34 2019

Crash reason:
 Exception: C0000005
 Location:  000000000059D2F6
 Message:   <none>

Within context:
     0: DoCommandP: tile: 116B662 (5730 x 2229), p1: 0x1, p2: 0x0, company: 0 (Little Brunway Transport), cmd: 0x11540009 (CmdRemoveSingleSignal), my_cmd: 1

OpenTTD version:
 Version:    jgrpp-0.31.3 (0)
 NewGRF ver: 1a006d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Jul 13 2019 18:25:42
 Configure:  ./configure --host=x86_64-w64-mingw32 --prefix=/home/jgr/mingw64/ CFLAGS=-I/home/jgr/mingw64/include LDFLAGS=-L/home/jgr/mingw64/lib --without-sdl --without-icu --with-lzo2=/home/jgr/mingw64/lib/liblzo2.a --without-uniscribe

Stack trace:
 00000000 00000000 00000001 00000000 0116B662 00000000 00474484 00000000
 00000000 00000000 040EB280 00000000 040EB280 00000000 040EB280 00000000
 131A0BD0 00000000 0059F4D5 00000000 00000301 00000000 131A0D08 00000000
 00000010 00000000 00000000 00000000 00000001 00000000 004C8C09 00000000
 040EB49F 00000000 FFFFFFFF 7FFFFFFF 131A0C50 00000000 131A0C58 00000000
 040EB120 00000000 00000000 00000000 0000FFFF 00000001 00000000 00000000
 00000000 0000FFFF 0055B524 00000000 131A0BD0 00000000 131A0BD8 00000000
 131A0BD8 00000000 00000000 00000000 00000000 0000FFFF 136735E0 00007FF9
 040EB1C8 00000000 00000000 00000000 040EB3D0 00000000 00000000 00000000
 0116B662 00000000 040EB280 00000000 00DC5DA0 00000000 00000000 00000000
 00000001 00000000 0046F51D 00000000 00000002 00000000 00100000 00000000
 80004005 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 042BD5E0 00000000 1340C9C8 00007FF9 3F478996 000042AE 042C7AA0 00000000
 040EB289 00000000 00000000 00000000 00000215 00000000 00000000 00000000
 00000000 00000000 00000001 00000000 003A02EC 00000000 04D68390 00000000
 00000000 00000000 9CDCABD2 FB287F14 00DC5E78 00000000 040EB250 00000000
 00000000 00000000 00033862 00000000 0000FFFF 00000001 00000000 00000000
 00000000 0000FFFF 00000000 00000000 00000000 00000000 13645013 00007FF9
 00000000 00000000 00000000 00000000 003A02EC 00000000 006BA621 00000000
 00000215 00000000 00000000 00000000 003A02EC 00000000 00000215 00000000
 00000000 00000000 00000202 00000000 01FC03EA 00000000 00000000 00000000
 11540009 00000000 0116B662 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 00000001 00000000 040EB3D0 00000000 00470317 00000000
 54A2119E 00009283 006E4F9C 00000000 00000000 00000000 00000000 00000000

Registers:
 RAX: 0000000000000002 RBX: 00000000040EB280 RCX: 0000000000000000 RDX: 0000000000000000
 RSI: 00000000131A0BD0 RDI: 00000000131A0BD8 RBP: 00000000011CF662 RSP: 00000000040EB050
 R8:  000000001DD0C350 R9:  0000000001F347C0 R10: 000000000F85F270 R11: 0000000000000004
 R12: 0000000000033862 R13: 000000000000001A R14: 0000000000E538C8 R15: 0000000008B5B310
 RIP: 000000000059D2F6 EFLAGS: 00010206

 Bytes at instruction pointer:
 F6 81 D8 01 00 00 02 48 89 CB 74 0A 66 83 B9 42 01 00 00 00 74 24 0F B6

Operating system:
 Name:     Windows
 Release:  10.0.18362 ()
 Compiler: GCC 7.3.0 "7.3-win32 20180312"

Configuration:
 Blitter:      32bpp-sse4-anim
 Graphics set: zBase (5588)
 Language:     C:\Users\tim.RIVERDALE\Documents\openttd-custom-jgrpp-0.31.3-MINGW-win64\lang\english_US.lng
 Music driver: dmusic
 Music set:    OpenMSX (96)
 Network:      no
 Sound driver: win32
 Sound set:    OpenSFX (87)
 Video driver: win32

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

Map size: 0x2000000 (8192 x 4096)

AI Configuration (local: 0) (current: 0):
  0: Human

Libraries:
 FreeType:   2.6.0
 LZMA:       5.2.1
 LZO:        2.09
 PNG:        1.5.23
 Zlib:       1.2.8

Module information:
 C:\Users\tim.RIVERDALE\Documents\openttd-custom-jgrpp-0.31.3-MINGW-win64\openttd.exe handle: 0000000000400000 size: 48641705 crc: F3E5A383 date: 2019-07-13 17:27:25
 C:\WINDOWS\SYSTEM32\ntdll.dll handle: 00007ff913620000 size: 1999960 crc: A8FFD7F0 date: 2019-09-20 06:37:56
 C:\WINDOWS\System32\KERNEL32.DLL handle: 00007ff911b70000 size: 722288 crc: FF4820CE date: 2019-09-20 06:37:44
 C:\WINDOWS\System32\KERNELBASE.dll handle: 00007ff910a30000 size: 2762296 crc: 2F362EF8 date: 2019-09-20 06:37:56
 C:\WINDOWS\System32\ADVAPI32.dll handle: 00007ff912bc0000 size: 654912 crc: 37E52142 date: 2019-09-20 06:37:43
 C:\WINDOWS\System32\msvcrt.dll handle: 00007ff911d70000 size: 638072 crc: 162578A8 date: 2019-03-19 04:44:35
 C:\WINDOWS\System32\sechost.dll handle: 00007ff911ca0000 size: 606112 crc: 0A9F850D date: 2019-08-16 06:21:52
 C:\WINDOWS\System32\RPCRT4.dll handle: 00007ff912310000 size: 1171192 crc: 8764D214 date: 2019-03-19 04:44:36
 C:\WINDOWS\System32\GDI32.dll handle: 00007ff9116d0000 size: 147912 crc: D05A781B date: 2019-03-19 04:44:06
 C:\WINDOWS\System32\win32u.dll handle: 00007ff910710000 size: 127064 crc: 7C672E06 date: 2019-09-20 06:37:50
 C:\WINDOWS\System32\gdi32full.dll handle: 00007ff910740000 size: 1647072 crc: D0C48830 date: 2019-09-20 06:37:59
 C:\WINDOWS\System32\msvcp_win.dll handle: 00007ff9115e0000 size: 639608 crc: 978951FC date: 2019-08-16 06:21:51
 C:\WINDOWS\System32\ucrtbase.dll handle: 00007ff910ce0000 size: 1020768 crc: B6F87AB7 date: 2019-08-16 06:21:51
 C:\WINDOWS\System32\USER32.dll handle: 00007ff912800000 size: 1654520 crc: 00AAC5E3 date: 2019-08-16 06:21:47
 C:\WINDOWS\System32\IMM32.dll handle: 00007ff911d40000 size: 176360 crc: 9ABFB1A4 date: 2019-03-19 04:44:38
 C:\WINDOWS\System32\ole32.dll handle: 00007ff911e10000 size: 1395600 crc: A9A1AAED date: 2019-07-10 07:40:28
 C:\WINDOWS\System32\combase.dll handle: 00007ff911f70000 size: 3372448 crc: 7C1B47BE date: 2019-09-20 06:37:56
 C:\WINDOWS\System32\bcryptPrimitives.dll handle: 00007ff910de0000 size: 524216 crc: DFD51AB1 date: 2019-08-16 06:21:52
 C:\WINDOWS\System32\SHELL32.dll handle: 00007ff912c70000 size: 7261648 crc: BA28463B date: 2019-09-20 06:37:55
 C:\WINDOWS\System32\cfgmgr32.dll handle: 00007ff911680000 size: 293344 crc: 0DED3A7A date: 2019-03-19 04:44:35
 C:\WINDOWS\System32\shcore.dll handle: 00007ff913530000 size: 684352 crc: F474ABD7 date: 2019-03-19 04:44:21
 C:\WINDOWS\System32\windows.storage.dll handle: 00007ff910e60000 size: 7902912 crc: D711D1ED date: 2019-09-20 06:37:50
 C:\WINDOWS\System32\profapi.dll handle: 00007ff910590000 size: 110280 crc: 468DCA89 date: 2019-03-19 04:44:36
 C:\WINDOWS\System32\powrprof.dll handle: 00007ff910520000 size: 291336 crc: 5EA3DD21 date: 2019-03-19 04:44:35
 C:\WINDOWS\System32\UMPDC.dll handle: 00007ff9104f0000 size: 54960 crc: DD4A4D6A date: 2019-03-19 04:43:49
 C:\WINDOWS\System32\shlwapi.dll handle: 00007ff911c30000 size: 329200 crc: AC7F2587 date: 2019-03-19 04:45:05
 C:\WINDOWS\System32\kernel.appcore.dll handle: 00007ff910570000 size: 59088 crc: E549CD16 date: 2019-03-19 04:44:15
 C:\WINDOWS\System32\cryptsp.dll handle: 00007ff9105b0000 size: 80112 crc: 4C3EEAA9 date: 2019-03-19 04:44:33
 C:\WINDOWS\System32\WS2_32.dll handle: 00007ff912660000 size: 443424 crc: B42C183A date: 2019-03-19 04:44:36
 C:\WINDOWS\SYSTEM32\WINMM.dll handle: 00007ff90e630000 size: 129880 crc: 55B5B362 date: 2019-03-19 04:43:47
 C:\WINDOWS\SYSTEM32\winmmbase.dll handle: 00007ff90e5f0000 size: 169632 crc: 8AE99BA1 date: 2019-03-19 04:43:47
 C:\WINDOWS\system32\uxtheme.dll handle: 00007ff90e870000 size: 606208 crc: 4B9C648E date: 2019-09-20 06:37:55
 C:\WINDOWS\System32\MSCTF.dll handle: 00007ff9129a0000 size: 1261256 crc: A1C3DD1E date: 2019-09-20 06:37:55
 C:\WINDOWS\System32\OLEAUT32.dll handle: 00007ff913400000 size: 797112 crc: 5D00900C date: 2019-09-20 06:37:56
 C:\WINDOWS\SYSTEM32\TextInputFramework.dll handle: 00007ff8ffbb0000 size: 642208 crc: 03AAAE2A date: 2019-08-16 06:21:46
 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll handle: 00007ff90ab70000 size: 3327256 crc: E389630F date: 2019-07-10 07:40:25
 C:\WINDOWS\SYSTEM32\CoreMessaging.dll handle: 00007ff90e1d0000 size: 859632 crc: 31890910 date: 2019-03-19 04:44:30
 C:\WINDOWS\SYSTEM32\ntmarta.dll handle: 00007ff90f490000 size: 181856 crc: 06EC83CA date: 2019-03-19 04:44:35
 C:\WINDOWS\SYSTEM32\wintypes.dll handle: 00007ff90bf70000 size: 1393960 crc: 6E69B31C date: 2019-08-16 06:21:51
 C:\WINDOWS\SYSTEM32\iertutil.dll handle: 00007ff900260000 size: 2771520 crc: 7150D7D8 date: 2019-09-20 06:38:00
 C:\WINDOWS\system32\mswsock.dll handle: 00007ff90fd00000 size: 407544 crc: 4F05F9C0 date: 2019-03-19 04:44:33
 C:\WINDOWS\SYSTEM32\MMDevAPI.DLL handle: 00007ff909130000 size: 478264 crc: 168B8196 date: 2019-09-20 06:37:42
 C:\WINDOWS\SYSTEM32\DEVOBJ.dll handle: 00007ff9102f0000 size: 158592 crc: 69185C94 date: 2019-03-19 04:44:35
 C:\WINDOWS\SYSTEM32\wdmaud.drv handle: 00007ff8fb1d0000 size: 253952 crc: 0D3BE49A date: 2019-03-19 04:43:47
 C:\WINDOWS\SYSTEM32\AVRT.dll handle: 00007ff90b2f0000 size: 30672 crc: CC5AFD63 date: 2019-03-19 04:43:47
 C:\WINDOWS\SYSTEM32\ksuser.dll handle: 00007ff8beed0000 size: 23264 crc: B862C2FB date: 2019-03-19 04:43:47
 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL handle: 00007ff909370000 size: 1413912 crc: 3881862B date: 2019-09-20 06:37:42
 C:\WINDOWS\SYSTEM32\msacm32.drv handle: 00007ff90d4e0000 size: 29184 crc: DCE0859B date: 2019-03-19 04:43:47
 C:\WINDOWS\SYSTEM32\MSACM32.dll handle: 00007ff90e6d0000 size: 107640 crc: C340459C date: 2019-03-19 04:43:47
 C:\WINDOWS\SYSTEM32\midimap.dll handle: 00007ff8fc200000 size: 25600 crc: 1A533078 date: 2019-03-19 04:43:47
 C:\WINDOWS\System32\clbcatq.dll handle: 00007ff9126d0000 size: 643752 crc: C1F090C7 date: 2019-03-19 04:44:30
 C:\WINDOWS\System32\dmusic.dll handle: 00007ff8faf70000 size: 132608 crc: C9F5B874 date: 2019-03-19 04:45:38
 C:\WINDOWS\System32\DSOUND.dll handle: 00007ff8fb100000 size: 602112 crc: C9C6543E date: 2019-03-19 04:43:47
 C:\WINDOWS\System32\bcrypt.dll handle: 00007ff910630000 size: 144376 crc: 49BE6FB0 date: 2019-08-16 06:21:51
 C:\WINDOWS\System32\dmsynth.dll handle: 00007ff8faf40000 size: 122880 crc: 408A0AD2 date: 2019-03-19 04:45:38
 C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll handle: 00007ff90eba0000 size: 70256 crc: 6783400B date: 2019-03-19 04:44:04
 C:\Windows\System32\Windows.UI.dll handle: 00007ff8ffc50000 size: 1383648 crc: FD6B1F06 date: 2019-03-19 04:44:00
 C:\Windows\System32\InputHost.dll handle: 00007ff8ffaa0000 size: 1052608 crc: EAFE1BEB date: 2019-09-20 06:37:49
 C:\Windows\System32\PROPSYS.dll handle: 00007ff90b720000 size: 977688 crc: C4E7943E date: 2019-08-16 06:21:47
 C:\WINDOWS\System32\psapi.dll handle: 00007ff913360000 size: 18832 crc: BED9353E date: 2019-03-19 04:44:28

---- gamelog start ----
Tick 0: new game started
Revision text changed to jgrpp-0.28.0, savegame version 202, not modified, _openttd_newgrf_version = 0x19006d64
New game mode: 1 landscape: 0
Tick 37532: game loaded
Revision text changed to jgrpp-0.29.0, savegame version 202, not modified, _openttd_newgrf_version = 0x19006d64
Tick 63419: game loaded
Revision text changed to jgrpp-0.29.2, savegame version 205, not modified, _openttd_newgrf_version = 0x19006d64
Tick 41790: game loaded
Revision text changed to jgrpp-0.29.3, savegame version 207, not modified, _openttd_newgrf_version = 0x19006d64
Tick 55625: settings changed
Setting changed: construction.max_bridge_length : 64 -> 65
Tick 55627: settings changed
Setting changed: construction.max_bridge_length : 65 -> 66
Tick 55629: settings changed
Setting changed: construction.max_bridge_length : 66 -> 67
Tick 55631: settings changed
Setting changed: construction.max_bridge_length : 67 -> 68
Tick 55633: settings changed
Setting changed: construction.max_bridge_length : 68 -> 69
Tick 55636: settings changed
Setting changed: construction.max_bridge_length : 69 -> 70
Tick 55638: settings changed
Setting changed: construction.max_bridge_length : 70 -> 71
Tick 55640: settings changed
Setting changed: construction.max_bridge_length : 71 -> 72
Tick 55642: settings changed
Setting changed: construction.max_bridge_length : 72 -> 73
Tick 55644: settings changed
Setting changed: construction.max_bridge_length : 73 -> 74
Tick 55646: settings changed
Setting changed: construction.max_bridge_length : 74 -> 75
Tick 55648: settings changed
Setting changed: construction.max_bridge_length : 75 -> 76
Tick 55650: settings changed
Setting changed: construction.max_bridge_length : 76 -> 77
Tick 55653: settings changed
Setting changed: construction.max_bridge_length : 77 -> 78
Tick 55655: settings changed
Setting changed: construction.max_bridge_length : 78 -> 79
Tick 55657: settings changed
Setting changed: construction.max_bridge_length : 79 -> 80
Tick 55659: settings changed
Setting changed: construction.max_bridge_length : 80 -> 81
Tick 55661: settings changed
Setting changed: construction.max_bridge_length : 81 -> 82
Tick 55663: settings changed
Setting changed: construction.max_bridge_length : 82 -> 83
Tick 55665: settings changed
Setting changed: construction.max_bridge_length : 83 -> 84
Tick 55667: settings changed
Setting changed: construction.max_bridge_length : 84 -> 85
Tick 55670: settings changed
Setting changed: construction.max_bridge_length : 85 -> 86
Tick 55672: settings changed
Setting changed: construction.max_bridge_length : 86 -> 87
Tick 55674: settings changed
Setting changed: construction.max_bridge_length : 87 -> 88
Tick 55676: settings changed
Setting changed: construction.max_bridge_length : 88 -> 89
Tick 55678: settings changed
Setting changed: construction.max_bridge_length : 89 -> 90
Tick 55680: settings changed
Setting changed: construction.max_bridge_length : 90 -> 91
Tick 55682: settings changed
Setting changed: construction.max_bridge_length : 91 -> 92
Tick 55684: settings changed
Setting changed: construction.max_bridge_length : 92 -> 93
Tick 55686: settings changed
Setting changed: construction.max_bridge_length : 93 -> 94
Tick 55688: settings changed
Setting changed: construction.max_bridge_length : 94 -> 95
Tick 55690: settings changed
Setting changed: construction.max_bridge_length : 95 -> 96
Tick 55692: settings changed
Setting changed: construction.max_bridge_length : 96 -> 97
Tick 55695: settings changed
Setting changed: construction.max_bridge_length : 97 -> 98
Tick 55697: settings changed
Setting changed: construction.max_bridge_length : 98 -> 99
Tick 55701: settings changed
Setting changed: construction.max_bridge_length : 99 -> 100
Tick 8090: settings changed
Setting changed: vehicle.wagon_speed_limits : 1 -> 0
Tick 35112: settings changed
Setting changed: construction.max_tunnel_length : 64 -> 65
Tick 35233: settings changed
Setting changed: construction.max_tunnel_length : 65 -> 66
Tick 35242: settings changed
Setting changed: construction.max_tunnel_length : 66 -> 67
Tick 35249: settings changed
Setting changed: construction.max_tunnel_length : 67 -> 68
Tick 35264: settings changed
Setting changed: construction.max_tunnel_length : 68 -> 69
Tick 35270: settings changed
Setting changed: construction.max_tunnel_length : 69 -> 70
Tick 35276: settings changed
Setting changed: construction.max_tunnel_length : 70 -> 71
Tick 35421: settings changed
Setting changed: construction.max_tunnel_length : 71 -> 100
Tick 31336: game loaded
Revision text changed to jgrpp-0.31.3, savegame version 213, not modified, _openttd_newgrf_version = 0x1a006d64
Tick 2771: settings changed
Setting changed: vehicle.plane_speed : 4 -> 3
Tick 3084: settings changed
Setting changed: vehicle.plane_speed : 3 -> 4
Tick 61926: settings changed
Setting changed: vehicle.plane_speed : 4 -> 3
Tick 61935: settings changed
Setting changed: vehicle.plane_speed : 3 -> 2
Tick 61947: settings changed
Setting changed: vehicle.plane_speed : 2 -> 1
Tick 62002: settings changed
Setting changed: vehicle.plane_speed : 1 -> 2
Tick 62007: settings changed
Setting changed: vehicle.plane_speed : 2 -> 3
Tick 62011: settings changed
Setting changed: vehicle.plane_speed : 3 -> 4
Tick 62028: settings changed
Setting changed: vehicle.plane_speed : 4 -> 3
Tick 62031: settings changed
Setting changed: vehicle.plane_speed : 3 -> 2
Tick 62033: settings changed
Setting changed: vehicle.plane_speed : 2 -> 1
Tick 44619: settings changed
Setting changed: construction.max_tunnel_length : 100 -> 101
Tick 44627: settings changed
Setting changed: construction.max_tunnel_length : 101 -> 102
Tick 44635: settings changed
Setting changed: construction.max_tunnel_length : 102 -> 103
Tick 44686: settings changed
Setting changed: construction.max_tunnel_length : 103 -> 104
Tick 44693: settings changed
Setting changed: construction.max_tunnel_length : 104 -> 105
Tick 44701: settings changed
Setting changed: construction.max_tunnel_length : 105 -> 106
Tick 44708: settings changed
Setting changed: construction.max_tunnel_length : 106 -> 107
Tick 44716: settings changed
Setting changed: construction.max_tunnel_length : 107 -> 108
Tick 44723: settings changed
Setting changed: construction.max_tunnel_length : 108 -> 109
Tick 44731: settings changed
Setting changed: construction.max_tunnel_length : 109 -> 110
Tick 44741: settings changed
Setting changed: construction.max_tunnel_length : 110 -> 111
Tick 44748: settings changed
Setting changed: construction.max_tunnel_length : 111 -> 112
Tick 44756: settings changed
Setting changed: construction.max_tunnel_length : 112 -> 113
Tick 44763: settings changed
Setting changed: construction.max_tunnel_length : 113 -> 114
Tick 44771: settings changed
Setting changed: construction.max_tunnel_length : 114 -> 115
Tick 44780: settings changed
Setting changed: construction.max_tunnel_length : 115 -> 116
Tick 44787: settings changed
Setting changed: construction.max_tunnel_length : 116 -> 117
Tick 44795: settings changed
Setting changed: construction.max_tunnel_length : 117 -> 118
Tick 44803: settings changed
Setting changed: construction.max_tunnel_length : 118 -> 119
Tick 44818: settings changed
Setting changed: construction.max_tunnel_length : 119 -> 120
Tick 50179: settings changed
Setting changed: construction.max_tunnel_length : 120 -> 140
---- gamelog end ----

Recent news messages (1 of 1):
(2426-08-12) StringID: 674, Type: 4, Ref1: 4, 12560, Ref2: 0, 4294967295
(2426-08-12) StringID: 674, Type: 4, Ref1: 4, 12203, Ref2: 0, 4294967295
(2426-08-11) StringID: 674, Type: 4, Ref1: 4, 11903, Ref2: 0, 4294967295
(2426-08-10) StringID: 675, Type: 4, Ref1: 4, 11879, Ref2: 0, 4294967295

Command Log:
 Showing most recent 3 of 3 commands
   0 | 2426-08-11, 13,   2 | --m----- |     5731 x    2221, p1: 0x00002E79, p2: 0x00000000, cc:  0, lc:  0, cmd: 0x11C50026 (CmdReverseTrainDirection)
   1 | 2426-08-11,  4,   1 | --m----- |     5730 x    2227, p1: 0x00002E79, p2: 0x00000000, cc:  0, lc:  0, cmd: 0x11C50026 (CmdReverseTrainDirection)
   2 | 2426-08-09, 28,   0 | --m----- |        0 x       0, p1: 0x00000002, p2: 0x00000000, cc:  0, lc:  0, cmd: 0x0000003E (CmdPause)

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] openttd              0x000000000059D2F6 ReReserveTrainPath (/home/jgr/openttd/cross-win64/src/rail_cmd.cpp:1256)
[01] openttd              0x000000000059F4D5 CmdRemoveSingleSignal(unsigned int, DoCommandFlag, unsigned int, unsigned int, char const*) + 2005 (/home/jgr/openttd/cross-win64/src/rail_cmd.cpp:1931)
[02] openttd              0x000000000046F51D Command::Execute(unsigned int, DoCommandFlag, unsigned int, unsigned int, char const*, unsigned int) const (/home/jgr/openttd/cross-win64/src/command_type.h:566)
[03] openttd              0x0000000000470317 DoCommandP(unsigned int, unsigned int, unsigned int, unsigned int, void (*)(CommandCost const&, unsigned int, unsigned int, unsigned int), char const*, bool, unsigned int) + 391 (/home/jgr/openttd/cross-win64/src/command.cpp:806)
[04] openttd              0x00000000008F1E99 GenericPlaceSignals (/home/jgr/openttd/cross-win64/src/rail_gui.cpp:245)
[05] openttd              0x00000000006C3229 VpHandlePlaceSizingDrag() + 489 (/home/jgr/openttd/cross-win64/src/viewport.cpp:4875)
[06] openttd              0x00000000006E7E8D MouseLoop (/home/jgr/openttd/cross-win64/src/window.cpp:2894)
[07] openttd              0x00000000006BAC21 WndProcGdi (/home/jgr/openttd/cross-win64/src/video/win32_v.cpp:706)
[08] USER32               0x00007FF91281681D CallWindowProcW + 957
[09] USER32               0x00007FF912816212 DispatchMessageW + 498
[10] openttd              0x00000000006BB513 VideoDriver_Win32::MainLoop() + 179 (/home/jgr/openttd/cross-win64/src/video/win32_v.cpp:1223)
[11] openttd              0x0000000000568094 openttd_main(int, char**) + 5684 (/home/jgr/openttd/cross-win64/src/openttd.cpp:948)
[12] openttd              0x000000000057B87E WinMain + 270 (/home/jgr/openttd/cross-win64/src/os/windows/win32.cpp:452)
[13] openttd              0x00000000004013F8 __tmainCRTStartup + 584 (./mingw-w64-crt/crt/crtexe.c:334)
[14] openttd              0x00000000004014EB WinMainCRTStartup + 27 (./mingw-w64-crt/crt/crtexe.c:184)
[15] KERNEL32             0x00007FF911B87BD4 BaseThreadInitThunk + 20
[16] ntdll                0x00007FF91368CEE1 RtlUserThreadStart + 33

*** End of additional info ***

**Comment by JGRennison** [comment]
Thanks for reporting this.
This issue is fixed as of 0.31.4. I would suggest upgrading to 0.31.5 which is the most recent release.

**Comment by timc6896** [comment]
Thank you sir!  :)
